### ISSUE TITLE
Marker clicks not always triggered on iOS

### ISSUE THREAD

**Issue by stevesims** [wf9a5m75/phonegap-googlemaps-plugin#115]
I have a bunch of markers defined that all have a relatively simple markerClick function that outputs "click" to the log, pans the camera in to that position and increases the zoom by 1.

What I've been finding is that sometimes (maybe 1 in 4 taps, possibly less) the markerClick function doesn't get executed.  Tap on the same marker a second time and it will execute.

I haven't been able to see a logic behind this inconsistency.

This only seems to affect iOS.  On Android the marker clicks seem to always work.

**Comment by wf9a5m75** [comment]
@stevesims Any update for this?

**Comment by wf9a5m75** [comment]
I close this issue, because there is no update.
But @stevesims, if you have additional information, please post it here.
I will open this issue again.
