### ISSUE TITLE
Google map Librarie

### ISSUE THREAD

**Issue by TolotraRam** [wf9a5m75/phonegap-googlemaps-plugin#14]
Hi,
Nice work, but i'd like to know how to implement Gmap Libraries such as PlaceService, should i use javascript or you need to implement it in your plugin ?

**Comment by Hirbod** [comment]
I guess, for now, Places over JS API V3 should be enough. Places support could be an own plugin and should not be included by default. (just prevent overhead as much as possible)

**Comment by wf9a5m75** [comment]
I'm waiting Google Play Services v23 which is support Places API.

**Comment by wf9a5m75** [comment]
@Hirbod 
If you have a time, would you like to try to implement [Places API](https://developers.google.com/places/) or [Directions API](https://developers.google.com/maps/documentation/directions/?hl=en) for iOS using http-request plugin?

I think the directions API is easy.
If you are interested in, let's make a fund-raising for you.

**Comment by Jerome2606** [comment]
Are you planning to work on Places API ?

**Comment by Hirbod** [comment]
Currently not.

**Comment by dflourusso** [comment]
Hi, are there some prevision from directions implementation? Thanks.
