### ISSUE TITLE
Event on location change ?

### ISSUE THREAD

**Issue by camory-fa** [wf9a5m75/phonegap-googlemaps-plugin#176]
Hello

First of all, thanks for your work. 
May I miss it but i did not find a way to listen the location change.
I know there is getMyLocation() to get the current location but, I would like to update the map when the location change to keep the user location at the center of the map. 
Best regards

**Comment by Hirbod** [comment]
I also think that this will just overload this plugin. Location change can be done simply with official third party plugins such as cordovas geolocation. Setting up a watchPosition trough the navigator is simple and should be enough. @wf9a5m75 agree with me? If yes, we should close this one here

Other documentations:
https://github.com/apache/cordova-plugin-geolocation/blob/master/doc/index.md#navigatorgeolocationwatchposition

**Comment by wf9a5m75** [comment]
Yes for currently, but I hope I will try to implement this and geofencing feature.
