### ISSUE TITLE
Tile Layer - Opacity

### ISSUE THREAD

**Issue by bFlood** [wf9a5m75/phonegap-googlemaps-plugin#191]
please add getOpacity() and setOpacity() to the TileLayer class

also, would it also be possible to support custom tile layers?

**Comment by wf9a5m75** [comment]
I added the `opacity` property to map.addTileOverlay(), and the `setOpacity()` method for TileOverlay.

**Comment by bFlood** [comment]
thanks! was opacity added to the core android sdk?

**Comment by bFlood** [comment]
nevermind, I see you added the custom tileprovider to handle this on android. thank you masashi, really great work!
