### ISSUE TITLE
Expose the API to create different colored Markers

### ISSUE THREAD

**Issue by sunsus** [wf9a5m75/phonegap-googlemaps-plugin#196]
It would be nice to expose the api to create different colored Marker.
https://developers.google.com/maps/documentation/ios/marker#change_the_default_marker_color

regards

Patrick

**Comment by wf9a5m75** [comment]
This code works on version 1.2.5.
```js
  map.addMarker({
    icon: '#FFFF00',
    position: new plugin.google.maps.LatLng(0, 0)
  });
```
