### ISSUE TITLE
Drop animation marker

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#208]
Hi Masashi,
is there any drop animation for markers? I thought I read about in your docs but can't even find it in your docs nor in the googlemaps-cdv-plugin.js

https://developers.google.com/maps/documentation/javascript/examples/marker-animations

If it's not already implemented, it would be a nice feature request I guess:

```javascript
map.addMarker({
   ...
   animation: plugin.google.maps.Animation.DROP
});
```

**Comment by wf9a5m75** [comment]
Implemented the marker animation feature both Android and iOS.
The code has merged into the test branch.

Test code:
```js
document.addEventListener('deviceready', function() {
  var div = document.getElementById("map_canvas");
  var map = plugin.google.maps.Map.getMap(div, {
    'camera': {
      'latLng': new plugin.google.maps.LatLng(35, 137),
      'tilt': 30,
      'zoom': 15,
      'bearing': 50
    }
  });
  map.on(plugin.google.maps.event.MAP_READY, function() {

    map.addMarker({
      position: new plugin.google.maps.LatLng(35, 137),
      icon: "http://www.google.com/intl/en_us/mapfiles/ms/icons/blue-dot.png",
      animation: plugin.google.maps.Animation.DROP
    }, function(marker) {
      
      var button = document.getElementById("button");
      button.addEventListener("click", function() {
        marker.setAnimation(plugin.google.maps.Animation.BOUNCE);
      });x
    });
  });
});
```
![animation_marker](https://cloud.githubusercontent.com/assets/167831/6519177/880291e8-c365-11e4-89c5-71f0f0dab24e.gif)

**Comment by yedeba** [comment]
WOW!!, thanks Masashi

**Comment by brunodb3** [comment]
This doesn't work for me, it gives me the following error:

"Uncaught TypeError: Cannot read property 'DROP' of undefined"

Note: I am using Ionic with the map on the $rootScope.

**Comment by wf9a5m75** [comment]
Please use the latest test branch, not main branch.

**Comment by brunodb3** [comment]
Oh, my bad. Sorry, i was using the master branch. Going to download the test.
