### ISSUE TITLE
Map Touch Listener

### ISSUE THREAD

**Issue by michaeleparkour** [wf9a5m75/phonegap-googlemaps-plugin#214]
Any plans to make touch events? The case is to get new markers on CAMERA_CHANGE event depending on VisibleRegion. But without touchEnd it makes requests  for new markers too often if user is dragging map.

**Comment by wf9a5m75** [comment]
I tried to implement this, but there is no way for iOS technically.

If I found another way in the future, I will open this issue, but I don't implement this currently.

**Comment by LouisMazel** [comment]
Hello, 
Why revert this ?

**Comment by eleva** [comment]
Is there any news about CAMERA_IDLE event on android?

**Comment by wf9a5m75** [comment]
@LouisMazel Read here. https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/844#issuecomment-200467799
