### ISSUE TITLE
White menu in demo app on Android 4.0.3

### ISSUE THREAD

**Issue by kodinets** [wf9a5m75/phonegap-googlemaps-plugin#289]
Hi Masashi!

Found problems with menu in phonegap-googlemaps-plugin on Andoid 4.0.3. It becomes white. Same problems we have in our own mobile app with phonegap-googlemaps-plugin.

Here is the video: https://www.dropbox.com/s/bj0qs71ksrs4kja/VID_20141107_201216.mp4?dl=0

And here is mobile software specs:
![image](https://cloud.githubusercontent.com/assets/7920726/4963620/bffde574-6722-11e4-99c6-6bc66efbd339.png)

Would be very grateful if you help with this issue

**Comment by wf9a5m75** [comment]
@kodinets Any update for this?

**Comment by wf9a5m75** [comment]
I close this issue at once, but if you find any tips, tell me please.
