### ISSUE TITLE
Google Map not getting close in android

### ISSUE THREAD

**Issue by anilbabaria** [wf9a5m75/phonegap-googlemaps-plugin#297]
Hi Masashi,

We have integrated the Google Map Plugin yesterday,

The issue that we are facing after integrating the latest version of plugin is Google Map is not getting closed on clicking of Close button in Android device,

We are using Cordova 3.5 version for our Application, also we have noticed that Map_Close is also not getting fired when we click on Close button,

Below is my Code:
```js
var displayMyLocation = function () {
    var map = plugin.google.maps.Map.getMap();
    map.clear();
    getCurrentLocation(map);// Find your current Loaction and set Latitude / Longitude
    map.addMarker({
        'position': mapLoc.latLng,
        'title': "I am here!"
    }, function (marker) {
        map.animateCamera({
            'target': mapLoc.latLng,
            'zoom': 18
        }, function () {
            marker.showInfoWindow();
        });
    });
    map.showDialog();
};
```

**Comment by wf9a5m75** [comment]
@leandro-shifteight Sorry, I lost track this issue.
I think this issue is fixed in the test branch.
Have you tried it?

**Comment by wf9a5m75** [comment]
I confirmed this.
This issue has been already fixed in the test branch.
![issue_297](https://cloud.githubusercontent.com/assets/167831/6319526/c8f5cd5a-ba73-11e4-98a3-0e00dacad312.gif)

In order to use the test branch, following like this.
```
$> cordova plugin rm plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
$> cordova run android
```
