### ISSUE TITLE
Problems with touch events after map initialization

### ISSUE THREAD

**Issue by kodinets** [wf9a5m75/phonegap-googlemaps-plugin#308]
**1) Here is console log before plugin init(finger moving on screen, application works fine):**
`blockWebkitDraw blockWebkitDraw lockedfalse`
`blockWebkitDraw blockWebkitDraw lockedfalse`
`blockWebkitDraw blockWebkitDraw lockedfalse`

**2) There are no such logs when map is opened (no blockWebkitDraw).**

**3) When we go to an other screen after map we have strange touch behaviour, slow performance and rendering artefacts.** 
Here is logs that appear in console at that moment (you can see lockedtrue =>lockedfalse=>lockedtrue):
`blockWebkitDraw blockWebkitDraw lockedtrue`
`blockWebkitDraw blockWebkitDraw lockedfalse`
`blockWebkitDraw blockWebkitDraw lockedtrue`
`blockWebkitDraw blockWebkitDraw lockedfalse`

So you can see that map pluging has bad influences to normal handling of touch events by application (mentioned in logs of state 1). Before visiting and initializing map plugin it works fine.

We've got these logs from Samsung Galaxy S3 (Android 4.3) but basically we see slow performance touches of the application on other devices with Android 4.x.

**Comment by mjaverto** [comment]
This does not happen on Android but does on iOS.

**Comment by wf9a5m75** [comment]
@mjaverto Any update?

**Comment by wf9a5m75** [comment]
I close this issue at once, but if you have any updates, just post the updates, then I will open this issue again.
