### ISSUE TITLE
Add option for custom watchDog timer interval

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#313]
Hi,

actually the watchdog-timer is set to 100ms.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L2018

Could you please provide a function to override the value or even disable it? (false = disabled, 0 = disbaled, 1 = 1ms, 20 = 20ms... etc)

**Comment by Hirbod** [comment]
@bFlood are you in for a bounty? This is a very urgent feature for me. I guess if we both reach 50 bucks masashi is in for doing this (I would do it myself, but I'm busy enough with the app)

**Comment by wf9a5m75** [comment]
Sorry. You guys are already enough donated. I'm really appreciate for you.
I just don't have enough time for my plugin.

**Comment by Hirbod** [comment]
No problem. I will send PR in 10 minuntes ;)
I'm finished in a few minutes

**Comment by Hirbod** [comment]
Hi @wf9a5m75 

just add these lines before setCenter function in your JS.

```js
/**
 * @desc Set watchDogTimer for map positioning changes
 */
App.prototype.getWatchDogTimer = function() {
  var self = this;
  time = self.get('watchDogTimer') || 100;
  return time;
};

/**
 * @desc Set watchDogTimer for map positioning changes
 */
App.prototype.setWatchDogTimer = function(time) {
  var self = this;
  time = time || 100;
  self.set('watchDogTimer', time);

  if(time < 50) {
    console.log('Warning: watchdog values under 50ms will drain battery a lot. Just use for short operation times.');
  }
};
```

And very close to the end, replace
```
    window._watchDogTimer = window.setInterval(function() { myFunc(); }, 100);
```

with this one:
```
    window._watchDogTimer = window.setInterval(function() { myFunc(); }, _mapInstance.getWatchDogTimer());
```

You still can't cancel the watchdog (this option really should still be implemented, but for now, I could set a high value like 10000 which will save a lot more battery...

You can set your own value with:

```javascript
Map.setWatchDogTimer(TIMEINMILLISECONDS);
```
Value needs to be an integer.

**Comment by Hirbod** [comment]
Here as a proof, the benefits are HUGE!
https://www.youtube.com/watch?v=cddcqIibOl8&feature=youtu.be

OnsenUI has a preopen and a postopen, preclose and postclose callbacks for the menu.

Workflow:
Preopen -> setWatchDogTimer(1);
Postopen-> setWatchDogTimer(false); (will reset)
Preclose -> setWatchDogTimer(1);
Postclose-> setWatchDogTimer(false); (will reset)

Of course I could leave it on 1ms till postclose (which is much smarter I guess... nobdy is going to leave the menu open for more then a few seconds.

**Comment by wf9a5m75** [comment]
Thank you, @Hirbod 
It seems looks good! 
Please send me a pull request. I will merge it.

**Comment by Hirbod** [comment]
#367 

Maybe you will find some time for adding the options for enable/disable totally.
