### ISSUE TITLE
Does this work with encodedPath?

### ISSUE THREAD

**Issue by canadaka** [wf9a5m75/phonegap-googlemaps-plugin#317]
It seems the Google mobile SDK's both support Googles encodedPath format, on Android it requires the Utility library
https://developers.google.com/maps/documentation/android/utility/

then used via pathFromEncodedPath
https://developers.google.com/maps/documentation/ios/reference/interface_g_m_s_path#a4060269354374332afbb532557c4899e

But will any of this work with the phonegap-googlemaps-plugin?

**Comment by chrisharney** [comment]
I use these javascript functions in my phonegap app to encode and decode: http://jsfiddle.net/8nzg7tta/

**Comment by wf9a5m75** [comment]
@chrisharney Thanks for your information.

**Comment by wf9a5m75** [comment]
@chrisharney Thank you for your information. I will implement the code that you referred into the next version.

**Comment by wf9a5m75** [comment]
Example:

```js
var encodedPolygon = "uyb~FupbzYqAoK|H{@~FaFjCxInFdGkBlEn@|FeEPmA|EaGsDiIUr@_L";
map.addPolygon({
        'points': plugin.google.maps.geometry.encoding.decodePath(encodedPolygon, 5),
        'strokeColor' : '#AA00FF',
        'strokeWidth': 5,
        'fillColor' : '#880000'
}, onPolygonAdded);
```

**Comment by wf9a5m75** [comment]
Example:

```js
var encodedPolygon = "uyb~FupbzYqAoK|H{@~FaFjCxInFdGkBlEn@|FeEPmA|EaGsDiIUr@_L";
map.addPolygon({
        'points': plugin.google.maps.geometry.encoding.decodePath(encodedPolygon, 5),
        'strokeColor' : '#AA00FF',
        'strokeWidth': 5,
        'fillColor' : '#880000'
}, onPolygonAdded);
```

**Comment by canadaka** [comment]
Can't seem to get this working, console error:
"Uncaught TypeError: Cannot read property 'encoding' of undefined"

Seems you only added this functionalty 17 days ago, I just installed the plugin using the "cordova plugin add plugin.google.maps" instructions, is that maybe not using the most recent source?

**Comment by Hirbod** [comment]
Yes, that is right, cordova registry isn't updated yet, please install directly from master source

```
cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#master --variable API_KEY_FOR_ANDROID....
```

**Comment by canadaka** [comment]
thanks, that worked!

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Geometry-Library
