### ISSUE TITLE
Map not displaying using Onsen UI

### ISSUE THREAD

**Issue by nhfruchter** [wf9a5m75/phonegap-googlemaps-plugin#324]
I'm using Onsen UI and haven't been able to get the map to show up correctly. I looked at Issue #199 and implemented its advice, but it doesn't seem to be the same problem: there, the map is black, but here the map doesn't show up whatsoever.

I have my controller:
```
app.controller('TestController', function($scope, $rootScope){
	ons.ready(function(){
        if($rootScope.map) {
            $rootScope.map.clear();
            $rootScope.map.remove();
            $('.gmap_div:not(:last)').remove();
            $rootScope.map = '';
        }		
		var div = document.getElementById("map_canvas");
		$rootScope.map = plugin.google.maps.Map.getMap(div);
		$rootScope.map.on(plugin.google.maps.event.MAP_READY, function(map){
			console.log("Map ready.");
			map.setMapTypeId(plugin.google.maps.MapTypeId.HYBRID);
			map.setDebuggable(true);
		});
	});
});
```
and page 
```
<ons-page ng-controller="TestController">
	<ons-toolbar>
		<div class="left navigation-bar__left navigation-bar--android__left">
			<ons-toolbar-button ng-click="menu.toggle()">
				<ons-icon icon="ion-navicon" size="28px" fixed-width="false"></ons-icon>
			</ons-toolbar-button>
		</div>
		<div class="center navigation-bar--android__center">Testing</div>
	</ons-toolbar>
	
    <div style="width:100%;height:400px" id="map_canvas"></div>
</ons-page>	
```

The events seem to be firing correctly (I get a map ready) and the map displays correctly with all changes (like the map type change) if I run `openDialog()` from the Chrome inspector. However, the map is not showing up embedded in the page—I just see a blank area where it should be with no controls or anything.

**Comment by eecsxielu** [comment]
@nhfruchter Hi, have you solved this problem yet?

**Comment by nhfruchter** [comment]
I switched to a different alternative (Mapbox GL) instead.

**Comment by FineRapha** [comment]
@eecsxielu I solved this by reloading the entire map each time the page is displayed.
Uses more data but whatever. It's the user's choice to leave the page without finishing using the map.

**Comment by oladipo** [comment]
@FineRapha How do you reload the entire map again?

**Comment by wf9a5m75** [comment]
@FineRapha This plugin does not use the google maps JavaScript api v3

**Comment by FineRapha** [comment]
You're right.
I'm currently answering on two Google Maps API x OnsenUI threads. And thought this one was the Javascript one.
I'll adjust my answer.
