### ISSUE TITLE
Display blank page after upgrade to the latest com.google.playservices V 21

### ISSUE THREAD

**Issue by jianbo** [wf9a5m75/phonegap-googlemaps-plugin#332]
After rebuild my app with latest version of playservices 21, it shows a blank page when first time visit the map view (other views works fine), the page then works if I exit and reopen the app. I had to revert to v 19 to make it work.
Any idea?

**Comment by wf9a5m75** [comment]
Use the test branch with Google Play Services **v22** (not v21).
```
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
```
