### ISSUE TITLE
iOS myLocationButton Click event does not fire.

### ISSUE THREAD

**Issue by jpmetcalf** [wf9a5m75/phonegap-googlemaps-plugin#333]
The following works fine on Android, but fails on iOS. I do not get any errors it just does not get called.

var evtName = plugin.google.maps.event.MY_LOCATION_BUTTON_CLICK;
map.on(evtName, function () {
    alert("Location Button Clicked");
});

**Comment by vosecek** [comment]
plugin.google.maps.event.MY_LOCATION_BUTTON_CLICK event seems to be broken again.
Plugin versions:
cordova-plugin-googlemaps: 1.4.0
com.googlemaps.ios: 2.1.1.
