### ISSUE TITLE
Plugin conflict with Salesforce mobile SDK

### ISSUE THREAD

**Issue by xuzongque** [wf9a5m75/phonegap-googlemaps-plugin#335]
Hi,

I have difficulties to have this plugin work together with Salesforce Mobile SDK plugin: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin

I have already opened an issue there: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/39

Could you have a check? 
Thanks.

**Comment by wf9a5m75** [comment]
Please follow @xuzongque's helps.
