### ISSUE TITLE
Urgent: map stop working with many remote markers

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#337]
Hi Masashi,

if I try to load more then 100 remote marker images, the map just stops working. From 50-80 it is ok and still fast, then suddently, it stops doing anything. If I set 6000 markers without image, everything works.

Just tested on iOS, I don't know how it would be on android. Please, could you have a look? I know, this problem will for sure be solved with marker cluster, but actually, it is a serious bug. I'm not sure what happen with locale marker images, but at least remote will die.. :(

**Comment by Hirbod** [comment]
Happy new year to all of you guys. Sorry when I jumped on this so quickly but any news on this bug?

**Comment by wf9a5m75** [comment]
@Hirbod 
I tried your dummy data (data_big.json), but I didn't face your error on my iPhone 5s.
However, I received some memory warnings.
So I think you got memory error.

In your code, at least, you need to improve your code.
Holding the icon data of markers domain large memory.
In order to reduce the memory usage, holding just the marker id (maybe uid in your code), then get the detail data when user click the marker.

For example:
```js

map.addMarker({
  "position": new plugin.google.maps.LatLng(...),
  "icon": ...,
  "uid": data.uid,
  "markerClick": function(marker) {
     var uid = marker.get("uid");
     // ie. jQuery
     $.getJSON("http://yourserver/getDetail/" + uid, function(response) {
       alert(response);
     });
  }
```


Further more, using one function for the same process is better memory performance in Javascript.
So, better the below code than the bottom one.

Better code:
```js
map.addMarker({
  ...
  "markerClick": onMarkerClick
});

function onMarkerClick(marker) {
    ....
}
```

Bad code:
```js
map.addMarker({
  ...
  "markerClick": function() {....}
})
```

**Comment by Hirbod** [comment]
Hi Masashi,

thanks for the tips. I know, there is some potential to optimize, and I will incorporate your suggestions, but still, it crashes only when I use the external images. If I leave them to the defaults, the map will load, no matter how many markers I've used...

**Comment by Hirbod** [comment]
Got the fix for this problem. It's not caused trough this plugin directly. Seems like this is the problem:
https://issues.apache.org/jira/browse/CB-8002

actually cordova has a bug which creates a new iframe every .exec() call is fired in bridge. As sonn as 999+ is reached, maps plugin crash. When I fire $('iframe').remove(), it works. I'm sure that this is my problem. This bug seems only to happen on 3.7.0+ and is fixed in 3.8.0.dev

For now (till 3.8.0) is out, ```$('iframe').not(':last').remove(); fix most of my issues.

**Comment by wf9a5m75** [comment]
Wow! I know Cordova creates iframe internally, but I didn't reach the idea of this.
You are great, and congratulation!

**Comment by wf9a5m75** [comment]
:100:

**Comment by Hirbod** [comment]
I'm so sad.... but this fixes at least some other problems, but not this one. It still crash when I have to many remote markers... DAMN!

**Comment by Hirbod** [comment]
SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
2015-01-24 03:24:51.712 Nachbarschaft[1052:19871] void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

event tried to add the remove stuff inside the addMarkers function.. im going crazy...

**Comment by Hirbod** [comment]
I got some new / better logs.

```
2015-01-24 03:27:45.907 Nachbarschaft[1098:21122] void SendDelegateMessage(NSInvocation *): delegate (webView:resource:didFinishLoadingFromDataSource:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
2015-01-24 03:27:46.653 Nachbarschaft[1098:21099] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: http://network.nachbarschaft.nightstomp.com/user/pictures/8/marker_pin.png?24012015)'
*** First throw call stack:
(0x185f1259c 0x1966680e4 0x185dfd1f8 0x100058538 0x100ab8df0 0x100ac28c8 0x100058368 0x100053ef8 0x186de5df0 0x185eca9ec 0x185ec9c90 0x185ec7d40 0x185df50a4 0x18ef975a4 0x18a72a3c0 0x100010604 0x196cd6a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

This seems to be something interessting:
2015-01-24 03:27:46.653 Nachbarschaft[1098:21099] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: http://network.nachbarschaft.nightstomp.com/user/pictures/8/marker_pin.png?24012015)'

**Comment by Hirbod** [comment]
When I have more then 60 markers with remote image... MAPS CRASH.
30.01 we want to submit the app to the appstore... I'm working 4 months on this App now.. 

My contractee is going to kill me when this app dies with 60 markers.. and I'm getting really nervous right now.

**Comment by Hirbod** [comment]
Marker.m file:

changed 
```C
        dispatch_queue_t gueue = dispatch_queue_create("GoogleMap_addMarker", NULL);
        dispatch_sync(gueue, ^{
```

to

```C
        //dispatch_queue_t gueue = dispatch_queue_create("GoogleMap_addMarker", NULL);
        dispatch_async(dispatch_get_main_queue(), ^{
```

AND DAMN YEAH. IT WORKS! Just need to download async, not sync. As Google SDK requeires all calls in the main thread, I've just called dispatch_get_main_queue() instead of  ```gueue```

2000 Remote markers work, then:

```
2015-01-25 01:35:58.414 Nachbarschaft[38767:1142089] ((null)) was false: Reached the max number of texture atlases, can not allocate more.
2015-01-25 01:35:58.414 Nachbarschaft[38767:1142089] ((null)) was false: Sprite can't update, icon or texture is null (icon=0x0)
(lldb) 
```

Any feedback on this, Masashi?

**Comment by wf9a5m75** [comment]
I'm in outside right now. My car gets an engine trouble (over heat).

**Comment by Hirbod** [comment]
http://stackoverflow.com/questions/25555778/optimising-custom-marker-image-performance-with-google-maps-sdk-for-ios

https://code.google.com/p/gmaps-api-issues/issues/detail?id=5756

So after 4 months of work... this plugin is useless for me without Cluster... cause it can't display more then 500-600 (after my fix) markers.. (in a small radius of 2,5 miles)

**Comment by Hirbod** [comment]
I still see some other bugs in Markers. Breakpoint exception.
```
          [self.iconCache setObject:data forKey:iconPath];
```
throwing:  'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil

**Comment by Hirbod** [comment]
Ok... there were a lot of logical bugs and many cases were  data could not be set.
I've investigated a lot of time and changed the code. I can load now up tp 1000-1500 markers till gMaps crashes because of 

```
2015-01-25 01:35:58.414 Nachbarschaft[38767:1142089] ((null)) was false: Reached the max number of texture atlases, can not allocate more.
```

Things I did:

1. Instead of dispatch_sync, rely on dispatch_async and attach to dispatch_get_main_queue()
2. Never use ```NSData *data = [NSData dataWithContentsOfURL:url options:NSDataReadingMapped error:nil];```as it is terrible slow and ends to memory leaks / result in broken downloads/data which will cause the NSInvalidArgumentException

3. I've created a generic function inside of Markers.m
```
- (void)downloadImageWithURL:(NSURL *)url completionBlock:(void (^)(BOOL succeeded, UIImage *image))completionBlock
{
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    [NSURLConnection sendAsynchronousRequest:request
                                       queue:[NSOperationQueue mainQueue]
                           completionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
                               if ( !error )
                               {
                                   UIImage *image = [[UIImage alloc] initWithData:data];
                                   completionBlock(YES,image);
                               } else{
                                   completionBlock(NO,nil);
                               }
                           }];
}
```
which will do a Async request to download the markers.  Last but not least:

```C
      /***
       * Load the icon from over the internet
       */
      NSData *imgData = [self.iconCache objectForKey:iconPath];
      if (imgData != nil) {
        UIImage* image = [UIImage imageWithData:imgData];
        if (width && height) {
          image = [image resize:width height:height];
        }
        marker.icon = image;
        [self.commandDelegate sendPluginResult:pluginResult callbackId:callbackId];
      } else {
        //dispatch_queue_t gueue = dispatch_queue_create("GoogleMap_addMarker", NULL);
        dispatch_async(dispatch_get_main_queue(), ^{
            
            
          NSURL *url = [NSURL URLWithString:iconPath];
          //NSData *data = [NSData dataWithContentsOfURL:url options:NSDataReadingMapped error:nil];
          
            // download the image asynchronously
            [self downloadImageWithURL:url completionBlock:^(BOOL succeeded, UIImage *image) {
                if (succeeded) {
                    
                    [self.iconCache setObject:image forKey:iconPath];
                    
                    
                    if (width && height) {
                        image = [image resize:width height:height];
                    }
                    marker.icon = image;
                    
                    
                    // The `anchor` property for the icon
                    if ([iconProperty valueForKey:@"anchor"]) {
                        NSArray *points = [iconProperty valueForKey:@"anchor"];
                        CGFloat anchorX = [[points objectAtIndex:0] floatValue] / image.size.width;
                        CGFloat anchorY = [[points objectAtIndex:1] floatValue] / image.size.height;
                        marker.groundAnchor = CGPointMake(anchorX, anchorY);
                    }
                    
                    
                    // The `infoWindowAnchor` property
                    if ([iconProperty valueForKey:@"infoWindowAnchor"]) {
                        NSArray *points = [iconProperty valueForKey:@"infoWindowAnchor"];
                        CGFloat anchorX = [[points objectAtIndex:0] floatValue] / image.size.width;
                        CGFloat anchorY = [[points objectAtIndex:1] floatValue] / image.size.height;
                        marker.infoWindowAnchor = CGPointMake(anchorX, anchorY);
                    }
                    
                }
            }];
        
          [self.commandDelegate sendPluginResult:pluginResult callbackId:callbackId];
        });
```

I wrap inside a async dispatch and call the download sync. This let the map load much faster and download much faster then ever. Of course, if you have too many markers, you will first see the default marker icon which gets replaced trough the downloaded marker - but this behaviour is better I guess. Maybe you now (I'm really not an experienced Obj-C developer) how to improve this.

Next thing is to support markers from file:/// path, then we could download markers outside of the Maps Plugin and pass the internal file:/// documents AND tmp path. I know this should be possible to implement. Hope you can help after your car works fine again.

**Comment by Hirbod** [comment]
And I think there is still more potential optimizing this:
http://khanlou.com/2012/08/asynchronous-downloaded-images-with-caching/

**Comment by Hirbod** [comment]
Changed the code a little bit:

```C
} else {
      /***
       * Load the icon from over the internet
       */
      NSData *imgData = [self.iconCache objectForKey:iconPath];
      if (imgData != nil) {
        UIImage* image = [UIImage imageWithData:imgData];
        if (width && height) {
          image = [image resize:width height:height];
        }
        marker.icon = image;
        [self.commandDelegate sendPluginResult:pluginResult callbackId:callbackId];
      } else {
        //dispatch_queue_t gueue = dispatch_queue_create("GoogleMap_addMarker", NULL);
        dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0ul);
        dispatch_async(queue, ^{

          NSURL *url = [NSURL URLWithString:iconPath];
          //NSData *data = [NSData dataWithContentsOfURL:url options:NSDataReadingMapped error:nil];
          
            // download the image asynchronously
            [self downloadImageWithURL:url completionBlock:^(BOOL succeeded, UIImage *image) {
                if (succeeded) {
                    
                    if (width && height) {
                        image = [image resize:width height:height];
                    }
                    
                    dispatch_async(dispatch_get_main_queue(), ^{
                        marker.icon = image;
                        
                        // The `anchor` property for the icon
                        if ([iconProperty valueForKey:@"anchor"]) {
                            NSArray *points = [iconProperty valueForKey:@"anchor"];
                            CGFloat anchorX = [[points objectAtIndex:0] floatValue] / image.size.width;
                            CGFloat anchorY = [[points objectAtIndex:1] floatValue] / image.size.height;
                            marker.groundAnchor = CGPointMake(anchorX, anchorY);
                        }
                        
                        
                        // The `infoWindowAnchor` property
                        if ([iconProperty valueForKey:@"infoWindowAnchor"]) {
                            NSArray *points = [iconProperty valueForKey:@"infoWindowAnchor"];
                            CGFloat anchorX = [[points objectAtIndex:0] floatValue] / image.size.width;
                            CGFloat anchorY = [[points objectAtIndex:1] floatValue] / image.size.height;
                            marker.infoWindowAnchor = CGPointMake(anchorX, anchorY);
                        }
                        
                        NSData *imgData = UIImagePNGRepresentation(image);
                        [self.iconCache setObject:imgData forKey:iconPath];
                        
                        
                        [self.commandDelegate sendPluginResult:pluginResult callbackId:callbackId];

                    });
                    
                }
            }];
        
        });
        
      }
    }
```

I think it is a bit more performant now (High priority) but the iconCache seems not to work...

**Comment by wf9a5m75** [comment]
It's midnight, and I finally get my private time. I'm reading your posts now.

**Comment by wf9a5m75** [comment]
@Hirbod 
Thank you for great work, and your code is really good.

One point, the reason of `dispatch_sync` is that some one asked to me before for that.
He wanted to hide markers until the icon images are loaded.
And I agree with this idea.

For the reason, I will modify a little your code. Just a moment.

**Comment by wf9a5m75** [comment]
![modified](https://cloud.githubusercontent.com/assets/167831/5891121/40e7177c-a437-11e4-8cd6-e38284209740.gif)

**Comment by wf9a5m75** [comment]
@Hirbod 
As I mentioned, I added some code. But basically it's your great code.
Thank you so much :100:

**Comment by Hirbod** [comment]
Hi Masashi,
wow, thanks for your reply and code modificaiton. Indeed, this is handled a bit better know. Still I don't understand isMapped (what is this for?) but the rest looks good to me.

Now just incoporate the watchdog and then please, release 1.2.5.
I guess this optimization was something really important cause now the map will not block the UI anymore when loading images from remote.
