### ISSUE TITLE
Plugin is not defined.

### ISSUE THREAD

**Issue by armonb** [wf9a5m75/phonegap-googlemaps-plugin#343]
I am using the Ionic framework and have installed this plugin. My cordova plugin list is showing it as successfully installed:
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.3 "Keyboard"
org.apache.cordova.console 0.2.12 "Console"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.geolocation 0.3.11 "Geolocation"
org.apache.cordova.network-information 0.2.14 "Network Information"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"

However when running the project I get the "plugin is not defined" error in the console. Is anyone able to advise on what may be causing this error and how it can be resolved?

Thanks.

**Comment by Hirbod** [comment]
iOS or Android?

**Comment by juniusrendel** [comment]
I had the same problem when I was automating build, I wrote a python script that called `cordova plugin add plugin.google.maps` and it wasn't waiting for the plugin to be really installed. I had to remove the plugin and its dependencies and install again. Everything works fine now...

**Comment by crododile** [comment]
I have same problem on android, map plugin works great on clean install and first opening, but closing and reopening the app plugin is not defined.

**Comment by wf9a5m75** [comment]
@crododile 
Could you send me your apk file to my e-mail address, wf9a5m75@gmail.com ?

**Comment by crododile** [comment]
I'm afraid I can't send apk, posting my resolution on github Thanks this
plugin is awesome

On Thu, Jan 15, 2015 at 3:59 PM, Masashi Katsumata <notifications@github.com

**Comment by crododile** [comment]
@wf9a5m75  
Thanks for the excellent plugin and for responding, I've found that it is some sort load timing issue. 
Only when the map is on the first view to load does it not work, or if on the first view wrapping map initialization in setTimeout works fine. I suppose I need to learn about more about Ionic app boot process

**Comment by wf9a5m75** [comment]
Ok, sounds good.
