### ISSUE TITLE
unable to uninstall plugin

### ISSUE THREAD

**Issue by edelworksgithub** [wf9a5m75/phonegap-googlemaps-plugin#344]
I had installed Google maps plugin in my system. I had added only android platform. While uninstalling its displaying
Error:ENOENT, no such file or directory {project directory}/plugins/com.googlemaps.ios/plugin.xml

![error-uninstalling](https://cloud.githubusercontent.com/assets/8638256/5612732/94021fca-94ff-11e4-9ebc-3349232367fd.jpg)

**Comment by wf9a5m75** [comment]
I have no idea.

**Comment by edelworksgithub** [comment]
Thanks. No probs
