### ISSUE TITLE
LocationClient cannot be resolved error

### ISSUE THREAD

**Issue by oneto018** [wf9a5m75/phonegap-googlemaps-plugin#345]
My cordova project already uses google play services. When I tried to import this plugin am getting following error in eclipse 

Description	Resource	Path	Location	Type
LocationClient cannot be resolved to a type	GoogleMaps.java	/MeDine/src/plugin/google/maps	line 118	Java Problem

**Comment by wf9a5m75** [comment]
Probably you are missing "com.google.playservices" plugin.
https://github.com/wf9a5m75/google-play-services

**Comment by oneto018** [comment]
I have google play services. But I have the latest version of the library. That version removed location client class completely

**Comment by wf9a5m75** [comment]
Even though, this plugin specifies the previous version on my repository.

**Comment by oneto018** [comment]
yes it does. but I am already using google play services library for a new function. I can't use both version of the library in same project. And google play services is being updated to devices very often. So even if the app compiles properly with older version of the library , it would crash or not work in new version of the phones. Anyway fixing this issue properly will solve that https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/158. until that this plugin would be unusable in newer devices

**Comment by wf9a5m75** [comment]
FusedLocationProviderApi did not work properly on some devices, the api never response, even if I set the timeout. So I enrolled back to LocationClient class.

**Comment by oneto018** [comment]
I think to get this thing work on all os is to check which one (fused location provider or locationclient)  and conditionally execute . But I haven't got any clue how that would be possible. Anyway hopefully in near future it would become more clear. Thank you for response

**Comment by wf9a5m75** [comment]
I'll keep in mind, and test it in near future.

**Comment by wf9a5m75** [comment]
@oneto018 
I updated the plugin code for Google Play Services v22. It's available on the test branch.
Check it out.
```
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
```

**Comment by iamwolf** [comment]
I will check the v22 release. Downgrading to v19 broke everything.

**Comment by wf9a5m75** [comment]
v22 is here.
https://github.com/wf9a5m75/google-play-services/tree/v22

```
$> cordova plugin rm com.google.playservices
$> cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
```
