### ISSUE TITLE
PhoneGap build

### ISSUE THREAD

**Issue by stoskoverflowcomunity** [wf9a5m75/phonegap-googlemaps-plugin#347]
So, why to use this plugin when there is no option for building .apk file and instaling on phone?

Or its maybe possible to use this with javascript code and build .apk?

I only need this plugin becouse google android map sdk allow compass mode...

**Comment by wf9a5m75** [comment]
This plugin does not support PhoneGap Build, because this plugin uses native Android Google Maps Android API v2 (Java) and Google Maps SDK for iOS (Objective-C).
PhoneGap Build does not allow to use these binary libraries.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Phonegap-Usage#phonegap-build-is-not-available

**Comment by aramgev** [comment]
Phonegap Build has already supported such plugins:

http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/

**Comment by wf9a5m75** [comment]
Oh, I didn't know that! It's really good news!

**Comment by aramgev** [comment]
But I tried it, map isn't shown :(

In logcat I see these lines: 
E/GooglePlayServicesUtil(21116): The Google Play services resources were not fou
nd. Check your project configuration to ensure that the resources are included.
E/GooglePlayServicesUtil(21116): The Google Play services resources were not fou
nd. Check your project configuration to ensure that the resources are included.
W/dalvikvm(21116): VFY: unable to resolve static field 2499 (MapAttrs) in Lcom/g
oogle/android/gms/R$styleable;
W/CordovaPlugin(21116): Attempted to send a second callback for ID: GoogleMaps18
17103905
W/CordovaPlugin(21116): Result was: "No result"

**Comment by wf9a5m75** [comment]
Probably the version of the google play services plugin is mismatch. This plugin still uses v21.
(Updating v22 is under construction)

**Comment by aramgev** [comment]
And approximately when it will be ready?

**Comment by wf9a5m75** [comment]
I have no idea, unfortunately.

**Comment by aramgev** [comment]
Ok, thanks. But it doesn't work on IOS too.

**Comment by wf9a5m75** [comment]
You know, I haven't tested Phonegap build at all. And I'm really busy. Please wait.

**Comment by wf9a5m75** [comment]
@aramgev 
According to #411 , @MichaelGooden uses this plugin on PhoneGap.

I merge this issue to #411
