### ISSUE TITLE
map.remove() issue on iOS

### ISSUE THREAD

**Issue by juniusrendel** [wf9a5m75/phonegap-googlemaps-plugin#348]
Hello, thank you for this amazing work.
I don't know if this is a bug, but if it is not, it is a kind of inconsistency.
I'm using angular, there are several views in my app, the map is on one of these.
When I change the location of the page (and then the view) I call the `map.remove();` method.
There is no problem on Android, the map is totally destroyed, everything is alright. But on iOS, when the map is destroyed, the zone where the map was still prevent the click propagation and the links behind it remains unclickable. I have to call `map.setClickable(false);` before removing the map in order to avoid that.

**Comment by wf9a5m75** [comment]
Take screen captures, please.

**Comment by juniusrendel** [comment]
(I used android to make screenshots but the problem is on iOS)
![explain jpg](https://cloud.githubusercontent.com/assets/3089875/5643097/3cdfbd96-9654-11e4-8228-185db447c228.jpeg)

**Comment by wf9a5m75** [comment]
@juniusrendel 
Thank you for taking screen captures. I reviewed the code, and your report is corrected.
Apply the patch https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/699fefa87970cf905da7a6c4356d260fc78d446a by your hand, or re-install the plugin from test branch.
You don't need to `map.setClickable(false)` before `map.remove()` anymore.

**Comment by juniusrendel** [comment]
Thank you!
