### ISSUE TITLE
Map not fully initialised on Nexus 5/Android 5 Lollipop

### ISSUE THREAD

**Issue by iamwolf** [wf9a5m75/phonegap-googlemaps-plugin#351]
Hey!
I've developed an app using Cordova and this fantastic plugin. It works fine on my physical test devices (both running 4.4.2 KitKat), and in the simulator (Genymotion, Nexus 5 Android 5.0.0. Lollipop image). However, I received a report including screenshots that the map does not fully load on Android 5 Lollipop on the Nexus 5 (which it does in simulation). 
![Map not fully initialised](https://cloud.githubusercontent.com/assets/1664508/5679298/aafed7b2-97fd-11e4-942d-5d0a78d0c7f3.png)
It partially loads, i.e. it shows the +/- buttons to zoom, but no map tiles are loaded. Internet connection on the device is on since the other features work and load data from the internet. Unfortunately, I do not see the debug output (errors, etc.) since I do not have the device here. Are there any known issues/incompatibilities with Nexus 5/Android 5 Lollipop that do not surface in a simulator?

NB: It works with Google Play Services version ...-470, and fails with ...-438.

```bash
$> cordova plugin list:
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.3 "Keyboard"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.geolocation 0.3.12-dev "Geolocation"
org.apache.cordova.inappbrowser 0.5.5-dev "InAppBrowser"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"
```

Thanks

**Comment by iamwolf** [comment]
Any news? I've been getting tons of people reporting issues with this. Is there any way to reproduce it or catch it and have a back up map show/error message?

**Comment by iamwolf** [comment]
Might be related to #332

**Comment by wf9a5m75** [comment]
The test branch code works with google play services **v22** (Not v21)

Try the test branch.
```
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
```

**Comment by wf9a5m75** [comment]
The same as with #345

**Comment by heks** [comment]
I've done this and my map still does not render

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/TroubleShooting:-Blank-Map

**Comment by iamwolf** [comment]
@heks Check whether you got both the DEBUG and RELEASE key SHA1 hashes entered into the Google API Console permissions.

**Comment by heks** [comment]
Thanks guys everything worked, you guys are great. If I sign the app for release (http://developer.android.com/tools/publishing/app-signing.html - all the way at the bottom), Im assuming I also have to add that new SHA1 key to Google API Console?

**Comment by iamwolf** [comment]
Yes, exactly

**Comment by wf9a5m75** [comment]
Thank you for your assistant @iamwolf

**Comment by iamwolf** [comment]
Thanks providing the community with a fantastic plug-in! :)
