### ISSUE TITLE
App crash randomly when receive ERROR: null

### ISSUE THREAD

**Issue by jianbo** [wf9a5m75/phonegap-googlemaps-plugin#352]
I am using Ionic framework, my map view crash randomly with following errors, even home key doesn't work, had to wait for about a minute still it quit itself .

2015-01-10 23:00:31.270 App[1123:60b] ERROR: null
2015-01-10 23:00:31.271 App[1123:60b] ERROR: null
2015-01-10 23:00:31.271 App[1123:60b] ERROR: null

**Comment by wf9a5m75** [comment]
Too much unclear. Please figure out the details in order to help.

**Comment by jianbo** [comment]
I am using version 1.2.4. The error occurs only on IOS with following code

  function initialize (div, coords, zoom){
    if (!coords){
      coords = $rootScope.currentLocation;
    }
    try{
      center = new plugin.google.maps.LatLng(coords.latitude, coords.longitude);
    }catch(e){
      console.log("Plugin is not available!");
      return 
    }

    if (!center){
        throw new Exception("Map cannot init without a center!");
    }

    var mapDiv = document.getElementById(div);
		  // Initialize the map plugin
      map = plugin.google.maps.Map.getMap(mapDiv);
    	console.log("map initialized");
      map.setOptions({
      'controls': {
        'compass': true,
        'indoorPicker': true,
        'myLocationButton': true,
        'zoom': false
      },
      'gestures': {
        'scroll': true,
        'tilt': true,
        'rotate': true
      },
      'camera': {
        'latLng': center,
        'zoom': (zoom||15)
      }
    });
      console.log("...........has map?")
    if (map){
         map.moveCamera({
          'target': center,
          'zoom': (zoom||15)
        });
      map.setClickable(true);
      map.clear();   
    }
    return map;
  }

**Comment by jianbo** [comment]
After the map is setup, I am looping through array of markers and call this function every time. Could this be the problem if I have over 300 markers?

    function addMarker(latLng, title, icon, _callback){
  	markerOptions = {
  	   'position': latLng
  	}
  	if (title){
  		markerOptions['title'] = title;
  	}
  	if (icon){
  		markerOptions['icon'] = icon
  	}
  //   'icon': 'www/img/icon-yellow.png'
  	map.addMarker(markerOptions, function(marker){
  		if (_callback){
  			_callback(marker);
  		}
  		if (icon){
  			marker.setIcon({
  				'url': icon
  			});
  		}
  	});   
  }

**Comment by jianbo** [comment]
This is the loop
  	angular.forEach($scope.array, function(item){
			if (item.coords){
				var position = new plugin.google.maps.LatLng(item.coords.latitude, item.coords.longitude);
				mapService.addMarker(
						position,
						item.name, 
						null,
						function(marker){
							marker.addEventListener(plugin.google.maps.event.INFO_CLICK, function() {
						
							});
						});
			}
		});

**Comment by wf9a5m75** [comment]
At least, you should wait `MAP_READY` event.

```js
function initialize(div, coords, zoom, callback) {
    var mapDiv = document.getElementById(div);
    // Initialize the map plugin
    map = plugin.google.maps.Map.getMap(mapDiv, {
        'controls': {
            'compass': true,
            'indoorPicker': true,
            'myLocationButton': true,
            'zoom': false
        },
        'gestures': {
            'scroll': true,
            'tilt': true,
            'rotate': true
        },
        'camera': {
            'latLng': center,
            'zoom': (zoom || 15)
        }
    });

    map.on(plugin.google.maps.event.MAP_READY, function() {
        console.log("map initialized");
        console.log("...........has map?")
        if (map) {
            map.moveCamera({
                'target': center,
                'zoom': (zoom || 15)
            });
            map.setClickable(true);
            map.clear();
        }

        callback(map);
    });
}
```

**Comment by jianbo** [comment]
Hi there,

    I tried to put everything inside the init callback, but it still crashes randomly, I found the ERROR: null is caused by scope.homeStoreMap.setClickable(true);

Any idea?
Thanks

		$scope.homeStoreMap = plugin.google.maps.Map.getMap(document.getElementById("map_canvas"));
		$scope.homeStoreMap.on(plugin.google.maps.event.MAP_READY, function(myMap){
			var center = plugin.google.maps.LatLng($rootScope.currentLocation.latitude, $rootScope.currentLocation.latitude);
			console.log(".........check0")
			$timeout(function(){
			    $scope.homeStoreMap.setOptions({
			        'controls': {
			          'compass': true,
			          'indoorPicker': true,
			          'myLocationButton': true,
			          'zoom': false
			        },
			        'gestures': {
			          'scroll': true,
			          'tilt': true,
			          'rotate': true
			        },
			        'camera': {
			          'latLng': center,
			          'zoom': (zoom||15)
			        }
			    });
			    
			    $scope.homeStoreMap.moveCamera({
		        'target': center,
		        'zoom': 15
		   		});
			});

		    
			    $scope.homeStoreMap.setVisible(true);
			    // $scope.homeStoreMap.setClickable(true);



    		angular.forEach($scope.stores, function(store){
				// console.log(".........checkxx" + store.name)
				if (store.coords && store.coords.latitude && store.coords.longitude){
				  	$scope.homeStoreMap.addMarker({
				  	   'position': new plugin.google.maps.LatLng(store.coords.latitude, store.coords.longitude),
				  	   'title': store.name,

				  	});   
				}
			});
	    });

**Comment by wf9a5m75** [comment]
Error null is Cordova bug. It's.not related. Please show me the actual error log.

**Comment by jianbo** [comment]
There is no other error log at all, it crash all by chance when I switch betwee map views, maybe I can put something together something in Github.

**Comment by wf9a5m75** [comment]
Could you send me your apk file to my e-mail address directly?

**Comment by jianbo** [comment]
Do you mean Achieve IPA file? Because it only happens to IOS version. Just confirm the email address: wf9a5m75@gmail.com, will send it to  you by today. I have donated some money for your time.

**Comment by wf9a5m75** [comment]
Oops, you are developing on iOS. Yes, send me your IPA file.

**Comment by Hirbod** [comment]
You can't transfer an IPA archive without the hassle of getting Masashi's UDID. After this, you need to register his UDID with the apple developer "Devices" and refetch the new provisioning profiles. Or use Testflightapp

**Comment by Hirbod** [comment]
HA!
I know why your app is crashing. It is exactly the same shit I have! I'm 100% sure that you are loading your markers from remote, (http), am I right?

**Comment by wf9a5m75** [comment]
Ah, yeah. I forgot about that. Thank you for point out.

I will reply my UUID when @jianbo send me your IPA file.

**Comment by Hirbod** [comment]
Bet a 100 bugs.... #337

**Comment by jianbo** [comment]
No man, my markers are loaded from array.
 		angular.forEach($scope.stores, function(store){
				// console.log(".........checkxx" + store.name)
				if (store.coords && store.coords.latitude && store.coords.longitude){
				  	$scope.homeStoreMap.addMarker({
				  	   'position': new plugin.google.maps.LatLng(store.coords.latitude, store.coords.longitude),
				  	   'title': store.name,

				  	});   
				}
			});

**Comment by Hirbod** [comment]
And where are your marker images? Inside your www folder? Or on your server?

**Comment by jianbo** [comment]
No, I am using the default marker, no custom icon at all.

**Comment by Hirbod** [comment]
OK - so wrong alarm. Cause this is my problem. I could load 1000 markers without any problem, as long as I used the default marker. With remote marker images, my app crashed.

**Comment by jianbo** [comment]
I will send the IPA later when I got back, but is this the right thing to do? I am using Ionic, so when left a map view, I had to clear the map, and when you arrive at another map view, I am re-initialize the newmap view. this is what I do when left a view.

     $scope.$on('$destroy', function() {
    	if ($scope.homeStoreMap){
	      $scope.StoreMap.setVisible(false);
	      $scope.StoreMap.removeEventListener();
	      $scope.StoreMap.setClickable(false);
	      $scope.StoreMap.clear();
    	}
    });

**Comment by Hirbod** [comment]
Actually it should be enough just to call ```$scope.StoreMap.remove()```

**Comment by jianbo** [comment]
Im unable to reproduce the problem after reduce the marker to 40, and only able to reproduce once when there is 80 markers.

**Comment by xuzongque** [comment]
I'm not sure it will solve the crash problem, but I found the reason for the message "ERROR:null" printed out at console.

in ` - setIcon` method of `Marker.m`

```
-(void)setIcon:(CDVInvokedUrlCommand *)command
{
  NSString *markerKey = [command.arguments objectAtIndex:1];
  GMSMarker *marker = [self.mapCtrl.overlayManager objectForKey:markerKey];
  
  CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_NO_RESULT];
  [pluginResult setKeepCallbackAsBool:YES];
  [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
  
  // Create icon
  pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
  NSDictionary *iconProperty = [command.arguments objectAtIndex:2];
  [self setIcon_:marker iconProperty:iconProperty pluginResult:pluginResult callbackId:command.callbackId];
}
```

The `[self.commandDelegate sendPluginResult]` in the middle should be unnecessary, because the `[self setIcon_]` method in the end will also send results to cordova. There is another spot in `-createMarker` that is similar to this situation, at line 95.
Comment out those lines and there will be no "ERROR:null" in console anymore
Also,  `[self setIcon_]` expects the iconProperty to be a `NSDictionary *`, so yes, need to pass in `{url: '...'}` from javascript.

**Comment by Hirbod** [comment]
You're right @xuzongque,

I think this is a copy & paste error. I guess this should be removed or wrapped around some if-else-statement @wf9a5m75

**Comment by wf9a5m75** [comment]
Thank you @xuzongque
