### ISSUE TITLE
How to remove bind click event

### ISSUE THREAD

**Issue by jianbo** [wf9a5m75/phonegap-googlemaps-plugin#353]
I added map click event like this:
map.on(plugin.google.maps.event.MAP_CLICK, function(latLng) {
  alert("Map is clicked.\n" + latLng.toUrlValue());
});

But how do I remove the bind event, when user left the map view, I want to hide the map and remove the event, currently I use map.remove() to remove the map completely.

Thanks

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/BaseClass

**Comment by Hirbod** [comment]
You're welcome.

**Comment by wf9a5m75** [comment]
Thanks, @Hirbod
