### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by alexislg2** [wf9a5m75/phonegap-googlemaps-plugin#356]
Would it be possible to use a background image instead of a color?

**Comment by wf9a5m75** [comment]
No

**Comment by siran** [comment]
Does this issue has to do with the fact that the map is 'below' the background-image of the "page"? (Im using jquerymobile/cordova/android)

**Comment by wf9a5m75** [comment]
Since this plugin uses native Google Maps (java and objective-c), the map view is located `under` the browser.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#how-does-the-plugin-work

**Comment by siran** [comment]
Thank you!

**Comment by Hirbod** [comment]
won't implement
