### ISSUE TITLE
Map markers don't display for some coordinate combinations

### ISSUE THREAD

**Issue by rwtaylorjr** [wf9a5m75/phonegap-googlemaps-plugin#357]
Greetings,

I have a hybrid app running Angular and Cordova 3.6.3. 

When a user selects an item in a list, the map displays the coordinates associated with that item. While testing this, i noticed that the map behaves as expected (markers display on the map within the specified boundary) when the coordinates are on the same continent. 
However, i was testing a coordinate combination where two coordinates were in India and one coordinate was in the US. For this use case, no markers displayed. However, my debug statements indicate that the markers were successfully added and the camera completed moving. No errors were generated in the logs.

```js
var latLngBounds = new window.plugin.google.maps.LatLngBounds(bounds);
var map = window.plugin.google.maps.Map.getMap(elem, options);


if (!map.initialized) {
    map.on(window.plugin.google.maps.event.MAP_READY, function() {
        //map.clear(); // clear any previous markers
        map.setClickable(false);
        angular.forEach(markers, function(m) {
            map.addMarker(m, function(marker) {
                $log.debug("marker added: %s", marker.getId());
            });
        });

        if (bounds.length > 1) {
            map.animateCamera({
                'target': latLngBounds,
                'duration': 100
            }, function() {
                $log.debug('Done moving camera');
            });
        }

        map.initialized = true;
    });

}
```

Relative console output:
```
    marker added: marker_m0 angular.js:10072
    marker added: marker_m1 angular.js:10072
    marker added: marker_m2 angular.js:10072
    Done moving camera 
```

However the map displays centered around the equator and the Atlantic ocean with the Zoom appearing to be all the way out (not sure exactly what the zoom value is). 
It's like the LatLngBounds is getting ignored and the markers not getting placed on the map.

Testing on Android 4.4.2 only for now.

**Comment by rwtaylorjr** [comment]
Hmmmm....maybe the markers are getting added, but i just cannot see them. My default zoom setting for the map is 12. I assumed that the animate.camera would zoom to the appropriate value given the latLngBounds.

**Comment by rwtaylorjr** [comment]
yep...the markers are there, its just not zoomed out far enough.
i reset the map zoom level to 19, but that didn't seem to help.

**Comment by rwtaylorjr** [comment]
I believe i'm at the max zoom level is not enough to display all the markers in the specified boundaries.
This may be just a limitation i need to deal with.

**Comment by rwtaylorjr** [comment]
So the question remains is how to notify the user when markers are within the LatLngBoundaries but outside the view port?

**Comment by wf9a5m75** [comment]
Could you show me the value of bounds?
The variable `bounds` should be like this:
```js
var bounds = [
  new plugin.google.maps.LatLng(41.79883, 140.75675),
     ....
  new plugin.google.maps.LatLng(41.79883, 140.75673)
];
var latLngBounds = new plugin.google.maps.LatLngBounds(bounds);
```

**Comment by rwtaylorjr** [comment]
The bounds array is an array of plugin.google.maps.LatLng(...) objects with valid geo coordinates.
You should be able to reproduce on android or ios phone by placing a coordinate in india and a coordinate in the us. Set the latLngBounds and open the map. The map centers somewhere between the two countries with max zoom. But the view port doesn't allow you to see the markers. Naturally, you could move the map to see the markers, but for my application, the map is embedded and the requirement is for no map interactivity.

**Comment by wf9a5m75** [comment]
```js
var bounds = [
  new plugin.google.maps.LatLng(28.556162,77.099958), //india
  new plugin.google.maps.LatLng(37.621313,-122.378955) // usa
];
bounds.forEach(function(position) {
  map.addMarker({
    position: position
  });
});

map.animateCamera({
  'target': bounds
}, function() {
    $log.debug('Done moving camera');
});
```

The above code works like this. This is natural behavior of Google Maps SDK.
![357](https://cloud.githubusercontent.com/assets/167831/5891226/9ce17ff8-a43d-11e4-98ef-67775cefa78e.gif)

And if you don't need the map interactivity, I recommend you use Google Static Map API. It's very easy than this plugin, and so fast.
