### ISSUE TITLE
Does external service support more than one destination?

### ISSUE THREAD

**Issue by rwtaylorjr** [wf9a5m75/phonegap-googlemaps-plugin#359]
I would like for the external.launchNavigation(...) to behave the same way the Javascript Google Maps API does when launching an external map with multiple destinations (a route with way points) instead of just a single destination.

The externalService API seems to imply that it only takes a single origin and destination.
Also, looking at the code, it seems to  only supports a single origin and destination.

Any plans on adding this functionality?

**Comment by wf9a5m75** [comment]
Google Maps app does not support that feature, so I can not.

**Comment by rwtaylorjr** [comment]
Ok...i guess i was thinking about the Google Maps iOS url scheme which should launch the native google maps application and support directions, etc....
https://developers.google.com/maps/documentation/ios/urlscheme

I don't think Android has an equivalent approach that will support directions.
The problem i have with my hybrid app, is that when the user is viewing the app in a browser and launches maps externally, they get one behavior (driving directions with mapped out way points), however, when they are viewing the app in a mobile device and launch the map externally, then they get driving directions but without the way points.

Not sure how to make this consistent between browser, android, and ios.

**Comment by wf9a5m75** [comment]
Please send me a pull request if you find out a better way.

Android code is here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/External.java

And iOS code is here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/External.m
