### ISSUE TITLE
Problem with addKmlOverlay on AppGyver

### ISSUE THREAD

**Issue by key4625** [wf9a5m75/phonegap-googlemaps-plugin#362]
Hello everyone, I have a problem during loading of a kml under Appgyver. I placed the code in function onMapInit(map) {} I'm doing well? There are  known issues about this?

**Comment by wf9a5m75** [comment]
Please tell me your code.
And what is the problem?
Where do you place your kml file, in your app, or loading from external server?
Is there any error message in the logcat?

**Comment by key4625** [comment]
Hello , sorry for the delay , here's the code:
<script type="text/javascript">
    var map;
    
    document.addEventListener("deviceready", function() {  
      const MARCHE = new plugin.google.maps.LatLng(43.3254945,13.0771565);
     map  = plugin.google.maps.Map.getMap({
          'backgroundColor': 'transparent',
          'mapType': plugin.google.maps.MapTypeId.HYBRID,
          'controls': {
            'compass': true,
            'myLocationButton': true,
            'indoorPicker': true,
            'zoom': true
          },
          'gestures': {
            'scroll': true,
            'tilt': true,
            'rotate': true
          },
          'camera': {
            'latLng': MARCHE,
            'tilt': 0,
            'zoom': 10,
            'bearing': 0
          }
      });     
     
      var div = document.getElementById("map_canvas");
      map = plugin.google.maps.Map.getMap(div);
      
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapInit);
      
   
    }, false);
    function onMapInit(map) {
       const MARCHE = new plugin.google.maps.LatLng(43.3254945,13.0771565);
        map.addKmlOverlay({
          'url': "example/kml/elcito.kml"
        });
        var Marker = supersonic.data.model('Marker');
        Marker.findAll().then( function(allMarkers) {
          console.log("the first was " + allMarkers[0].name);
          for (i = 0; i < allMarkers.length; i++) {
            console.log(allMarkers[i].Nome + " by " + allMarkers[i].Lat + " brewed since " + allMarkers[i].Long);
             map.addMarker({
                'position': new plugin.google.maps.LatLng(allMarkers[i].Lat,allMarkers[i].Long),
                'title': allMarkers[i].Nome,
                 'snippet': allMarkers[i].descrizione
             }); 
          }
        });     
      map.showDialog(); 
    }
    </script>

**Comment by key4625** [comment]
I've tried to change the url of kml in a lot of way..  'url': "example/kml/elcito.kml" 
Example is the name of the selected App in appgyver multi-app project.

**Comment by wf9a5m75** [comment]
start with www/

**Comment by key4625** [comment]
I don't have folders starting with www in my project , I have a folder named app where inside there is the folder " views" , the folder " scripts " and the folder that I've created " kml " . The code I wrote is in the folder views...  In any case I will continue to investigate , maybe building a new app , then I'll let you know something. Thank you so much for what you're sharing.

**Comment by wf9a5m75** [comment]
Even though, the plugin assems the local path from www.

**Comment by key4625** [comment]
I've created a fresh app with a single-page. In this project there is the www folder and I wrote this 
map.addKmlOverlay({
        'url': "www/kml/marker.kml"
      }); 
on map init event but nothing appear, i tried with other kml to.. nothing
I don't know

**Comment by key4625** [comment]
I've done it compiling on cloud with appgyver_test2 branch, it is a version problem?

**Comment by yedeba** [comment]
Hello, sorry, one question.
I thought for appgyver not work this plugin.
Then, is it possible to integrate?

**Comment by key4625** [comment]
I've try successufully the appgyver_test2 branch but the last branch no longer work...

**Comment by wf9a5m75** [comment]
Regarding of AppGyver, this plugin works with it. However there are some problems.
Ask to @bFlood, he uses this plugin on AppGyver.

**Comment by wf9a5m75** [comment]
@key4625 Have you been trying to use this plugin with AppGyver?

**Comment by bFlood** [comment]
I haven't tried addKmlOverlay from appgyver but everything else seems to be working

**Comment by key4625** [comment]
I confirm that everything working except the addKml feature.. I don't know why.. For the moment , however , I stopped make use of it , because I started to develop from the native Android system and OpenStreetMap

**Comment by wf9a5m75** [comment]
addKmlOverlay cannot load KML files from local path currently.
(I'm planing though, there is no enough time)

Thanks, @bFlood

**Comment by bFlood** [comment]
appgyver can serve file from the local path, try using http://localhost/some_file_in_app_user_folder.kml

I use this to serve locally cache tiles when needed, so it works for TileOverlays

**Comment by MichaelGooden** [comment]
I have had problems with addKml on iOS. It was crashing on the same kml
files that worked on Android.

I simplified the kml file and then it worked.

**Comment by MichaelGooden** [comment]
@wf9a5m75 I can load KML files from local path successfully?
```js
  map.addKmlOverlay({
    'url': "www/kml/map.kml"
  }, function(kmlOverlay) {
    console.log("add kml overlay success");
    /* ........ */
  });
```

**Comment by wf9a5m75** [comment]
@MichaelGooden The code is fine. I think there is/are some problem in the kml file.
The KML file parser is written by myself, but the xml file parser inside of the KML parser are different Android and iOS.
Do you mind if you share the KML file with me?

**Comment by MichaelGooden** [comment]
Going to open a separate issue for this.

**Comment by wf9a5m75** [comment]
@MichaelGooden :+1:

**Comment by wf9a5m75** [comment]
I close this issue at once, because there is no news.
If you have additional information, just post here.
