### ISSUE TITLE
map.showDialog() is taking time to open map dialog on iOS

### ISSUE THREAD

**Issue by nishithrajyaguru** [wf9a5m75/phonegap-googlemaps-plugin#363]
Hi Masashi,

I am using your plugin to show google map in our application. Thanks for making this plugin.

I am using below command to add the map plugins in the application.

cordova plugin add plugin.google.maps --variable API_KEY_FOR_IOS="our_ios_key"

When I try to show the map dialog by calling map.showDialog(), nothing happens for 3-4 minutes. Map is getting open after this time interval. I tried by putting MAP_READY event to check this. This event is getting fired after 3-4 minutes. This problem was not coming earlier.

also, we were using below command in past. But it is not working anymore for us.

cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_IOS="our_ios_key"

Please help me for this problem.

**Comment by wf9a5m75** [comment]
Do you use other plugins?

**Comment by nishithrajyaguru** [comment]
I am using other plugins like File, File-transfer, geo-location, device, imagepicker, camera etc. But any of them are not related to map.

**Comment by wf9a5m75** [comment]
Try to create a simple project just use the map plugin, and write a small
code for test.

**Comment by nishithrajyaguru** [comment]
Thank for your reply. I will try to create a simple project and add map plugin and I will see if it works.
