### ISSUE TITLE
Cannot click on Ionic components inside the Map

### ISSUE THREAD

**Issue by rougin** [wf9a5m75/phonegap-googlemaps-plugin#365]
Hello! I am using this plugin now and it's nice. The problem is that when I try to insert an Ionic component inside the map, there was no response. When I double tap it, the map zooms. Here is my code about this:
```
<div id="map-canvas">
	<label class="item item-input">
		<i class="icon ion-search placeholder-icon"></i>
		<input type="text" placeholder="Search a place here" ng-model="keyword" id="keyword" ng-keyup="search(keyword)">
	</label>
	<div class="list">
		<div class="item" ng-repeat="place in places | filter:keyword" ng-show="keyword" ng-hide="clear" ng-click="searchPlace(place)">
			<span>{{ place.name }}</span>
			<p>{{ place.type }}</p>
		</div>
	</div>
</div>
```

**Comment by rougin** [comment]
I'm sorry. I missed something in the documention. I forgot to read ```map.setClickable()```.

**Comment by felquis** [comment]
I'm trying to set `map.setClickable()` when the popover is shown, but it's not working well..

map should be a global variable?

**Comment by rougin** [comment]
@felquis Yes. Set map as a global variable.
