### ISSUE TITLE
Getting warning on Xcode.

### ISSUE THREAD

**Issue by ramsabarish** [wf9a5m75/phonegap-googlemaps-plugin#366]
I have successfully implemented the plugin but on Xcode  I get this warning. 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/

 Debug Session On Xcode  shows that My App is consuming more 140 mb  of memory. 

This is my First mobile App  kindly tell me what am I supposed to do .

**Comment by wf9a5m75** [comment]
```
Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
```
The above messages are always displayed, so just ignore them.

```
Debug Session On Xcode shows that My App is consuming more 140 mb of memory.
```
I think your app uses too much memory (such as your app loads many photo files).

**Comment by ramsabarish** [comment]
Okay...

In my app I'm  showing  information about nearby places .  I'm  using  Google Maps Places Library for JavaScript. It provides information about nearby places and also provides a map but that is not  responsive , so I  have used  Phonegap Google Maps Plugin  to show the map  and I fetch nearby places information from  Google Maps Places Library.   

So  now  I have  2  maps in my  App but  I  only show the map that is provided by the plugin . I guess its because of the 2 maps, my App is consuming more memory. 


 Kindly tell me is there a better way to tackle this issue .

**Comment by Hirbod** [comment]
Just get the result of the JS-Api and display it on the real map - without displaying the JS map

**Comment by wf9a5m75** [comment]
@ramsabarish Please follow with the @Hirbod 's advice.

**Comment by ramsabarish** [comment]
OK...Thanx a lot ...
