### ISSUE TITLE
Icon from file:/// not possible

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#368]
Dear Masashi...

I'm going insane. Tried to fixed the #337 bug and wrote a CachePlugin to download markers into tmp directory, now it turns out that file:/// (used cordovas file plugin) seem not to work.

I'm really under heavy pressure right now. Could you please support file:/// icons?
Seems like local markers only work inside of www/ but there have to be a way to access

```
file:///Users/Hirbod/Library/Developer/CoreSimulator/Devices/ECE99348-51E2-471B-A41F-FEBCE717391E/data/Containers/Data/Application/26A88466-E977-41D9-88C3-8C78659827FE/tmp/data/3602645082.png
```

Tried toDataURL but it did not work!

**Comment by Hirbod** [comment]
And base64 will Crash with more than 1000 markers. (Cant atlas memory Blabla)

**Comment by Hirbod** [comment]
No idea? @wf9a5m75

**Comment by wf9a5m75** [comment]
Regarding of base64, it's probably related with memory caching.
Since next version, the plugin does not cache any icon images.

**Comment by wf9a5m75** [comment]
And regarding of "file:///", use relative path include "www" instead of "file:///"
i.e `www/icon/icon.png`

**Comment by wf9a5m75** [comment]
![base64](https://cloud.githubusercontent.com/assets/167831/5891177/83254ff2-a43a-11e4-9059-79ac734247d2.gif)

Add 1094 markers that use base64 encoded icon.

**Comment by Hirbod** [comment]
Not possible, cause FileTransfer Plugin can not download to www

**Comment by Hirbod** [comment]
It's easy to do:

http://stackoverflow.com/questions/7840607/initialize-a-uiimage-with-the-path-of-an-image

For Cordova, you could check if file:/// is present in path and then rely on

```
UIImage *image = [UIImage imageWithContentsOfFile:imagePath];
```

But I dont know how to do it for Android. But I'm sure it is easy and done in few minutes

**Comment by Hirbod** [comment]
Here, the final code for iOS

```C
        /**
         * Load the icon from local path
         */
          
        NSRange replaceRange = [iconPath rangeOfString:@"file://"];
          
        if (replaceRange.location != NSNotFound){
            iconPath = [iconPath stringByReplacingCharactersInRange:replaceRange withString:@""];
            image = [UIImage imageWithContentsOfFile:iconPath];
            
        } else {
            image = [UIImage imageNamed:iconPath];
        }
          
        if (width && height) {
          image = [image resize:width height:height];
        }

```

**Comment by Hirbod** [comment]
Optimized:

```
        /**
        * Load the icon from local path
        */

        NSRange fileRange = [iconPath rangeOfString:@"file://"];
        NSRange cdvRange = [iconPath rangeOfString:@"cdvfile:/"];
          
        if (fileRange.location != NSNotFound){
          iconPath = [iconPath stringByReplacingCharactersInRange:fileRange withString:@""];
          image = [UIImage imageWithContentsOfFile:iconPath];
          
        } else if (cdvRange.location != NSNotFound){
            iconPath = [iconPath stringByReplacingCharactersInRange:cdvRange withString:@""];
            image = [UIImage imageWithContentsOfFile:iconPath];
            
        } else {
          image = [UIImage imageNamed:iconPath];
            
        }

        if (width && height) {
          image = [image resize:width height:height];
        }
```

**Comment by wf9a5m75** [comment]
I have never used the file transfer plugin. Is `cdvfile:/` the same as `file://`?

**Comment by Hirbod** [comment]
It's nearly the same. But it worked. My patch above works fine

**Comment by Hirbod** [comment]
I guess Android could be managed from here:
http://stackoverflow.com/questions/4181774/show-image-view-from-file-path-in-android

**Comment by Hirbod** [comment]
CDVFILE seems to have some own logic and should not be used in markers. Ignore the improved version 

```
        /**
         * Load the icon from local path
         */

        NSRange replaceRange = [iconPath rangeOfString:@"file://"];

        if (replaceRange.location != NSNotFound){
            iconPath = [iconPath stringByReplacingCharactersInRange:replaceRange withString:@""];
            image = [UIImage imageWithContentsOfFile:iconPath];

        } else {
            image = [UIImage imageNamed:iconPath];
        }

        if (width && height) {
          image = [image resize:width height:height];
        }
```

This is perfectly for iOS

**Comment by Hirbod** [comment]
Android (in Simulator) returns something like this:

file:///storage/sdcard/Android/data/net.nachbarschaft/cache/data/4058648657.png 

This is my cached file. Just need to figure out how to pass this to Marker

**Comment by Hirbod** [comment]
Any News?

**Comment by Hirbod** [comment]
and what about file:/// ? My Plugin returns path as file:/// not als CDV. I gave you the code above, it's tested!

**Comment by wf9a5m75** [comment]
It's still coding.

Did you see the CDVFile.m?
Your code is not perfect.

https://github.com/apache/cordova-plugin-file/blob/master/src/ios/CDVFile.m

**Comment by Hirbod** [comment]
But was perfect for my use case as the Cordova cache plugin returned the file path. Thought minimal code should be enough. But you are for sure more experienced.

**Comment by wf9a5m75** [comment]
Test code
```js
$(document).on('deviceready', function() {
    var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
    map.on("map_ready", function() {


        var fileTransfer = new FileTransfer();
        var uri = encodeURI("http://mw2.google.com/mw-panoramio/photos/square/522084.jpg");

        fileTransfer.download(
            uri,
            "cdvfile://localhost/persistent/test2.jpg",
            function(entry) {
                console.log("download complete: " + entry.toURL());

                map.addMarker({
                    position: new plugin.google.maps.LatLng(0, 0),
                    icon: entry.toURL()  // or "cdvfile://localhost/persistent/test2.jpg"
                });
            },
            function(error) {
                console.log("download error source " + error.source);
                console.log("download error target " + error.target);
                console.log("upload error code" + error.code);
            },
            false
        );
    })
});
```

**Comment by Hirbod** [comment]
When you use
https://www.npmjs.com/package/cordova-file-cache

It return file:/// and not cvd://
This is the reason why I need file:/// support

**Comment by wf9a5m75** [comment]
Did you try the test branch?

file protocol is also acceptable.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/test/src/ios/GoogleMaps/Marker.m#L495

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/test/src/android/plugin/google/maps/PluginMarker.java#L476

**Comment by Hirbod** [comment]
Hi Masashi,

is test stable? Does it include all the other fixes we've incorporated? (Like watchdog and the new marker-async)

**Comment by wf9a5m75** [comment]
I appreciate if you check that.

**Comment by Hirbod** [comment]
I've tested it but there seem to be some caching issues (deactivated my cache right now). It shows random marker images on reinit.

http://www.youtube.com/watch?v=qZI57PUHem4

**Comment by Hirbod** [comment]
Sorry, it's my bug! Forget it please.
