### ISSUE TITLE
plugin is not defined ( AppBuilder )

### ISSUE THREAD

**Issue by Titella** [wf9a5m75/phonegap-googlemaps-plugin#369]
Firstly congratulations on the Plugin is very interesting and useful for those who work with maps as google map js v3 is much slower.

I work with Appbuider programming environment for phonegap / cordova, I'm making an app where I want to incorporate the plugin (phonegap-googlemaps-plugin) but I have not gotten to yet.

When I have done all the steps, installing plugins, key's of google, update index.html with  src =" Plugins / phonegap-googlemaps-plugin / www / googlemaps-cdv-plugin.js 

I get the following errors:

Uncaught ReferenceError: module is not defined 'from http: //local/Simulator/Plugins/phonegap-googlemaps-plugin/www/googlemaps-cdv-plugin.js: 2072

Uncaught ReferenceError: plugin is not defined 'from http: //local/Simulator/scripts/app.js: 32 Error occured
(In var map = plugin.google.maps.Map.getMap (mapDiv);)

Took many hours with it and I can not make it work.

I think it is a very good plugin and if I can make it work if you please I can propose to incorporate within recommended in this application plugins.

Any help needed aboutI am willing.

thank you very much

**Comment by Titella** [comment]
I noticed that when I compile the project also I get an error I do not understand:

-compile:
     [javac] Compiling 98 source files to / tmp / 7643dd6a4e5a424aa702ddbf1158784c / bin / classes
     [javac] /tmp/7643dd6a4e5a424aa702ddbf1158784c/src/plugin/http/request/HttpRequest.java:56: error: incompatible types
     [javac] Iterator <Object> = params.keys iterator ();
     [javac] ^
     [javac] required: Iterator <Object>
     [javac] found: Iterator <String>
     [javac] Note: Some input files use or override a deprecated API.
     [javac] Note: Recompile With -Xlint: deprecation for details.
     [javac] Note: Some input files use unchecked or unsafe operations.
     [javac] Note: Recompile With -Xlint: unchecked for details.
     [javac] 1 error


Error: [javac] /tmp/7643dd6a4e5a424aa702ddbf1158784c/src/plugin/http/request/HttpRequest.java:56: error: incompatible types
Error:
BUILD FAILED

**Comment by wf9a5m75** [comment]
I changed the code at HttpRequest.java, line 56.
https://github.com/wf9a5m75/phonegap-http-request/commit/bc54d4aac50d974f36f6f63c28ef74c443f0ca4c

So try again.

**Comment by wf9a5m75** [comment]
@Titella Any update?

**Comment by alexislg2** [comment]
It's not working for me when I do `cordova plugin add plugin.google.maps` it installs http.request (the latest version I guess) but I still have the error:

`HttpRequest.java:56: error: incompatible types`

**Comment by wf9a5m75** [comment]
I changed the code again just now. Try again.

**Comment by wf9a5m75** [comment]
@alexislg2 Any update for this?

**Comment by wf9a5m75** [comment]
I close this issue at once, because nobody posts any update.
But if you have additional information, please post here.
I will open this again.
