### ISSUE TITLE
#test Branch killed android

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#370]
Hi Masashi,

I've installed the test branch, iOS is fine, but on Android I cant build anymore because of play-services
```
     [aapt] invalid resource directory name: ......../platforms/android/com.google.playservices/nachbarschaft-google-play-services_lib/bin/res/crunch
```

Nerver seen play services in that path before...It gets intalled inside of the android platform folder AND inside of plugins folder. Seems something is wrong.

**Comment by wf9a5m75** [comment]
Do you use the version 22?

**Comment by Hirbod** [comment]
yes

**Comment by Hirbod** [comment]
com.google.playservices 22.0.0 "Google Play Services for Android"

**Comment by wf9a5m75** [comment]
I think just remove the `bin` directory. (For safety, just rename `bin_original` something like that)

**Comment by Hirbod** [comment]
Yeah, deleting works, but as soon as I open eclipse (really hate this software...hate android...) it gets recreated again. It's also a pain setting up Cordova in Android..

**Comment by wf9a5m75** [comment]
I think this folder appears since one or two years ago, because Google Play Services library has changed.
I usually build using eclipse, and eclipse removes the crunch, then generates it again automatically.

**Comment by wf9a5m75** [comment]
https://github.com/floatinghotpot/cordova-plugin-admob/issues/24

**Comment by wf9a5m75** [comment]
http://stackoverflow.com/questions/24937540/android-ant-error-invalid-resource-directory-name-bin-res-crunch

**Comment by Hirbod** [comment]
Yeah but I have to do it again and again again... did not had this problems before v22..

**Comment by wf9a5m75** [comment]
http://stackoverflow.com/a/23774198/697856

```
$> cd platforms/android/
$> ant clean
$> cordova build android
```

**Comment by Hirbod** [comment]
BUILD FAILED
/Users/Hirbod/Desktop/appdev/Nachbarschaft/platforms/android/build.xml:55: sdk.dir is missing. Make sure to generate local.properties using 'android update project' or to inject it through the ANDROID_HOME environment variable.

**Comment by wf9a5m75** [comment]
```
$> echo $ANDROID_HOME
/(path to your )/android-sdk
```

If empty, `export ANDROID_HOME=/(path to your android-sdk)`

**Comment by Hirbod** [comment]
Could you please explain a little more? I don't understand and don't know how to link the SDK without eclipse (and right now eclipse is damaged)

**Comment by wf9a5m75** [comment]
Where did you install your Android SDK in your Mac?
If you don't know, use find command.

```
$> find / -name "platform-tools"
find: /.DocumentRevisions-V100: Permission denied
find: /.fseventsd: Permission denied
find: /.Spotlight-V100: Permission denied
find: /.Trashes: Permission denied
/android-sdk/platform-tools   <--------Find!
^C 
$> 
```

Then type:
```
$> export ANDROID_SDK=/android-sdk
```

**Comment by Hirbod** [comment]
/Users/Hirbod/Development/adt-bundle/sdk/platform-tools

**Comment by wf9a5m75** [comment]
```
$> export ANDROID_SDK=/Users/Hirbod/Development/adt-bundle/sdk
```

Then try again (ant clean; cordova build android)

**Comment by Hirbod** [comment]
Now everything is broken... ANDROID_HOME is empty and SDK is set to export ANDROID_SDK=/Users/Hirbod/Development/adt-bundle/sdk

**Comment by Hirbod** [comment]
OK, fixed cause I set ANDROID_HOME

**Comment by wf9a5m75** [comment]
Resolved the all problems?

**Comment by Hirbod** [comment]
Seems like it's fine now, yes! Build Successful. Don't know what happen if I open eclipse again

**Comment by wf9a5m75** [comment]
sounds good.

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 25 11](https://cloud.githubusercontent.com/assets/504909/5895931/7aa08340-a52c-11e4-9e9f-773af3a1b309.png)

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 26 08](https://cloud.githubusercontent.com/assets/504909/5895935/9e6045c2-a52c-11e4-9ef2-0d3496e6e792.png)

**Comment by wf9a5m75** [comment]
So what's the problems (Errors 9 items)?

**Comment by wf9a5m75** [comment]
The CordovaApp project should be linked like this.
I don't know the facebook plugin case.
![screen shot 2015-01-25 at 10 27 36 pm](https://cloud.githubusercontent.com/assets/167831/5895951/7d09b246-a4e1-11e4-92b1-5db700af2c46.png)

**Comment by Hirbod** [comment]
Removed ant-build and Cordova App from workspace, and included FaceBook SDK - seems to run now

**Comment by Hirbod** [comment]
But i get this (but app starts)
[2015-01-26 07:29:51 - nachbarschaft-google-play-services_lib] R.java was modified manually! Reverting to generated version!

**Comment by wf9a5m75** [comment]
project > clean

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 31 21](https://cloud.githubusercontent.com/assets/504909/5895978/5cfa408c-a52d-11e4-9288-5a5aa572a6a3.png)

**Comment by Hirbod** [comment]
"Unfortunalty, Nachbarschaft stopped"...

**Comment by wf9a5m75** [comment]
CordovaLib is `CordovaApp-CordovaLib`

**Comment by wf9a5m75** [comment]
Use my google-play-services v22 
```
$> cordova plugin rm com.google.playservices`
$> cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
```

**Comment by Hirbod** [comment]
I have used yours... when i install #test it automatic installs your service

**Comment by Hirbod** [comment]
I've cleaned my workspace and deleted everything. I'm going crazy with this shitty android stuff..

![bildschirmfoto 2015-01-26 um 07 34 52](https://cloud.githubusercontent.com/assets/504909/5896012/ef46f566-a52d-11e4-9c46-7b0a0105d11c.png)
![bildschirmfoto 2015-01-26 um 07 36 06](https://cloud.githubusercontent.com/assets/504909/5896017/050e41b0-a52e-11e4-9bd0-8bf344afd1d5.png)
![bildschirmfoto 2015-01-26 um 07 36 11](https://cloud.githubusercontent.com/assets/504909/5896020/085af78c-a52e-11e4-9c09-8494d54a462e.png)

Something is wrong....

**Comment by wf9a5m75** [comment]
Ah, you don't need to import `CordovaApp (ant-build/bin)` and `ant-build` projects.

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 38 21](https://cloud.githubusercontent.com/assets/504909/5896031/5299ad7a-a52e-11e4-8ab3-e1d044f08360.png)

Is this correct?

**Comment by wf9a5m75** [comment]
yes.

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 39 50](https://cloud.githubusercontent.com/assets/504909/5896045/89a13680-a52e-11e4-8c46-5df073248e1a.png)

**Comment by wf9a5m75** [comment]
Show me the errors

**Comment by Hirbod** [comment]
No errors... But I opened CordovaLib right now and "ticked" "Library" and after that I could choose it

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 41 30](https://cloud.githubusercontent.com/assets/504909/5896059/c428cc96-a52e-11e4-8229-b8e458efa089.png)

**Comment by Hirbod** [comment]
Lol... But when I save... it gets red again

**Comment by wf9a5m75** [comment]
I think there are some errors in the Problems pain.

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-01-26 um 07 43 46](https://cloud.githubusercontent.com/assets/504909/5896077/14921bd8-a52f-11e4-9fe8-c7ac7ce6716b.png)

Look here: ( Video will be available in few seconds)
http://youtu.be/kWVo90_4L68

**Comment by Hirbod** [comment]
[2015-01-26 07:50:18 - Nachbarschaft] Uploading Nachbarschaft.apk onto device 'emulator-5554'
[2015-01-26 07:50:24 - Nachbarschaft] Installing Nachbarschaft.apk...
[2015-01-26 07:51:11 - Nachbarschaft] Success!
[2015-01-26 07:51:11 - CordovaApp-CordovaLib] Could not find CordovaApp-CordovaLib.apk!

**Comment by wf9a5m75** [comment]
CordovaApp-CordovaLib is just library project of Cordova.

**Comment by Hirbod** [comment]
Ok, after I've setup everything I made a ant clean and cordova build, now eclipse is working

**Comment by wf9a5m75** [comment]
good

**Comment by Hirbod** [comment]
thanks for your help

**Comment by Hirbod** [comment]
Last question: booting emulator and installing app is taking 5-6 minuntes. This is CRAZY. How to improve this?

**Comment by Hirbod** [comment]
I try to install HAXM

**Comment by Hirbod** [comment]
WOW INTEL HAX speed up 500%

**Comment by wf9a5m75** [comment]
Intel hax is a popupar and easy solution.
