### ISSUE TITLE
Failed resolving plugin

### ISSUE THREAD

**Issue by avi417** [wf9a5m75/phonegap-googlemaps-plugin#373]
Hy there,
I am stuck on a problem regarding the usage of your plugin on android platform(have not tryed on other platforms yet).
I have completly followed the windows tutorial(several times actually) without encountering any errors.
On build, my project target shows Android 4.4.2(API level 19)
Cordova version is 4.2

running cordova plugin list i get:
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"

What i have tried:
-switching to older version of cordova(3.5 to be precise, i encountered the same errors)
-installing other plugins just to test if something is wrong with the way cordova connects the plugins to android platform(everything worked)

Many thanks for your effort to create this plugin. If you need more info about this problem please let me know.

The logcat shows:
01-28 11:08:12.398: I/dalvikvm(27575): Failed resolving Lplugin/google/maps/GoogleMaps; interface 275 'Lcom/google/android/gms/maps/GoogleMap$OnMarkerClickListener;'
01-28 11:08:12.398: W/dalvikvm(27575): Link of class 'Lplugin/google/maps/GoogleMaps;' failed
01-28 11:08:12.398: W/System.err(27575): java.lang.ClassNotFoundException: plugin.google.maps.GoogleMaps
01-28 11:08:12.418: W/System.err(27575): 	at java.lang.Class.classForName(Native Method)
01-28 11:08:12.418: W/System.err(27575): 	at java.lang.Class.forName(Class.java:204)
01-28 11:08:12.418: W/System.err(27575): 	at java.lang.Class.forName(Class.java:169)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.PluginEntry.getClassByName(PluginEntry.java:117)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.PluginEntry.createPlugin(PluginEntry.java:93)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:281)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.PluginManager.execHelper(PluginManager.java:232)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
01-28 11:08:12.418: W/System.err(27575): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
01-28 11:08:12.418: W/System.err(27575): 	at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
01-28 11:08:12.418: W/System.err(27575): 	at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
01-28 11:08:12.418: W/System.err(27575): 	at android.webkit.JWebCoreJavaBridge.fireSharedTimer(JWebCoreJavaBridge.java:92)
01-28 11:08:12.418: W/System.err(27575): 	at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:108)
01-28 11:08:12.418: W/System.err(27575): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 11:08:12.418: W/System.err(27575): 	at android.os.Looper.loop(Looper.java:137)
01-28 11:08:12.418: W/System.err(27575): 	at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:814)
01-28 11:08:12.418: W/System.err(27575): 	at java.lang.Thread.run(Thread.java:841)
01-28 11:08:12.418: W/System.err(27575): Caused by: java.lang.NoClassDefFoundError: plugin/google/maps/GoogleMaps
01-28 11:08:12.418: W/System.err(27575): 	... 17 more
01-28 11:08:12.418: W/System.err(27575): Caused by: java.lang.ClassNotFoundException: Didn't find class "plugin.google.maps.GoogleMaps" on path: DexPathList[[zip file "/data/app/com.testapp.test-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.testapp.test-1, /vendor/lib, /data/cust/lib, /system/lib]]
01-28 11:08:12.428: W/System.err(27575): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
01-28 11:08:12.428: W/System.err(27575): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
01-28 11:08:12.428: W/System.err(27575): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
01-28 11:08:12.428: W/System.err(27575): 	... 17 more
01-28 11:08:12.428: I/System.out(27575): Error adding plugin plugin.google.maps.GoogleMaps.

**Comment by wf9a5m75** [comment]
Did you choose Google APIs x86 (Google Inc.)?
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/TroubleShooting:-Blank-Map#1-do-you-use-android-emulator

**Comment by avi417** [comment]
I only tested with my Huawey device, but when you mentioned to choose Google APIs x86, i wanted to try also on emulator. So, after a bit of digging, it seemed that my android sdk had some issues.
I managed to resolve everything! Thank you.
