### ISSUE TITLE
Fallback to web API v3 ?

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#375]
Hello !

This could be really usefull to have at least a partial support for not natively supported phones, as  Windows Phone 8, Firefox OS, Blackberry or simple browsers...  
[ edit: and all unsupported Android/iOS version as Android Gingerbread or iOS 5 ]

Do you known how we could do to not rewrite 2 times the same code (for your plugin, and for the API v3) ?

Thanks a lots for this great plugin !
Best,

**Comment by masashiGMS** [comment]
If Google supports Windows Phone8, Firefox OS, Blackberry and something like that, I might support them.
But Google doesn't support them currently, so I can not support.

If you don't want to rewrite 2 times the same code, just use Google Maps JavaScript API v3.
