### ISSUE TITLE
Which strict minimun Android build-tools API is required ?

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#376]
Hi !

In your documentation you ask to use the last build-tools for Android ( Rev. 19.0.3 on the screenshot ), so this mean at least an Android Kit Kat, 40% of the Android market only.

So, your plugin doesn't works on 60% of Android mobiles ?
Or could we use an older API Revision ?

Regards,

**Comment by masashiGMS** [comment]
Google Maps Android API v2 works on from Android 2.3 - Android 5.x.
This plugin also works on them.
