### ISSUE TITLE
Click on a marker which overlays another marker will propagate click on the one that is behind

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#377]
Hi Masashi,

when I have two markers like that:
![bildschirmfoto 2015-01-31 um 01 17 11](https://cloud.githubusercontent.com/assets/504909/5985752/0df072aa-a8e7-11e4-92cf-3f386f0a40cb.png)

and I click/tab the first one, it will ALWAYS trigger the marker behind of it. I don't know if this is a "google" maps bug, but maybe you know how to fix this?

![bildschirmfoto 2015-01-31 um 01 17 22](https://cloud.githubusercontent.com/assets/504909/5985759/278a7a6c-a8e7-11e4-8406-12ec38627a4c.png)

As you can see, it opens my (Hirbod) actionsheet, but should open "Desiree".
When I zoom more, it works well, but when they overlay, it don't. This is really bad...

**Comment by wf9a5m75** [comment]
That comes from Google Maps default behavior. The plugin doesn't (can't) manage which one is over the other markers.

**Comment by Hirbod** [comment]
Just reported this bug to google... I thought that is a Google Maps bug.

**Comment by Hirbod** [comment]
Google had confirmed my bugreport. So it will be fixed one day.
When do you update Gmaps? I'm getting a newer version notice when I launch the app. (iOS)

**Comment by wf9a5m75** [comment]
`Confirmed` means Google just recognises the issue.
I can not do anything until Google release the next version of the SDK.

**Comment by Hirbod** [comment]
Ah ok... thought confirmed means they really confirmed the bug.
There is a new Version out...
