### ISSUE TITLE
Blank map under iOS but worked before

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#378]
Hello,

I try your usefull plugin (v. 1.2.4 ) since yesterday :)
This works like a charm under Android.

Under iPhone 5 device / iOS 8.1, I only see the Google image on the bottom left.
The event MAP_READY is sent.

It's strange because I have successfully show the map one time, but I don't known why this no more working even when I reverting back my changes...

I use Ionic, and I have tried to recreate from scratch, install again the plugin etc, but nothing seems to help :-/

In Google Console Admin, I don't see errors and I see the specific iOS SDK stats count my iOS tests, so this seems to be working for Google.

I have an error in the Safari debug console :
Your errorHandler catch an error inside 'callbackFromNative' at line 114 of googlemaps-cdv-plugin.js
as you could see on this screenshot :

![loading-map](https://cloud.githubusercontent.com/assets/731955/5988853/7ca9d4d0-a972-11e4-8662-fe4043f0c47a.png)

My Ionic HTML code :
```html
<ion-view title="Map" ng-controller="Map">
    <ion-content padding="false" scroll="false" data-tap-disabled="true">
    <div style="width:100%;height:100%" id="map-canvas"></div>
    </ion-content>
</ion-view>
```

And the JS code :
```javascript
app.controller('Map', function($scope, $state)
{
    if (window.cordova) {
        console.log('Loading google map');
        var div = document.getElementById("map-canvas");
        map = plugin.google.maps.Map.getMap();
        map.on(plugin.google.maps.event.MAP_READY, function()
        {
            console.log('map ready');
        });
        map.setClickable(true);
        map.setDiv(div);
    }
});
```

Thanks in advance for your time & your help :)

**Comment by wf9a5m75** [comment]
Did you register your app bundle to Google APIs console?

**Comment by lakano** [comment]
Yes, and Google Console show me 2 times of loaded Google Maps on iOS stats... so this mean this have been works before ( but surely before the bug occurs ) :-/

This is what I have done (I've removed Android parts) :
```
$ ionic start --id com.mywebsite.app -a "Map" app
$ ionic platform add ios
$ ionic plugin add plugin.google.maps --variable API_KEY_FOR_IOS="....." 
```

Then I have replaced the content of ./www/templates/tab-dash.html with :
```html
<ion-view title="Votre client">
    <ion-content padding="false" scroll="false" data-tap-disabled="true">
    <div style="width:100%;height:100%" id="map-canvas"></div>
    </ion-content>
</ion-view>
```

And added in the $ionicPlatform.ready() function of ./www/js/app.js :
```javascript
    if (window.cordova) {
        console.log('Loading google map');
        var div = document.getElementById("map-canvas");
        map = plugin.google.maps.Map.getMap();
        map.on(plugin.google.maps.event.MAP_READY, function()
        {
            console.log('map ready');
            map.setVisible(true);
        });
        map.setDebuggable(true);
        map.setClickable(true);
        map.setDiv(div);
    }
```

Then in Google Console admin, I have created new iOS SDK with bundle id 'com.mywebsite.app'.
And try to launch it.
```
$ ionic build ios
$ ionic run ios
```

**Comment by wf9a5m75** [comment]
Ok, have you tried without ionic?

**Comment by lakano** [comment]
I'll try, and I remember I have upgraded ionic from 1.3.2 to 1.3.3 in the afternoon between some tests ( because I have 1.3.2 on my Linux OS and 1.3.3 on OSX... so I have upgraded after to not make bugs... but I'll try to re-install on 1.3.2 to see if it's the reasons ! )

**Comment by lakano** [comment]
Sorry for the waste of time, this was a problem from my Wifi network ! ( my dnsmasq return bad router informations to my iPhone ! :-/ ).
