### ISSUE TITLE
question: Map Move Event

### ISSUE THREAD

**Issue by deliriousrhino** [wf9a5m75/phonegap-googlemaps-plugin#380]
Is it possible to listen for map move events like when a user has stopped panning a map or zooming?

**Comment by wf9a5m75** [comment]
This plugin supports only these events currently.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#listen-events

**Comment by wf9a5m75** [comment]
For your purpose, listen the `CAMERA_CHANGE` event.
