### ISSUE TITLE
addMarker works under Android but not under iOS

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#381]
Hello ! 

I love your plugin, it's really smooth and fast :-)

I have a problem with markers, this works for Android, but not works under iOS ( my version is 8.1 ).

        map.addMarker({
            icon:       'www/img/marker.png',
            position:   coords,
            title:      title
        }, function(marker)
        {
            marker.set('id', id);
            console.log('added marker ', marker.get('id'), marker);
        });

With or without icon, it's the same problem, and I see a "null" error each time I call the addMarker : 

![capture d ecran de 2015-02-02 10 35 34](https://cloud.githubusercontent.com/assets/731955/5998442/c28ddf36-aac7-11e4-9d7f-675bbbbd0a94.png)

After the error, I see in my log my message "added marker X".

In Android, I don't see any "null" error and all works as expected.

May be a bug or may be I forgot to do something ? 

Thanks in advance for your precious help ! :)

**Comment by lakano** [comment]
Solved, the map wasn't fully loaded. May be iOS require more time than Android to load the map.
I have added a trick to be sure the map wasn't fully loaded.
Regards,

**Comment by wf9a5m75** [comment]
Do you listen `MAP_READY` event?
You have to wait until `MAP_READY` event before adding any markers.

**Comment by lakano** [comment]
yep, this is what I have done to fix it !
thanks for your answer :)
