### ISSUE TITLE
Cordova CLI fails to build

### ISSUE THREAD

**Issue by JcDenton86** [wf9a5m75/phonegap-googlemaps-plugin#382]
Hello, after installing the plugin Cordova CLI fails to build. I tried both master and test branch. I can only run my app from Eclipse, by importing the project in the workspace. Can you provide any help why is that happening? In the tutorial after following the steps which is a straightforward procedure it's ok. But when I run cordova build I get:

invalid resource directory name: C:\Users\admin\Desktop\folder\platforms\android\com.google.playservices\google-play-services_lib\bin\res crunch

and later it fails with error code 8.

Running from Eclipse though I have no issues building the project.

**Comment by wf9a5m75** [comment]
Delete `bin\res\crunch` directory.

**Comment by wf9a5m75** [comment]
FYI: http://stackoverflow.com/questions/23773268/android-cli-build-shows-invalid-resource-directory-name-error-my-project-res-cr

**Comment by JcDenton86** [comment]
Thank you 'ant clean' fixed it.
