### ISSUE TITLE
compatibility with cca

### ISSUE THREAD

**Issue by rafaelcardoso** [wf9a5m75/phonegap-googlemaps-plugin#383]
Hello.
I loved this repo, I tried the demo app and the user experience is a thousand times better than the default implementation with the javascript SDK. But, I want to use this plugin with Chrome Mobile Apps, is this repo fully compatible with cca? there is any common issues?

Thank you.

**Comment by wf9a5m75** [comment]
Duplicate #302

**Comment by wf9a5m75** [comment]
This plugin does not work on cca currently.
