### ISSUE TITLE
Problem loading the map the first time iOS

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#384]
Hey guys! I have been working with this plugin for a while and works really well. I am developing on Android and iOS, on Android works perfect, no errors and the map start ok. On iOS, the first time i try to init the map, for some reason it remains blank, although MAP_READY event is broadcasted. If then i go to other state of the app and return, the maps works ok and it is showed.
I am waiting for the for the MAP_READY eve t before loading the markers, and i try too adding a $timeout to wait 10 seconds and then start it with no luck.
Someone with the same problem?

**Comment by wf9a5m75** [comment]
Um,,, it's wired. Some people reports the similar issues recently, but I didn't change the iOS code anything.

Is there any error message in Xcode console?

**Comment by Hirbod** [comment]
I think that some elements did not get transparent as they should. Try to bubble up every parent node or some absolute positioned layers and check their css property for background-color: rgba(0,0,0,0).

When you find one without, try to delete the node with the inspector and check if this caused the problem. Remember the "buggy" node and set it manually during init. (Or after)

The most reasons for "map is not showing" is normally related to this transparency problem.

**Comment by leandroz** [comment]
Before the map ready event i get THREAD WARNING: ['GoogleMaps'] took '165.079834' ms. Plugin should use a background thread.
And then just the SDK version: Google Maps SDK for iOS version: 1.9.13516.0
I have all the nodes with background-color: rgba(0,0,0,0), i tried what @Hirbod said but the same.
The weird thing is that when i navigate through the app and then return in some point to the view with the map sometimes it loads ok. I am using Angular and removing the app when i leave the view with the map and adding it again when i return.
In Android works perfect.

**Comment by leandroz** [comment]
Something to add, after one time loading ok, then is always working.

**Comment by wf9a5m75** [comment]
Oh, please tell me the `something`.

**Comment by leandroz** [comment]
I navigate the app and at random the map start showing, then if i continue with the navigation the map init ok always, the problem is always at the beginning.

**Comment by wf9a5m75** [comment]
I see. thank you for your information.

**Comment by leandroz** [comment]
@wf9a5m75 why you closed it? i am still having the problem and i want to solve it

**Comment by wf9a5m75** [comment]
Oh, you didn't solve this? I can not reproduce your issue.

**Comment by wf9a5m75** [comment]
Please share your whole project code. And please take a video.

**Comment by jonmanzo** [comment]
Seeing something similar.  Sporadic but able to reproduce on sim.  Here is Sys Log Excerpt:

CoreAnimation: warning, deleted thread with uncommitted CATransaction; created by:
	0   QuartzCore                          0x00000001138d3c88 _ZN2CA11Transaction4pushEv + 312
	1   QuartzCore                          0x00000001138d3ffe _ZN2CA11Transaction15ensure_implicitEv + 276
	2   QuartzCore                          0x00000001139621d5 _ZN2CA5Layer13thread_flags_EPNS_11TransactionE + 37
	3   QuartzCore                          0x000000011396431a _ZN2CA5Layer4markEPNS_11TransactionEjj + 64
	4   QuartzCore                          0x000000011396c8de _ZN2CA5Layer25set_needs_display_in_rectERK6CGRect + 300
	5   QuartzCore                          0x000000011396c98d -[CALayer setNeedsDisplay] + 62
	6   UIKit                               0x000000010fc91749 -[UIView(Rendering) setNeedsDisplay] + 83
	7   UIKit                               0x000000010fc9b340 -[UIView(Internal) _setBackgroundCGColor:withSystemColorName:] + 913
	8   Rise                                0x000000010ebc551f __21-[GoogleMaps getMap:]_block_invoke + 511
	9   libdispatch.dylib                   0x0000000113e2aba6 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x0000000113e487f4 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000113e30b22 _dispatch_queue_drain + 1417
	12  libdispatch.dylib                   0x0000000113e30432 _dispatch_queue_invoke + 235
	13  libdispatch.dylib                   0x0000000113e32fc1 _dispatch_root_queue_drain + 685
	14  libdispatch.dylib                   0x0000000113e345d9 _dispatch_worker_thread3 + 111
	15  libsystem_pthread.dylib             0x00000001141cc637 _pthread_wqthread + 729

**Comment by leandroz** [comment]
I see the map like this:
![map-blank](https://cloud.githubusercontent.com/assets/4624850/6118421/93454980-b111-11e4-8097-d2be054358c4.png)

What i have to do to give you useful information?, like logs or something?

**Comment by leandroz** [comment]
Ok, i solved the problem.
I was doing something like:
````
var div = document.getElementById("map_canvas");
map = window.plugin.google.maps.Map.getMap(options);
map.setDiv(div);
// Rest of code
````
When the correct way to do ti is:
````
var div = document.getElementById("map_canvas");
map = $window.plugin.google.maps.Map.getMap(options);
map.addEventListener(window.plugin.google.maps.event.MAP_READY, function(map) {
    console.log('MAP READY');
    map.setDiv(div);
    // Rest of code
````
For some reason the wrong way was working ok on Android but not on iOS. If anyone else has this issue check this.

**Comment by wf9a5m75** [comment]
@leandroz 
Yes, you have to wait every plugin methods until the MAP_READY event is fired.
Before the event, the plugin prepares many things, and it takes a few milli-seconds.
Since Android and iOS are different OS, the initialize process are different.
It means the spending time is also different.

**Comment by castrojr913** [comment]
I have tried a lot of times and it has been impossible, it always show a white background. This is my code and executed on iOS 9.2 Simulator:

      var map, div;
      document.addEventListener("deviceready", function() {
                       div = document.getElementById("map_canvas")
                       map = plugin.google.maps.Map.getMap();
                       map.on(plugin.google.maps.event.MAP_READY, onMapReady);
       }, false);
                                          
       function onMapReady() {
                      console.log("------ READY- ---");
                      map.setDiv(div);
       }

The interesting thing is if I call map.showDialog(), it shows the map on fullscreen mode AND, then, if I close it right away, this time the map is shown correctly. However, as I said, when map is loaded first time, it's always white.
