### ISSUE TITLE
GeoCoder error : Cannot use 'in' operator to search for 'position'

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#385]
Hello,

I'm trying for the first time the geocoder feature, but I have this error each time, whatever the request value : 
![geocoder](https://cloud.githubusercontent.com/assets/731955/6039706/d4133b68-ac69-11e4-8cfa-6f16d4441a59.png)

Here is my code : 
        
        var request = "Avenue des Champs-Élysées, Paris, France";
        plugin.google.maps.Geocoder.geocode(request, function(results) {
            console.log('geocoder results', results);
        });

Is it a bug or do I missed something ?

Thanks :)

**Comment by wf9a5m75** [comment]
The parameter `request` is wrong.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Geocoder

**Comment by lakano** [comment]
Oups ! Thanks a lot :)
