### ISSUE TITLE
[Fix included] GoogleMaps.java getLicenseInfo() not working before initializing the map 

### ISSUE THREAD

**Issue by jpcancienne** [wf9a5m75/phonegap-googlemaps-plugin#386]
GoogleMaps.java
line 218:
if (("getMap".equals(action) == false && "isAvailable".equals(action) == false ) && [...]){ ... }

The above causes the plugin to reject the getLicenseInfo action if the map plugin has not been initialized. This action does not require initializing the map in order to display the License Information.

The fix is quite simple:
line 218:
if (("getMap".equals(action) == false && "isAvailable".equals(action) == false && "getLicenseInfo".equals(action) == false) && [...]){...}

I've tested this on my application on my Android device (Verizon Motorola Droid Mini) and it works. This problem does not seem to exist on the ios part of this plugin.

The application I am developing doesn't load a googlemap as the first screen. I also have the licensing info somewhere else in the application that doesn't require creating a google map screen initially. Please put this fix in for others who need this functionality in order to satisfy the terms of use. 

You may need to  review other commands that could have this same issue.

Thank you!

**Comment by wf9a5m75** [comment]
Thank you @jpcancienne 
I patched it on the test branch, and it will include in the next release.

**Comment by giovanniorigins** [comment]
Can you explain how you used this function, because I'm using v1.2.5 and when i try to call this function from plugin.google.maps.Map.getLicenseInfo() it is undefined?

I only use the map in one of my tabs so it is not always initialized either.

**Comment by jpcancienne** [comment]
via:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map.getLicenseInfo()

```javascript
plugin.google.maps.Map.getLicenseInfo(function(txt1,txt2){
    var textToUse = txt1 || txt2;
    //show the information
});
```

Remember that this is a native function, so you need to use a callback javascript function.

**Comment by giovanniorigins** [comment]
worked like a charm, thanks!
