### ISSUE TITLE
map.toDataURL crashes device Samsung Galaxy S4 mini

### ISSUE THREAD

**Issue by Isodata-JP** [wf9a5m75/phonegap-googlemaps-plugin#388]
Nice plugin. Everything works fine except this one thing. Using Cordova. Running in actual device.

I got this code which in the app (Crash message: "[Appname] has stopped"):

map.toDataURL(function(imageData) {
              		  //var image = document.getElementById("mapPic");
              		  //image.src = imageData;
              		});

Or could there be something in that device version?

I tracked that the line that crashes is in cordova.js file Line 927 (Cordova version 4.2.0)
var messages = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);

**Comment by wf9a5m75** [comment]
Hi Isodata-JP, could you show me the whole error log? Not only `[Appname] has stopped`

**Comment by wf9a5m75** [comment]
Any update?

**Comment by wf9a5m75** [comment]
I close this issue at once, because there is no new data.
However you can open again if you have additional data.

I think the issue causes `out of memory` error.
