### ISSUE TITLE
deactivate zoom

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#389]
Hi @wf9a5m75 ,

is it possible to deactivate the zoom (with pinch) on the map?
Did not find any documentation for that.

-Hirbod

**Comment by wf9a5m75** [comment]
```js
var map = plugin.google.maps.Map.getMap(div, {
  'gestures': {
    'zoom': false
  }
});
```

**Comment by wf9a5m75** [comment]
The above code should work.
