### ISSUE TITLE
can't pass float value for zoom

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#390]
Hi Masashi,
GMaps does support float values for zoom (12.312345) but it seems you round this value (just tried on moveCamera)

```js
               map.moveCamera({
                  //'target' : $scope.latLngBounds
                  target: pos,
                  zoom: 12.8,
                  tilt: $scope.tilt
                });
```

Could you please fix this that we can pass float values? Thanks.

**Comment by wf9a5m75** [comment]
Hi, I fixed it in the test branch directly (I haven't tested it yet).
Please try it.
