### ISSUE TITLE
Symbols in polyline?

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#391]
Hey!, is possible to set symbols to make the polyline? Something like this:

````
// Define a symbol using SVG path notation, with an opacity of 1.
  var lineSymbol = {
    path: 'M 0,-1 0,1',
    strokeOpacity: 1,
    scale: 4
  };

  var lineCoordinates = [
    new google.maps.LatLng(22.291, 153.027),
    new google.maps.LatLng(18.291, 153.027)
  ];

  // Create the polyline, passing the symbol in the 'icons' property.
  // Give the line an opacity of 0.
  // Repeat the symbol at intervals of 20 pixels to create the dashed effect.
  var line = new google.maps.Polyline({
    path: lineCoordinates,
    strokeOpacity: 0,
    icons: [{
      icon: lineSymbol,
      offset: '0',
      repeat: '20px'
    }],
    map: map
  });
}
````
Source: https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-dashed

**Comment by wf9a5m75** [comment]
Hi @leandroz 
I hope Google supports the symbol feature for Google Maps Mobile SDKs,
but there is no function currently.
Thus, this plugin cannot do it at the time.

**Comment by leandroz** [comment]
@wf9a5m75 thanks for your response, when do you think that will be a new release of this plugin?, i saw that there are a lot o fixes in the code but not in a new version yet. Something to do to make it quickly?

**Comment by wf9a5m75** [comment]
If you help to decrease the issues for yours and other people's one, release will be earlier.

**Comment by canadaka** [comment]
The API doesn't support symbols, but often the use-case is to create dotted or dashed lines. Seems others have made their own functions in Java to do this:
http://stackoverflow.com/questions/13721008/how-to-draw-dashed-polyline-with-android-google-map-sdk-v2
