### ISSUE TITLE
New Ionic version - caching off but plugin goes into loop

### ISSUE THREAD

**Issue by mladenp** [wf9a5m75/phonegap-googlemaps-plugin#392]
So i was using this plugin successfully until recently after Ionic introduced caching. So now they are not removing elements from DOM. So it happens that i have several #map_canvas elements that plugin needs. That doesn't work at all, i couldn't think of a fix so i tried to disable caching. But when i disable caching plugin goes into some kind of loop and starts adding **millions of _gmpas_cdv_** classes. One after another, and after some time it breaks of course.

So why is this happening? Is there any idea how to fix it?

**Comment by wf9a5m75** [comment]
Please try to use the test branch.

**Comment by mladenp** [comment]
Created new ionic project, added test version of plugin and added android.support.v4 just in case, but i got this error:
`    [javac] c:\Users\Mladen\testapp\platforms\android\src\plugin\google\maps\GoogleMaps.java:326:     error: cannot find symbol
        [javac]         case ConnectionResult.DATE_INVALID:`

**Comment by wf9a5m75** [comment]
You don't use the test version, because `DATE_INVALID` is not contained in GoogleMaps.java file of the test branch.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/test/src/android/plugin/google/maps/GoogleMaps.java

**Comment by wf9a5m75** [comment]
In order to install the test branch, follow these commands:

```
$> cordova plugin rm plugin.google.maps
$> rm -rf  /platforms/ios/(your app)/Plugins/plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=... --variable API_KEY_FOR_IOS=...
```

**Comment by wf9a5m75** [comment]
@mladenp Any update for this?

**Comment by mladenp** [comment]
Hey sorry i forgot about this. There was a problem with plugin not checking if class already exist and i had a reload option that i didn't see, so that's the reason why it added classes until it broke. 
But my colleague figured out where the check is and fixed it. If he didn't submit the fix here is pastebin: http://pastebin.com/J0fS11bm

**Comment by wf9a5m75** [comment]
As far as I mentioned before, this issue is already fixed in the test branch.
Anyway, congrats!
