### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by jaredgreener** [wf9a5m75/phonegap-googlemaps-plugin#395]
I am getting a black screen when using this plugin... Geolocating myself and the maps center works, but the whole screen is black. I am using Sencha Touch and Cordova. Any ideas??

**Comment by wf9a5m75** [comment]
Can you see the screen capture?

**Comment by jaredgreener** [comment]
![screen shot 2015-02-11 at 12 03 13 am](https://cloud.githubusercontent.com/assets/2931865/6142722/7d86f84e-b181-11e4-93cd-62f5986cec93.png)

**Comment by jaredgreener** [comment]
This is the simulator but does same on iOS device

**Comment by wf9a5m75** [comment]
Hmm, I've never seen like this.
Is there any error log in xcode?

**Comment by jaredgreener** [comment]
no...

![screen shot 2015-02-11 at 12 03 27 am](https://cloud.githubusercontent.com/assets/2931865/6147393/abc701dc-b1bc-11e4-8521-a3d9b19a5a62.png)

**Comment by jaredgreener** [comment]
I saw another thread speaking of a black screen -- but they said it had something to do with their framework ionic. I am not using ionic, but maybe its related? They said they fixed it by wrapping it in a special kind of div...

**Comment by wf9a5m75** [comment]
Did you try to create a new project that just use only this plugin?

**Comment by Hirbod** [comment]
The map is there, try to look in the DOM Inspector. Seems like this plugin set background color to rgba(0,0,0,0) but somehow another CSS or inline-setting changed the opacity to 1.

Bubble up every single DOM-node from your #map till ```html``` and check the CSS. Sometimes, there are some absolute positioned elements which haven't been set transparent correctly (remeber, the map is placed under the webview, therefor every single element infront of the map had to be transparent).

I had the same problem once with OnsenUI and fixed this problem (a little js magic to remove/make elements transparent after map-init, sometimes related on timing issues)

**Comment by wf9a5m75** [comment]
Thanks @Hirbod :+1:

**Comment by wf9a5m75** [comment]
@jaredgreener Is there any update?

**Comment by saputro-dwy** [comment]
excuse me, @Hirbod, i have same problem with onsen ui, when i use slide menu,
can you explain me, how it work in slide menu
i have try with code -> map.setVisible(false); 
and show again with -> map.refreshLayout();map.setVisible(true) 
thank you

**Comment by denisgaletin** [comment]
I have the same problem, https://github.com/saputro-dwy ! Can somebody explain how to fix it?

**Comment by wf9a5m75** [comment]
Read this thread
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/374

**Comment by wf9a5m75** [comment]
@denisgaletin Did you read #374?

**Comment by denisgaletin** [comment]
@wf9a5m75 Sorry, my English is bad.. I dont understand the solution to a problem.

**Comment by wf9a5m75** [comment]
Ok, what plugins do you use?
Could you show me the result of `$> cordova plugin list` command?

**Comment by denisgaletin** [comment]
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Services for Android"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"

**Comment by wf9a5m75** [comment]
Oops, I missed. You are not talking about black screen.

Could you show me the screen capture?

**Comment by denisgaletin** [comment]
http://www.youtube.com/watch?v=RWfZIk8BX_U
My problem is very similar, but it appers, when i'm using slide menu.

**Comment by denisgaletin** [comment]
I'm using onsen ui

**Comment by wf9a5m75** [comment]
Thanks, your problem is similar with the first person's one.

Anyway, I think there are some errors in your code.
Because the map is displayed at the first time, thus the map plugin works
perfectly.

Could you share your code with me using github?

If you don't publish your code in public, use private repository, or
compress your whole project files with zip, upload to your google drive,
then share with me and @Hirbod:
wf9a5m75@gmail.com and
info@nightstomp.com

**Comment by wf9a5m75** [comment]
@denisgaletin I checked your project file, but the JavaScript file is completely different from your youtube demo.

**Comment by denisgaletin** [comment]
It's not my youtube video, it is just an example.

**Comment by wf9a5m75** [comment]
I can not your code in the files.
![device-2015-03-05-233540](https://cloud.githubusercontent.com/assets/167831/6521757/695dbe22-c390-11e4-87cd-ef91c9d54ff3.png)

**Comment by denisgaletin** [comment]
hi, i'm a beginner. code is located: platforms/android/assets/www

**Comment by wf9a5m75** [comment]
Ok, I'll check there again. Just a moment please.

**Comment by wf9a5m75** [comment]
I can not read Russian language. How do I check your code?
Please instruct me (e-mail is fine)

**Comment by denisgaletin** [comment]
Okay, just a second

**Comment by wf9a5m75** [comment]
@denisgaletin Any updates?

**Comment by Hirbod** [comment]
closed for now, if we receive any further updates or comments, we'll reopen  - if this issue still exists!
