### ISSUE TITLE
App-Release to Play Store

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#397]
Dear Masashi,

I want to push the app to the stores right now. Apple is done, but Android not.
You only describe how to get "debug" keys. What do I have to do now if I want to release the app? You have any documentation?

**Comment by wf9a5m75** [comment]
You forgot to register your release key to Google API console.

**Comment by Hirbod** [comment]
I did not forget anything, I dont have a release key. This information is missing in your documentation. I've never released an app to Play Store. What do I have to do?

**Comment by wf9a5m75** [comment]
It's not related to this plugin though, read this page.
This blog describes the steps in detail.
https://blog.nraboy.com/2014/09/signing-apache-cordova-android-app-release/

**Comment by Hirbod** [comment]
Thank you.. Managed to get this work :)

**Comment by wf9a5m75** [comment]
Congratulations!!
