### ISSUE TITLE
Thank you masashi

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#398]
Hi Masashi,

finally, my app is live.
https://play.google.com/store/apps/details?id=net.nachbarschaft

Thank you so much for all your help in  the last 5 months. Android is still not perfect, but iOS isn't live yet.
Hope we'll get the marker clusterer soon :)

Again, thank you very much for everything. Without your help, this app wouldn't be stable as it is!

:100:

**Comment by wf9a5m75** [comment]
Hi @Hirbod ,

Really congratulation!!
You fount out many issues, help other people and me so much!
I apologize for marker cluster, I couldn't release before you release your app.
But the development is on progress little by little.
Keep in touch!
