### ISSUE TITLE
marker.setIcon (*base64Image*) crashes ios version

### ISSUE THREAD

**Issue by schnuet** [wf9a5m75/phonegap-googlemaps-plugin#399]
Hello Masashi! First, many thanks for the awesome plugin. It is fast and works flawlessly - except for the error I just found:

When trying to set the icon of a marker to an base64 Image using the setIcon command, the app is terminated with an error message:
`NSUnknownKeyException: this class is not key value code-compliant for the key url`

The image was generated using the canvas.toDataUrl command. 
Since there are no labels, I am writing text on my markers using that method.

I got my app running again using a workaround:
Everytime I want to change the icon, i remove the marker and create a new one at the same place using a different image.
That works, because setting the icon on creating doesn't pose any problem, even though I am using the same images when setting the icons.

On android, that problem doesn't exist, everything works fine.

Under iOS, I am developping unter Xcode 6.1.1 and Yosemite 10.10.1

I use the plugin with cordova and the ionic framework.

**Comment by wf9a5m75** [comment]
Could you show me the whole error log?

**Comment by schnuet** [comment]
Yes, of course. Sorry that I didn't earlier. Just finished the workaround when I thought that this might interest you.

    015-02-12 23:46:21.869 parkpocket[1160:486482] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/7C3DCC4A-0BA5-4C9A-    A9E5-132C97DC8AE6/Library/Cookies/Cookies.binarycookies
    2015-02-12 23:46:22.659 parkpocket[1160:486482] Multi-tasking -> Device: YES, App: YES
    2015-02-12 23:46:22.685 parkpocket[1160:486482] Unlimited access to network resources
    2015-02-12 23:46:22.857 parkpocket[1160:486482] [CDVTimer][keyboard] 0.170052ms
    2015-02-12 23:46:23.241 parkpocket[1160:486482] [CDVTimer][splashscreen] 383.948982ms
    2015-02-12 23:46:23.242 parkpocket[1160:486482] [CDVTimer][TotalPluginStartup] 385.367036ms
    2015-02-12 23:46:24.088 parkpocket[1160:486482] Resetting plugins due to page load.
    2015-02-12 23:46:25.148 parkpocket[1160:486482] Finished load of: file:///private/var/mobile/Containers/Bundle/Application/10F46F43-4320-4A50-8754-3245B195E28C/parkpocket.app/www/index.html#/app/search
    2015-02-12 23:46:25.378 parkpocket[1160:486482] This app uses phonegap-googlemaps-plugin     version 1.2.4
    2015-02-12 23:46:25.419 parkpocket[1160:486482] ---getMyLocaiton
    2015-02-12 23:46:25.422 parkpocket[1160:486482] ---status=4
    2015-02-12 23:46:25.423 parkpocket[1160:486482] ---status=authorized
    
      ( * some debug outputs from my code, then the error log after the call of setIcon: * )
    
    2015-02-12 23:46:39.650 parkpocket[1160:486482] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSCFString 0x1571cdc00> valueForUndefinedKey:]: this class is not key value coding-compliant for the key url.'
    *** First throw call stack:
    (0x18436de48 0x194a600e4 0x18436dacc 0x1852080f4 0x1851550f0 0x1000e4090 0x1000e3cc8 0x18523ddf0 0x1843260e8 0x18432538c 0x18432343c 0x1842511f4 0x18d3e75a4 0x188b82784 0x1000af248 0x1950cea08)
    libc++abi.dylib: terminating with uncaught exception of type NSException
    (lldb) 
If you need more data, don't be afraid to ask - I might not be the best programmer, but I will try my best to assist you.

**Comment by wf9a5m75** [comment]
I can not confirm your issue. Please give me your example.

![screen shot 2015-02-14 at 1 04 05 am](https://cloud.githubusercontent.com/assets/167831/6199128/6421cc38-b3e5-11e4-9309-376c63762e93.png)

```js
$(document).on('deviceready', function() {
  var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
  map.on("map_ready", function() {
  
    var icon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAACVUlEQVRIS8WWjVXCMBRGwwTqBMIEuAG4ARuIE6gTKBOgEyAT4AbABjKBMIE/C+h3m6S2pWlJ8BzfOTkpad6770teEzom3bZy/VbrpYTopDjJZ6w2c77X6p9j46SCUXvuYDxHq04BZ2rPHXa3y/DRqlPAmdqZW+hrkMZEq44F52q3oGTdrjEpqmPBudoxKVBVKqsU1THgPbW+klNUt4GHCn6idqEGuMveerUeXFGtNTCvah9qaz+n2gMmKMGBnLrfjPFcMirZ7231XUF19RUJkIhPZqXnT8AM9Osy62v0VPihUqIfjWwx1RkJvbxIpjArhabfbEJ6zQYwysiiT3CW8kJ6Q4BgqMALEnqVNAqQZGSkM/R7nMOBLhZ/B/ZQeg9V/1EsrpLy5dIqP8aAXV6WlQIlZrWq/wzeBK0DM3Y0vA0aAh8FPwTaBC7B2W8+qUOMT4l9dYUUrJK2k4tCOHl7O7zK+Xx69nbWU/iebgKz1+9E+OYPToR1fqOe+SquujeBWdzlYGBPohhjW9b2lGbRa72bwLdyml5d2auvaPyeTOzIw4MxzCkal8h8no3cqT3WJd0ExuFmOjXmlhRIXbnfKZQ7hfJ4HDTM8wVIMi6xJ01y3mV8E5glGlDRGIEKS75DrAtFn/0DA3x/b0ddZbPgGt23JnBW0agpKPzUGCvhoT4iv1HG9Zodtc6HGBTYnoXAXc3UR5SbBwK1d8y+8RUAzxNwU2orOwQeyolF/lLT7mUqQ8BqCj4Bt+j1lR0Cs3Sopt8GFLYNF/2JU7K2k6stePL7fwP/AER2xy+mY1/QAAAAAElFTkSuQmCC";
    var canvas = document.createElement('canvas');
    canvas.width = 120;
    canvas.height = 40;
    var context = canvas.getContext('2d');
    
    var img = new Image();
    img.src = "./images/google_logo.gif";
    img.onload = function() {
      context.drawImage(img, 0, 0);
      
      context.font = '15pt Calibri';
      context.fillStyle = 'blue';
      context.fillText('Google', 40, 15);
      context.fillText('Tokyo!', 60, 35);
      
      console.log(canvas.toDataURL());
      
      map.addMarker({
        'position': new plugin.google.maps.LatLng(0, 0),
        'title': canvas.toDataURL(),
        'icon': icon
      }, function(marker) {
        marker.showInfoWindow();
      });
    };
    
  });
});
```

**Comment by wf9a5m75** [comment]
Thank you for your report.
This issue is fixed in the test branch. Check it out.

```
$> cordova plugin rm plugin.google.maps
$> rm -rf  /platforms/ios/(your app)/Plugins/plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=... --variable API_KEY_FOR_IOS=...
```
