### ISSUE TITLE
Implement StreetView

### ISSUE THREAD

**Issue by wf9a5m75** [wf9a5m75/phonegap-googlemaps-plugin#40]

**Comment by adi-ads** [comment]
did this get implemented then?

**Comment by wf9a5m75** [comment]
Not yet.

**Comment by adi-ads** [comment]
any plan to put this on the roadmap?

**Comment by wf9a5m75** [comment]
I'm sorry but my private time is really limited these days.

**Comment by adi-ads** [comment]
no worries, appreciate the work so far!

**Comment by bFlood** [comment]
hi masashi  - how much work do you think is needed to get streetview working?

**Comment by wf9a5m75** [comment]
Thank you for offering.
Actually I need some help instead of money.

**Comment by wf9a5m75** [comment]
@adi-ads ,@bFlood
How do you want to display the street view?

**Comment by bFlood** [comment]
yea, no problem, I can try to help out. I was just wondering if you've done any analysis on how much work is required

it would be great if we could just overlay the streetview directly over the existing map, that way we could reuse a lot of the existing code for div/map management but I'm not sure if this could be done, it might require a completely new div for display. I would also need the OnStreetViewPanoramaCameraChange event just like the map's camera change event

**Comment by Hirbod** [comment]
This feature will be canceled for now!

**Comment by wf9a5m75** [comment]
The street view feature will come to the next version finally.
https://youtu.be/Gotd70aXX6k
