### ISSUE TITLE
Polyline handle empty

### ISSUE THREAD

**Issue by der-ede** [wf9a5m75/phonegap-googlemaps-plugin#400]
Hi there,

it seems as if the handle for the polyline returned by the callback function of addPolyline() is an empty object *{}*. Is this a bug or an error in my programming?

Here some code:
```Javascript
...
var listOfPolyHandles = [];
var polygon = {};
pt1 = new plugin.google.maps.LatLng(p1.lat, p1.lng);
pt2 = new plugin.google.maps.LatLng(p2.lat, p2.lng);
map.addPolyline({
  points: [
    pt1, pt2
  ],
  'color' : '#AA00FF',
  'width': 5,
  'geodesic': false
  }, function(poly) {
    console.log("polyline handle: " + JSON.stringify(poly));
    listOfPolyHandles.push(poly);     // this works
    polygon.handle = poly;                // this doesnt work
});
listOfPolyHandles.push(polygon);   // this doesnt work
```
Here the console output will be *polyline handle: {}* and the polyline will not be removed.
I am testing on a LG G2 Android Version 4.4.2.
Strangely for addCircle() the handle is ok and I can *handle.remove()* circles later on.

By the chance, there is no other way to recover the handles?

**Comment by wf9a5m75** [comment]
![screen shot 2015-02-13 at 11 42 21 am](https://cloud.githubusercontent.com/assets/167831/6194049/6ff1c786-b375-11e4-851b-6c792554ed69.png)

**Comment by wf9a5m75** [comment]
![screen shot 2015-02-13 at 11 45 43 am](https://cloud.githubusercontent.com/assets/167831/6194102/de6e2eac-b375-11e4-8421-229e6e82ba4e.png)

**Comment by wf9a5m75** [comment]
All source code is open.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L869

**Comment by der-ede** [comment]
Hi, thank you for the fast response, I don't know whether *polyline = new Polyline(..)* is a function or an object, but the solution was actually quite simple (I updated the question above).

**Comment by wf9a5m75** [comment]
```polyline = new Polyline(...)``` generates an instance of Polyline class.
The generated instance (polyline) is still `function`, not JSONObject.
That's why you get `{}` using JSON.stringify()   (because it's no JSONObject)

Do you mean you want to save polylines into an array?
Your code is wrong. You need to understand in asynchronous.

The browser executes this steps.
![steps](https://cloud.githubusercontent.com/assets/167831/6195000/a83ca97c-b37e-11e4-9e75-639d8e6abce7.png)

**Comment by wf9a5m75** [comment]
In order to help your understand, write a simple code.

```js
function addPolyline(colorValue, callback) {
  setTimeout(function() {
    return {
       color: colorValue
    }
  }, 100);
}

var polygon = {};
addPolyline("#AA00FF", function(poly) {
  console.log( "poly.color = " + poly.color );
});
console.log("polygon = " + JSON.stringify( polygon ));
```

**Comment by der-ede** [comment]
You're right, but now I got it this way, but thank you anyway.
No problem I got it, the callback function is only executed when the polygon is drawn
