### ISSUE TITLE
Circle Radius "relative"

### ISSUE THREAD

**Issue by der-ede** [wf9a5m75/phonegap-googlemaps-plugin#401]
Hi Mr. Katsumata,

just one more question. The polylines have a constant width independent of the zoom level.
How would you implement the same behaviour for circles, meaning the circle should look the same in every zoom level?
Or do I have to add an event listener for CAMERA_CHANGE and then redraw the circle for changing zoom factors, which would be inconvenient.

Regards

**Comment by wf9a5m75** [comment]
You have to add an event listener for CAMERA_CHANGE and then redraw the circle for changing zoom factors.
The plugin does not support this feature because Google does not support.

**Comment by der-ede** [comment]
Ok, then, or maybe use a circle shaped marker instead, but then I would probably have to take different screensizes into account.
