### ISSUE TITLE
Multiple markers results in sluggish performance

### ISSUE THREAD

**Issue by imduffy15** [wf9a5m75/phonegap-googlemaps-plugin#402]
Hi,

If I had multiple markers (100+) I experience sluggish performance.

Any workaround or fix for this?

**Comment by wf9a5m75** [comment]
I have been developing MarkerCluster to solve this problem, but not finished yet.https://github.com/wf9a5m75/phonegap-googlemaps-plugin#do-you-want-to-use-marker-cluster

**Comment by deliriousrhino** [comment]
Once the markers are drawn the performance seems fine.
Would it be possible to a create a bulk add marker feature might speed up the process rather than loop calls going over the cordova js bridge?

**Comment by imduffy15** [comment]
I'd have to disagree with that. Performance is awful with lots of markers
zooming becomes jaggy, panning/tilting about the map is insanely slow.

I believe clustering the markers is the only solution.

**Comment by deliriousrhino** [comment]
Would depend on your device. Clustering would be a valuable feature. I also think bulk add could help in some situations even for smaller numbers it could increase performance

**Comment by imduffy15** [comment]
I was testing on a nexus 7 tablet and a Samsung s5.
