### ISSUE TITLE
class "_gmaps_cdv_" is not being removed from parent divs.

### ISSUE THREAD

**Issue by drrasic** [wf9a5m75/phonegap-googlemaps-plugin#406]
Hi,
As i said in the title, i am getting this class "_gmaps_cdv_" appened to all perent elements of map DIV every time i navigate to Map page, 
so they get stacked like this: class="_gmaps_cdv_ _gmaps_cdv_ _gmaps_cdv_"

(its an Ionic app with standard map initialisation, nothing special.)
other than that, everything is working fine.

**Comment by wf9a5m75** [comment]
Please use the test branch.
```
$> cordova plugin rm plugin.google.maps
$> rm -rf  /platforms/ios/(your app)/Plugins/plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=... --variable API_KEY_FOR_IOS=...
```

**Comment by wf9a5m75** [comment]
This issue has fixed in the test branch.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/358

**Comment by drrasic** [comment]
I am unable to build my app with test branch, build is failing with error 653 & 698,
so i just took few lines of code where the fix was, and its working fine... thanks.
