### ISSUE TITLE
in Sencha Touch how can i use this plugin in a view

### ISSUE THREAD

**Issue by dkiran** [wf9a5m75/phonegap-googlemaps-plugin#409]
we would like to learn how this plugin map can be used in sencha view panel,

when we use panel ->html:<div id=map"></div>, map is loading but it taking full screen, and other panels in the view are not shown

**Comment by wf9a5m75** [comment]
I'm sorry, but I'm not familiar with Sencha Touch.

In order to display the map in the div, you need to specify the div tag like this:
```js
var div = document.getElementById("map_div");
var map = plugin.google.maps.Map.getMap(div);
map.addEventListener(map, plugin.google.maps.event.MAP_READY, function() {
   
   // map.addMaker(...) 

});
```

**Comment by wf9a5m75** [comment]
@dkiran Is there any update?

**Comment by dkiran** [comment]
Hi Sir,
we are not having any problem in showing map. the problem is while we use it in Sencha view,  map is taking 100% size of height. and its overlapping other components of the view.

Thanks for your reply

**Comment by dkiran** [comment]
in sencha view, this map is placed on top of all components, so other components are not visible. we tried by making map div tag background color transprent

**Comment by wf9a5m75** [comment]
Could ypu show me the screenshot?

**Comment by wf9a5m75** [comment]
@dkiran Any update?

**Comment by dkiran** [comment]
![screenshot_2015-03-03-16-32-28](https://cloud.githubusercontent.com/assets/5877921/6462628/b0b5405e-c1d0-11e4-936f-d00b0e4248f1.png)

This is how map covers all my other elements

**Comment by dkiran** [comment]
![screenshot_2015-03-03-17-26-06](https://cloud.githubusercontent.com/assets/5877921/6462656/de7d6e76-c1d0-11e4-9a3c-b680e34cb5ea.png)

These are all my other components on the screen. i need all componets on the map. when i use map, it is covering all these components. 
![e__sencha_latestworkings_fasttrack4_mentormaksim_www_app_view_showmap js mentormaksim - sublime text 2 unregistered 2015-03-03 17 50 42](https://cloud.githubusercontent.com/assets/5877921/6462676/1ad49318-c1d1-11e4-8537-fd21d10d9797.png)

this is how i used map in sencha

![e__sencha_latestworkings_fasttrack4_mentormaksim_www_app_controller_showmap js mentormaksim - sublime text 2 unregistered 2015-03-03 18 01 20](https://cloud.githubusercontent.com/assets/5877921/6462682/23eda1e2-c1d1-11e4-8288-0481bc4ef5f6.png)

this how i used map to load in sencha

**Comment by MichaelGooden** [comment]
​You cannot use HTML overlays when you are using fullscreen map dialog. You
need to remove the `map.showDialog();` call.

**Comment by MichaelGooden** [comment]
​Additionally, all your other elements you want shown need to reside
*within* the `map_canvas` `div`, so the plugin knows to display them.

**Comment by wf9a5m75** [comment]
@dkiran You are on the wrong way.
Please follow the @MichaelGooden 's comments.

**Comment by dkiran** [comment]
@Michael Gooden, Thanks for your information, as you said all other elements need to be inside map_canvas. div. how can sencha elements can be placed inside div tag. i struck here.

**Comment by MichaelGooden** [comment]
​Unfortunately I have no experience with Sencha.​ See if you can use custom
template or similiar method to ensure sencha elements reside in map_canvas
element.

**Comment by dkiran** [comment]
Thanks Michael Gooden, i will try, Thanks for your quick reply

**Comment by Yoinbol** [comment]
I'm also trying to get this plugin works with Sencha Touch and I'm having issues to, but the opposite. My elements are appearing in front of the map

https://www.dropbox.com/s/3ow2e3excvpfutv/Screenshot%202015-03-09%2020.28.00.png?dl=0

**Comment by wf9a5m75** [comment]
@Yoinbol Your app is cool design :+1: 
But I couldn't understand what is your problem.

**Comment by Yoinbol** [comment]
Thanks @wf9a5m75 
The problem is (I think) that the map is trying to use all the available space on the screen, not only the space covered by the div where I'm creating it.

This screenshot is from the app running on Chrome ( the plugin does not run on this mode of course ):

https://www.dropbox.com/s/xczzb6st3j96cxl/Screenshot%202015-03-09%2020.33.36.png?dl=0

As you can see, there is a blue div, which is the one that I'm using to wrap the map, but when I run the app on a device context ( where the plugin runs successfully ) it seems like the map try to cover not only the div but also the entire viewport.

**Comment by wf9a5m75** [comment]
@Yoinbol Could you send me your apk file to wf9a5m75@gmail.com ?
I will check it.

**Comment by wf9a5m75** [comment]
I think the div is large size than you expected.
In order to test, try to specify small size (such as 400x400) to the map div.

**Comment by Yoinbol** [comment]
@wf9a5m75 great news!! It's working now!!! And looks great on both iOS and Android!! I had to change some css but on my sencha elements, not on the plugin.

Thanks for your quick responses and interest!

**Comment by wf9a5m75** [comment]
Sounds great!

**Comment by dkiran** [comment]
@Yoinbol did you placed any sencha elements on top of the map? please share your email id

**Comment by dkiran** [comment]
@Yoinbol  can you help me in placing sencha elements on top of this google map api.

Thanks in advance
D Kiran

**Comment by Yoinbol** [comment]
Hi @dkiran I have an "empty" map working (empty = no sencha elements into it).
Now I'm trying to create a second map on a "full screen" view. The map is created successfully but it's been rendered behind the whole app content.

I'm guessing (and it's just a guess) all this problems are related to a z-index property on the rendered map.

You can contact me at diego.garcia.segura@gmail.com just in case. I can share code if you need.

**Comment by wf9a5m75** [comment]
You can not put any HTML elements on the map if you use map.showDialog(),
because the map is over the browser view.

**Comment by Yoinbol** [comment]
Thanks @wf9a5m75 I'm not using map.showDialog() currently.

**Comment by dkiran** [comment]
@Yoinbol, its not z-index property, i tried using z-index but no use. my problem is map is occupying complete screen, iam using xtype:panel and in that html tag am using map div, all other panels are behind the map.

**Comment by wf9a5m75** [comment]
Any update, guys?

**Comment by Yoinbol** [comment]
I have it partially working but it's kind of hard to make it work in Sencha Touch. Once the map is rendered there are a lot of things that are going to give you troubles like showing sencha dialogs which buttons won't work unless you disable (and enable again later) "click" events on the map.

The plugin is great, maps looks awesome but at least the app that I'm working on right now it's not worthy to have to deal with all those problems. My app is not "geolocation based", I mean, maps are a "nice to have" but app's core functionality does not rely on geolocation, so, that's why I'm giving up with this plugin + Sencha Touch (for now). I'll be using the google maps javascript API and I'll be using pure html based maps as that API works. I know the performance and the user experience won't be the same but again, I know my final users won't die because maps are not the main thing on my app.

Thank you very much @wf9a5m75 for your attention and for building an outstanding plugin.

**Comment by wf9a5m75** [comment]
Ok, thank you for letting me know, @Yoinbol

**Comment by dkiran** [comment]
@wf9a5m75, same problem for me, am successful in using plugin +sencha touch, but the problem is other components of sencha like dialog etc wont work till we disable and enable click events on the map. can we improve some thing on this.

**Comment by wf9a5m75** [comment]
The plugin can not detext what HTML elements on the map except the elements under the map div.

It means the plugin can not detect the dialog is over  on the map or not.

So if the dialog is shown, but if you don't set `map.setClickable(false)`, the plugin passes the.click event to the map view.

**Comment by dkiran** [comment]
Thanks @wf9a5m75, am using map.setClickable(false), its working for me. but every time i need to take care when dialog display on map/ or any other component of sencha.

Thanks

**Comment by wf9a5m75** [comment]
Yes, you have to.
