### ISSUE TITLE
Distinguishing between events on map

### ISSUE THREAD

**Issue by der-ede** [wf9a5m75/phonegap-googlemaps-plugin#410]
Hi there,

maybe this is also interesting to other users since it is a quite common usecase for a map.
I can handle the events as listed in your readme file (https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#listen-events).
I am updating the map every second with the actual gps signal, so my position is always in the middle.
But when the user "scrolls" the map, this event should be handled extra (timeout to move camera back to my position being in the middle of the map after 10 seconds of no scrolling or clicking of the map by the user).

The problem is now that the CAMERA_CHANGE event which I am using is also fired when the map is scrolled via map.animateCamer or map.moveCamera.
How can I distinguish now whether the map is moved by the user or the camera?

I've tried everything so far but haven't found a solution yet.
Maybe also some other programmers that utilize this plugin know an answer to this.

Regards

**Comment by wf9a5m75** [comment]
Hmm, there is no way currently (I think).

How about use global variable as flag?

```js
var moveFlag=flase;

map.on(plugin.google.maps.event.CAMERA_CHANGE, function(){
    console.log( "moveFlag="+ moveFlag);
});

function onBtnClick(){
    moveFlag=true;
    map.animateCamera({...}, function(){
        moveFlag = false;
    });
}
```

**Comment by der-ede** [comment]
I've tried that already actually, didn't work.
onBtnClick() could also be the update-function for gps.
It is because the gps is updated every second and the manual scrolling of the map will happen likely in between the moveFlag=true and setting it false again.
Actually, I will try it again tomorrow, maybe there are still errors.

**Comment by der-ede** [comment]
Ok, it was just a little error in a script similar to your suggestion.

**Comment by dkiran** [comment]
Hi der-ede,

i have a map with animateCamera, i dont want CAMERA_CHANGE event fire, while animateCamera event. after animateCamera i want to handle CAMERA_CHANGE,
Can you help me. in this

Thanks & Regards
D Kiran

**Comment by der-ede** [comment]
Hi @dkiran : 
I dont have a lot of time right now, but should be more or less sth like this:
``` Javascript
wfgwefweg
```

**Comment by dkiran** [comment]
Thanks der-ede, its working, i tried as per your code. it is working. thanks for your reply
