### ISSUE TITLE
Getting X and Y coordinates of a marker

### ISSUE THREAD

**Issue by i11ume** [wf9a5m75/phonegap-googlemaps-plugin#412]
First of all thanks for this amazing plugin. Is it possible to get X,Y coordinates of a marker? What I'd like to do is be able to put an html element on top of the map like your examples, but I want it to line up with a specific marker and use css animations. Let me know if there's some way I could do that. I don't mind writing the code myself or helping in some way if there's a need.

**Comment by wf9a5m75** [comment]
Use `map.fromLatLngToPoint(LatLng, function([x, y]) {})`

**Comment by Hirbod** [comment]
Hi,

there are a few ways to achieve this. By default, a marker click will always be centered after click. As you know the position of the map and the height and width, you could calculate this easily.

If you've disabled autopan (there is a function for this), then you need to get the coords of your click event.

The third and last method (and probably) the easiset one is to use 

```
map.fromLatLngToPoint()
```

**Comment by wf9a5m75** [comment]
Thanks @Hirbod :+1:

**Comment by i11ume** [comment]
Amazing, I thought I read through the whole reference, but I missed it. Thanks so much!

**Comment by Hirbod** [comment]
You're welcome!
