### ISSUE TITLE
Inconsistent KML parsing on Android and iOS

### ISSUE THREAD

**Issue by MichaelGooden** [wf9a5m75/phonegap-googlemaps-plugin#414]
I have noticed odd behaviour with `addKmlOverlay` between Android and iOS.

This is the KML exported directly from Google Earth: https://gist.github.com/MichaelGooden/12d28b98e8e7bfe1d2e2
This KML loads fine into Android, however on iOS crashes with the following error:
`NSInvalidArgumentException Trace: <redacted> -[KmlOverlay _filterStyles:styles:] -[KmlOverlay _filterStyles:styles:] __31-[KmlOverlay parseKML:command`
(that is what I get from the crash logger on Google Analytics, I do not have a Mac to be able to debug the device correctly)

This is the KML I hand modified, which now works fine on both iOS and Android: https://gist.github.com/MichaelGooden/c9a4a1ee859205db90ae

**Comment by wf9a5m75** [comment]
Thank you for sharing your kml file.

I think `<hotSpot x="32" y="1" xunits="pixels" yunits="pixels"/>` causes this error.
Remove this code, and try again, please.

**Comment by wf9a5m75** [comment]
I tested your KML, but I didn't get your error.

**Comment by wf9a5m75** [comment]
Ah, ok. I was wrong. I got the same error with you.

**Comment by wf9a5m75** [comment]
I fixed this issue. You can load the original KML file from Google Earth.

**Comment by MichaelGooden** [comment]
I discovered removing the <StyleMap> elements fixed the file for me. Does your fix cover that?

**Comment by wf9a5m75** [comment]
You don't need to remove the stylemap elements anymore.
Use the test branch.

**Comment by MichaelGooden** [comment]
I am using PhoneGap Build, so I need to wait for you to release full version :)

**Comment by wf9a5m75** [comment]
I think you can use the test branch even you use PhoneGap Build.

In the below issue list, @goya mentioned building from the branch is implemented.
https://github.com/phonegap/build/issues/2

**Comment by MichaelGooden** [comment]
​That is for the actual app code, not for plugins. Don't worry, I did my
quick fix for now, once you release the new version I will then not need to
worry.​
