### ISSUE TITLE
store a marker in a global variable ?

### ISSUE THREAD

**Issue by faouzig1990** [wf9a5m75/phonegap-googlemaps-plugin#416]
Hello,
i came across this issue lately when i was trying to remove specific markers and then i just found out that i can't store the marker in a global variable or any variable, am i the only one going through that ?
Any help regarding how to store a marker in a global variable will be appreciated and thanks in advance ;)

best regards

**Comment by Hirbod** [comment]
You can store a marker into a global var.

var myglobal;

map.addMarker({
... Options
}, function(marker){
  myglobal = marker;
});

**Comment by faouzig1990** [comment]
Thank you ;)

**Comment by Hirbod** [comment]
you're welcome.
