### ISSUE TITLE
Ionic + plugin = weird view positioning

### ISSUE THREAD

**Issue by Serafijn** [wf9a5m75/phonegap-googlemaps-plugin#417]
Hi all,

This is my first post on github so excuse me if i'm not providing enough information.

I'm working on a hybrid app with the ionic framework and I have to implement a map in some view.
Everything works well, the map is rendered but there

 are two issues i'm facing with.
1) My side menu - actually the content of it - is visible and its placed over the map. I'm 100% sure that my menu is collapsed and its only the content of the side menu that is places above the map.

![img_20150225_202229](https://cloud.githubusercontent.com/assets/6762294/6384561/333e0ab4-bd2c-11e4-9a69-74176ff113ef.jpg)

2) My app works way slower when i'm using this plugin. It's only slower on a specific view and in that view the map is not used at all.

Does anyone has an idea how to fix at least one of these issues?

**Comment by wf9a5m75** [comment]
@Serafijn I can't understand what the problem is for (1).

(2) I'm not expert of ionic. Please check the past Q&A
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?q=ionic&type=Issues&utf8=%E2%9C%93

**Comment by Serafijn** [comment]
Thanks for your response.

The problem with (1) is that for some reason in that view the content of my side menu is shown, yet the side menu is not opened. You can see that because the open/hide button is all the way to the left en the buttons doesn't respond on any clicks.

**Comment by wf9a5m75** [comment]
Did you read this?
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#mapsetclickable

**Comment by Serafijn** [comment]
Yes, i've already tried that with no result.

**Comment by MichaelGooden** [comment]
This has to do with the Ionic side menu. It is a problem someone had before, I also solved it previously, but I have stopped using the side menu since.

You need to hide the side menu when it is fully closed.

**Comment by Serafijn** [comment]
Allright, I'll try that.
Also now the map is the only content inside an ion-view but when i'm placing the map inside a more complex view, lets say a card view, the view is getting rendered even more strange with very strange behavior.

**Comment by wf9a5m75** [comment]
Ah, I just remembered. Ionic places the side menu UNDER the ion-view, but because of map view is under the browser, the plugin changes all HTML element backgrounds are transparent.
https://googledrive.com/host/0B1ECfqTCcLE8R0h6T3dIdWFBOHM/mechanism.png

https://googledrive.com/host/0B1ECfqTCcLE8SVJLc2VWZHV3dWM/ionic_sidebar.gif

In order to solve this, you need to place your side menu OVER the ion-view.


Please read this thread.
http://forum.ionicframework.com/t/using-google-maps-cordova-plugin/4456/41

**Comment by Serafijn** [comment]
Ok thank you.
I'll try that when i'm done with another aspect of the application.

Thank you for your help!

**Comment by Hirbod** [comment]
I don't know Ionic as I do use OnsenUI, but when available, you should use a "push" menu, not "underlay", "overlay" or "reveal" animation. This will work as it will push the content (and the map has a watchdogTimer for repositioning)

**Comment by Serafijn** [comment]
I'm very new to Ionic so someone correct me if I'm wrong but Ionic doesn't work like that. 
As mentioned in an answer you can find above, Ionic places his menu under the view, but the map sets the background of the view to blank.

**Comment by Hirbod** [comment]
You need to listen to the menu events (preopen, postopen etc) and hide the map.
OnsenUI had a lot of more configs for the menu, I thought Ionic has also.

**Comment by ricardobylife** [comment]
I did this.
Menu item:
<ion-side-menu side="left" ng-class="(hide_menu === true) ? 'no-show' : 'show'">

and in the controller:
$rootScope.hide_menu = false;
  $scope.$watch(function(){
    return $ionicSideMenuDelegate.isOpenLeft();
  },
  function(isOpen){
      if(isOpen){
        $rootScope.hide_menu = false;
      } else {
        $rootScope.hide_menu = true;
      }
  });

**Comment by poseydonfba** [comment]
I am having the same problem.
But I could not understand how to solve.

**Comment by gonadn** [comment]
Hi

Iam having same issue with side menu, does anyone manage to fix this issue with menu diaplying over the map?
