### ISSUE TITLE
Weird crash on addGroundOverlay

### ISSUE THREAD

**Issue by MichaelGooden** [wf9a5m75/phonegap-googlemaps-plugin#418]
I am getting a really odd crash when I am using the `addGroundOverlay` function.

This crash only happens on certain devices, it is reproducible 100% of the time on those devices, but on other devices it never crashes.

These are the crash details obtained, they are identical on both devices that crash:
```
java.lang.NullPointerException
	at com.google.maps.api.android.lib6.gmm6.c.m.a(Unknown Source)
	at com.google.maps.api.android.lib6.gmm6.c.u.a(Unknown Source)
	at com.google.maps.api.android.lib6.gmm6.o.l.a(Unknown Source)
	at com.google.maps.api.android.lib6.gmm6.o.l.b(Unknown Source)
	at com.google.maps.api.android.lib6.gmm6.o.cw.k(Unknown Source)
	at com.google.maps.api.android.lib6.gmm6.o.cw.run(Unknown Source)
```
I so far have found this crash on 3 devices. 2x Sony D6603 and a generic 8'' tablet. The Sonys runs 4.4.4 and the tablet 4.4.2. The app runs successfully on my personal phone with Android 4.4.2, so I do not believe that it is related to the Android version.

The Sony devices belongs to two of my Beta testers, but I was able to pull a device log from my tablet. I have filtered by my apps PID, I did not want to go finer than that, as I do not know what information you need: https://gist.github.com/MichaelGooden/53d0c1069f953117586a

This is log pulled from my device that does not crash: https://gist.github.com/MichaelGooden/93b96f3c155ab49b442e

This is code where the crash happens:
```js
          console.log("venue");
          var bounds = [
            new plugin.google.maps.LatLng(-33.98215741131521,25.65981583852531),
            new plugin.google.maps.LatLng(-33.9844941948672,25.65636689728938)
          ];
          map.addGroundOverlay({
            'url': "www/kml/Boardwalk.png",
            'bounds': bounds,
            'opacity': 1,
            'bearing': 228.6771966058391
          }, function(groundOverlay) {
            console.log("add ground overlay success");
          });
          console.log("add ground overlay");
```
This code is wrapped earlier in a `MAP_READY` callback.

Comparing logs between the crashing device and working device, the success callback is never called on crashing device, as long does not reflect `console.log("add ground overlay success");`

What stands out to me is that on the crashing device, this log line shows up immediately after the crash:
```
D/CordovaLog(17415): file:///android_asset/www/plugins/plugin.google.maps/www/googlemaps-cdv-plugin.js: Line 114 : null
```
Whereas in the working device, that `null` never gets logged.

I thank you again for your assistance.

**Comment by wf9a5m75** [comment]
In your log, the key-point is here:

```
W/System.err(17415): java.lang.reflect.InvocationTargetException
W/System.err(17415):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17415):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(17415):    at plugin.google.maps.MyPlugin.execute(MyPlugin.java:50)
W/System.err(17415):    at plugin.google.maps.GoogleMaps$3.run(GoogleMaps.java:250)
W/System.err(17415):    at android.os.Handler.handleCallback(Handler.java:808)
W/System.err(17415):    at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(17415):    at android.os.Looper.loop(Looper.java:193)
W/System.err(17415):    at android.app.ActivityThread.main(ActivityThread.java:5292)
W/System.err(17415):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17415):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(17415):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
W/System.err(17415):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
W/System.err(17415):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(17415): Caused by: java.lang.NullPointerException
W/System.err(17415):    at com.google.k.a.cj.a(Unknown Source)
W/System.err(17415):    at com.google.maps.api.android.lib6.c.dc.<init>(Unknown Source)
W/System.err(17415):    at com.google.maps.api.android.lib6.c.db.a(Unknown Source)
W/System.err(17415):    at com.google.maps.api.android.lib6.c.eu.a(Unknown Source)
W/System.err(17415):    at com.google.android.gms.maps.model.internal.k.onTransact(SourceFile:246)
W/System.err(17415):    at android.os.Binder.transact(Binder.java:361)
W/System.err(17415):    at com.google.android.gms.maps.model.internal.c$a$a.m(Unknown Source)
W/System.err(17415):    at com.google.android.gms.maps.model.GroundOverlay.setImage(Unknown Source)
W/System.err(17415):    at plugin.google.maps.PluginGroundOverlay._setImage(PluginGroundOverlay.java:95)
W/System.err(17415):    at plugin.google.maps.PluginGroundOverlay.createGroundOverlay(PluginGroundOverlay.java:74)
W/System.err(17415):    ... 13 more
```

In the above log, you can find two lines:
```
W/System.err(17415):    at plugin.google.maps.PluginGroundOverlay._setImage(PluginGroundOverlay.java:95)
W/System.err(17415):    at plugin.google.maps.PluginGroundOverlay.createGroundOverlay(PluginGroundOverlay.java:74)
W/System.err(17415):    ... 13 more
```

This means your app calls 
```
(js) map. addGroundOverlay() ->
    (native) PluginGroundOverlay.createGroundOverlay (PluginGroundOverlay.java:74) ->
        (native) PluginGroundOverlay.createGroundOverlay (PluginGroundOverlay.java:95) ->
           ----> crash inside the Google Maps Android API v2
```

Let's take a look at [PluginGroundOverlay.java line 95](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/PluginGroundOverlay.java#L95).
![addgroundoverlay](https://cloud.githubusercontent.com/assets/167831/6391907/2af18efa-bd70-11e4-94ee-90a955b6e9c8.png)

So your app tied to load your picture file, but it couldn't load it.

----

I'm not sure what dimension of the image file, but in order to confirm the problem more detail,
- try to set more small image,
- change the image file format,
- or change the bounds.

If the error is still occurred, report to Google Maps API issues list.
It seems the internal error of Google Maps Android API v2.

**Comment by wf9a5m75** [comment]
@MichaelGooden Any updates for this issue?

**Comment by wf9a5m75** [comment]
It seems this is a bug of Google Maps Android API v2.
https://code.google.com/p/gmaps-api-issues/issues/detail?id=6286

**Comment by wf9a5m75** [comment]
And also this issue is related.
https://code.google.com/p/gmaps-api-issues/issues/detail?id=7696

**Comment by wf9a5m75** [comment]
I fixed this issue using alternative code.
You can use this in next version.
The next version will be released in couple of days.
Please wait.
