### ISSUE TITLE
Draw route line between two geographic locations on Google Maps

### ISSUE THREAD

**Issue by sangariv** [wf9a5m75/phonegap-googlemaps-plugin#419]
HI,
can you tell me how to draw a route path between two points.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?q=direction+&type=Issues&utf8=%E2%9C%93

**Comment by wf9a5m75** [comment]
This plugin does not support Google Direction API.
I want to implement it, but there is no enough time.

Meanwhile, you can use through Google Maps JavaScript API v3, or write your code for Google Direction API.

**Comment by sangariv** [comment]
THanks for your reply
