### ISSUE TITLE
How to draw a rout on the map?

### ISSUE THREAD

**Issue by Maturaprojekt** [wf9a5m75/phonegap-googlemaps-plugin#422]
Hello, I just implemented your demo plugin and everything is working fine - thanks!
But before i implement your plugin in my real app i wanted to test a few things in the demo map which i dont really know how to do.
First off all i would like to draw routes on the map: For example i would like to give the start and endpoint and a polyline gets draw on the map where i could go with the car. Can i just use googles calculateRoute() function you find on there official webside?
Like this for example:

function calcRoute() {
  var start = document.getElementById('start').value;
  var end = document.getElementById('end').value;
  var request = {
      origin:start,
      destination:end,
      travelMode: google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

And my second question is am I able to style the map so it apears different? If yes, how can i do it?
Thanks in advance and thanks for making this easy to use plugin!

**Comment by wf9a5m75** [comment]
As your training, create a small app before implementing to your real app.

(1) DirectionService does not provide this plugin, thus you need to get the result using Google Maps Javascript API v3.
But the map is not HTML element, so you need to parse the result, then add markers and polylines for this plugin.

(2)styled map is not provided for Google Maps Android API v2 and Google Maps SDK for iOS.
Thus, this plugin can not provide it.

**Comment by Maturaprojekt** [comment]
Thanks for the answere! But if i create a marker and connect these two markers with a polyline wont i have just a straight line? If this would be the case it isnt thast usfully for my app since i only wont to print out routes.

**Comment by wf9a5m75** [comment]
The result of direcyionService includes the steps of the route.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?q=direction+&type=Issues&utf8=%E2%9C%93
