### ISSUE TITLE
Error trying to use Test branch

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#423]
I am using this plugin with master version without problems, but now i need to solve the error that cause the map in dialog mode not being able to close so i try the test branch but is giving me an error when compiling Android:
````
Error code 1 for command: ant with args: debug,-f,/Users/leandroz/Desktop/project_zone/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR building one of the platforms: Error: /Users/leandroz/Desktop/project_zone/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
````
Without the plugin installed is working just fine, when i add it the error start.

**Comment by Hirbod** [comment]
Please post more of the error log. I guess this is again related to the "res/crunch" directory inside of google-play-services

**Comment by leandroz** [comment]
More info:
invalid resource directory name: /Users/leandroz/Desktop/project_zone/platforms/android/com.google.playservices/wooftagg-google-play-services_lib/bin/res crunch

**Comment by Hirbod** [comment]
Yeah, as I thought. @wf9a5m75 why does this error start since v22? We need to get rid of this.

@leandroz: Bug is easy fixed. Just go to

```/Users/leandroz/Desktop/project_zone/platforms/android/com.google.playservices/wooftagg-google-play-services_lib/bin/res```

and delete the "crunch" folder inside of it (just this), not the res folder itself. Remember: as soon as you open eclipse it will be regenerated, avoid to work with eclipse. After you've deleted, the plugin will build

**Comment by leandroz** [comment]
Thanks @Hirbod , i saw #415 and solve it! thanks!

**Comment by wf9a5m75** [comment]
I don't know the reason. Please ask to Google.
