### ISSUE TITLE
Custom HTML in dialog (fullscreen) mode?

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#424]
Is posible to show html in fullscreen mode? if is not, which part of the code i need to look at to be able to change the bottom bar with the Close and Legal Noticies or at least change the style?

**Comment by Hirbod** [comment]
What do you mean with fullscreen mode?

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map.showDialog%28%29

**Comment by leandroz** [comment]
Yes when i call showDialog(), i want to show custom HTML or remove/edit the bar at the bottom or add a new one at the top, i am looking at the code right now in GoogleMaps.java, when i change something i need to compile or something?

**Comment by Hirbod** [comment]
Yes, the code is native. It should be enough to build with cordova after you've changed it

**Comment by leandroz** [comment]
I am making changes (just some colors) but is still the same, maybe @wf9a5m75 know what i need to do to see the changes reflected on the app.

**Comment by wf9a5m75** [comment]
I think you change the file under the plugins/plugin.google.maps/android/src/plugin/google/maps/

But you need to modify the file under platforms/android/src/plugin/google/maps/GoogleMaps.java

I recommend you should install the test branch with `--link` option. 
```
$ cordova help plugin
Synopsis

    cordova plugin <command> [options]

Manage project plugins

    add <pluginid>|<directory>|<giturl> [...] ..... add specified plugins
                                                    pluginid will be matched in --searchpath / registry
                                                    directory is a directory containing a plugin
                                                    giturl is a git repo containing a plugin

        [--searchpath <directory>] ................ when looking up plugins by ID, look in this directory and
                                                    each of its subdirectories for the plugin before hitting the registry.
                                                    Multiple search paths can be used by either specifying the flag multiple
                                                    times, or by separating paths with a delimiter (: on 'nix, ; on Windows).

        [--noregistry] ............................ don't search the registry for plugins

        [--link] .................................. create a symbolic link to the plugin instead of copying files

    remove <pluginid> [...] ....................... remove plugins with the given IDs

    list .......................................... list currently installed plugins
    search [<keyword>] [...] ...................... search the plugin registry for plugins matching the keywords

aliases:
    plugins -> plugin
    rm -> remove
    ls -> list


Experimental Flags

    --browserify .......................... Plugins javascript gets loaded at build time instead of runtime using browserify.
                                            Replaces cordovajs file with one that includes the JS of the installed plugins.
```

**Comment by leandroz** [comment]
@wf9a5m75 i got ````--link is not supported for git URLs and will be ignored````, so i will change the code in both places, thanks!

**Comment by wf9a5m75** [comment]
Clone the repo to local path at once, then install the plugin from the directory with --link option.

**Comment by leandroz** [comment]
Great!, so there is no way to add any html in fullscreen?, yes or yes native code?, thanks and then close the issue!

**Comment by wf9a5m75** [comment]
There is no way currently.
