### ISSUE TITLE
launchNavigation on iOS

### ISSUE THREAD

**Issue by bFlood** [wf9a5m75/phonegap-googlemaps-plugin#425]
just want to confirm this works on iOS? tested on iOS7.1 only. It doesn't start the google maps app at all (which is installed), same code works great on android

thanks!

**Comment by MichaelGooden** [comment]
​There are many of us using this on both iOS and Android.

Secondly, this does not require the "Google Maps App" to be running or even
installed to work.​

Ensure you have installed the plugin correctly for both platforms.

**Comment by bFlood** [comment]
thanks michael, good to know its working for most people. I'll check everything again

**Comment by wf9a5m75** [comment]
@MichaelGooden :+1:

**Comment by bFlood** [comment]
hi masashi - it doesn't seem to work on appgyver, not sure why

**Comment by wf9a5m75** [comment]
I think it's depends on the values.

This plugin just passes the data to Google Maps app or iOS map app.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/External.m#L17

**Comment by wf9a5m75** [comment]
@bFlood Did you solve this?

**Comment by bFlood** [comment]
no, even tried the simple to/from values in the docs, doesn't do anything on iOS 7.1 (iPad). i agree the plugin is just calling an external service so its pretty straight forward, maybe there's something in the appgyver runtime that's blocking it

if its working for everyone else on iOS, then I guess I'll have to figure it out with appgyver

**Comment by wf9a5m75** [comment]
I see. Have you tried with another iOS devices?

**Comment by bFlood** [comment]
no, this is all I have for testing on iOS at this point

**Comment by wf9a5m75** [comment]
Could you tell me the example the values?

**Comment by bFlood** [comment]
any values I try fail but I also tried this from the docs, nothing happens. I wondering if there's something else in the plugin.xml or maybe another cordova setting that allows for calling external services in iOS (and maybe appgyver does not expose this)

plugin.google.maps.external.launchNavigation({
  "from": "Tokyo, Japan",
  "to": "Kyoto, Japan"
});

**Comment by wf9a5m75** [comment]
I have one question, does your map app will be launched?

**Comment by bFlood** [comment]
no, neither app (google maps or apple maps) is launched

**Comment by bFlood** [comment]
ok, I just deleted the google maps app and now it does work, the apple maps app is launched and the route is displayed. so, it must be something with google maps app

**Comment by wf9a5m75** [comment]
When did you install your google map app?

**Comment by bFlood** [comment]
I just reinstalled the google maps app and the problem is back, so the latest version might cause the issue (I'm pretty sure I had the latest version before as well)

**Comment by wf9a5m75** [comment]
Ok, I will check it.

**Comment by wf9a5m75** [comment]
I don't have my test iPhone(iOS7) right now, I will check this later.

Oh, I just remembered that if your app name includes space character, the Google Maps app does not work probably.... (I forgot the details).

**Comment by bFlood** [comment]
it does have a space, I'll try testing without the space later on

thanks for the help masashi

**Comment by wf9a5m75** [comment]
For your test, modify the `appName` value.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/External.m#L36

**Comment by bFlood** [comment]
that was it, removing the spaces from the app name fixed the issue

thanks masashi

**Comment by wf9a5m75** [comment]
:+1:
