### ISSUE TITLE
deprecations

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#427]
Hi Masashi ( @wf9a5m75 )

I've pulled some code by mistake into master:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/3fbbc159adf2064fbd7adf8f331cf74004197efb

actually wanted to push it into test. If you don't like, please revert and copy to test

**Comment by wf9a5m75** [comment]
Thank you @Hirbod , good patch.

Let's discuss the backward compatibility.
Cordova 3.5 has released almost one year ago (23/May/2014).

I think it's better to keep one year backward compatibility for everyone.
What do you think?

**Comment by Hirbod** [comment]
InAppBrowser does the same, it is backward compatible

**Comment by wf9a5m75** [comment]
`cdv_base64EncodedString` is implemented in Cordova ios 3.8.
There is no `cdv_base64EncodedString` method in cordova-3.5 to 3.7.

So we need to write the code for both, Cordova iOS 3.5-3.7 and Cordova iOS 3.8

**Comment by Hirbod** [comment]
I see, I was talking about the NSJSONSerialization. I don't know if you want to provide two codechecks. 4.0.0 will remove base64EncodedString

**Comment by wf9a5m75** [comment]
Patch code for `NSJSONSerialization` is fine.

**Comment by wf9a5m75** [comment]
But the patch code for `base64EncodedString` needs to consider for old versions (in my opinion).

**Comment by Hirbod** [comment]
Ok, can you do the checks?

**Comment by wf9a5m75** [comment]
I'm looking the cordova's code. I'm thinking.

**Comment by wf9a5m75** [comment]
```objc
  #ifdef __IPHONE_7_0
    if ([PluginUtil isIOS7_OR_OVER] == true) {
      #ifdef __CORDOVA_3_8_0
        base64Encoded = [NSString stringWithFormat:@"data:image/png;base64,%@", [imageData cdv_base64EncodedString]];
      #else
        base64Encoded = [NSString stringWithFormat:@"data:image/png;base64,%@", [imageData base64EncodedString]];
      #endif
    } else {
      base64Encoded = [NSString stringWithFormat:@"data:image/png;base64,%@", [imageData base64Encoding]];
    }
  #else
    base64Encoded = [NSString stringWithFormat:@"data:image/png;base64,%@", [imageData base64Encoding]];
  #endif
```

**Comment by Hirbod** [comment]
But IPHONE_7_0 has nothing to do with Cordova

**Comment by Hirbod** [comment]
I'm blind. Sorry. Of course, there it is

**Comment by wf9a5m75** [comment]
Yeah, let's use the version definition.
I found them in this file.
https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/CDVAvailability.h

**Comment by wf9a5m75** [comment]
Using macro `if` statement, it's a good way to keep backward compatibility easily.

**Comment by Hirbod** [comment]
OK, good. Is CDVAVailablility alwas included?

**Comment by wf9a5m75** [comment]
`CDVAvailability.h` file is included in the `CDV.h` file.
So the file is always included.

**Comment by wf9a5m75** [comment]
https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/CDV.h#L20

**Comment by Hirbod** [comment]
Ok, nice. Then we'll have a good way

**Comment by wf9a5m75** [comment]
Yeah!
Thank you for creating a good patch.

**Comment by Hirbod** [comment]
Just one fix left:

GoogleMapsViewController.m

```C
    NSString* jsString = [NSString stringWithFormat:@"plugin.google.maps.Map._onMapEvent('will_move', %hhd);", gesture];
```
BOOL passed for char, don't know how to handle it. Actually we could convert to CHAR but this could lead into errors


Thank you :)

**Comment by wf9a5m75** [comment]
Oh, I've forgotten the code.
In order to prevent the error, how about like this:

```js
App.prototype._onMapEvent = function(eventName) {
  var args = [eventName];
  for (var i = 1; i < arguments.length; i++) {
    if (typeof(arguments[i]) === "string") {
     if (["true", "false"].indexOf(arguments[i].toLowerCase()) > -1) {
       arguments[i] = parseBoolean(arguments[i]);
     }
    }
    args.push(arguments[i]);
  }
  args.push(this);
  this.trigger.apply(this, args);
};
```
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L228

**Comment by Hirbod** [comment]
Looks good to me

**Comment by wf9a5m75** [comment]
The master branch is already patched. ( I forgot to write the issue number )
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/Map.m#L267-L279

**Comment by Hirbod** [comment]
ok

**Comment by wf9a5m75** [comment]
Thank you for your work ;)

**Comment by Hirbod** [comment]
I wanted to push to test but I can't revert. But if its ok for you, thanks.
