### ISSUE TITLE
Install Problem with plugin.http.request

### ISSUE THREAD

**Issue by rgallagher27** [wf9a5m75/phonegap-googlemaps-plugin#428]
I'm getting errors when adding this plugin to my project:
 
    Installing "plugin.google.maps" for android
    Fetching plugin "plugin.http.request" via plugin registry
    npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/plugin.http.request/-/plugin.http.request-1.0.4.tgz
    npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/plugin.http.request/-/plugin.http.request-1.0.4.tgz
    npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/plugin.http.request/-/plugin.http.request-1.0.4.tgz
    Failed to install 'plugin.google.maps':Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:124:16)
    Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:124:16)

**Comment by wf9a5m75** [comment]
Try again later

**Comment by Hirbod** [comment]
I'm closing this. If you'll stuck later, don't hesitate to write, I'll reopen afterwards.
