### ISSUE TITLE
Force language in geocode

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#429]
Hi Masashi,

currently, I'm getting the geocoding results in the users device language (sometimes it's arabic, sometimes russian). How can I force the device to always return in "de" for german?

In Google Maps JS API, I just need to put &language=de to the string, thats enough. We really need a way to set this in this plugin also.

**Comment by Hirbod** [comment]
Regarding to this: http://stackoverflow.com/questions/12174606/how-to-force-language-in-which-reverse-geocoding-data-on-ios-is-received

and this: http://stackoverflow.com/questions/22596087/google-maps-sdk-for-ios-localization
(when really true) it seems not to be possible... Damn.

**Comment by wf9a5m75** [comment]
There is no option for that.

**Comment by dukhanov** [comment]
Hi Hirbod, 

Have you tried to change the localization for your app (Applies to the Android only)?

```java
public class CordovaApp extends CordovaActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        super.init();

        // change application locale
        String languageToLoad  = "de";
        Locale locale = new Locale(languageToLoad);
        Locale.setDefault(locale);
        Configuration config = new Configuration();
        config.locale = locale;
        getBaseContext().getResources().updateConfiguration(config, null);

        loadUrl(launchUrl);
    }
}
```
