### ISSUE TITLE
Geocoding api v2 is down must upgrade to v3

### ISSUE THREAD

**Issue by mrabbah** [wf9a5m75/phonegap-googlemaps-plugin#430]
Hello,
First thanks for your hard work on this plugin,
Geocoding api v2 was turned off by google and upgrade to v3 must be done!
https://developers.google.com/maps/documentation/geocoding/
https://developers.google.com/maps/articles/geocodingupgrade

**Comment by Hirbod** [comment]
:D 

Android Maps SDK v2 has nothing todo with JS-API. Everything is fine!

**Comment by mrabbah** [comment]
Oh, Yes your ar right, it seem that i have reached limit request per day
Thanks alot

**Comment by Hirbod** [comment]
If you use the internal decoder, you'll have no limits

**Comment by mrabbah** [comment]
can you give me a link were I can read about internal decoder

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Geocoder
