### ISSUE TITLE
tilt not found when we send more than one latlng coordinates

### ISSUE THREAD

**Issue by fgarzonhz** [wf9a5m75/phonegap-googlemaps-plugin#431]
We are sending this: 
```js
map.animateCamera({
    'target': latLngBoundsLocal,
    'tilt': 40,
    'zoom': 18,
    'bearing': 0
}, function() {
    latLngBounds = "";
});
```
however the map not set the camera such as we wrote.
latLngBoundsLocal has like this: 

```
points.push(new plugin.google.maps.LatLng(value.latitude, value.longitude)); //two times with teo different coordinates

latLngBounds = new plugin.google.maps.LatLngBounds(points);
```

**Comment by wf9a5m75** [comment]
Yes, that's the correct behavior.

If you set multiple points to the `target` property, 

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/PluginMap.java#L219

**Comment by wf9a5m75** [comment]
For other people, I added this tips. Thanks 
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map.animateCamera()#fit-camera-to-multiple-points

**Comment by fgarzonhz** [comment]
Thanks.
