### ISSUE TITLE
Arrow (in polilines) with styles

### ISSUE THREAD

**Issue by fgarzonhz** [wf9a5m75/phonegap-googlemaps-plugin#433]
For example, we draw a line, however we want to put over the line the direction of the line, so will be great if we can set the type of the line, such as line with arrow at the sides .

Thanks.

**Comment by wf9a5m75** [comment]
If you create that feature, I'm very appreciated for you :)

**Comment by wf9a5m75** [comment]
Try this one.
http://www.wolfpil.de/v3/arrow-heads.html

The above page draws arrow signs using Google Maps JavaScript API v3 without Symbol.

I don't have enough time to try for this plugin currently, so please try by youeself.
