### ISSUE TITLE
Phonegap Build + googlemaps-plugin

### ISSUE THREAD

**Issue by meneldil** [wf9a5m75/phonegap-googlemaps-plugin#435]
Hello,
Can we expect to have a version for Phonegap Build in the near future? :)
We are limited to the use of Google Maps for Web... This plugin would be a must! :)

Thanks.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/411#issuecomment-75452290

**Comment by meneldil** [comment]
Thank you!
I will look at that. :)
