### ISSUE TITLE
external.launchNavigation couldn't find route on IOS7 

### ISSUE THREAD

**Issue by aramgev** [wf9a5m75/phonegap-googlemaps-plugin#436]
var from = new plugin.google.maps.LatLng(currentLat, currentLng),
            to = new plugin.google.maps.LatLng(posLat, posLng);
    
        plugin.google.maps.external.launchNavigation({
          "from": from,
          "to": to
        }); 

These code works on Android. But on IOS it opens map application and says:
      Directions not available 
      A route cannot be determined from this start location

**Comment by wf9a5m75** [comment]
This plugin just passes the data to the map app.
You need to adjust your input values.
