### ISSUE TITLE
map.getMyLocation() issue on iPhone 4 and maybe others

### ISSUE THREAD

**Issue by n00dl3** [wf9a5m75/phonegap-googlemaps-plugin#437]
Hi,
I'm experiencing issues with your plugin, 
it seems the callback of the method `map.getMyLocation` is called only once.

code :
---------
This is the callback that gets called only once :

    function onLocationFound(location){
        var myLocation = location.latLng;
        $scope.map.addMarker({
            position : myLocation,
            icon : 'www/icons/my_position.png',
            flat : true
        });
    }

This function is called in order to display the map on a page that needs one

    $scope.createMap = function() {
            //do stuffs nothing related to plugin
            $scope.map = plugin.google.maps.Map.getMap(mapElement);
            $scope.map.setDiv(mapElement);
            $scope.map.clear();
            $scope.map.setClickable(true);
            //when we go elsewhere, we remove the map
            $rootScope.$on('$locationChangeStart', removeMap );
            //the callback will only be called the first time
            $scope.map.getMyLocation(onLocationFound);
        }

When you go to another page this function is called in order to remove the map from the screen

    function removeMap(){
        if ($scope.map) {
            $scope.map.setClickable(false);
            $scope.map.remove();
        }
    }

Scenario:
-------------
 1. I'm on page A, a map should be displayed on it so the `$scope.createMap` function is called, and then `onLocationFound`
 2. I switch to page B, the `removeMap` function get called (there's no map on it so no other call is made)
 3. I switch back to page A, another call to `$scope.createMap` but the `onLocationFound` function never gets called

Greetings
---------------
Thank you, Masashi, your plugin saved my life ;)

**Comment by wf9a5m75** [comment]
Thanks for describe your issue. I will check this later.

**Comment by wf9a5m75** [comment]
I just recognized your issue.
```html
<div style="position:fixed;bottom: 100px;">
<input type="button" id="removeBtn" value="Remove Map">
<input type="button" id="addBtn" value="Add Map">
<input type="button" id="locationBtn" value="map.getMyLocation()">
</div>

<script type="text/javascript">
$(document).one("pageLoad", function(evt, result) {
  map.setDiv($("#map_canvas")[0]);

  $("#addBtn").prop('disabled', true);

  $("#removeBtn").click(function() {
    map.remove();
    $("#locationBtn").prop('disabled', true);
    $("#addBtn").prop('disabled', false);
    $(this).prop('disabled', true);
  });
  $("#addBtn").click(function() {
    $(this).prop('disabled', true);
    
    map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
    map.on(plugin.google.maps.event.MAP_READY, function() {
      $("#locationBtn").prop('disabled', false);
      $("#removeBtn").prop('disabled', false);
    });
  });
  
  $("#locationBtn").click(function() {
  
    map.getMyLocation(onLocationFound);
  
  });
  
  function onLocationFound(result) {
    alert(JSON.stringify(result.latLng));
  }
  
});
</script>
```
![issue_437](https://cloud.githubusercontent.com/assets/167831/6604658/20b618f8-c7e7-11e4-93a8-418ac38c3434.gif)

**Comment by wf9a5m75** [comment]
Fixed. Thank you for your report.

In order to fix this issue in your project, open the file at `platforms/ios/DevApp/Plugins/plugin.google.maps/GoogleMap.m" with your text editor, then remove the line `self.locationCommandQueue = nil;` in the remove method.

See: https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/3dd45fabe42b56f45c3d034d30283bf630ca4992

![issue_437](https://cloud.githubusercontent.com/assets/167831/6605146/c510f460-c7ea-11e4-8e47-36e4c9aded68.gif)

**Comment by n00dl3** [comment]
Thanks you for your quick patch ;)
