### ISSUE TITLE
automatic setClickable / jQuery Mobile info

### ISSUE THREAD

**Issue by siran** [wf9a5m75/phonegap-googlemaps-plugin#438]
This is not an issue, maybe a tiny contribution to the docs. 

Regarding the setClickable feature and JQM panels, maybe it would be good to add in the documentation that this can be automatically achievable using:

		$(panelSelector).on("panelbeforeopen",function(){
			map.setClickable( false );
		});
		$(panelSelector).on("panelbeforeclose",function(){
			map.setClickable( true );
		});

**Comment by Hirbod** [comment]
Thanks, I've changed the title and closed the issue, so it will be still searchable for those who search for it.
