### ISSUE TITLE
iOS bug when keyboard opened with an input on the bottom of the map

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#440]
Hello !

Thanks a lots for this really usefull plugin :)

I have a weird behaviour under iOS ( 7.1.2 and 8.1 ).
With the map in fullscreen and an input field on the bottom of the screen.
The keyboard push the map and create a gap between the map and the keyboard ( in green with setDebuggable )

I have tried a lots of things ( empty CSS, differents CSS management, config.xml special keyboard/ViewPort preferences .. ) 

Of course, if I put the field on the top of the screen, there is no problem ( and I need it on the bottom ... and this works great under Android 4.4.4 )

The simplest CSS version : 
```
#map-canvas {
width: 100%;
height: 100%;
left: 0;
top: 0;
}

#map-canvas form {
position: absolute
width: 100%;
left: 0;
bottom: 0;
}
```
See below pictures, the exact same view with / without keyboard.

Thanks for your help !

![img_0016_1](https://cloud.githubusercontent.com/assets/731955/6672532/7d3faf10-cc0d-11e4-9dbc-be004e3ade21.PNG)
![img_0017_1](https://cloud.githubusercontent.com/assets/731955/6672533/7d4361c8-cc0d-11e4-9e5a-be6da1bb9568.PNG)

**Comment by wf9a5m75** [comment]
Could you give me a simple example html?
(From <html> to </html>)

**Comment by chrisharney** [comment]
try to add bottom 0px  to your #map-canvas css

**Comment by lakano** [comment]
Here, a simple example under a new cordova project created from scratch : 

```html
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
        <title>Hello World</title>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript">
var map;
document.addEventListener("deviceready", 
function() {
    var div = document.getElementById("map_canvas");
    map = plugin.google.maps.Map.getMap(div);
    map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
}, false);

function onMapReady() {
    console.log('map ready');
    map.setDebuggable(true);
}
        </script>
    </head>
    <body>
        <div id="map_canvas" 
            style="position:absolute;top:0;left:0;height:100%;width:100%">
            <form style="position:absolute;bottom:0;left:0;width:100%">
                <input style="width:100%" />
            </form>
        </div>
    </body>
</html>
```

As you could see, the map is pushed on the top and disappear.

The config.xml is the default version created by cordova.

Thanks for your help ! :)  

![img_0018](https://cloud.githubusercontent.com/assets/731955/6676406/d8e3cf62-cc27-11e4-9b6a-53ed21171664.PNG)
![img_0019](https://cloud.githubusercontent.com/assets/731955/6676407/d8e58668-cc27-11e4-883a-6c6c8667e947.PNG)

**Comment by lakano** [comment]
@chrisharney : This doesn't help... I have tried a lots of things in CSS side, this doesn't seems to have any effect.

**Comment by wf9a5m75** [comment]
Thank you for giving the example. I inspected the example code, and it seems a bug in native side.

**Comment by lakano** [comment]
Ok, for information, some preference option in config.xml to inspect : 
````
  <preference name="EnableViewportScale" value="true"/>
  <preference name="KeyboardDisplayRequiresUserAction" value="true"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
````
And some others requested to change the viewport to : 
```html
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, maximum-scale=1, user-scalable=no, height=device-height, width=device-width">
```
Notice the "height" and "maximum-scale", for some uses this have solved some Keyboard gap bugs, but not for me.

Thanks a lots for all the time spent on this plugin, and also for all the support, your reactivity is really perfect, it's really appreciate ! :)

Tell me if I can help in something.

**Comment by wf9a5m75** [comment]
Thank you for your additional information, and sorry for your inconvenience.
I reproduced the issue. And I will fix it in couple of days asap.
Please just a moment.

**Comment by wf9a5m75** [comment]
The bug is fixed.

Comment out the below two lines in the www/googlemaps-cdv-plugin.js file:
```js
  divRect.width = divRect.width < pageRect.width ? divRect.width : pageRect.width;
  divRect.height = divRect.height < pageRect.height ? divRect.height : pageRect.height;
```

Or use the test branch.

![issue_440](https://cloud.githubusercontent.com/assets/167831/6725767/6c57a21a-cdcb-11e4-8beb-9ab48d67e7a5.gif)

**Comment by lakano** [comment]
You're really quick !! 
THANKS A LOTS :+1: 

For users of 1.2.4 it's named "divSize" ( renamed in divRect in test branch )
```javascript
  divSize.width = divSize.width < pageWidth ? divSize.width : pageWidth;
  divSize.height = divSize.height < pageHeight ? divSize.height : pageHeight;
```
