### ISSUE TITLE
plugin fails for appgyver iOS

### ISSUE THREAD

**Issue by klightning7** [wf9a5m75/phonegap-googlemaps-plugin#443]
Hi Masashi, 

I like you google maps plugin. I am trying to use the plugin on iOS but I keep getting this message.

"One of your plugins does not seem to compile for 64bit architecture. You will need to contact the plugin author. (error was: 'ld: symbol(s) not found for architecture arm64)' " 

Can you please help me figure out what's going on.
The other plugins  (i.e googlemaps sdk-ios and http request) work

Thanks
Michael

**Comment by wf9a5m75** [comment]
Is there any other log?

And there are some people who use AppGyver.  Try to contact to them.
(I think @bFlood is the most knowledge person of AppGyver and this plugin)

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?q=appgyver&type=Issues&utf8=%E2%9C%93

**Comment by klightning7** [comment]
Thanks for your quick reply. No that's the only message it gives. I also tried bFlood's plugin and it gave me the same error. None of the appgyver links seems to have a solution. When I build the app with the other neccesary plugins it builds but when I use the google map plugin it gives me the 64bit error.

**Comment by wf9a5m75** [comment]
So what's the error. Could you show me the whole error log?

**Comment by klightning7** [comment]
This is the full error log 

"
Error One of your plugins does not seem to compile for 64bit architecture. You will need to contact the plugin author. (error was: 'ld: symbol(s) not found for architecture arm64)'    "

It doesn't say anything else.

**Comment by klightning7** [comment]
Hi,

I solved the problem by using a branch of bflood's googlemaps plugin.

https://github.com/bFlood/phonegap-googlemaps-plugin/tree/appgyver_bf

The master branch also gave me the 64 bit error but this branch worked. I had to download the branch and create a new repository since github or iOS did not allow me to use the direct link to the above branch.

The plugin works on iOS. But the app crashes when I zoom in close to render buildings. But I will try to figure why it does this. 

Thanks again for your help and for creating this plugin.

**Comment by bFlood** [comment]
you can use this from appgyver config:

  {"source":"https://github.com/wf9a5m75/googlemaps-ios-sdk-for-phonegap"},
  {"source":"https://github.com/bFlood/phonegap-googlemaps-plugin#appgyver_bf","variables":{"API_KEY_FOR_IOS":"your_key_value_here"}},
  {"source":"https://github.com/wf9a5m75/phonegap-http-request#app_gyver"},

**Comment by klightning7** [comment]
Thanks @bFlood I used the above plugin and the app works. 

I have a new problem with Android. I get a white screen on all html elements but the

**Comment by bFlood** [comment]
the plugin above definitely works on android, I have a couple testing devices in front of me now. if you are seeing a white/light gray screen that shows the zoom in/zoom out buttons where the map should be, then it is almost certainly your android api key. It took me several attempts and many days to get the correct android key to work, you can look through this forum for pointers, I know masashi has posted them somewhere.

**Comment by klightning7** [comment]
@bFlood I think it has something to do with the plugin because 
when I create a new version of the default supersonic app and build, the default app works well. Then when I add the plugin all divs become blank white when I install the plugin(the only new thing I've done is add a plugin and made no changes to default supersonic app). 

I saw a sample app you put on dropbox where you solved this problem. Any idea on what might be casing this?

**Comment by bFlood** [comment]
ok, I'm not using supersonic, just steroids.js directly (I started on appgyver before they announced supersonic). this may be the issue, I've not looked into how supersonic hosts the native nav bar and the webviews. also, this plugin only works with the Web Platform build, it is not compatible with the Crosswalk one (the one that appgyver recommends)

**Comment by klightning7** [comment]
Thanks for your quick reply. When I build the app with the web platform build and try to start it, it stayed on splash screen for more than 30minutes. I just had to stop it. Any ideas why? What version of the build tools did you use?

**Comment by bFlood** [comment]
for android, I just built 2 days ago using 4.0.5-edge10 (Web Platform). it works on a MotoG (4.4), a Samsung Galaxy4 (4.3), a Galaxy Tab(4.4) and newer Samsung with lollipop(5.0)

there are definitely small issues but the map works as expected in all of them

**Comment by klightning7** [comment]
Thanks. Then it might be my phone that has an issue because it is an Android 4.2.2. I will try it later today once on a phone with a higher OS. I will also try other builds to see if any works for an android 4.2.2.
Also my app crashes frequently on iOS when I am zooming. Are you also experiencing this issue?

**Comment by bFlood** [comment]
4.2.2 - have not tested that but thanks, good to know

ios - no, there are random crashes but I think these are appgyver issues. none seem to related to the map panning/zooming. are you on ios7 or ios8?

**Comment by klightning7** [comment]
i use ios7.1

**Comment by bFlood** [comment]
7.1 was always more stable for me, sorry. I didn't really see any issues with the plugin, definitely none with panning/zooming. are you listening to any events (map_idle etc) and then possibly running some bad code?

**Comment by klightning7** [comment]
I am running the example code from the tutorials.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-Windows.

My guess is that app uses a global event listener that fires when the device is ready but the other pages use angularjs(views, scripts format). 

It could also be a supersonic problem. I will run a couple of tests later today to try to find out what is causing the crashes.

**Comment by klightning7** [comment]
@bFlood  I turned my iOS off and turned it back on and crashing stopped. Some other appgyver sample apps that used to crash now work well. 
Thanks again for your help modifications to the plugin.
Please let me know if you find a solution to the blank white screen.

**Comment by wf9a5m75** [comment]
Thank you for your support, @bFlood
