### ISSUE TITLE
Orientation Change issue on Android 5

### ISSUE THREAD

**Issue by roberthovhannisyan** [wf9a5m75/phonegap-googlemaps-plugin#447]
Hi, 

The plugin is great, thanks!
Howerver we have issue when changing phone orientation and it seems like the problem occurs only on Android 5. When changing orientation from e.g. portrait to landscape, the rightmost area becomes non-touchable. It seems like the problem is with areas falling outside the size of previous orientation. 

When we remove maps plugin everything works ok

**Comment by wf9a5m75** [comment]
Call `map.refreshLayout()` after the orientation change.

**Comment by roberthovhannisyan** [comment]
Hi again,
it didn't helped.
As I understand map.refreshLayout() internally calls onMapResize (although passes strange data), which is automatically called on orientation change.

Were you able to reproduce the issue ?

**Comment by wf9a5m75** [comment]
What version do you use?
I merged the latest code into the master branch.
Try to install the plugin from master branch.

**Comment by wf9a5m75** [comment]
I develop on Nexus 5 always, and I don't face this issue.
If the error  occurs this issue with the master branch, there might be the error in your HTML or CSS.

**Comment by roberthovhannisyan** [comment]
I am using it through plugins.cordova.io, so I suppose it uses master branch.
Further, I am using Phonegap Build v3.7.0. Will try to look more on html, although when I remove plugin row from config.xml orientation change works as expected.

**Comment by wf9a5m75** [comment]
I haven't uploaded the latest code to plugins.cordova.io yet.

**Comment by roberthovhannisyan** [comment]
I am looking forward to testing it. 
Thanks again

**Comment by Hirbod** [comment]
Try with

```
cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#master --variable API_KEY_FOR_ANDROID.....
```

faced some issues today.. as I also forgot to download the lastest version

**Comment by roberthovhannisyan** [comment]
Hi again, 

I've built my app with new version 1.2.5 from plugins.cordova.io. But the problem is still there.
It seems like there is invisible layer in front of all views, which does not resized when orientation is  changed and prevents taps outside of area of initial orientation. By the way I'm using Sencha Touch.

Do you have any ideas or suggestions on what to check ?

**Comment by wf9a5m75** [comment]
Have you turned on the map.setDebuggable(true)?

**Comment by wf9a5m75** [comment]
I think there is some HTML elements on the map div. Check it with Google Chrome inspector(for Android) or Safari (for iOS)

**Comment by roberthovhannisyan** [comment]
Hi again,
The problem I describe occurs not only when th view with the map is displayed. When I open app it is ok, when I rotate it there is non tappable area at the right side. I thin there some problem in plugin initialization, because when  I remove plugin lines from config.xml everything works as expected.

I have turned on setDebuggable and the screenshot is attached. But I want to make sure again that the problem occurs before this view is even displayed, just after opening app.
![screenshot_2015-03-28-02-26-01](https://cloud.githubusercontent.com/assets/2118842/6878234/7421ee8e-d4eb-11e4-8f40-f29740a7daa0.png)
Another point worth mentioning is that I have checked for invisible divs with phonegap build weinre inspector tool, and did not find any invisible div at that area.

**Comment by wf9a5m75** [comment]
Could you send me your apk to wf9a5m75@gmail.com?

**Comment by roberthovhannisyan** [comment]
I have sent it

**Comment by wf9a5m75** [comment]
Um, at least, the plugin should draw the above region of the map as green.

**Comment by wf9a5m75** [comment]
It seems you use old version. Try to use veraion 1.2.5

**Comment by roberthovhannisyan** [comment]
I am using phonegap build, and did not mention any specific version in config.xml. according to pgb documentation it should use the latest version.
How can I ensure I am using the latest one?

**Comment by roberthovhannisyan** [comment]
Hi Masashi,

Did you received the phonegap project with sample app and were you able to reproduce the issue? 
Do you have any ideas on causes of the issue?

Thanks in advance

**Comment by Hirbod** [comment]
Please remove the plugin and try to install from testbranch

Try with

```
cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#master --variable API_KEY_FOR_ANDROID.....
```

**Comment by roberthovhannisyan** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin#master

Will this install plugin from test branch ?

**Comment by Hirbod** [comment]
sorry, I've updated my post. It's #test 

Cause it has some improvements and considered stable.

**Comment by roberthovhannisyan** [comment]
Thanks @Hirbod,

However, now I've got build error

    [javac] c:\SenchaTestPhonegap\platforms\android\src\plugin\google\maps\PluginMap.java:231: error: cannot find symbol

    [javac]         webView.setZOrderOnTop(true);
    [javac]                ^
    [javac]   symbol:   method setZOrderOnTop(boolean)
    [javac]   location: variable webView of type CordovaWebView

**Comment by Hirbod** [comment]
Seems like I've missed something here. Actually setZOrderOnTop should only be called when building on crosswalk. @wf9a5m75 need to fix this. Sorry, as of two days ago, #test was totally stable.

**Comment by roberthovhannisyan** [comment]
Anyways, I've commented the specified line and it has successfully built.
But still the main problem (orientation change issue) persist

**Comment by roberthovhannisyan** [comment]
Hi @Hirbod, @wf9a5m75 
I was able to workaround the issue by setting android:hardwareAccelerated="false" on application in android manifest file.

This could be helpful for others using sencha touch

**Comment by ra-krishna** [comment]
hardware accelaration would be required for performance reasons, any other possible solution?

**Comment by masashiGMS** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)
