### ISSUE TITLE
/PlanVale/src/plugin/google/maps/GoogleMaps.java:794: error: cannot find symbol

### ISSUE THREAD

**Issue by AdrianoMoura** [wf9a5m75/phonegap-googlemaps-plugin#449]
Hi @wf9a5m75,

I getting the follow error when I try to build the Android version of my app with the last plugin version

This is the log return:

```
-compile:
    [javac] Compiling 69 source files to .../PlanVale/bin/classes
    [javac] .../PlanVale/src/plugin/google/maps/GoogleMaps.java:794: error: cannot find symbol
    [javac]     this.webView.showCustomView(dummyLayout, new WebChromeClient.CustomViewCallback() {
    [javac]                 ^
    [javac]   symbol:   method showCustomView(FrameLayout,<anonymous CustomViewCallback>)
    [javac]   location: variable webView of type CordovaWebView
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
```

**Comment by wf9a5m75** [comment]
Do you use general Cordova?

**Comment by AdrianoMoura** [comment]
Yes, but with build in Intel XDK cloud

**Comment by wf9a5m75** [comment]
I've never used it ....

It seems Intel XDK uses CrossWalk Cordova instead of Apache Cordova.

**Comment by wf9a5m75** [comment]
Yes, I'm correct.
They uses Crosswalk project.
https://software.intel.com/en-us/xdk/docs/crosswalk-application-runtime-overview

However Crosswalk has a bug, so this plugin does not work with Crosswalk currently.

Merge to #302.
And check here https://crosswalk-project.org/jira/plugins/servlet/mobile#issue/XWALK-3742

**Comment by AdrianoMoura** [comment]
But when I try to build traditional Android app the build fail too. I don't have any idea to solve this. :/

**Comment by AdrianoMoura** [comment]
Had something that I can do, maybe fork your plugin and change something?

**Comment by wf9a5m75** [comment]
Crosswalk does not support the showCustomeView() method. Just comment out it

**Comment by AdrianoMoura** [comment]
I will try, thanks a lot
