### ISSUE TITLE
To many NSLog outputs

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#451]
Will you leave them all there? I have like 2000 console fires with remote markers, language and coutryCodes. Shall I comment them out?

**Comment by wf9a5m75** [comment]
Um, instead of just comment out, let's implement a flag with `map.setDebuggable()`.
The reason why is many people reports many issues, however they don't tell us how the program run.

**Comment by Hirbod** [comment]
Yes, thats a good idea. There is alreay a setDebuggable, lets bind to this.

**Comment by wf9a5m75** [comment]
Done 
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/d63f18ea637d1cbafd6804ee8341c0857f0413a5

**Comment by Hirbod** [comment]
:+1:
