### ISSUE TITLE
We still facing deprecation warnings

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#452]
Seems like the if/else 

```C
        if ([PluginUtil isIOS7_OR_OVER]) {
          decodedData = [[NSData alloc] initWithBase64EncodedString:tmp[1] options:0];
        } else {
          decodedData = [NSData dataFromBase64String:tmp[1]];
        }
```

still throws a deprecation error. I guess there need to be something more runtime-stable or we will have compiling errors later

**Comment by wf9a5m75** [comment]
Done https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/db0783aae0a1dff69c3d5665a8c820f492b14ce4#diff-0f995cdc9daa8ae3dfc78c6a10b75e0dR385

**Comment by Hirbod** [comment]
:+1:
