### ISSUE TITLE
3rd Party Offline Tiles

### ISSUE THREAD

**Issue by canadaka** [wf9a5m75/phonegap-googlemaps-plugin#454]
It would be great if this would support tile sources offline from a local source, like an sqlite DB of tiles. Not talking about Caching Google tiles, but our own tiles in the standard z/y/z tile format.

A final step would be supporting vector tiles, like Mapbox Vector Tile Format, PBF.

Have you given this any thought, or investigated it?

**Comment by wf9a5m75** [comment]
I appreciate if you send me a pull request even whether Android or iOS.
That saves my times, and gives me to development for marker-cluster.

**Comment by canadaka** [comment]
I found a Google Maps SDK add-on for loading offline tiles in MBTiles format, which is even better than sqlite. If this could be used, that would be amazing.
https://github.com/cocoahero/android-gmaps-addons/blob/master/src/com/cocoahero/android/gmaps/addons/mapbox/MapBoxOfflineTileProvider.java

**Comment by wf9a5m75** [comment]
I'm not interested in.
