### ISSUE TITLE
3rd Party TileProvider

### ISSUE THREAD

**Issue by canadaka** [wf9a5m75/phonegap-googlemaps-plugin#455]
Unless I'm missing something you don't seem to be able to add a 3rd party tile server as your basemap layer. You can add it as an overlay, but the Google tiles seem to still load underneath. So i can't totally replace the google tiles with tiles from OSM, BING, ARC, or a custom source.

````
map.addTileOverlay({
        tileUrlFormat: "http://tile.openstreetmap.org/<zoom>/<x>/<y>.png"
    }, function() {
        console.log('LOAD');
    });
````

I tried setting this, but the Google tiles still load underneath:
map.setMapTypeId(plugin.google.maps.MapTypeId.MAP_TYPE_NONE);

**Comment by canadaka** [comment]
Sorry I was hasty in posting this, i got it working, MAP_TYPE_NONE should just be NONE.
Google still shows their watermark when using 3rd party tiles though.

**Comment by Hirbod** [comment]
This can be changed. You're also not allowed to hide the watermark. It has to be visible.

**Comment by canadaka** [comment]
Any idea why tiles from tileOverlay are all blurry? Whether its our own tiles or OSM tiles in the example above.

It seems the Java code does pass along the size of the tiles, but there doesn't seem to be a way to specify this size with the JS function above?
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/c65460e7aa32fde53ee88763464f7388ce8aef2a/src/android/plugin/google/maps/PluginTileOverlay.java#L32
Is setting a TileProvider width & height available as an option?

I'm guessing the default might be 512x512, but most 3rd party tiles are 256x256?

**Comment by wf9a5m75** [comment]
Are you talking about iOS, or Android?

**Comment by wf9a5m75** [comment]
Can you show me the screen capture?

**Comment by wf9a5m75** [comment]
Google does not say which size are default tile size.
https://developer.android.com/reference/com/google/android/gms/maps/model/TileOverlay.html
https://developers.google.com/maps/documentation/ios/reference/interface_g_m_s_tile_layer

Google Maps JavaScript API v3 uses 256x256 tile size, I guess that's why most 3rd party tiles are 256x256.

**Comment by canadaka** [comment]
Here is a screenshot http://imgur.com/77bQEDZ

It is less blurry at certain zoom levels. I guess native google SDK doesn't really have zoom levels? Since vector tiles can really be viewed at any level. So I guess it scales the image tiles until it hits a threshold.

But other native google map apps don't seem to be blurry, but that might be because they are using much larger tile sizes, so they can be scaled in more?

**Comment by wf9a5m75** [comment]
This demo apk display the map tile clearly.

The code is this:
```
map.addTileOverlay({
  tileUrlFormat: "http://tile.stamen.com/watercolor/<zoom>/<x>/<y>.jpg"
});
```

**Comment by wf9a5m75** [comment]
Could you share your code?

**Comment by canadaka** [comment]
I tried with that watercolor tile as well, it is also blurry, its just much harder to tell because its kinda a fuzzy image to begin with.

````
map.setMapTypeId(plugin.google.maps.MapTypeId.NONE);

map.moveCamera({
	target: new plugin.google.maps.LatLng(49.701, -123.158),
	zoom: 13
}, function() {

});

map.addTileOverlay({
	tileUrlFormat: "http://a.tile.openstreetmap.org/<zoom>/<x>/<y>.png"
}, function() {
});
````

**Comment by wf9a5m75** [comment]
Here is what happen on my Nexus 5 with the above code.
![device-2015-03-25-174517](https://cloud.githubusercontent.com/assets/167831/6838449/bf8e5d16-d316-11e4-9996-aa1bd4db5a60.png)

**Comment by canadaka** [comment]
Yah those tiles are pretty blurry, I think its just a limitation of using image tiles in these native map frameworks that don't really have set zoom levels.

Your always zooming into the image until it reaches a threshold to load the next z/x/y tile.

I will generate some high resolution tiles at 512x512 and see if that improves it.

**Comment by wf9a5m75** [comment]
Let me know the result of 512x512

**Comment by canadaka** [comment]
Yup 512x512 tiles look way better!
http://imgur.com/PdHAQ9S

**Comment by wf9a5m75** [comment]
Add `tileSize` property for addTileOverlay().

**Comment by canadaka** [comment]
how can a Tile Overlay be removed?

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L1682

**Comment by canadaka** [comment]
I must be missing something, the overlay is not being removed.

````
var overlay;

map.addTileOverlay({
  tileUrlFormat: 'http://URL/<zoom>/<x>/<y>.png',
  zIndex: 5,
  width: 512,
  height: 512
}, function(TileLayer) {
  overlay = TileLayer;
});

overlay.remove();
````
when I call the overlay.remove(); the overlay is not removed, no JS errors though.

**Comment by wf9a5m75** [comment]
```js
var overlay;

map.addTileOverlay({
  tileUrlFormat: 'http://URL/<zoom>/<x>/<y>.png',
  zIndex: 5,
  width: 512,
  height: 512
}, function(TileLayer) {
  overlay = TileLayer;
overlay.remove();
});

```

**Comment by canadaka** [comment]
I need to remove the overlay outside the callback function at a later time. When a user untoggles a checkbox.

**Comment by wf9a5m75** [comment]
```js

console.log("----one");

map.addTileOverlay({
  tileUrlFormat: 'http://URL/<zoom>/<x>/<y>.png',
  zIndex: 5,
  width: 512,
  height: 512
}, function(TileLayer) {
   console.log("----Three");
});

console.log("----Two");
```

**Comment by canadaka** [comment]
the .remove() fucntion isn't called right after creating the overlay like in my code example above. It gets fired later if a user goes to a settings page and disables the overlay.

I can console.log(overlay); right before calling the overlay.remove(); and it returns the TileOverlay object fine.

It works fine for markers & polylines. I can remove them outside the callback function, example:
````
var polyline = polylines[index];
if (polyline) {
  polyline.remove();
}
````

**Comment by Hirbod** [comment]
Just use the callback and assign it to a global var

**Comment by canadaka** [comment]
That's what I did, that is why  "var overlay;"  is called outside & before the callback.

**Comment by wf9a5m75** [comment]
I guess you use old version.

**Comment by canadaka** [comment]
nope, we last merged 3 days ago
