### ISSUE TITLE
Marker Labels

### ISSUE THREAD

**Issue by canadaka** [wf9a5m75/phonegap-googlemaps-plugin#457]
I think you might use this library already for the polyline encoding and maybe were going to use it for clustering?
http://googlemaps.github.io/android-maps-utils/

Would be good to also add the marker display text or labels feature.
![screenshot](http://googlemaps.github.io/android-maps-utils/bubblemarker.png)

**Comment by wf9a5m75** [comment]
You can create it with base64 encoded strings.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Marker#base64-encoded-icon

**Comment by wf9a5m75** [comment]
You need to draw using HTML5/Canvas, then export the data.

**Comment by canadaka** [comment]
awesome, missed that section of the wiki!
