### ISSUE TITLE
grey div

### ISSUE THREAD

**Issue by freelancer12** [wf9a5m75/phonegap-googlemaps-plugin#458]
Hello everybody,
this is my first use of googlemaps plugin, i can't understand why when i run examples i just have a grey div, and the map is not loaded, i'v tried the examples provided with plugin in 
![map](https://cloud.githubusercontent.com/assets/11075429/6847083/a9b79f02-d3bb-11e4-9b9f-03f586e47cfa.jpg)

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/TroubleShooting:-Blank-Map

**Comment by freelancer12** [comment]
thank you very much
