### ISSUE TITLE
plugin.google.maps.event.MAP_CLOSE does not fire

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#461]
Also tried with closeDialog(); The callback does not fire on iOS (did not test Android)

**Comment by wf9a5m75** [comment]
Have you check the native code?

**Comment by Hirbod** [comment]
No, just tried in JS and never received my test "alert"

**Comment by wf9a5m75** [comment]
This issue has been fixed in the test branch. Check it out.

**Comment by Hirbod** [comment]
:+1:
