### ISSUE TITLE
Can't build Android: LocationSettingsRequest cannot be resolved to a type

### ISSUE THREAD

**Issue by nullday000** [wf9a5m75/phonegap-googlemaps-plugin#462]
Hello there!

Installed the last version of plugin and can't build it on Andrid because of:
LocationSettingsRequest cannot be resolved to a type	GoogleMaps.java
and many others.

![image](https://cloud.githubusercontent.com/assets/11681641/6870152/5b858aa0-d457-11e4-81af-b3f4a57bc5e6.png)

Tried to remove/add platform, remove/add plugin, build from command line (cordova build, the same errors). Don't know how to fix it :(

Please, give some advice.

**Comment by Hirbod** [comment]
See #456 

You need to remove the plugin, remove google play services and reinstall version 23.

**Comment by wf9a5m75** [comment]
@nullday000 
As @Hirbod said, you need to remove old plugins at once.

```
$> cordova plugin rm plugin.google.maps
$> cordova plugin rm com.google.playservices  // <-- very important
$> cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID=...
```

**Comment by nullday000** [comment]
Thanks, it helped.
