### ISSUE TITLE
IOS Deprecations

### ISSUE THREAD

**Issue by jpmetcalf** [wf9a5m75/phonegap-googlemaps-plugin#463]
GoogleMaps.m
1. 'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

GoogleMapsViewController.m
1. 'sizeWithFont:constrainedToSize:' is deprecated: first deprecated in iOS 7.0 (Use -boundingRectWithSize:options:attributes:context:)
2. 'drawInRect:withFont:lineBreakMode:alignment:' is deprecated: first deprecated in iOS 7.0 (Use -drawInRect:withAttributes:)

Map.m
1. 'base64Encoding' is deprecated: first deprecated in iOS 7.0

**Comment by wf9a5m75** [comment]
This plugin need to support even iOS6, because Google Maps SDK for iOS works on iOS6.
I appreciate if you send a pull request with great patch.

**Comment by wf9a5m75** [comment]
And at least `base64Encoding` is not used anymore.
You might see the old code.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?utf8=%E2%9C%93&q=base64Encoding

**Comment by wf9a5m75** [comment]
Done
