### ISSUE TITLE
Call to location.reload() removes custom marker icons.

### ISSUE THREAD

**Issue by tycjones** [wf9a5m75/phonegap-googlemaps-plugin#464]
I'm trying to use custom marker icons.  The first time I load the map, the correct (custom) icons show.  Without getting into the full architecture of my app, I need to call location.reload() when the user chooses a new event.  After a location.reload, I load the view with the google map and all the icons are in the proper place and their info windows are correct.

But the custom icon images are not used.  Instead the default images are there.  I've tried many things including: map.remove(), iterate through all markers and manually remove/re-add them.  Nothing seems to work.  It appears that the plugin does not like calls to location.reload()?
![img_1418](https://cloud.githubusercontent.com/assets/5827356/6877550/27436536-d48f-11e4-9b5c-6cc250fe3ee9.PNG)
![img_1419](https://cloud.githubusercontent.com/assets/5827356/6878826/2dcaacbc-d4a2-11e4-812d-93a6c8fe2af8.PNG)

**Comment by wf9a5m75** [comment]
Any error in logcat, or xcode?

**Comment by tycjones** [comment]
There were no errors in the web view console or in the Xcode console.

**Comment by wf9a5m75** [comment]
I couldn't reproduce your issue.
```html
<script type="text/javascript">
document.addEventListener("deviceready", function() {
  alert("deviceready");
    
  var mapDiv = document.getElementById("map_canvas");
  var map = plugin.google.map.Map.getMap(mapDiv);
  
  map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

    
    map.addMarker({
      position: new plugin.google.maps.LatLng(0, 0),
      icon: "http://www.google.com/intl/en_us/mapfiles/ms/icons/blue-dot.png"
    });
    
    var button = document.getElementById("execBtn");
    button.addEventListener("click", function() {
      location.reload();
    });
  
  });
});
</script>

<button id="execBtn">location.reload()</button>
```
![issue_464](https://cloud.githubusercontent.com/assets/167831/6883653/baee7c72-d574-11e4-8d8d-e5a9d1c6cbb6.gif)

**Comment by tycjones** [comment]
Upon further investigation I was able to isolate the issue to the icon png.  In your example, you used an icon hosted by google: http://www.google.com/intl/en_us/mapfiles/ms/icons/blue-dot.png

When I used the same path (remote file), I had no issue.  But when I saved the file locally (it's the same file, just bundled in my www directory of the app), I had the issue.  Here's a demo:

https://youtu.be/y7VLYWIy-fk

**Comment by wf9a5m75** [comment]
I'm very busy. Please find the bug code.
All source code is open.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/Marker.m

**Comment by tycjones** [comment]
On line 600, your regular expression finds the webview url and removes everything after the last '/'.  But I'm using the ionic framework and utilizing a router that passes information via the url with hashtags and semicolons (hashtags indicate the state route and semicolons are state parameters) .  Such as: 
/private/var/mobile/Containers/Bundle/Application/49943D20-D5D3-4A67-99A1-B415BE46F979/leaderboard.app/www/index.html#/tab/:somevariablevalue/:someothervalue

What needs to happen is for my path: img/gm_icons/blue-dot.png  to be appended after the www/ in the path.  But the regex only removes :/someothervalue.
So the image path becomes:

/private/var/mobile/Containers/Bundle/Application/49943D20-D5D3-4A67-99A1-B415BE46F979/leaderboard.app/www/index.html#/tab/:somevariablevalue/img/gm_icons/blue-dot.png

Then on line 677, there is a check to make sure the file exists at that path (which of course it doesn't).  So the default marker icon is used instead.

I found that I could work around the issue by constructing the absolute path myself and passing that to the plugin.  This works for me.  But anyone using ionic (that also needs to do location.reload(), will experience this problem.

Thanks for addressing this so quickly.
Domo Arigato!

**Comment by tycjones** [comment]
Here's the code I had to use to get that root path:

                var path = window.location.pathname;
                var index = path.search("/www/");
                path = path.substring(0, index + 5);
                $scope.icons = {
                    "medical": path + "img/gm_icons/medical.png",
                    "photo": path + "img/gm_icons/photo.png",
                    "stopwatch": path + "img/gm_icons/stopwatch.png",
                    "water": path + "img/gm_icons/water.png"
                };

**Comment by wf9a5m75** [comment]
Thank you for your great investing.
That saves my time.

Ok, I didn't suppose the ionic uses such as odd path. That might be error.
But why don't you pass the relative path?

Until v1.2.4, you just pass the relative path include `www`.
```
$scope.icons = {
  "medical": "www/img/gm_icons/medical.png",
  "photo":  "www/img/gm_icons/photo.png",
  "stopwatch":  "www/img/gm_icons/stopwatch.png",
  "water":  "www/img/gm_icons/water.png"
};
```

From v1.2.5, the plugin recognizes the correct relative path.
(I haven't tested it with ionic framework though)

The below code should work.
```
$scope.icons = {
  "medical": "img/gm_icons/medical.png",
  "photo":  "img/gm_icons/photo.png",
  "stopwatch":  "img/gm_icons/stopwatch.png",
  "water":  "img/gm_icons/water.png"
};
```

**Comment by tycjones** [comment]
That works for me if I prepend “www/“ to the path.  But this isn’t how I would reference the files in the DOM.  In the DOM “www” wouldn’t be recognized as that’s the root directory for all web assets.  Thanks again!

**Comment by wf9a5m75** [comment]
Prepend `www/` is the rule of this plugin.  Or prepend `./`

**Comment by tycjones** [comment]
No problem. Thanks again for the help!
