### ISSUE TITLE
plugins examples

### ISSUE THREAD

**Issue by freelancer12** [wf9a5m75/phonegap-googlemaps-plugin#465]
Hello everybody,
this is my first use of this plugins, can i have an examples without  the  the function function loadPages(map, pageName) {} provided in the examples.
my architecture is : 

the first page :  index.html contain a description of my project.
the second page map.html  contain a map with a marker.
i don't want to use the function function loadPages(map, pageName) {} that create the pages. i want just to load maps in the maps.html 

thanks

**Comment by wf9a5m75** [comment]
The above links are not linked.

**Comment by freelancer12** [comment]
it s not link, it as the architecture of my project.
the index.html : the first page contains a description of my project.
the map.html : contains a map with a marker.

thanks

**Comment by wf9a5m75** [comment]
Why don't you create by your self without example.

**Comment by freelancer12** [comment]
I tried all day but I have not succeeded :)

**Comment by wf9a5m75** [comment]
There are many other developers who use this plugin at here.

https://plus.google.com/u/0/communities/117427728522929652853
