### ISSUE TITLE
map.fromPointToLatLng

### ISSUE THREAD

**Issue by celron** [wf9a5m75/phonegap-googlemaps-plugin#466]
When I use map.fromPointToLatLng() to place a marker using the given window or display screen size.

If I adjust the X and Y with the window.devicePixelRatio then the marker is placed (relatively) correctly on the screen.  When I use fromLatLngToPoint it appears to use the window.screen.height and window.screen.width, as I would expect.

The documentation for these functions is a little sparse and I was wondering if I what I was observing is correct.  I am using 1.2.4

**Comment by wf9a5m75** [comment]
First of all, please update to v1.2.5.
Many bugs of v1.2.4 were fixed in v1.2.5

**Comment by celron** [comment]
This is still an issue in v1.2.5

**Comment by wf9a5m75** [comment]
map.fromLatLngToPoint() converts the position based on the left-top position of the map div.
Not window or screen size.

**Comment by wf9a5m75** [comment]
And your description is little unclear for me. Please take some screen captures or screen record.

**Comment by celron** [comment]
I am using a galaxy note 3.  The screen resolution 1080x1920 , while in cordova it is reported to be 360x615 so there is a dpi of 3.

![image](https://cloud.githubusercontent.com/assets/7539817/6882977/d2590102-d56f-11e4-8b8b-2cc8330980f8.png)

A is an image that the user will press and I wish to place a marker around there.  It is approximately 310,100
Using to following code

```javascript
                                    //lets try to put the yellow marker underneath the users finger
                                    var xpos=event.pageX*1;
                                    var ypos=(event.pageY+64)*1;
                                    console.log('mousedown xpos' + xpos + ' ypos:' + ypos);
                                    map.fromPointToLatLng([xpos, ypos], function (point) {
                                        console.log('mousedown lat' + point[0] + ' lng:' + point[1]);
                                        midlocation = new google.maps.LatLng(point[0], point[1]);
                                        midCircle.drawSearchCircle(midlocation, false, true);
                                        console.log(startingLocation1.position);
                                        map.fromLatLngToPoint(startingLocation1.position, function (point) {
                                            console.log('position of marker 1 1 x:' + point[0] + ' y:' + point[1]);
                                        });
                                    });
                                }
```
<b>With this output</b>
mousedown xpos290 ypos:141 index.html:400
mousedown index.html:411
290,77 index.html:412
mousedown lat40.78262953536867 lng:-73.91297399997711 index.html:402
search circle routein(40.78262953536867, -73.91297399997711) search flag:false draggable: true index.html:960
removing venue markers index.html:1824
adding circle marker index.html:989
LatLng {lat: 40.7741637, lng: -73.909398, equals: function, toString: function, toUrlValue: function}
index.html:405
position of marker 1 1 x:180 y:307.6666564941406 index.html:407
adding listener to the yellow marker 

![image](https://cloud.githubusercontent.com/assets/7539817/6882984/2d5a73ec-d570-11e4-875f-c5f22c047d27.png)
Note that marker 1 is in the center of the screen and the reported position from <i>fromLatLngToPoint()</i> is (180,307) the LAT and LNG of (40.7741537,-73909398).

The yellow marker has an x,y of (290, 141) which is converted to a LAT, LNG (40.78262953536867, -73.91297399997711) using <i>fromPointToLatLng()</i>, yet it is placed to the left of marker 1.  You would think that it would be placed around and below the image A, but it is not.

If I multiply the x and y by a factor of 3
```javascript
                                    var xpos=event.pageX*3;
                                    var ypos=(event.pageY+64)*3;
                                    console.log('mousedown xpos' + xpos + ' ypos:' + ypos);
                                    map.fromPointToLatLng([xpos, ypos], function (point) {
                                        console.log('mousedown lat' + point[0] + ' lng:' + point[1]);
                                        midlocation = new google.maps.LatLng(point[0], point[1]);
                                        midCircle.drawSearchCircle(midlocation, false, true);
                                        console.log(startingLocation1.position);
                                        map.fromLatLngToPoint(startingLocation1.position, function (point) {
                                            console.log('position of marker 1 1 x:' + point[0] + ' y:' + point[1]);
                                        });
                                    });
```
<b>with an output of</b>
mousedown xpos885 ypos:369 index.html:400
mousedown index.html:411
295,59 index.html:412
mousedown lat40.780246934168744 lng:-73.9042242988944 index.html:402
search circle routein(40.780246934168744, -73.9042242988944) search flag:false draggable: true index.html:960
removing venue markers index.html:1824
adding circle marker index.html:989
LatLng

    equals: function (other) {
    lat: 40.7742505
    lng: -73.9091597
    toString: function () {
    toUrlValue: function (precision) {
    __proto__: Object

index.html:405
position of marker 1 1 x:180 y:307.6666564941406 index.html:407
adding listener to the yellow marker 

![image](https://cloud.githubusercontent.com/assets/7539817/6883000/0a128cb6-d571-11e4-85b7-a66f6200913c.png)
Where the marker is in appropriate vicinity.  You can see that with an x,y of (885,369) converted to LAT, LNG of (40.780246934168744, -73.9042242988944) which would indicate to me that the x,y for <i>fromPointToLatLng()</i> is using screen resolution.

You would think that with a value of 885,369 that it would be off the screen, but it is placed where I would expect it to be.

**Comment by wf9a5m75** [comment]
This plugin did not design for zoomed browser view.

**Comment by celron** [comment]
I'm in a zoomed browser?  How did I do that?

**Comment by wf9a5m75** [comment]
>>I am using a galaxy note 3. The screen resolution 1080x1920 , while in cordova it is reported to be 360x615 so there is a dpi of 3.

**Comment by wf9a5m75** [comment]
Use ` <meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by celron** [comment]
I've replaced that meta tag into my app but it still behaves the same way.

**Comment by wf9a5m75** [comment]
Then you don't need to *3

**Comment by celron** [comment]
While I have placed the meta and see it in the debugger, the screen behaves the same as before.

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/example/DemoApp/www/pages/customInfoWindow.html

**Comment by celron** [comment]
Should I modify this example to do the conversion back to fromPointToLatLng?

**Comment by wf9a5m75** [comment]
yes
