### ISSUE TITLE
plugin.google.maps.external.launchNavigation - problems with %20

### ISSUE THREAD

**Issue by nullday000** [wf9a5m75/phonegap-googlemaps-plugin#467]
Hello there.

I use an example from docs: 
plugin.google.maps.external.launchNavigation({
  "from": "Tokyo, Japan",
  "to": "Kyoto, Japan"
});

And it calls Google Maps or Apple Maps with next strings:
Tokeyo,%20Japan
Kyoto,%20Japan

Nav map says that it's incorrect address.
I tried to comment next lines in External.m:
  from = [from stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
  to = [to stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];

And after that everything works okay, without %20.
What's wrong? Mistake in plugin or I do something wrong?

Thanks.

**Comment by wf9a5m75** [comment]
Please send me a pull request.

**Comment by nullday000** [comment]
What do you mean?
I changed only two line just for test.

**Comment by wf9a5m75** [comment]
Please find the bug, then send me the patch. The all source code is open.

**Comment by wf9a5m75** [comment]
The bug is fixed. Use the master branch.

```
$> cordova plugin rm plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable ...
```
![ios simulator screen shot mar 28 2015 4 01 57 pm](https://cloud.githubusercontent.com/assets/167831/6883287/c70c5210-d563-11e4-8803-1499e166db2e.png)
