### ISSUE TITLE
map.addPolyline()

### ISSUE THREAD

**Issue by celron** [wf9a5m75/phonegap-googlemaps-plugin#468]
when I use <b>color: grey</b>, the routine will crash 
03-28 15:44:53.333: W/System.err(25102): java.lang.reflect.InvocationTargetException
03-28 15:44:53.333: W/System.err(25102): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-28 15:44:53.343: W/System.err(25102): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-28 15:44:53.343: W/System.err(25102): 	at plugin.google.maps.MyPlugin.execute(MyPlugin.java:49)
03-28 15:44:53.343: W/System.err(25102): 	at plugin.google.maps.GoogleMaps$3.run(GoogleMaps.java:263)
03-28 15:44:53.343: W/System.err(25102): 	at android.os.Handler.handleCallback(Handler.java:733)
03-28 15:44:53.343: W/System.err(25102): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-28 15:44:53.343: W/System.err(25102): 	at android.os.Looper.loop(Looper.java:146)
03-28 15:44:53.343: W/System.err(25102): 	at android.app.ActivityThread.main(ActivityThread.java:5752)
03-28 15:44:53.343: W/System.err(25102): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-28 15:44:53.343: W/System.err(25102): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-28 15:44:53.343: W/System.err(25102): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
03-28 15:44:53.353: W/System.err(25102): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
03-28 15:44:53.353: W/System.err(25102): 	at dalvik.system.NativeStart.main(Native Method)
03-28 15:44:53.353: W/System.err(25102): Caused by: org.json.JSONException: Value null at color of type org.json.JSONObject$1 cannot be converted to JSONArray
03-28 15:44:53.353: W/System.err(25102): 	at org.json.JSON.typeMismatch(JSON.java:100)
03-28 15:44:53.353: W/System.err(25102): 	at org.json.JSONObject.getJSONArray(JSONObject.java:553)
03-28 15:44:53.353: W/System.err(25102): 	at plugin.google.maps.PluginPolyline.createPolyline(PluginPolyline.java:42)

It appears that whatever routine you used to get the color changed from 1.2.4, where this worked.  I think this color parser is an android routine.  

I can use <b>gray</b> instead, however I believe that it is better to use a default color if the color parser can't find a color rather than leave it null and crash, or maybe return an error.

**Comment by wf9a5m75** [comment]
I couldn't reproduce your issue.
```js
const HND_AIR_PORT = new plugin.google.maps.LatLng(35.548852,139.784086);
const SFO_AIR_PORT = new plugin.google.maps.LatLng(37.615223,-122.389979);
map.addPolyline({
  points: [
    HND_AIR_PORT,
    SFO_AIR_PORT
  ],
  'color' : 'gray',
  'width': 10,
  'geodesic': true
});
```

![device-2015-03-28-143326](https://cloud.githubusercontent.com/assets/167831/6882995/6e6bc188-d557-11e4-9003-e9777b5ea083.png)

**Comment by celron** [comment]
It works with gray but crashes with grey.  In 1.2.4 grey worked.

**Comment by wf9a5m75** [comment]
In v1.2.5, only defined color names are available.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Available-HTML-colors

**Comment by celron** [comment]
That's fine.  But shouldn't the plugin report an error?  I only noticed the problem because I was looking at the java monitor.

**Comment by wf9a5m75** [comment]
Because of the `HTMLColor2RGBA` function() does not take callback, it is difficult to invite the error callback.

Alternatively, if the plugin can not understand the color value, the overlay is drew by `black`, and the plugin outputs a warning log.
`"Warning: 'hogehoge' is not available. The overlay is drew by black."`

In order to use that, use master branch.
```
$> cordova plugin rm plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable ...
```
