### ISSUE TITLE
Animation locks down marker position

### ISSUE THREAD

**Issue by krazeh** [wf9a5m75/phonegap-googlemaps-plugin#471]
While a marker animation is being played, its position cannot be changed. This would be fine if it weren't for the fact that the animation cannot be stopped either. Some kind of change should be implemented so that you won't have to wait for the animation to finish before moving the marker around.

**Comment by wf9a5m75** [comment]
If you implement that feature and send me a pull request, I will implement that.
All source code is open.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/PluginMarker.java#L267-L350

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/Marker.m#L443-L551
