### ISSUE TITLE
moveCamera - zoom snapped to integer value

### ISSUE THREAD

**Issue by bFlood** [wf9a5m75/phonegap-googlemaps-plugin#473]
if you pass in a fractional zoom value to moveCamera, it seems to snap to the nearest integer zoom level. not sure if this is a plugin or iOS sdl issues

ex: 16.4 becomes 16 after the moveCamera

**Comment by bFlood** [comment]
ok, found the issue. I had an older version of the code, the new one uses a double value instead of an int

**Comment by wf9a5m75** [comment]
Yes.

**Comment by bFlood** [comment]
fwiw, bearing should be a double too, it's still cast to an int
