### ISSUE TITLE
Plugin slows down the app performance on Android in combination with ember-cli

### ISSUE THREAD

**Issue by jaimevent** [wf9a5m75/phonegap-googlemaps-plugin#475]
I have an application based on ember-cli and the addon ember-cli-cordova for compiling the app on Cordova. 
Before I'd installed this plugin the entire app was running really smooth and without any performance problems. Now the entire app, not just the page where the Google Map is shown, became really slow with reactions > 1s.
I found some similar issues like [this](http://stackoverflow.com/questions/28880597/cordova-google-map-plugin-slows-down-the-app-performance-on-android), but no one using ember/ember-cli.
Are there somebody experiencing the same problem or that could help me fixing this issue?

P.s. I installed the example app and it works fine.

**Comment by wf9a5m75** [comment]
I see. I've never heard ember actually.

**Comment by wf9a5m75** [comment]
Could you try to run with comment out this line?
```java
        if (Build.VERSION.SDK_INT >= 11){
//          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }
```
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L197

**Comment by wf9a5m75** [comment]
And add `android:hardwareAccelerated="true"` into the AndroidManifest.xml file under the platforms/android/

```
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name">
```

**Comment by jaimevent** [comment]
I tried with your solutions, but nothing to do. The app is still very slow. I also uninstalled all the other plugins, thinking that there could be maybe some incompatibility between plugins, but nothing changed. 
So there has to be something in your code which slows down ember-cli, but I really don't know where to look or what could be the problem.

**Comment by wf9a5m75** [comment]
Merge #426

**Comment by wf9a5m75** [comment]
Try to use this plugin with Crosswalk project. The problem might be solved.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)

**Comment by Hirbod** [comment]
Open platform/android/src/plugin/google/MyPluginLayout.java and GoogleMaps.java

search for line

```
          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```

and change to 
```
          webView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
```

this boosted my app so heavy I can't describe

**Comment by jaimevent** [comment]
Thanks for the help, but I switched meanwhile to Mapbox.

**Comment by canadaka** [comment]
setting this to LAYER_TYPE_HARDWARE added a huge performance boost for list scrolling outside the map portions of the app. Thnaks!

**Comment by seme1** [comment]
I'm running into a similar problem. Adding the plugin to my app made it run extremely slow on Android. It was running smoothly before the plugin was added. My test device is Galaxy Nexus (Android 4.3). The map works fine, it's just the performance that has degraded ALOT. 

I'm using crosswalk 17. I'm also using the github version of the plugin (added with the following commad:

cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="Replaced_With_My_API_Key"

Any help would be greatly appreciated.
