### ISSUE TITLE
Undefined exception

### ISSUE THREAD

**Issue by barbatus** [wf9a5m75/phonegap-googlemaps-plugin#476]
I am getting undefined exception.
It seems [this check](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/3dc75cdb50eb11ce29bdd1b575a79b55ebb7dc43/www/googlemaps-cdv-plugin.js#L281) needs ```` currentDiv.className ```` instead of  ```` div.className ```` .

**Comment by wf9a5m75** [comment]
Oh, that's miscopy code...
It has to be `currentDiv.className` instead of `div.className`
