### ISSUE TITLE
Issue after upgrade to android 5.1

### ISSUE THREAD

**Issue by alexislg2** [wf9a5m75/phonegap-googlemaps-plugin#477]
Hey I just updated my phone to lollipop 5.1 and now I get this error:
`The browser does not support the getPropertyCSSValue method!`

**Comment by wf9a5m75** [comment]
use v1.2.5  or master branch.

**Comment by alexislg2** [comment]
thanks it works.
But the map.setbackgroundcolor doesn't work anymore now...

**Comment by wf9a5m75** [comment]
Only defined colors are available.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Available-HTML-colors

**Comment by wf9a5m75** [comment]
Or specify using rgb() or #RRGGBB

**Comment by alexislg2** [comment]
I'm doing `map.setBackgroundColor("#1b1f2b");`
Le 3 avr. 2015 6:15 PM, "Masashi Katsumata" <notifications@github.com> a
écrit :

**Comment by wf9a5m75** [comment]
Please find the bug position. Allsource code is open

**Comment by alexislg2** [comment]
OK I had to put it after the mapReady event. That makes sense but it is strange because it was working in the 1.2.4
Thank you

**Comment by wf9a5m75** [comment]
Yes, because the initialization of Google Maps Android API v2 has been changed as asynchronous.
But I provide the  `MAP_READY` event before this changing.
All statements except some static methods are have to wait the `MAP_READY` event. 

By the way, why don't you use just like this?
```js
var map = plugin.google.maps.Map.getMap(mapDiv, {
  'backgroundColor': 'white'
});
 ```
