### ISSUE TITLE
Navbar hiding compass

### ISSUE THREAD

**Issue by klightning7** [wf9a5m75/phonegap-googlemaps-plugin#479]
Hi Masashi,

I am having 2 issues with the plugin on my ipad. 

When I use a normal div with height 100% I get a white space under my navbar header( see second image)
When I use fullscreen(map.showdialog) the navbar header hides the compass(see first image ).

Do you have any ideas on how this issues can be solved?

Thanks.

Here I use fullscreen(map.showdialog). The navbar hides the compass and the Google logo. How do I prevent this from happening or how do i change the location of the compass?

![img_0287 1](https://cloud.githubusercontent.com/assets/11530966/6999090/ac21dd92-dbaf-11e4-845d-e0edf9d9534a.PNG)

Here I place the map in a div. There is a white space between the map and the blue navbar header.
How do I get rid of this whitespace?

![img_0286 1](https://cloud.githubusercontent.com/assets/11530966/6999092/b1ccb14a-dbaf-11e4-81b8-c1b5274f194c.PNG)

**Comment by wf9a5m75** [comment]
What the map plugin version do you use?
I think I already answered to simular issue in the past.
Did you check the issue list?

**Comment by klightning7** [comment]
I use 1.2.4
I searched the issue list but I could not find a similar issue. Can you please provide a link?

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/242


I don't support old version of this plugin.
Please update it.

**Comment by klightning7** [comment]
I tried updating the plugin and building the app with the new plugin but I get an error message. it says

"One of your plugins does not seem to compile for 64bit architecture. You will need to contact the plugin author. (error was: 'Id: symbol(s) not found for architecture arm64)'

**Comment by wf9a5m75** [comment]
Please include error line number and file name.
And I saw this error at once.
Please find the issue list at once becore asking.
