### ISSUE TITLE
Build error after update 1.2.5

### ISSUE THREAD

**Issue by jianbo** [wf9a5m75/phonegap-googlemaps-plugin#480]
Do I need to update google play service to 23 before update 1.2.5. Im getting following errors with 1.2.5. How do I update my google play service? 

Fetching plugin "com.google.playservices@23" via plugin registry
npm http GET http://registry.cordova.io/com.google.playservices
npm http 304 http://registry.cordova.io/com.google.playservices
Error: No compatible version found: com.google.playservices@'>=23.0.0-0 <24.0.0-0'
Valid install targets:
["9.0.0","15.0.0","15.0.1","16.0.0","17.0.0","18.0.0","19.0.0","21.0.0"]

    [javac] /home/jianbo/Desktop/0/platforms/android/src/plugin/google/maps/GoogleMaps.java:1011: error: cannot find symbol
    [javac]       public void onResult(LocationSettingsResult result) {
    [javac]                            ^
    [javac]   symbol: class LocationSettingsResult
    [javac] /home/jianbo/Desktop/0/platforms/android/src/plugin/google/maps/GoogleMaps.java:1014: error: cannot find symbol
    [javac]           case LocationSettingsStatusCodes.SUCCESS:
    [javac]                ^
    [javac]   symbol: variable LocationSettingsStatusCodes
    [javac] /home/jianbo/Desktop/0/platforms/android/src/plugin/google/maps/GoogleMaps.java:1018: error: cannot find symbol
    [javac]           case LocationSettingsStatusCodes.RESOLUTION_REQUIRED:
    [javac]                ^
    [javac]   symbol: variable LocationSettingsStatusCodes
    [javac] /home/jianbo/Desktop/0/platforms/android/src/plugin/google/maps/GoogleMaps.java:1042: error: cannot find symbol
    [javac]           case LocationSettingsStatusCodes.SETTINGS_CHANGE_UNAVAILABLE:
    [javac]                ^
    [javac]   symbol: variable LocationSettingsStatusCodes
    [javac] Note: /home/jianbo/Desktop/0/platforms/android/src/plugin/google/maps/AsyncKmlParser.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /home/jianbo/Desktop/0/platforms/android/src/plugin/http/request/HttpRequest.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 14 errors

**Comment by wf9a5m75** [comment]
Please search in the issue list before asking.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?utf8=%E2%9C%93&q=google+play+services+v23

**Comment by Hirbod** [comment]
```
cordova plugim rm plugin.google.maps
cordova plugin rm com.google.playservices
cordova plugin add https://github.com/wf9a5m75/google-play-services#v23
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by anaibol** [comment]
@Hirbod: you made a misspelling error on "plugim"

**Comment by Hirbod** [comment]
Thx
