### ISSUE TITLE
window.location.reload will not remove map

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#481]
Hi Masashi,

this plugin should listen to the "onBeforeUnload" event and remove the map automatically. Currently it will persist after a window.location.reload and get readded multiple times. What you think?

**Comment by Hirbod** [comment]
This is my workaround for now.

```javascript

        // we need this workaround because of location.reload
        window.onbeforeunload = function(e) {
            $rootScope.map.remove();
        };

```

**Comment by wf9a5m75** [comment]
I don't understand when you want to reload the page.
Why do you want to reload the page?

**Comment by Hirbod** [comment]
It is because of Crosswalk. Crosswalk has native pull-to-refresh. And this trigger location.reload()

**Comment by wf9a5m75** [comment]
I see.
I think crosswalk should disable that feature.
Because normal application does not have such as feature, doesn't it.

**Comment by Hirbod** [comment]
Yes, I've issued this in crosswalk JIRA. But my workaround fix this problem.

**Comment by wf9a5m75** [comment]
Ok, but I will consider this, but I need to improve this code.
This plugin reloads the browse from the java side when you use this at once
on Android 2.3.
(To be transparent the background.)

**Comment by Hirbod** [comment]
I think this is indeed a very special case, maybe my workaround is enough (Crosswalk don't work on 2.3, only 4.0 + and up)

**Comment by Hirbod** [comment]
For everyone:

```js
var lastTouchY = 0;
var preventPullToRefresh = false;

$('body').on('touchstart', function (e) {
    if (e.originalEvent.touches.length != 1) { return; }
    lastTouchY = e.originalEvent.touches[0].clientY;
    preventPullToRefresh = window.pageYOffset == 0;
});

$('body').on('touchmove', function (e) {
    var touchY = e.originalEvent.touches[0].clientY;
    var touchYDelta = touchY - lastTouchY;
    lastTouchY = touchY;
    if (preventPullToRefresh) {
        // To suppress pull-to-refresh it is sufficient to preventDefault the first overscrolling touchmove.
        preventPullToRefresh = false;
        if (touchYDelta > 0) {
            e.preventDefault();
            return;
        }
    }
});
```

add this and you'll be able to disable the feature in crosswalk. Don't know if this have any other sideeffects, but for now, it works good.

**Comment by wf9a5m75** [comment]
It seems Chromium team won't fix the reload issue. They says this is default action.
https://code.google.com/p/chromium/issues/detail?id=456515

But they also provide some alternative options.
https://docs.google.com/document/d/12Ay4s3NWake8Qd6xQeGiYimGJ_gCe0UMDZKwP9Ni4m8/edit

**Comment by Hirbod** [comment]
Thanks. Maybe Crosswalk will add an option. But the alternative options look good, will look at it.
