### ISSUE TITLE
Android: calling .remove() before addMarker() has finished will cause app crash

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#482]
Hi Masashi,

when I load the map (with many markers) and change the page (and remove the map with that change) before addMarker queue, the App will crash with this error:

```log
W/art     (10479): Attempt to remove local handle scope entry from IRT, ignoring
D/AndroidRuntime(10479): Shutting down VM
E/AndroidRuntime(10479): FATAL EXCEPTION: main
E/AndroidRuntime(10479): Process: net.nachbarschaft, PID: 10479
E/AndroidRuntime(10479): java.lang.IllegalArgumentException: Released unknown imageData reference
E/AndroidRuntime(10479): 	at com.google.l.a.cd.a(Unknown Source)
E/AndroidRuntime(10479): 	at com.google.maps.api.android.lib6.c.db.c(Unknown Source)
E/AndroidRuntime(10479): 	at com.google.maps.api.android.lib6.c.aj.a(Unknown Source)
E/AndroidRuntime(10479): 	at com.google.android.gms.maps.model.internal.t.onTransact(SourceFile:204)
E/AndroidRuntime(10479): 	at android.os.Binder.transact(Binder.java:380)
E/AndroidRuntime(10479): 	at com.google.android.gms.maps.model.internal.zzl$zza$zza.zzn(Unknown Source)
E/AndroidRuntime(10479): 	at com.google.android.gms.maps.model.Marker.setIcon(Unknown Source)
E/AndroidRuntime(10479): 	at plugin.google.maps.PluginMarker$8.onPostExecute(PluginMarker.java:818)
E/AndroidRuntime(10479): 	at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:134)
E/AndroidRuntime(10479): 	at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:18)
E/AndroidRuntime(10479): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime(10479): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(10479): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime(10479): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10479): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10479): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(10479): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10479): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10479): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(10479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

This is a big bug. I can't force the user to wait until all markers are loaded.

**Comment by Hirbod** [comment]
.remove() should stop every async task (ie. downloading markers) immediatly or we need to provide some .stop() methods

**Comment by Hirbod** [comment]
http://stackoverflow.com/questions/21523202/released-unknown-bitmap-reference-setting-marker-in-android

this is at the end something similar to my problem.

**Comment by Hirbod** [comment]
Here is a video for proof:

https://youtu.be/74R9ngJ4f7c

**Comment by wf9a5m75** [comment]
Not bug. Ofcource you shouldn't remove the marker before completing the addMarker().
Because the addMarker is asynchronize method.

**Comment by Hirbod** [comment]
It is a bug. I can't detect when the async adding is finished.

**Comment by Hirbod** [comment]
You need to add extra if/else statements inside of the code to prevent crash

**Comment by wf9a5m75** [comment]
No. AddMadker has a call back.

**Comment by Hirbod** [comment]
iphone does not crash...

**Comment by wf9a5m75** [comment]
It is not relared.

**Comment by wf9a5m75** [comment]
You don't use callback at all????

```js
map.addMarker({
  options
}, function() {
   // Adding is completed.
});
```

**Comment by Hirbod** [comment]
I use the callback, but it is not related to that. It is the AsyncTask which try to add something to the map which doesn't exist anymore. I will check the callback now..

**Comment by wf9a5m75** [comment]
Google Maps Android API v2 and Google Maps SDK for iOS are completely
different software.
Thus different behaviors are correct.

**Comment by Hirbod** [comment]
I've checked, I don't use the callback. And again, I know that this is different, but It should not crash when you check the marker reference.

**Comment by Hirbod** [comment]
```
                $rootScope.map.addMarker({

                    position: latLng,
                    uid: obj["uid"],
                    firstname: obj["firstname"],
                    picture: obj["picture"],
                    isFavorite: obj["isFavorite"],
                    isMe: obj["isMe"],
                    picture_profile: obj["picture_profile"],
                    icon: {
                        url: obj['icon'],
                        //url: $rootScope.nncache.toInternalURL(obj['icon']), 
                        size: {
                            width: 30,
                            height: 36
                        }
                    },
                    markerClick: $scope.onMarkerClick     

                });
```

**Comment by wf9a5m75** [comment]
No. The plugin already provides callback that is only way to work all
statements safely.

**Comment by Hirbod** [comment]
Discussion is very difficult with you today. I don't use the callback. Tell me how to prevent crashing and I will go your way.

**Comment by Hirbod** [comment]
What I say is logic.
I don't have a overall progress and I can't determine when the AsyncTask inside of Java is over.

And when I remove the map, the AsyncTask still runs and try to add a marker to the map which does not exist anymore. It is impossible to prevent this on JS side, the only way is to make the AsyncTask more safe

if marker then add else do nothing

**Comment by wf9a5m75** [comment]
This plugin does not consider the develper remove the map during
map.addMarker()

In order to implement your order, I need to write buch of `if` statements.

**Comment by Hirbod** [comment]
Yeah, but this should be done this way from the beginning. You can never assume that something is "there" for sure.

**Comment by Hirbod** [comment]
Or I need a cancel() method for the async task to trigger from JS-Side. This should be the easiest way if you could provide something

**Comment by Hirbod** [comment]
Or much simpler: .remove() should kill all async tasks before removing markers and map.

**Comment by wf9a5m75** [comment]
(I back from breakfast)
That might be better idea.

**Comment by Hirbod** [comment]
But sadly I do not have enough know how with java and the architecture to send a pr :(

**Comment by wf9a5m75** [comment]
ok

**Comment by Hirbod** [comment]
If you could fix this soon, I will push another small donation to you :)

**Comment by wf9a5m75** [comment]
Since you are getting into this plugin deeply, I  recommend you start to
learn Android java programming any time now.
That helps you to understand how work this plugin.

**Comment by Hirbod** [comment]
I guess I'll never develop for android again :D
I'll stick on Obj-C and web-development. I'm an experienced PHP developer.

**Comment by wf9a5m75** [comment]
That's very disappointed answer for me :(

**Comment by Hirbod** [comment]
I'm just kidding. I will, but as you may also know... time is the problem.

**Comment by wf9a5m75** [comment]
Yes, large time will be required to learn Android programming, but I hope you understand the Android part of this plugin little by little.

Even me, I haven't experienced Objective-C programming for real before starting this plugin, but now I'm better (I don't believe I'm an expert of Objective-C though).

**Comment by Hirbod** [comment]
This bug also happen without crosswalk

**Comment by wf9a5m75** [comment]
As I said, this plugin does not consider to reload the page, because nobody like that.

**Comment by Hirbod** [comment]
This has nothing to do with reload. It has to do with .remove()

**Comment by Hirbod** [comment]
Reload (which will also just do a .remove() onBeforeUnload)
https://youtu.be/74R9ngJ4f7c

Only .remove()
https://youtu.be/ETpYfZIekYQ

I do need to remove the map when I change the page. Otherwise the performance is bad. I can't just hide an reattch, I've tried that, the performance is very sluggish in that case.

**Comment by wf9a5m75** [comment]
I'm terribly busy.

**Comment by Hirbod** [comment]
I talked with some people, everybody agreed with me, that using references without a bulletproof check isn't the "good" way, even when it is a special case. Nonetheless, I can't wait, as this is a production ready app. I've changed my code and refactored everything and I don't rely on .remove() anymore, instead, I reattach my map to the new div.

This will increase memory and will release less memory then before but also has some benefits, as the map will reload super fast right now. So, I'll leave this open, maybe you decide to change the code, when not, I'm fine with it, as I'm the only one who complains

**Comment by wf9a5m75** [comment]
Nobody remove the map such as you tested.
You shouldn't remove the map until the markers are loading.
Decreasing the memory, use `map.clear()` and `map.setDiv(null)`

This plugin is not product level software. It's just free software.

Developing of this plugin is not my occupation, it's my hobby.
Increasing issue reports that using the way I'm not designed for are really increased my stress.
So I have been considering to discontinue this plugin recently.

If you want to use perfect software, please use alternatives:
such as Google Maps JavaScript API v3, or mapbox.js
They develops their software for enterprise with many developers.
This plugin's developer is just one person, and my private time is very limited.


I stopped receiving the e-mails from github from last night.
It means I will reply the issues but very slow.
However this certainly decrease my stress.

**Comment by Hirbod** [comment]
You should really consider to read and understand first, before you write something. As I told you, I fixed it and it is fine now. Nobody support this project more then me (after you), I don't know why you're so harsh the last weeks, as I try to help were I can.

**Comment by Hirbod** [comment]
And I also try to help making this "hobby project" perfect. No need to be stressed.

**Comment by webprofusion-chrisc** [comment]
As a follow up to this, my Open Charge Map app has just been updated with the latest version of this plugin and crashes on some devices. I'm setting the icon as a markerOption, rather than using marker.setIcon. This suggests that we're setting the icon elsewhere when the marker is not ready or has been cleared (my app is clearing markers regularly, so could be related).

The app got a 1-star review from a grumpy user because of this, so I've patched my version to catch the exception if it occurs ( in PluginMarker.java onPostExecute) - will see if that stops the reported crashes.

**Comment by kevinnivek** [comment]
In my case this was caused by me using map.clear(); to clear all markers on a map. What solved it for me was to iterate through the markers and remove them individually , one by one, instead of the catch-all clear.

This solution was what I used : http://stackoverflow.com/a/21887173

**Comment by Hirbod** [comment]
The crash should not happen in the new version anymore, as I've wrapped a try/catch block around it
