### ISSUE TITLE
Rendering label on retina display - Different behaviour inside and outside of plugin

### ISSUE THREAD

**Issue by antoniocapelo** [wf9a5m75/phonegap-googlemaps-plugin#483]
Hi, 

First of all, thanks for the useful plugin!

I'm trying to display some custom markers using the base64 method you described on the Marker section. However, the size of the text rendered on the canvas element isn't the expected. I' both passing the created canvas to the addMarker method:

    map.addMarker({
                    'position': position,
                    'title': canvas.toDataURL(),
                    'icon': 'www/images/logo_map.png',
                    ...

And I'm appending that same canvas to the document body for comparison:

                        document.body.appendChild(canvas);
However the one inside the plugin comes with the doubled dimensions (even if I try to scale it down, or for its css attributes to half of what I want)

 
![screen shot 2015-04-10 at 11 30 13](https://cloud.githubusercontent.com/assets/3236388/7086392/78ec503e-df78-11e4-8ffc-53d2cefc0a49.png)

Do you have any clue / insight of what may be happening?

**Comment by antoniocapelo** [comment]
Ping :)

**Comment by Hirbod** [comment]
We need contributor, no fix currently due to limited time. will close this for now, feel free to send a PR
