### ISSUE TITLE
cannot find symbol   symbol: variable LocationSettingsStatusCodes

### ISSUE THREAD

**Issue by raza2022** [wf9a5m75/phonegap-googlemaps-plugin#486]
![pasted_image_at_2015_04_11_06_42_pm_720](https://cloud.githubusercontent.com/assets/5462788/7101791/f95b107e-e082-11e4-8690-2107416fc462.png)

**Comment by raza2022** [comment]
first time trying your module on my client project. but getting 14 errors like this...
Stuck with for all day.

**Comment by Hirbod** [comment]
your missing the google play services v23

**Comment by Hirbod** [comment]
```
cordova plugim rm plugin.google.maps
cordova plugin rm com.google.playservices
cordova plugin add https://github.com/wf9a5m75/google-play-services#v23
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by raza2022** [comment]
k i trying thanks man..

**Comment by raza2022** [comment]
am close but now am getting the below error
Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

**Comment by raza2022** [comment]
one thing am also using Google+ with my app, before adding this module is there any any thing seems to be conflict with these two?

**Comment by raza2022** [comment]
the error on this line in AndroidManifest.xml
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

**Comment by wf9a5m75** [comment]
I think you installed two google play services, one is for Google+, the other hand is for this plugin.

But remove old version of google play services.
I think Google+'s one is old.

**Comment by raza2022** [comment]
Thanks for your rply @wf9a5m75 @Hirbod 
i remove all plugins and then install only this but 1 error remain same.....
Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

**Comment by wf9a5m75** [comment]
Um, it seems `plugin.google.maps` is not linked to `com.google.playservices`.
You can fix it either way:

1) Open your project under the `platforms/android/` with eclipse, then link to the `com.google.playservices` project.
http://stackoverflow.com/questions/19879844/adding-google-play-services-version-to-your-apps-manifest

2) Add `project.properties` file under `platforms/android/` , then put following text:
```
target=android-21
android.library.reference.1=CordovaLib
android.library.reference.2=com.google.playservices/(yourapp)-google-play-services_lib
```

**Comment by raza2022** [comment]
Thanks guys...
i added the google play services as module (before that i add these as libraries only)
and on my android i added above module (playservices) as dependency
and also add all jar libraries as android dependencies (ie. volly and playservices too)
Here all i did and it works for me

**Comment by rolinger** [comment]
Hi all, I am having similar issues as orig poster, I am still having his original issues and can't seem to get past it:

cordova plugim rm plugin.google.maps
cordova plugin rm com.google.playservices
cordova plugin add https://github.com/wf9a5m75/google-play-services#v23
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

And that reduced my errors from 38 down to 24.

These are the two primary errors now, about 12 from each .java file:

C:\Users\RPO\Documents\Developer\MobileApp\lust\platforms\android\src\plugin\google\maps\GoogleMaps.java:881: error: cannot find symbol
divTop + divH - webView.getScrollY());
^
symbol: method getScrollY()
location: variable webView of type CordovaWebView
C:\Users\RPO\Documents\Developer\MobileApp\lust\platforms\android\src\plugin\google\maps\MyPluginLayout.java:53: error: cannot find symbol
this.root = (ViewGroup) webView.getParent();

And my plugins:
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 23.0.0 "Google Play Services for Android
com.jamiestarke.webviewdebug 1.0.8 "WebView Debug"
com.ludei.webview.plus 2.4.3 "Webview+"
cordova-plugin-device 1.0.0 "Device"
cordova-plugin-whitelist 1.0.1-dev "Whitelist"
net.orworks.cordovaplugins.cordovasqlite 1.5.0 "CordovaSQLite"
org.apache.cordova.device-motion 0.2.11 "Device Motion"
org.apache.cordova.device-orientation 0.3.11 "Device Orientation"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.globalization 0.3.4 "Globalization"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.apache.cordova.vibration 0.3.13 "Vibration"
plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.4 "phonegap-http-request"
