### ISSUE TITLE
Add goundOverlay from a base64 image on Android

### ISSUE THREAD

**Issue by iDams** [wf9a5m75/phonegap-googlemaps-plugin#489]
Hey,

Is there anyway to add a groundOverlay from a base64 image as a url in Android?
The url looks like this:

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAf8AAAKkCAYAAAAOUDYXAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzsvXmUXFd1L/w7+5xzb03dVT1VaWhrtjxKNpawIwixwYBfnDgY8ySGF5KXxfTBwh+8j7BIQvzihExk4AufeRBwgMcHcZ6tZyAMIlYwk7GNZcmSJdka3FJbUqvV1d3qqcY7nLO/P8691SXFJiHx91beWr3X6nWrbt26VV116/z2/u3f3ltgyZZsyX4m27DhF/25uVd7QXDYq9Xe4wNXeb5/XgdB1df6vRr4gBdFX9DAd5W68bc0b/qCMps/p7F2l5Ir9khTPiBl37PSZOcEesYIuXMkMwui+zVMu5fRXG5RG7ayVWIze6WRk9cazK23mNlgzbltBtNXWDn+KmNO3GrUqV808bNvNgCg1HUmjvtZqX4W4vY4isqsdYWjqMLAQVLqhzKOH5fACQJGSV15v8TQfopzE0L1jIs4NylkYVxc/H+b+gpWzTLHtRUMAJjYajF5ncXZV1hgrVWqj+O4n4FLrdbvi4BrbRTdboBXWgDwvNUM3Gy7zxmGJzuv43mjIgzXunPjB5Tu1/q0iKJVnG49bzWH4Vr2vPcbABDijTYIrmbf38zAu6wQH7TA3VaIv7KtljTAAVsofMzU69r09R00nnd5XK3eb4AfxMy/b4RgfokujX+jCQJ+jzZseEKOjKySg4Pr5fT0Dgm8igqFSNbrd8ls9pAE3kat1mbp+3fIILhTAjvJ8z4hgYcpDO+TwB7SepcEDhHzEYrjx6VSMwI4SSg8TXH+rFDFMxd8v/H8JawaKxn1ayywzrrrZ5sR4goLbLJRdKsBrree9zYD3GzD8P8ywHbr+/cYIT5o2+1fYADIZF7D7fbrOZu9lQGg1bqds9kd3Gq9nYEDNpf7lACAZrMqs9mvi1Zrl8hkdgvgbmq3H0/e0205YDgDvC2jrnyXz//xtRnc8u6MedknfWy5J0ObP5e12/6ohzZ8Nb82++Piq6fhvxrAzQB+HoRNAK6DxcY6gG8Q8IQFHk+2h+D+pgBMJNuLLU9Aw7rti1nOAssADAEoA6gA2ARgHQE3WODnCLgZqG9yLzcCi6Mg7AHwRPL3PQ92/0rbqjU2tum52xv25G0t2vvBhnjio03zvb9syS8daoi/Hq7H8Z8FWn8rAIAoWpVcq4+S1mPC7bvwt6q1+31G0TADr7Tp7wV4vfW8jSzEGy3wNqv+uctxyZZsyRZty5Z9et++X9PAPTqXK3jA/9MBfuANHvBxzfwXHlZ+SuN113rxxvuV3MRarrtbYfhHygwelqh8UmHwqJRbJ4nzE2R1U7BqCuvVBABQ2MOIc0xRjkVjmcXWssX05cZUPx3LVonRGLayfonF86+NTfN2lkfeHsVnbjS4frMFgLh6rcXEVotgiKNn32yUus5EkXMG3H8xQsBTUl15v4z9Twlc+g0Z5yaFXPWwjDPTQhYmO4uJyZwXsj3gnpc5L2IAsj3A5syNBlcDmHKvieqNFs1lrADEI79iuPoqDbw+VupKG8fPCaUG2dpZxPEYa/0a4xwRQGvdeS3mjdAaiKIKa/06EUVVofWkAJZBa8CttmVmrjBQ4TA8Y7V+kwlDyUDFBsE11vM2MvC0DYIRA3zHAh+R2awx9fqDlM+/nuL4A2J29gkB/JIYHu4VW7fuFcxb438vDsCWLbeJfftuEpXKm0W12iuAHejpebWo1TaLXO5TotmsCqAkMpk50W7vFb5/WDAfFc6JOiW0HhNRtI+i6KBQ6ggBxygF/riyS6riT4RKHL3u11XNZYypl9l4fpdQ1VuhFCxwjJiBOC4zsI+0vo3D8JQATgrPOyqEOCyCYK8AflX6/lYGgHb7FgY+YplfkzgDa8C8B5nMHgAA82ct8wcpk/nvZO3dBOwV7faXyPefFsAp4XmfkGG4yQN+2VNXvsvn19zpmc0f0vLqL3rY+EWPLv+xtr2nJOX+QqJ3TJUWSBYBFOAuwzyAHAANAqYs0LRAFcBosq0CaBIwYR3wNy8C+Jx1wA8sbn+aE9AkAOnxyXF1ArZZoA74cH+55HANixwIChbFEJQLQQ0ZCngLBH+WbHFUyso+JXPnhVnxiER8mVTqLgnco6JoBS8C+7gAxkUUnRNaVy/4Lt3vZzkDK1jrMRGGqRPwWQHcbJlvhRDAEvgv2ZL9C2379p1y587P6WLxMT0//xWv2TyjLwT+3/Si6KMeXvYhT77ydo1tf+hhze8oXP1Fzwy+QcrVn9Ry6wFlSicl9z4vbe8pSaolKD9JVrU7P2ALgOIMo1G2Js4yLaw2WL7GYN13rNlWtnL2UoPaJyzObotlY9hixS9INAdYTtxisLDemkaZZXuAU4eg4wyM3mbiudWMlY8Ryp8iXPoNKcsHKF7xiJSFSYGBB0n2niCTme28F5k7L4w3J9LbAIC59Vau/ZYFABO81YHmzGWW2wOM6Sst1t5s0LyeUV1n44UKAxWgd0zEI79iVPGMiJ7d1GEouiE3jmeFUn2sFOD2zwrmxfcSx32sVB8zA0ptsMB/tsAVVus0Mr3RhuErLXCTBT4ufT9ngmCVYf6KAB4T1r5dNBqbBHBIAN9Gu/2AqFbfj61b9+LfgwOwffsDYufOjwvgfZ19xWKfmJ/fLvL5twjmVQCATGa3aLeF8P39ArgPYXhcONbkUYqicaF1VUTRMxTH00KpEUqBH+WnKF62l1TPuEAXu2PqKxjNMse5CYGJrTbGLqjqrQCAOB5g4BlyzNG4AB4lF0keF74P+P6HZRBczUEAAL9ufR8A7pDMJTjHwJnvb2V3/5fh+/tFEBwUvv9q4XlzFIZvF0GwmzxvnWC+m7T+uGZ+n45XtyQ2f07LK+7WGN6kcPk+ZZfv0VR+WNt8VZKqEwD4sCiBMAQLDYs8yIFtnYA63N/3k20TDtSb5G5fbE1yDsC/1HL2Qgeg2xpufyG5u+iYWOTTzyUmYb22oMwcITNDpFrC6LqQwz9SsvC0MCvPE6rHKIoeklrv4kWnuSqi6KHEOQaiaEq4/UOs9SE4ti89fovVekwwb7NCAMAuMN+6BP5LtmT/Utu5c0j39f2pnp29V2ez1+tW67c95g96jur/uE6BH6/9Pz1zQ8OTV3xa47L7PKzcqeTWXZ4pnZS0bI9G7xmJwphEYZe02RkiGQjopiAKBABY6zOiHFvjM1r9FvW/N6gPGwrzbOvDxjSHLKY2x9j2Q41zW2I5/8cK1c0GG3sZ9UssxrcahCXGFV9mzL/V4vjtsWwPMs9cYXHiVqOayzhe+w8yHjpIuPSrCv1fJ1M8QTJ3XqB0guDNC5mbEcabFyY/1gl7TLKVUe8iSIa9jLm1buWbvM5gZoPF5rdyPHOZle0BlgNHyDTKHPc3CDOTNoYP2X6ETb3MPD5mgAR8AABFxNXNVvWMi/i5XzGq19GaqDxFcW0Fq+YyBoB4YZgxeZ1VjZXM9Wss8PoY+GUG3hQDm63WtxngV20Q3Eye9zVqtw35/h5qtb5K2exBEuI9gmhWRNExAQD/nhwAABge/m0xNjYogPCC/c3m34hs1gjmD8L3nxDAOxEER4TnjYgw/IJwNPC4iKKHhFLTIo6fozieFar0NKniT0S8bC+hcoDioYMks1PCZKadU9ce5Lg1xCmLo4IhRuNpiuduYuA5UmqQHQszLoCtIgxPCc8bEcy3EgB43tfgqGTnCPj+4QT0lwn3+FERBHuEY2V2URCcFFo/JIPgjADOEPAsaV0VzBsRRWNSlV6Zxeuv9/Da23287B4Pl93nofKgwuAhhcx5QvGkotykhFejoQaUB3eJRlgEYc+50En03hW5161zCi7ef8EH3eUAvFjUX+gC/BdyFi5iFPRFr+V3vVdC7Bg/2RbITRIK73AHDxwhVSyK+OyTUqnLEkfXAXsUPUNKTYsoct+hUucTJ8CxdO47G2TgKqv1LgFca4GtYAZSB2AJ/Jdsyf4FltD9Ko63qGw2p1ut89rzNugwfIfW+gMe

It works on iOS but not Android.
Your plugin adds 'www/' in front of the url and I got this error which is normal:

"Can not load image from www/..."

I tried to remove these lines: (PluginGroundOverlay.java L100)

if (filePath.indexOf("://") == -1 && 
        filePath.startsWith("/") == false && 
        filePath.startsWith("www/") == false) {
      filePath = "./" + filePath;
    }
    if (filePath.indexOf("./") == 0) {
      String currentPage = this.webView.getUrl();
      currentPage = currentPage.replaceAll("[^\\/]*$", "");
      filePath = filePath.replace("./", currentPage);
    }

So now the url is right but I still get the "Can not load image" error.

Thanks!

**Comment by wf9a5m75** [comment]
There is no plan to support base64 for groundoverlay.

**Comment by iDams** [comment]
Ok, thanks for your answer!
