### ISSUE TITLE
Square (Polygon) that follows the zoom

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#490]
Hey guys!, I need a square in the map that follows the zoom.

Currently I am using a function that you pass the center and a distance in km and it returns the vertices for the square. Is working perfect, but I need to resize the polygon as the user zooms in and out.

Is there any relation that I can use for creating the function for converting the zoom into the distance to use for getting the square points?

**Comment by wf9a5m75** [comment]
You can use `polygon.setPoints()`

**Comment by leandroz** [comment]
Yes but I need to know which points to set, could be difficult to implement google.maps.geometry.spherical library?

**Comment by leandroz** [comment]
Never mind, is not what we need, thanks anyway!
