### ISSUE TITLE
Drawing on the map (Drawing Manager)

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#492]
I need to let the user draw a rectangle in the map.
I know that is not implemented but the API is available in both Android and iOS SDKs?

https://developers.google.com/maps/documentation/javascript/examples/drawing-tools?hl=es
http://jsbin.com/harawira/1/edit?html,css,js,output

**Comment by wf9a5m75** [comment]
Not available.

**Comment by sarantist** [comment]
@wf9a5m75  Are you planning to implement drawing tools in the near future?

**Comment by wf9a5m75** [comment]
no
