### ISSUE TITLE
Is it possible to cache the map for offline usage ?

### ISSUE THREAD

**Issue by sn0opr** [wf9a5m75/phonegap-googlemaps-plugin#494]
Basically I wan to show the current position in the map using GPS, 
I would like to cache the map, so if the there is no more network, at least I can show the user the cached map.

**Comment by sn0opr** [comment]
Up

**Comment by Hirbod** [comment]
No, that's not possible. Google will cache some regions automatically (so a running session will work after network abort, but after restart, the cache will be pruned.) There are no capabilities for caching maps.
