### ISSUE TITLE
1.2.5 The second time map is created, the map position stays the same.

### ISSUE THREAD

**Issue by Moulde** [wf9a5m75/phonegap-googlemaps-plugin#495]
I just upgraded to 1.2.5, and i experience an issue.

When i load the app, everything looks great, the map is showing and everything is fine.
But after the map is removed and then created once, the position of the map will not change.

So when i open the swipe in menu, the entire screen should be pushed to the right, but the underlying map (below the transparent div) is not changing position.

I can manually execute the refreshLayout() so that it will work as it did before upgrading the plugin.

**Comment by wf9a5m75** [comment]
Please find a bug, and send me a pull request.

**Comment by Moulde** [comment]
I have been unable to find the issue, but i solved it by manually running refreshLayout when the user is interacting with the swipe menu in my app. Not really a pretty solution though.
