### ISSUE TITLE
Expose computeDistanceBetween function

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#497]
Hey!, could be easy to add computeDistanceBetween to the plugin?, if i want to do it where i should start looking? thanks!

**Comment by wf9a5m75** [comment]
https://www.google.com/search?q=computeDistanceBetween+javascript&oq=computeDistanceBetween+javascript&aqs=chrome..69i57.5089j0j7&sourceid=chrome&es_sm=119&ie=UTF-8
