### ISSUE TITLE
Implement maxWidth for Marker InfoWindow

### ISSUE THREAD

**Issue by trancee** [wf9a5m75/phonegap-googlemaps-plugin#498]
It would be quite helpful to limit the width of the InfoWindow according to Google's own API:
https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions

If there is much text in the content of the InfoWindow, currently it takes up full width of the available map screen and just does not look good. If we could use maxWidth it would be possible to limit that.

**Comment by wf9a5m75** [comment]
At the first, please try to implement by yourself.

Android code is here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L1749-L1869

iOS code is here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/GoogleMapsViewController.m#L343-L667

**Comment by trancee** [comment]
OK, I will try to do this by myself. I might make a pull request once I am finished with the implementation.

**Comment by wf9a5m75** [comment]
:+1

**Comment by trancee** [comment]
I have added the pull request, please review.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/503

**Comment by Hirbod** [comment]
Thanks @trancee, merged!
