### ISSUE TITLE
getMyLocation doesnt work after crosswalk installed on ionic

### ISSUE THREAD

**Issue by k1ng440** [wf9a5m75/phonegap-googlemaps-plugin#499]
Hello,
i have installed the plugin in crosswalk and everything seems to be working except the getMyLocation. it was working just fine before i have installed crosswalk.

i have following code in my AndroidManifest.xml
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by Hirbod** [comment]
I really recommend you to use cordovas geolocation plugin, it is much more optimized and works cross platform without any problems - even on crosswalk

**Comment by k1ng440** [comment]
thanks. can i set users current location to map?

**Comment by Hirbod** [comment]
If course. The plugin returns you lat and lng, just convert to google latlng obj and pass as position to as marker
