### ISSUE TITLE
Animating map view re-positioning

### ISSUE THREAD

**Issue by stevesims** [wf9a5m75/phonegap-googlemaps-plugin#50]
I'd really like to animate the position of the map view.  The scenario I'm imagining is that the user presses a button and the map slides to the right to reveal a menu hidden underneath the map (displayed in the cordova web view).

I've looked at the code, and it seems to me that the logical place to put support for this on the JS side would be to add an "animated" flag to the map.refreshLayout method.  I guess that the animation duration could be a default value which could get overridden in params passed into the getMap method.

**Comment by Hirbod** [comment]
dropped for now due to limited time
