### ISSUE TITLE
Application gets crashed while adding custom image as marker to the map

### ISSUE THREAD

**Issue by ManoMuthu** [wf9a5m75/phonegap-googlemaps-plugin#500]
Hi,

I'm using this plugin in sencha application. Its working fine with the default marker.
But I need to use custom image as marker instead of default marker and I want to clear the markers in certain time interval for that i'm using map.clear() function. For first 50 markers it is working fine. If no. of markers is above 50, the application gets crashed.

I'm getting warning in logcat that : (Attempted to send a second callback for ID: GoogleMaps1752554559
Result was: {"id":"marker_m8","hashCode":1127133392}
)
 Is there any other option to clear the custom marker.Please suggest a solution to solve this problem.

Thanks in advance!!!

**Comment by masashiGMS** [comment]
Please post the whole error log.

**Comment by Hirbod** [comment]
I'm sure this happens on Android, right? I'm sure it is related to #482 

When you clear or remove an marker, which async task wasn't finished, it will crash.
Actually, this plugin should have some more checks, but currently, it just simple does not proof if the marker reference is still there..

**Comment by ManoMuthu** [comment]
@Hirbod  Thanks for your reply..

I can't able to define no.of markers before set them on map.Is it possible to remove marker and its reference dynamically.Please suggest a solution.

Thanks in advance.

**Comment by Hirbod** [comment]
I already posted you the only way of working around this problem. And I'm sure you iterate trough your for-loop - so you will just need to save "markers.length" in your global var, and increase the counter inside of your addMarker method or for-loop. And your interval should check, if makers-length match the inited count, and only if === true, calling "clear()", else retry (and be sure to also include a retry counter, not ending in there forever)
