### ISSUE TITLE
Center marker on map

### ISSUE THREAD

**Issue by AlexMili** [wf9a5m75/phonegap-googlemaps-plugin#502]
Hi,

I'am trying to center a custom HTML marker on my map with the following code :

```html
<style>
    #cursor {
      text-align: center;
      margin: auto;
      z-index:10;
      padding-top:60%;
    }
</style>
<div id="map_canvas" style="width:100%;height:100%;">
    <div id="map_container">
        <div id="infoDiv">
          <img src="img/search.png" style="float:left;margin-right:20px;" height="32px" width="32px" id="searchAction"/>
          <div class="MapTitle">&nbsp;</div>
          <div class="MapContent">&nbsp;</div>
        </div>
        <div id="cursor"><img class="cursorimg" onClick="showInfo();" width="50%" src="img/zone.png"/>         
      </div>
    </div>
</div>
```

The cursor is always centered but with the margin-top, I can't drag the map above the cursor.

Am I doing wrong or is there any other way to do it ?

Thanks in advance for your help.

**Comment by Hirbod** [comment]
You have placed your overlaying code inside of your map container. This will prevent the map beeing dragged if you are moving inside of your HTML element.

**Comment by AlexMili** [comment]
It works thank you !

The problem is when I do so, I can't click on my cursor anymore.

Is there another way ?

**Comment by Hirbod** [comment]
Just one thought, but I'm not sure. Try 

```css
.myelement {
   pointer-events: none;
}
```

**Comment by AlexMili** [comment]
None of you proposition works.

Maybe there is another way to have a custom marker constantly centered on the map ?

**Comment by Hirbod** [comment]
Could you provide a video or a screenshot, so I can better understand what you are trying to achieve?

**Comment by AlexMili** [comment]
Here is the current behavior I have (with your suggestions) : 

![Map gif](http://media.giphy.com/media/3oEdv9gTuwyEm90FTW/giphy.gif)

The cursor "Commander ici" (order here) is always centered but when I try to click or double click on it, the map zoom.

I tried your suggestions, when I put the HTML of my cursor (it's not a map marker) as I presented in my first post, the above part of the map is not draggable.

**Comment by chadwhitaker** [comment]
@AlexMili It appears your zoom issue is related to an issue I just submitted here, #525.

**Comment by AlexMili** [comment]
Thank you for your response but I think the problems aren't the same.
My cursor stay on the center on the map, the problem is I can't click on it. In the GIF I am trying to click,  then double click on it to trigger an event I previously bound to it without any effect.

**Comment by wf9a5m75** [comment]
@AlexMili 
Could you record a video with `map.setDebuggable(true)`?
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#mapsetdebuggable

**Comment by AlexMili** [comment]
@wf9a5m75 I did but nothing new appeared (no green or red color)

**Comment by AlexMili** [comment]
My problem is not fixed yet, why did you closed the thread ?

**Comment by maheshvembu** [comment]
Am also facing same issue ):
