### ISSUE TITLE
[bug] App crashes on android 4.1

### ISSUE THREAD

**Issue by piernik** [wf9a5m75/phonegap-googlemaps-plugin#504]
Sorry for new topic, but other one is closed and You could missed it.
There is issue with Your plugin and android 4.1 - https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/355#issuecomment-94301925 app crashes.
Can You tak a look?

**Comment by piernik** [comment]
I confirm that it works with v 1.2.3

**Comment by piernik** [comment]
I've installed Your example https://github.com/wf9a5m75/phonegap-googlemaps-plugin#example on android 4.1 and it crashes also

**Comment by piernik** [comment]
Any news?

**Comment by iRajul** [comment]
any Update on fix for this crash?

**Comment by Hirbod** [comment]
Any crash reports here?

**Comment by mabdelfattah** [comment]
I've the same problem and here is my log:

    08-30 22:44:53.361: D/AndroidWebViewClient(1921): onPageFinished(file:///android_asset/www/index.html#/)
    08-30 22:44:53.361: D/CordovaActivity(1921): onMessage(onPageFinished,file:///android_asset/www/index.html#/)
    08-30 22:44:53.433: D/AndroidChromeClient(1921): file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 21157 : pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
    08-30 22:44:53.433: W/Web Console(1921): pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details. at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21157
    08-30 22:44:53.569: D/dalvikvm(1921): GC_CONCURRENT freed 792K, 8% free 9959K/10823K, paused 0ms+0ms, total 2ms
    08-30 22:44:53.725: D/dalvikvm(1921): GC_CONCURRENT freed 784K, 10% free 9747K/10823K, paused 0ms+1ms, total 3ms
    08-30 22:44:53.729: D/dalvikvm(1921): GC_CONCURRENT freed 25K, 6% free 10216K/10823K, paused 1ms+0ms, total 2ms
    08-30 22:44:53.837: V/StatusBar(1921): Executing action: _ready
    08-30 22:44:53.837: W/CordovaPlugin(1921): Attempted to send a second callback for ID: StatusBar1508777111
    08-30 22:44:53.837: W/CordovaPlugin(1921): Result was: "Invalid action"
    08-30 22:44:53.877: D/CordovaActivity(1921): onMessage(spinner,stop)
    08-30 22:44:53.897: D/TilesManager(1921): new EGLContext from framework: b810d408 
    08-30 22:44:53.897: D/GLWebViewState(1921): Reinit shader
    08-30 22:44:54.413: D/GLWebViewState(1921): Reinit transferQueue
    08-30 22:44:54.449: D/CordovaNetworkManager(1921): Connection Type: wifi
    08-30 22:44:54.449: D/CordovaNetworkManager(1921): Connection Extra Info: null
    08-30 22:44:54.505: D/CordovaNetworkManager(1921): Connection Type: wifi
    08-30 22:44:54.505: D/CordovaNetworkManager(1921): Connection Extra Info: null
    08-30 22:44:54.505: D/CordovaActivity(1921): onMessage(networkconnection,wifi)
    08-30 22:44:54.505: I/CordovaLog(1921): This app uses phonegap-googlemaps-plugin version 1.2.5
    08-30 22:44:54.505: I/dalvikvm(1921): DexOpt: access denied from Lcom/google/android/gms/common/GooglePlayServicesUtil; to field Landroid/app/Notification;.extras
    08-30 22:44:54.505: W/dalvikvm(1921): VFY: unable to resolve instance field 18
    08-30 22:44:54.505: D/dalvikvm(1921): VFY: replacing opcode 0x54 at 0x00b3
    08-30 22:44:54.505: E/dalvikvm(1921): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
    08-30 22:44:54.505: W/dalvikvm(1921): VFY: unable to resolve check-cast 29 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/common/GooglePlayServicesUtil;
    08-30 22:44:54.505: D/dalvikvm(1921): VFY: replacing opcode 0x1f at 0x000e
    08-30 22:44:54.505: I/dalvikvm(1921): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzg
    08-30 22:44:54.505: W/dalvikvm(1921): VFY: unable to resolve virtual method 549: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
    08-30 22:44:54.505: D/dalvikvm(1921): VFY: replacing opcode 0x6e at 0x000b
    08-30 22:44:54.517: D/dalvikvm(1921): GC_FOR_ALLOC freed 716K, 11% free 9732K/10823K, paused 3ms, total 3ms
    08-30 22:44:54.517: I/dalvikvm-heap(1921): Grow heap (frag case) to 10.796MB for 1324812-byte allocation
    08-30 22:44:54.529: D/dalvikvm(1921): GC_FOR_ALLOC freed 3K, 10% free 11023K/12167K, paused 13ms, total 13ms
    08-30 22:44:54.549: D/dalvikvm(1921): GC_CONCURRENT freed 0K, 10% free 11023K/12167K, paused 17ms+0ms, total 20ms
    08-30 22:44:54.797: D/OpenGLRenderer(1921): TextureCache::get: create texture(0xb854c158): name, size, mSize = 8, 1324800, 2860800
    08-30 22:44:54.845: I/App(1921): WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
    08-30 22:44:54.861: A/libc(1921): Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 1921 (com.myApp)

**Comment by Hirbod** [comment]
Should be fixed in the current master (version >= 1.2.7 )

**Comment by Mojo90** [comment]
I recently discovered that my App crashes on 4.1 as well.
Reinstalled plugins installed is:
```
plugin.google.maps 1.3.2 "phonegap-googlemaps-plugin"
```
What I get till the crash:
```
4683-4683/ I/CordovaLog﹕ This app uses phonegap-googlemaps-plugin version 1.2.5
10-04 20:25:55.619    4683-4683/ W/GooglePlayServicesUtil﹕ Google Play services out of date.  Requires 7895000 but found 1
10-04 20:25:55.719    4683-4683/ D/dalvikvm﹕ GC_FOR_ALLOC freed 227K, 7% free 19025K/20423K, paused 73ms, total 75ms
10-04 20:25:55.809    4683-4683/ I/dalvikvm-heap﹕ Grow heap (frag case) to 25.690MB for 7348336-byte allocation
10-04 20:25:55.849    4683-4699/ D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 6% free 26200K/27655K, paused 38ms, total 38ms
10-04 20:25:55.909    4683-4690/ D/dalvikvm﹕ GC_CONCURRENT freed 0K, 6% free 26201K/27655K, paused 29ms+4ms, total 66ms
10-04 20:25:56.569    4683-4683/ A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 4683 (app.meetfriends)
```

Only have Simulator with Android 4.1 and Google Maps is on latest Update for API 16. Does the Plugin not support this version anymore?

**Comment by Hirbod** [comment]
Update your SDK Android Support and Google Play Library and your play services, as it cleary tells you that the Google Play service version is out of date

**Comment by Jerome2606** [comment]
Hi,

```
Should be fixed in the current master (version >= 1.2.7 )
```

which part of code fix that because I use cordova 5.1.1 and so I need to use a fork version to fix two bugs ?

**Comment by Hirbod** [comment]
Check

1) your API Level. Above functions are only available since API Level 16
2) Update you Android Support SDK and Google Play service libraries inside of the SDK Manager

**Comment by Jerome2606** [comment]
I have this log only on Android 4.1.1 (works on 4.1.2 and 5.0), the application launch as expected but fails silently after 2-3 seconds only on this android 4.1.1.
I update the last Google Maps SDK on the test device.

I have all installed in SDK Manager and up to date on my dev machine

Here's a part of logcat:
```
D/dalvikvm(18148): start new thread

D/dalvikvm(18148): threadid=25: notify debugger

D/dalvikvm(18148): threadid=25 (SharedPreferencesImpl-load): calling run()

D/dalvikvm(18148): threadid=25: exiting

D/dalvikvm(18148): threadid=25: bye!

I/dalvikvm(18148): DexOpt: access denied from Lcom/google/android/gms/common/GooglePlayServicesUtil; to field Landroid/app/Notification;.extras

W/dalvikvm(18148): VFY: unable to resolve instance field 19

D/dalvikvm(18148): VFY: replacing opcode 0x54 at 0x00b3

E/dalvikvm(18148): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza

W/dalvikvm(18148): VFY: unable to resolve check-cast 29 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/common/GooglePlayServicesUtil;

D/dalvikvm(18148): VFY: replacing opcode 0x1f at 0x000e

I/dalvikvm(18148): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzg

W/dalvikvm(18148): VFY: unable to resolve virtual method 544: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;

D/dalvikvm(18148): VFY: replacing opcode 0x6e at 0x000b

I/System.out(18148): [CDS][DNS]Unable to resolve host "plugins.cordova.io": No address associated with hostname

W/PluginManager(18148): THREAD WARNING: exec() call to GoogleMaps.isAvailable blocked the main thread for 31ms. Plugin should use CordovaInterface.getThreadPool().

```

and 

```

F/libc    (18148): Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 18148 (.infotec.TECApp)
```

**Comment by Hirbod** [comment]
Please post your AndroidManifest.xml

**Comment by Jerome2606** [comment]
```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10" android:versionName="0.0.10" package="MYAPPNAME" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" 
			android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="XXXXXX" />
        <activity android:exported="true" android:name="com.adobe.phonegap.push.PushHandlerActivity" />
        <receiver android:name="com.adobe.phonegap.push.CordovaGCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="MYAPPNAME" />
            </intent-filter>
        </receiver>
        <service android:name="com.adobe.phonegap.push.GCMIntentService" />
    </application>
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="MYAPPNAME.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="MYAPPNAME.permission.C2D_MESSAGE" />
</manifest>

```

**Comment by Hirbod** [comment]
Thought you're missing the google_play_services_version, but it's fine
Please try to raise minSdkVersion to 16. (you need to specify it inside of config.xml, or it will be overwritten.

Or just try

> cordova run android -- --minSdkVersion=16

Did you see the double -- ? That's important, just do it like I've explained, it's not an error.

**Comment by Jerome2606** [comment]
For the moment, I use this version of the plugin:
https://github.com/dubcanada/phonegap-googlemaps-plugin/commits/master
for the Phenome, Nipher and Cosmith fixes.

As it is now, maybe the master branch is compatible with cordova 5.1.X ?

**Comment by Hirbod** [comment]
Our plugin is 5.X stable and have a lot more improvements than the forks. I won't give any further support on forked plugins, as the codebase is different / changed

**Comment by Jerome2606** [comment]
WOW, It's work ! :)

I added this to config.xml:

```
<preference name="android-minSdkVersion" value="16" />
```

**Comment by Hirbod** [comment]
If you had read my post 23 minutes before more patiently, you would have saved me time.

**Comment by Jerome2606** [comment]
Sorry for your time ... I don't pay attention that Android 4.1 will use SDK 14 if you don't specify him to use min 16 ...

**Comment by Hirbod** [comment]
Nevermind, glad it worked for you!
