### ISSUE TITLE
map.off( <some_event> ) remove all event listeners

### ISSUE THREAD

**Issue by bairathirahul** [wf9a5m75/phonegap-googlemaps-plugin#506]
HI,

In case an event listener is not set for the map and map.off is called for that event listener, it removes listeners for all events.

e.g. $scope.map.off( plugin.google.maps.event.MY_LOCATION_BUTTON_CLICK ); // this will clear all event listeners if no listener is set for plugin.google.maps.event.MY_LOCATION_BUTTON_CLICK event before this line.

I have made a fix in the googlemaps-cdv-plugin.js to fix this issue. The code is as follows:

self.off = function(eventName, callback) {
    var i;
    if (typeof eventName === "string"){
		if(eventName in _listeners) {
      
      if (typeof callback === "function") {
        for (i = 0; i < _listeners[eventName].length; i++) {
          if (_listeners[eventName][i].callback === callback) {
            document.removeEventListener(eventName, _listeners[eventName][i].listener);
            _listeners[eventName].splice(i, 1);
            break;
          }
        }
      } else {
        for (i = 0; i < _listeners[eventName].length; i++) {
          document.removeEventListener(eventName, _listeners[eventName][i].listener);
        }
        delete _listeners[eventName];
      }
		}
    } else {
      //Remove all event listeners
      var eventNames = Object.keys(_listeners);
      for (i = 0; i < eventNames.length; i++) {
        eventName = eventNames[i];
        for (var j = 0; j < _listeners[eventName].length; j++) {
          document.removeEventListener(eventName, _listeners[eventName][j].listener);
        }
      }
      _listeners = {};
    }
  };

**Comment by Hirbod** [comment]
Please send us a PR. Fork the project, make your fixes and submit to #test branch

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/517
