### ISSUE TITLE
Plugin Adding "GoogleMaps" Binaries

### ISSUE THREAD

**Issue by bryanwokich** [wf9a5m75/phonegap-googlemaps-plugin#507]
Hi all,
Love the plugin, but I've run into an interesting issue recently.  My (ionic) app has been building to the app store without any issues, but I recently ran into a build error, so recreated the ios application.

Everything seemed to work fine, until I tried to send my app to apple.  

I ended up with "GoogleMaps" appearing 3 times underneath "Binary and Entitlements".  Apple then rejects the app as only 1 binary is allowed in an app package. 

I removed this plugin, rebuilt, and the "GoogleMaps" binaries disappear.   

Adding the plugin causes the binaries to return and I cannot submit.

Am I doing something wrong?  Does anyone have an idea as to what's happening?

**Comment by Hirbod** [comment]
Just have a look at your included frameworks. If there are multiple ones, delete them and just reference one!
