### ISSUE TITLE
addGroundOverlay don't load images in old Android OS's

### ISSUE THREAD

**Issue by marcovergueira** [wf9a5m75/phonegap-googlemaps-plugin#510]
addGroundOverlay don't load images in old Android OS's, this issue happens in Android 4.1.x when i use persistent locations.

map.addGroundOverlay({
    'url': cordova.file.dataDirectory + overlayData.file,
    'bounds': bounds,
    'opacity': 0.5
  }, false);

**Comment by Hirbod** [comment]
Try absolute path /www or /img/....

**Comment by marcovergueira** [comment]
The absolute path works, the issue happens when i use persistent locations like cdvfile:// this only happens in Android old devices, iOS more recent Android os it's ok.

**Comment by Hirbod** [comment]
please have a look at #405 

Read @wf9a5m75 posts, I guess you need to access with file://
