### ISSUE TITLE
Can't find google play services

### ISSUE THREAD

**Issue by craig-at-rsg** [wf9a5m75/phonegap-googlemaps-plugin#511]
My app won't build with this plugin - the build error is
Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

Under platforms/android I have a com.google.playservices directory, and that has a google-play-services_lib/res/values/version.xml file that defines the google_play_services_version, but it isn't seen by the build process.

I recently upgraded to Cordova 5.0.0 - could this be an incompatibility issue with that? Or something else?

**Comment by jskrzypek** [comment]
This might be similar to #512

**Comment by Hirbod** [comment]
This is a different error, but yes, Cordova-CLI 5.0 and Android-JS 4 won't work currently. Closing this, as #512 is the current bug thread for this!
