### ISSUE TITLE
Need changes to continue the plugin development.

### ISSUE THREAD

**Issue by wf9a5m75** [wf9a5m75/phonegap-googlemaps-plugin#514]
Hi everyone,

This is Masashi who is main developer of **PhoneGap-GoogleMaps-Plugin**.
Please read this issue (but not technical issue).

First of all, thank you for using this plugin.
I'm proud to help your project through this plugin.
And some people sent some pull requests, and donated to the project, these are extremely helpful for me.
I would like to really appreciate for your helps.

---

Although this plugin has been becoming popular, my life has changed.
- my job is really busy, works for the company project even Saturday or Sunday sometimes,
- I got my wife (it means there is no private time than before, but it's good for me ;p ),
- my private time is an hour or less per day, but I have been writing my new book recently,
- **I don't use Cordova anymore except for this plugin, at least last one year**.

The reason of I started this plugin, to use native Google Maps from JS for myself.
But I don't use Cordova anymore (at least in last one year).
It means no benefit for me to develop the plugin, and using Cordova that is stressful itself.

Also developing for the plugin, that reduces my life time.
I worked on even Saturdays and Sundays for this plugin.
If I feel fun, that's no problem, but I don't feel fun, that's really problem.

And people just ask to add features, or just report issues without
test code and/or detailed descriptions, ... etc.

*This is not my job, I'm not free service, I'm not public service.*

I'm really tired :tired_face:

----

I know many people depend on this plugin, but I have been considering to stop this plugin.

**In order to continue the development, we need to change the current situation.**
At least I hope so.

- involving another committers who can understand JS, Java, and Obj-C,
- donating the code to Apache Software Foundation or similar,
- or posting issues with bounty.

---

The idea of posting issues with bounty is that a person who fixes an
issue with pull request receives the bounty (not me).

The benefit of this is, I don't spend much time to invest many issues,
it means I can focus on the development new features.
![screen shot 2015-04-28 at 10 43 44 am](https://cloud.githubusercontent.com/assets/167831/7376342/fb6a9768-ed93-11e4-8920-96bfaa5cac67.png)

----

Unless the current situation is changed, I don't want to develop this plugin.

What do you think? Please post and share your comments.

----
Regarding of the marker cluster, because of many people donated to the project, I don't consider to stop it. At least, I will finish the work, don't worry for the marker cluster.

**Comment by leandroz** [comment]
100% agree @wf9a5m75 , is an Open Source project and I think that everyone can help to continue the development.
Something that maybe could be helpful to someone that want to start digging into the code is add a page in the Wiki on what is your working environment, how do you debug, test, etc. So the person that want to start has things a bit easier.
In my case I wanna work to update the plugin to work with Cordova 5.0 and Android Platform 4.0, i have already searched about the changes and add some information in other issue, we need to make easy for someone to help i think.

**Comment by jskrzypek** [comment]
Also agreed, @wf9a5m75 (and congrats!). The one thing to possibly make sure of is that someone on the project can respond to PRs. Too many open-source projects die because no one is available to do code reviews and approve PRs...

**Comment by Hirbod** [comment]
Also agree. I'll write some rules for submitting in the next days and when people do not deliver correct or good informations, we'll just close the issues

**Comment by jskrzypek** [comment]
Awesome, thanks @Hirbod I suggest grabbing a decent contribution style guide (angular's might be a bit much but it's pretty good https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md) and working from there rather than starting from scratch.

**Comment by canadaka** [comment]
I have PayPal issues, but I will get my co-workers to donate some bounty. We have decided to use your plugin for a project, so we will contribute some bounty and some code when ready.

**Comment by Hirbod** [comment]
@jskrzypek yes that is a very good idea. We need to copy the parts that fit to us and start implementing the rules. This plugin also should block new feature requests for now, till everything is a bit less stressful and some important milestones are reached.

In my opionion, the milestones should be following.
1) Support for new Cordova 5.0.0 with newest android-js
2) Register plugin to npm, the cordova plugin registry will be set to readonly in june and will be deactivated in october
3) Implement marker cluster
4) Places API (maybe I have enough time for iOS-Version)

After that, we can have a look for everything else. I think, our Q&A is very good so far, we need maybe some better documentation, most questions here are the same or by lazy people.

**Comment by jskrzypek** [comment]
@Hirbod agreed. I think GH issue tracking is a good system for what it does, but lacks some capabilities for supporting discussions etc. Perhaps we could set up something like a gitter (https://gitter.im/) or google group?

**Comment by sradforth** [comment]
Firstly I'd like to say a huge thanks for making your work open source, it's hugely helpful.  Regarding bounties may I suggest using bitcoins instead, many people aren't based in America and using Paypal is not available worldwide yet. (trybtc.com for anyone who's not familiar with it).
Anyhow,thought I'd mention it as when I saw the cluster bounty I thought this was a brilliant way to further the development and more than happy to contribute to a plugin I'd be using if I could.

**Comment by Luukschoen** [comment]
@wf9a5m75 Thank you for your awesome work. Whenever and wherever I can I'll contribute to this repository. Your plugin is the best for google maps out there and it would be a pity to lose it. I totally understand your situation. I'll help in issues wherever I can and i think asking some money for new features is just a logical step. Keep up your good work!

**Comment by leandroz** [comment]
I opened a gitter, here is the url: https://gitter.im/leandroz/phonegap-googlemaps-plugin
