### ISSUE TITLE
possibility to show user location above map pins

### ISSUE THREAD

**Issue by dafi87** [wf9a5m75/phonegap-googlemaps-plugin#515]
Might there be the possibility to make it an option to strictly show the user location (blue dot) on map on a higher level than other map pins? Currently the user location gets hidden under map pins.

Thanks!

**Comment by VictorQueiroz** [comment]
+1

**Comment by wf9a5m75** [comment]
Not possible. Google does not provide that feature.
If you want to do that, you should create a marker with blue dot image, then manage it by yourself.
There is no plan to implement this.
