### ISSUE TITLE
Build Errors: cannot find symbol & incompatible types (all seemingly to do with 'webView')

### ISSUE THREAD

**Issue by rolinger** [wf9a5m75/phonegap-googlemaps-plugin#518]
Hi all, I am having similar issues as orig poster, I am still having his original issues and can't seem to get past it:  https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/486

I implemented some of the suggestions on the above post, it helped a tad but I am still having a lot of errors:

cordova plugim rm plugin.google.maps
cordova plugin rm com.google.playservices
cordova plugin add https://github.com/wf9a5m75/google-play-services#v23
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

And that reduced my errors from 38 down to 24.

These are the two primary errors now, about 12 from each .java file:

C:\Users\RPO\Documents\Developer\MobileApp\lust\platforms\android\src\plugin\google\maps\GoogleMaps.java:881: error: cannot find symbol
divTop + divH - webView.getScrollY());
^
symbol: method getScrollY()
location: variable webView of type CordovaWebView
C:\Users\RPO\Documents\Developer\MobileApp\lust\platforms\android\src\plugin\google\maps\MyPluginLayout.java:53: error: cannot find symbol
this.root = (ViewGroup) webView.getParent();

And my plugins:
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 23.0.0 "Google Play Services for Android
com.jamiestarke.webviewdebug 1.0.8 "WebView Debug"
com.ludei.webview.plus 2.4.3 "Webview+"
cordova-plugin-device 1.0.0 "Device"
cordova-plugin-whitelist 1.0.1-dev "Whitelist"
net.orworks.cordovaplugins.cordovasqlite 1.5.0 "CordovaSQLite"
org.apache.cordova.device-motion 0.2.11 "Device Motion"
org.apache.cordova.device-orientation 0.3.11 "Device Orientation"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.globalization 0.3.4 "Globalization"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.apache.cordova.vibration 0.3.13 "Vibration"
plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.4 "phonegap-http-request"

**Comment by Hirbod** [comment]
Did you install the #test branch? Did you followed the tutorial for crosswalk? Are you on Cordova 5.0.0 or 4.3.0? (This plugin currently does not support the newest cordova version)

**Comment by rolinger** [comment]
I assume #test branch and crosswalk are pre-requisites for this plugin?  If so, I have searched the github site and plugin for the install requirements for those but haven't found any notes/directions or hardly any mention of them.  Where can I find this?
I was on Cordova 5.0.0 and have already downgraded to 4.3.0.
-Russel


Date: Sun, 3 May 2015 08:56:51 -0700

**Comment by Hirbod** [comment]
The cli is not the problem, it is the android-js of Cordova. You have to install cordova platform add android@3.7.0 (or anything before 4.0.0)

We'll dig into the newer versions as soon as possible
