### ISSUE TITLE
Map is flickering with black background when shown 

### ISSUE THREAD

**Issue by roberthovhannisyan** [wf9a5m75/phonegap-googlemaps-plugin#521]
Hi,
I am experiencing a weird problem, when there is a black background displayed before the map itself becomes visible. This problem is observed on different devices, with different versions of androids.

Probably the reason is the latest google play services update (7.3.29). I have found this: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7936 
Can someone confirm this. If so, let's star the issue in order to be fixed asap.

**Comment by roberthovhannisyan** [comment]
The same problem is with demo phonegap-googlemaps-plugin-v1.2.5.apk.

**Comment by jskrzypek** [comment]
Is the problem showing up on all of the devices or just some? Can you give us a few examples of devices/android versions you've seen this on so people can try to replicate the flickering?

**Comment by jskrzypek** [comment]
Also according to one of the commenters, they're currently working on a fix: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7936#c13

**Comment by roberthovhannisyan** [comment]
Following is the list, and all of them have Google play services 7.3.29
* Android 5.0.2 on Motorola Moto G (2nd Generation) (XT1068)
* Android 4.4.2 on Acer Iconia A1 (A1-811)
* Android 4.2.2 on Samsung Galaxy Tab 2 10.1 (GT-P5110)

**Comment by wf9a5m75** [comment]
@jskrzypek :+1:

**Comment by jskrzypek** [comment]
It looks like there's a new release of the google play services client sdk (v24.0.0) while this plugin is still using wf9a5m75/google-play-services#23 to pull in v23.0.0.

I've created a fork with a v24.0.0 of google play services here which you can try to install by using:
```
cordova plugin rm plugin.google.maps
cordova plugin add 'https://github.com/jskrzypek/phonegap-googlemaps-plugin#test-gps-v24' --variable API_KEY_FOR_ANDROID="...."
```

Does this fix the issue?

**Comment by jskrzypek** [comment]
@wf9a5m75 if you want to pull v24.0.0 into your main google-play-services repo, the branch is here: https://github.com/jskrzypek/google-play-services/tree/v24, I just followed the steps in the readme

**Comment by roberthovhannisyan** [comment]
@jskrzypek - using forked plugin didn't helped. I think the reason is in play services update pushed by google.

**Comment by Hirbod** [comment]
The bug has been fixed regarding to the gmap link. We need to incorporate a new play service version

**Comment by roberthovhannisyan** [comment]
@Hirbod 
Isn't it possible to take advantage of `framework` element of plugin.xml file like it is specified here https://cordova.apache.org/docs/en/edge/plugin_ref_spec.md.html#Plugin%20Specification
```xml
<!-- Depend on latest version of GCM from play services -->
<framework src="com.google.android.gms:play-services-gcm:+" />
```

**Comment by roberthovhannisyan** [comment]
According to https://developers.google.com/android/guides/setup we can add 
```
<framework src="com.google.android.gms:play-services:+" />
```
or selectively 
```
<framework src="com.google.android.gms:play-services-maps:+" />
```

**Comment by Hirbod** [comment]
Please use the new version 1.2.8 (use the tag or just download from master.)
