### ISSUE TITLE
Map not Showing in IOS?

### ISSUE THREAD

**Issue by jokerxvier** [wf9a5m75/phonegap-googlemaps-plugin#522]
Hi I currently build in IOS using ionic framework. But the Map is not showing up it only show the marker but empty map. Do you have any configuration with IOS? or this is a bug? Kindly help me fixed my problem with IOS

**Comment by jheissat** [comment]
Hello jokerxvier,

I also have a blank map issue on ios (working fine on android) but I haven't identified the issue so far...

**Comment by jskrzypek** [comment]
Hey guys, a blank map is possibly an indication that your API key is being rejected by the Google Maps servers, particularly if you're still able to place markers. I.e. this would seem to indicate that the local plugin functionality is working – i.e. setup of the map, attachment to the DOM, and pre-configured methods like `addMarker()` that only need to execute native code without making API calls – while the calls to the maps servers fail to return valid/renderable responses.

Check to make sure you've completely followed the [tutorial for mac steps for setting up the iOS API key](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-Mac#4b-obtain-the-google-maps-api-key-for-ios). After you get the new API keys remove the old plugin from your project with 
```sh
cordova plugin rm plugin.google.maps
```
and then add it back to your project with 
```sh 
cordova plugin add plugin.google.maps --variable API_KEY_FOR_IOS="<iOS API key>"
```

> *If you're using both iOS and android make sure to provide both keys.*
> ```sh
> cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="<android API key>" --variable API_KEY_FOR_IOS="<iOS API key>"
> ```

**Comment by jheissat** [comment]
Thanks a lot for your answer jskrzypek. 

On my side it was not an issue related to API key but something else I was not able to identify (conflict with another plugin ? ). I had to reinstall cordova, my code and all plugins and it now works. 

Thanks !

**Comment by danclaydonpm** [comment]
I'm having a similar white screen issue on iOS, but the map was working OK about a week ago

**Comment by wf9a5m75** [comment]
@jskrzypek Thanks for your help.

Everybody, please understand that the map is located UNDER THE BROWSER.

The reasons of you got white map maybe:
- your API Key for iOS is wrong,
- your JS framework located OVER THE MAP,
- you use Cordova 5.0 (this plugin does not work with Cordova 5.0 **yet**),
- your JS code is wrong.

In order to confirm your issue, please follow the tutorials **with a new project and simple code**.

**Comment by jokerxvier** [comment]
thanks guys. I just enable the IOS in google map deve account. closing this issue now.

**Comment by castrojr913** [comment]
I struggled with this problem but it not was neither transparency nor API Key. It was the Cordova ios version. So, you can try with this approach. The commands are [here](https://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html)

**Comment by wf9a5m75** [comment]
Use the master branch.

**Comment by channainfo** [comment]
I had the same problem. @jskrzypek had a good reason. My api key was rejected.

**Comment by markygab** [comment]
I had the same issue - i'd **changed the App ID** and thus invalidated the iOS api key

**Comment by radwani** [comment]
I tried generating new keys and all, but my issue was cordova version.
" this plugin is unfortunately not compatible with Cordova Version 4.x. So we will need to remove the iOS platform, and add it with an older version of Cordova instead." 
:(

Did that and faced a lot many errors! So, I am still with the same issue
