### ISSUE TITLE
is it possible to Create a rounded map or superimpose an image top ?

### ISSUE THREAD

**Issue by zaouifahd** [wf9a5m75/phonegap-googlemaps-plugin#523]
Hi, great job for plugin, i'm new developer on Cordova.
I need create app with a rounded map using google map plugin. 
after much try and search no solution work for me.

I need create that 
![exemple](https://cloud.githubusercontent.com/assets/12213089/7576322/aa8b14cc-f83c-11e4-963a-ad86cdb74d59.png)

is work fine for me on browser (Chrome) but in device or emulator i have that 
![exemple2](https://cloud.githubusercontent.com/assets/12213089/7576474/39a719e8-f83e-11e4-9e0d-87be0fda3c86.PNG)

i have try Z-index but with google map no work. the map is always superior.
Please if you have a idea? sorry for my english :)

**Comment by jskrzypek** [comment]
Hi @zaouifahd, can you show us (or give us a stripped down example) the code you're using in your html for the app?

**Comment by jskrzypek** [comment]
Also fair warning: you may be in violation of the [Google Maps API terms](https://developers.google.com/maps/terms) (see 10.1.1(b)) if you don't use [`Map.setPadding()`](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map.setPadding()) to adjust the positions of the Google identity markers so they're visible.

**Comment by zaouifahd** [comment]
Yes sir, of course.
you can see that html and css http://jsfiddle.net/9wuznL9z/
but when i run that on cordova with jquery mobile the map don't show if run withaout jquery mobile the map are visible, have you a idea ?

thank you in advance

**Comment by wf9a5m75** [comment]
Technically not possible.
The map plugin recognizes the region of touchable area as rectangle.
