### ISSUE TITLE
Prevent map from changing center location on zoom.

### ISSUE THREAD

**Issue by chadwhitaker** [wf9a5m75/phonegap-googlemaps-plugin#525]
I'm attempting to recreate a "drag the map to set your location" feature in my app. This feature is very common on apps like Uber and Lyft, where you set the location of where you want to be picked up.

This is easily accomplished by adding a marker/pin icon on top of the map interface, setting that pin to the center, and finally you can use `map.getCameraPosition();` to find the lat long of your set pin.

One major UX issue with this idea is when you pinch to zoom on the map. By default it will zoom *and drag* the map to the location of your fingers.

Here is an example of pre-zoom (notice the pin at the cross roads) and then after I zoom in using pinch.

![img_0803](https://cloud.githubusercontent.com/assets/433078/7595428/98ee8ad0-f8ac-11e4-944d-c0bde3ef9bd0.jpg)

To solve this you must lock the map's center position (ie. prevent dragging) when zooming.

Here is a post resolving this issues using the iOS SDK:
http://stackoverflow.com/a/28158654/293585
*I have yet to find any documentation on how to accomplish this via the Android SDK, but I will gladly put in the effort to find it.*

Could this be implemented easily into this plugin and then set as an option via javascript?

**Comment by chadwhitaker** [comment]
@wf9a5m75 @masashiGMS @Hirbod @fabriziogiordano @webalchemist 

My company is willing to provide a bounty via Bountysource to have this implemented. What do you think it would talk?

**Comment by wf9a5m75** [comment]
Try the below code (I haven't tested this yet)

```js
map.setOptions({
  'gestures': {
    'scroll' :false
  }
});
```

**Comment by chadwhitaker** [comment]
@wf9a5m75 That's getting me started :)

Although it locked the map at all times. So, I need a way to set scroll to true when I want to drag the map around. Any suggestions on the best way to detect map drag only?

**Comment by wf9a5m75** [comment]
This plugin can not detect the timing that the user starts the pinching, because Google Maps Android API v2 and Google Maps SDK for iOS do not notify the gesture to the program.

**Comment by wf9a5m75** [comment]
Suggestion way is that place a state button (such as "place a pin button"), then set `gestures.scroll = false`.
Tap the button again, clear the flag (`gestures.scroll = true`).

**Comment by wf9a5m75** [comment]
I just came up another better way.
Place a pin image at the center of the map in the map div. 
```html
<div id="map_canvas" style="position:relative;width:400px;height:400px">
<img src="pin.png" style="position:absolute;left:200px;top:200px">
</div>
```

Then you just listen the CAMERA_CHANGE event.
```js
map.on(plugin.google.maps.event.CAMERA_CHANGE, function(latLng) {
  console.log("center = " + latLng);
});
```

**Comment by chadwhitaker** [comment]
Here is a test app that I'm working on. I'm actually using your idea that you just posted above. 
https://github.com/demandfood/HelloMap

If you run this app you'll see that it zooms in & out without moving the pin. This is just what I'm looking for.

But, I'm unable to drag the map to move the pin location. This can only be done by setting `gestures.scroll = true`. So I need a way to detect drag and set it to `gestures.scroll = true` on `drag start`, and then back to  `gestures.scroll = false` on `drag end`.

Anyway to accomplish this with this plugin or by detecting the drag gesture with a different plugin?

**Comment by wf9a5m75** [comment]
How about checking the camera position by timer repeatedly?
This is the possible way currently to detect the gesture.

I tried at once to capture the drag gesture, but in iOS, because of the mechanism of the event bubbling is, I could not do that.
Thus, in the native side, the plugin can not catch the gesture, as far as I know.

**Comment by chadwhitaker** [comment]
Can you show me an example of the `setInterval()` solution?

I'm not entirely sure if it will work since CAMERA_CHANGE event updates on zoom and drag.

**Comment by wf9a5m75** [comment]
The idea is something like this.
(I haven't tested this code)

```js
var points = new array(2);
var isDragging = false;

map.on(plugin.google.maps.event.CAMERA_CHANGE, function(latLng) {
  if (points.length > 2) {
    points.splice(points.length - 1, 1);
  }
  points.push(latLng);
});

setInterval(function() {
  if (points.length < 2) {
    return;
  }
  var isEquals = points[0].equals(points[1]);
  if (!isEquals) {
    if (!isDragging) {
      map.trigger("drag_start");
    }
    isDragging = true;
  } else if (isDragging && isEquals) {
   map.trigger("drag_end");
    isDragging = false;
  }
}, 100);


map.on("drag_start", function() {

});
map.on("drag_end", function() {

});
```

**Comment by chadwhitaker** [comment]
I'm sorry, but I've spent a bit of time trying to debug your code above.

I'm seeing the following error:
`TypeError: undefined is not an object (evaluating 'points[0].equals')`

Any ideas what would be causing this? I get the idea that your suggesting with this code, I just can't get it to work properly to test.

**Comment by wf9a5m75** [comment]
Oops, I mistaken.
```js
var isEquals = (points[0].lat == points[1].lat && points[0].lng == points[1].lng);
```

**Comment by maheshvembu** [comment]
Logic is not working for me.

**Comment by chadwhitaker** [comment]
The logic never worked for us either. I temporarily paused this idea and used the web version of Google Maps API.

@wf9a5m75 My company is willing to provide a bounty if you would be willing to implement a solution via the plugin.

**Comment by radhakrishnancegit** [comment]
@chadwhitaker How did you achieve the solution via google maps api? I'm trying with plain google maps javascript api. But not able to do that.. A link to solution/idea will be really great.

**Comment by chadwhitaker** [comment]
@radhakrishnancegit Currently our only option via the Google Maps Javascript API is to disable pinch to zoom. This prevents the marker from being displaced.

**Comment by vipinnegi90** [comment]
@chadwhitaker did you find a solution to this yet on native android. ?

**Comment by chadwhitaker** [comment]
@vipinnegi90 I'm working on solution that I'm pretty close to releasing. I'll follow up here with a link to the forked plugin.

**Comment by chadwhitaker** [comment]
@vipinnegi90 Here is my forked version that contains the java solution. https://github.com/chadwhitaker/cordova-plugin-googlemaps

It still needs a little work and I'm open to pull requests.

**Comment by parveshhc** [comment]
Is this issue resolved ?

**Comment by mikesmo** [comment]
@chadwhitaker Thanks for your folked version! Our team has been trying to solve this for many months now and this seemed to do the trick for when the user zooms with two fingers. Great effort!

Do you also know how to modify the code for when the user double taps on the map, so that it stays centred? 

Many thanks!

**Comment by chadwhitaker** [comment]
@mikesmo Glad my repo was helpful!

To my knowledge double tap works on iOS by default. Is this something you're trying to accomplish on Android?

To be honest, most of the Java work (Android) was completed with the help of a friend.

**Comment by prasanthyejje** [comment]
i got solution for this issue ..
when the finger touch count >1 than place this "setScrollGesturesEnabled(false);" otherwise make it True.

**Comment by prasanthyejje** [comment]
here is the complete code 
public boolean dispatchTouchEvent(MotionEvent ev) {

        Log.d("on dispatchTouchEvent ", " dispatchTouchEvent ");
        switch (ev.getAction() & MotionEvent.ACTION_MASK) {
            case MotionEvent.ACTION_POINTER_DOWN:
                fingers = fingers + 1;
             break;
            case MotionEvent.ACTION_POINTER_UP:
                fingers = fingers - 1;
                break;
            case MotionEvent.ACTION_UP:
                fingers = 0;
                break;
            case MotionEvent.ACTION_DOWN:
             if (firstClick != 0 && System.currentTimeMillis() - firstClick > 300) {
                 Log.w("on count=0", " count=0 ");
                    count = 0;
                }
                count++;
                if (count == 1) {
                    Log.w("on count ", " count=1 ");
                    firstClick = System.currentTimeMillis();
                } else if (count == 2) {
                    Log.w("on count ", " count=2 ");
                    lastClick = System.currentTimeMillis();
                    if (lastClick - firstClick < 300) {

                        CameraUpdate getzoom = CameraUpdateFactory.zoomIn();
                        mMap.animateCamera(getzoom, 400, null);
                        Log.w("on double click ", " event ");
                    }
                }
                    fingers=1;
                break;
        }
      if (fingers >1) {
          Log.d("2fingersaction ", "2fingersaction ");
             mMap.getUiSettings().setScrollGesturesEnabled(false);
         // mMap.getUiSettings().setRotateGesturesEnabled(true);         // disableScrolling()
      }
      else if (fingers < 1 )
        {
          Log.d("onefinger ", "onefinger ");
            mMap.getUiSettings().setAllGesturesEnabled(false);

                   mMap.getUiSettings().setScrollGesturesEnabled(true);
           // enableScrolling();
        }
       if (fingers > 1) {
           Log.d("double if condition ", "doubleifcondition "); 
             return gestureDetector.onTouchEvent(ev);
             } else
            return super.dispatchTouchEvent(ev);
    }

**Comment by dmitry-novikov** [comment]
Please star this Feature Request to let Google know that we need it: https://issuetracker.google.com/issues/69795937

**Comment by QVMaster** [comment]
I used to reset map center to current location when map zoom changed.

google.maps.event.addListener(map, 'zoom_changed', function() {
  //here you can set map center to current location you hold before
});
