### ISSUE TITLE
KML feature data

### ISSUE THREAD

**Issue by Renrell** [wf9a5m75/phonegap-googlemaps-plugin#530]
Hi,

I'am looking for reading data from KML.
For example i have this inside my KML file:

< ExtendedData>< SchemaData schemaUrl="#simp_qgis6">
		< SimpleData name="ID">1< /SimpleData>
		< SimpleData name="level">0< /SimpleData>
		< SimpleData name="dept">13< /SimpleData>
< /SchemaData>< /ExtendedData>

I saw that in the Javascript API there is this function : featureData
So i tried this:

kmlOverlay1.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay1, latLng) {
                        alert(overlay1.featureData.dept);
                    });

But didn't work.
Any idea ?

**Comment by masashiGMS** [comment]
This plugin supports only the below tags:
-style
-stylemap
-linestyle
-polystyle
-linestring
-outerboundaryis
-placemark
-point
-polygon
-pair
-multigeometry
-networklink
-link
-key
-styleurl
-color
-width
-fill
-name
-description
-icon
-href
-coordinates
