### ISSUE TITLE
Fails in Cordova 5.0.0

### ISSUE THREAD

**Issue by arcoirislabs** [wf9a5m75/phonegap-googlemaps-plugin#531]
This plugin fails in Cordova 5.0.0
Here is the verbose output. I am not sure if it is Cordova's new Gradle based build system's mistake or plugin's fault.
:generateDebugSources UP-TO-DATE
:compileDebugJava
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:15: e
rror: cannot find symbol
import org.apache.cordova.ScrollEvent;
                         ^
  symbol:   class ScrollEvent
  location: package org.apache.cordova
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:138:
error: cannot find symbol
    root = (ViewGroup) webView.getParent();
                              ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:197:
error: cannot find symbol
          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
                 ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:206:
error: cannot find symbol
          webView.setBackgroundColor(0);
                 ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:663:
error: cannot find symbol
      ScrollEvent scrollEvent = (ScrollEvent)data;
      ^
  symbol:   class ScrollEvent
  location: class GoogleMaps
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:663:
error: cannot find symbol
      ScrollEvent scrollEvent = (ScrollEvent)data;
                                 ^
  symbol:   class ScrollEvent
  location: class GoogleMaps
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:789:
error: cannot find symbol
    webView.setVisibility(View.GONE);
           ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:807:
error: cannot find symbol
        webView.setVisibility(View.VISIBLE);
               ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:879:
error: cannot find symbol
          divTop - webView.getScrollY(),
                          ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\GoogleMaps.java:881:
error: cannot find symbol
          divTop + divH - webView.getScrollY());
                                 ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:5
3: error: cannot find symbol
    this.root = (ViewGroup) webView.getParent();
                                   ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:5
5: error: cannot find symbol
    webView.setBackgroundColor(Color.TRANSPARENT);
           ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:5
7: error: cannot find symbol
      webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
             ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:1
32: error: cannot find symbol
    int scrollY = webView.getScrollY();
                         ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:1
80: error: method removeView in class ViewGroup cannot be applied to given types
;
    frontLayer.removeView(webView);
              ^
  required: View
  found: CordovaWebView
  reason: actual argument CordovaWebView cannot be converted to View by method i
nvocation conversion
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:1
91: error: no suitable method found for addView(CordovaWebView)
    root.addView(webView);
        ^
    method ViewGroup.addView(View,int,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invo
cation conversion)
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
00: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                               ^
  symbol:   method getScrollX()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
00: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                                                     ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
14: error: no suitable method found for removeView(CordovaWebView)
    root.removeView(webView);
        ^
    method ViewGroup.removeView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invo
cation conversion)
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
21: error: no suitable method found for addView(CordovaWebView)
    frontLayer.addView(webView);
              ^
    method ViewGroup.addView(View,int,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invo
cation conversion)
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
61: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
66: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:2
92: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
C:\Users\m\meetin\platforms\android\src\plugin\google\maps\MyPluginLayout.java:3
03: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
24 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 17.367 secs

C:\Users\m\meetin\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\m\meetin\platforms\andr
oid\gradlew cdvBuildDebug -b C:\Users\m\meetin\platforms\android\build.gradle -P
cdvBuildArch=x86 -Dorg.gradle.daemon=true"
ERROR running one or more of the platforms: Error: C:\Users\m\meetin\platforms\a
ndroid\cordova\run.bat: Command failed with exit code 8
You may not have the required environment or OS to run this project

**Comment by Davide95** [comment]
Please see https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/512

**Comment by arcoirislabs** [comment]
Sorry I was not aware of this thread. Will close it right away
