### ISSUE TITLE
 getMyLocation method doesn't show an error message when the device's location is turned off.

### ISSUE THREAD

**Issue by ramsabarish** [wf9a5m75/phonegap-googlemaps-plugin#533]
map.getMyLocation(  locationSucess ,
                                     function(msg){                   
                                        alert( 'Please ensure your location services are enabled and then press done');
                                  });  

It works when the location is On but doesn't show an error message when the location is turned Off. I guess the thread keeps on waiting to get user location, isn't there a way to set timeout for this method. 
Kindly tell me how can I notify the user if the location services were turned off in his device.

**Comment by Davide95** [comment]
If you're using Cordova, you could use geolocation.getCurrentPosition :)

**Comment by pmwisdom** [comment]
getCurrentPosition wont show you an error if the device has location services off. Neither for Android or iOS.  I rolled out my own solution, but I also found this on the plugin repo awhile ago. http://plugins.cordova.io/#/package/de.fastr.phonegap.plugins.checkgps

**Comment by masashiGMS** [comment]
This plugin shows the display if the location settings is turned off.
Or you can get error as the second arguments.
```js
var option = {
    enableHighAccuracy: true      // Force GPS
};
map.getMyLocation(option, onLocationSuccess, onLocationError);

function onLocationSuccess( result ) {
    alert(JSON.stringify( result, null, 4 ));
}
function onLocationError( error_msg ) {
    alert( error_msg );
}
```

**Comment by ramsabarish** [comment]
Thanks a lot.
