### ISSUE TITLE
compile issue with cordova 5.00 m ScrollEvent not found

### ISSUE THREAD

**Issue by pallu87** [wf9a5m75/phonegap-googlemaps-plugin#535]
I could not compile this plugin with cordova 5.00.

I tried the instruction at the below place. And the app built and ran, but I get an empty screen and cannot see any map.

http://stackoverflow.com/questions/30290523/cordova-google-map-plugin-not-compiling

The sample demo .apk works flawlessely on my phone.

Has anyone faces this similar issue. Can anyone suggest another plugin that works with cordova.

I am looking to use this for my new app in android. All suggestions/help appreciated.

**Comment by pallu87** [comment]
i guess this is already a known issue.

**Comment by cosmith** [comment]
See https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/516

**Comment by Hirbod** [comment]
duplicate
