### ISSUE TITLE
android screen goes blank first time

### ISSUE THREAD

**Issue by badbobo** [wf9a5m75/phonegap-googlemaps-plugin#538]
We are building a cross-platform app using PhoneGap Build.  We are using phonegap-googlemaps-plugin to provide map services.  The following code initializes the map:

	initializeMap: function()
	{
		alert( 'initializeMap ..' );
		
		//  Clean up previous map environment
		if ( beerMap ) {
			alert( 'beerMap already exists' );
			beerMap.clear();		//  Delete all markup
			beerMap.off( plugin.google.maps.event.MAP_READY );
		};
	
		//  Define Google map
		try {
			beerMap = plugin.google.maps.Map.getMap();
		} catch(e) {
			alert('beerMap error - getMap: ' + e.message);
		}
		if ( ! beerMap ) {
			alert( 'beerMap not created' );
		} else {
			alert( 'beerMap created' )
		};
	
		beerMap.on( plugin.google.maps.event.MAP_READY, app.onMapReady );
	},

	onMapReady: function(map) {
		alert('onMapReady ..');
	
		alert( 'beerMap.setOptions ..' );
		var opts = {
			'controls': { 
				'myLocationButton': true,
				'zoom': true 
			},
			'gestures': { 'gestures': true },
			'camera': { 'zoom': 10 }
		};
		beerMap.setOptions( opts );
		alert( 'beerMap.setBackgroundColor ..' );
		beerMap.setBackgroundColor( 'transparent' );
		alert( 'beerMap.setMapTypeId ..' );
		beerMap.setMapTypeId( plugin.google.maps.MapTypeId.ROADMAP );
		
		alert( 'beerMap.setDiv ..' );
		var mapDiv = document.getElementById( 'google_map' );
		beerMap.setDiv( mapDiv );

		alert('onMapReady done');
		app.scheduleApp();
	},

The app runs successfully on the iPhone, but behaves peculiarly on Android devices.  The first time through, a blank white screen is displayed after the call to setDiv.  After hiding the app by returning to the home screen and then restoring the app, the page is displayed correctly with the map.  On all following accesses the app runs without issues.

Thank you for your help.

**Comment by badbobo** [comment]
I get the same issue using with your DemoApp.  Blank screen at start-up and then everything works well after restoring the app.  My device is Android 4.4.2

**Comment by adamhwang** [comment]
Same thing happening here.  First run is blank/gray, but refresh view and it's rendered normally

**Comment by Luukschoen** [comment]
Somehow it seems that setting the mapdiv goes wrong. Did you try it out on an emulator and with debug mode to reattach the mapdiv if it's giving you a blank map on startup?

**Comment by badbobo** [comment]
Good afternoon,

We didn't use any simulators or emulators because 
we are on a very short path and we decided to use 
PhoneGap Build rather than Cordova/PhoneGap 
CLI.  This way we could test quickly on physical 
devices rather than the simulators and emulator 
which we previously found cumbersome.

Please keep me posted, because several others 
have reported the same problem on Android.

Thanks for your response,
Bo.


At 04:38 PM 6/10/2015, you wrote:

>Somehow it seems that setting the mapdiv goes 
>wrong. Did you try it out on an emulator and 
>with debug mode to reattach the mapdiv if it's 
>giving you a blank map on startup?
>
>­
>Reply to this email directly or 
><https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/538#issuecomment-110922251>view 
>it on GitHub.


-------------------------------------------------------------------------
  T u r n i n g    i n f o r m a t i o n    i n t o    k n o w l e d g e .
--------------------------------------------------------------------------
The Learning Edge Corp.                Visit us at http://www.TheLedge.com
90 Claremont Street
Toronto  ON
Canada  M6J 2M5
416.248.0667
