### ISSUE TITLE
SHA-1 fingerprint & blank map

### ISSUE THREAD

**Issue by tburd** [wf9a5m75/phonegap-googlemaps-plugin#540]
Thank you for such a great plugin, this is what I really need to use.

Once I am new here I tried a lot of times to run the maps and check the issues here.
Although I was not able to get the map running.

First, I did not install Android SDK, Apach Ant, etc...
I just installed phonegap from Node.js.
From the prompt I create new projects, load plugins, etc...  and I am using PhoneGap Desktop + PhoneGap App to test the projects.

Therefore I had no success on getting the SHA-1 fingerprint to create the Android Key (Google's API console).
I understood that this SHA-1 is related to Java and not related to the SDK or anything else. Is that right?

I really need this SHA-1 to proceed?
Should I compile the apk in a different way to make it work?
Does anybody else tested the plugin using phonegap desktop + phonegap app?

Additional info: phonegap v5.0.0-0.28.1

Best regards! =)

**Comment by Davide95** [comment]
You have to install Android SDK before compiling your project. Furthermore, if you don't have Android SDK then you can't do anything related to  Android, like obtaining a key for Google Maps.
