### ISSUE TITLE
OVERLAY_CLICK not working on iOS

### ISSUE THREAD

**Issue by alexislg2** [wf9a5m75/phonegap-googlemaps-plugin#541]
Hey I'm adapting my working code from Android to iOS. And I noticed that OVERLAY_CLICK event return undefined. Here is my code:

```
circle.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay, latLng){
    console.log(latLng); // Here I get undefined when I click somewhere on the circle
});
```

I'm using the last version of the plugin with iOS 8 simulator and iOS8 on real device with cordova 5.1.1

I know this plugin doesn't work on android with cordova 5.X but here it is iOS. This code works perfectly fine on Android. Anything I'm doing wrong?

**Comment by alexislg2** [comment]
I also tried with cordova 4.2, same issue

**Comment by masashiGMS** [comment]
Google Maps SDK for iOS does not pass the latlng to the event delegator.
Thus, it's unpossible.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/bbe9a96c7916221559282980650ea76e2947d6b7/src/ios/GoogleMaps/GoogleMapsViewController.m#L277-L285

Use MAP_CLICK instead.

**Comment by alexislg2** [comment]
What do you mean use MAP_CLICK instead? I already use it but it doesn't work when there's a circle above the map (the onclick event of the map is never called).

**Comment by masashiGMS** [comment]
```js
map.on(plugin.google.maps.event.MAP_CLICK, function(latlng) {
});
```

**Comment by alexislg2** [comment]
Yes I already use that but when someone taps on a place where there is a
circle, the map click event is not triggered.

**Comment by alexislg2** [comment]
OK I managed to make it work by removing this line:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/Circle.m#L40

**Comment by Hirbod** [comment]
@masashiGMS @wf9a5m75 

is it safe to remove the line as @alexislg2 did?

**Comment by Hirbod** [comment]
While removing circle.tappable worked for you, it would break click events on circle.
As this is something special, I will close this issue. Anybody who needs this can incoporate your fix manually.

**Comment by joewoodhouse** [comment]
Never say anything is unpossible :)

I needed this to work, so I came up with a solution. You can see it on my fork:
https://github.com/joewoodhouse/phonegap-googlemaps-plugin/commit/d101641f4f182e4551e92712b15ccb56f2e26c20

Basically I add a gesture handler to the entire map view and track the last clicked position constantly. Then when the overlay click handler is called, I just use the last clicked position and send that with the event.

Might be a bit hacky but it works. Also I'm far from an iOS developer, so it may well have introduced a memory leak, or be very bad practice, no idea (let me know if you see anything!).

**Comment by Hirbod** [comment]
Thank you very much. Send me a PR, i will merge this @joewoodhouse

**Comment by alexislg2** [comment]
Great! Interested by that!
