### ISSUE TITLE
KML doesn't load on iOS

### ISSUE THREAD

**Issue by Renrell** [wf9a5m75/phonegap-googlemaps-plugin#542]
Hi,

I'm having trouble with loading KML files on iOS. That's works perfectly on android, but on iOS, if i load only one KML file, there is the "Please wait...' loader appearing and disappearing but no KML showed on the map, and when i try to load more than one KML file, there is an infinite loader.

I tried to create a new project, but i got the same problem.
Here is my log:
2015-06-15 16:27:49.264 preventionIncendieIos[333:26027] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/9078B2AC-756E-4467-A978-C9F585F91634/Library/Cookies/Cookies.binarycookies
2015-06-15 16:27:49.406 preventionIncendieIos[333:26027] Apache Cordova native platform version 3.8.0 is starting.
2015-06-15 16:27:49.409 preventionIncendieIos[333:26027] Multi-tasking -> Device: YES, App: YES
2015-06-15 16:27:49.426 preventionIncendieIos[333:26027] Unlimited access to network resources
2015-06-15 16:27:49.685 preventionIncendieIos[333:26027] [CDVTimer][keyboard] 0.513017ms
2015-06-15 16:27:49.761 preventionIncendieIos[333:26027] [CDVTimer][file] 74.562967ms
2015-06-15 16:27:49.762 preventionIncendieIos[333:26027] [CDVTimer][TotalPluginStartup] 77.108026ms
2015-06-15 16:27:50.490 preventionIncendieIos[333:26027] Resetting plugins due to page load.
2015-06-15 16:27:51.987 preventionIncendieIos[333:26027] Finished load of: file:///private/var/mobile/Containers/Bundle/Application/A1A2DE01-6683-49E2-A5D7-486D2AE7D019/preventionIncendieIos.app/www/index.html#/tab/dash
2015-06-15 16:27:53.231 preventionIncendieIos[333:26027] This app uses phonegap-googlemaps-plugin version 1.2.5
2015-06-15 16:27:55.211 preventionIncendieIos[333:26027] THREAD WARNING: ['GoogleMaps'] took '24.461182' ms. Plugin should use a background thread.

**Comment by masashiGMS** [comment]
I suggest you should provide your KML file for other people to help you.

**Comment by Renrell** [comment]
Here is one of my KML files (but this is working as well on Android): 

<?xml version="1.0" encoding="utf-8" ?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document><Folder><name>massif_2A_12</name>
<Schema name="massifs_2A_12" id="massifs_2A_12">
	<SimpleField name="Name" type="string"></SimpleField>
	<SimpleField name="Description" type="string"></SimpleField>
</Schema>
  <Placemark>
      <Polygon><outerBoundaryIs><LinearRing><coordinates>8.897764375218925,42.060555901532638 8.88665908902378,42.061445291305411 8.88643317738223,42.063597771234875 8.887858388917488,42.06636974180779 8.889703038922219,42.067691302411895 8.891023550321314,42.068147583038119 8.895466945606763,42.071280212212812 8.896569528955439,42.072327355082898 8.899243957650482,42.072064990571363 8.900959499967296,42.071543429715454 8.90204069264021,42.072382897904781 8.903722446614708,42.07282010504256 8.904934670624886,42.073535964462813 8.906660407700596,42.073807253982913 8.907698875530612,42.073538717856451 8.909735429406199,42.074000071621796 8.911242985501485,42.074871170938927 8.912519659345728,42.074796869449145 8.9138627593767,42.074774069909289 8.91486710261519,42.074869839569395 8.915487712778395,42.075367020419257 8.916625987874914,42.075355981526172 8.918911932806847,42.075540413194489 8.920891561954194,42.076744831793285 8.923697914770903,42.077856084241759 8.926118110423184,42.080624826249377 8.928486300945293,42.081598779281826 8.929317679760439,42.082715724261362 8.9312363785446,42.083445067319559 8.933765087456028,42.085845885186629 8.935911662068479,42.08609159953108 8.937757312282949,42.085298643043018 8.938854572983606,42.08560575368903 8.939620424685238,42.086194413516068 8.94122440735643,42.086580263187798 8.942181586145354,42.087636301729979 8.943702868568392,42.087917984455132 8.944477821449656,42.089191645468993 8.946298729360994,42.089564876934077 8.948780624957614,42.089530328894831 8.952119878142719,42.091558128041576 8.954439289871278,42.092055938468086 8.956503714025706,42.092786277274456 8.957064347897775,42.095597810197681 8.956563224480965,42.096837237296228 8.956982841001594,42.098193878518565 8.955913736309439,42.100847992454007 8.957475412777951,42.100812069016882 8.95917430308185,42.100127253092218 8.96010727591031,42.100234807731887 8.961957483382744,42.099495658321068 8.966440696027707,42.100979271499057 8.970654480329122,42.102531900007456 8.971914242370923,42.102405283026584 8.973819590136229,42.102881213144798 8.975226413271441,42.104171611951244 8.976175643312368,42.104433405379105 8.977492247368186,42.106109295689315 8.977889172051794,42.108515183428516 8.979487046688439,42.1095328900319 8.98049730185507,42.111063155483087 8.982490552222327,42.111688316709532 8.986913707110642,42.113969155540381 8.992533435616625,42.113424567128824 8.996564587841592,42.113930905794994 8.99811501887282,42.113796024837235 9.000014659054266,42.112945373586321 9.002102828495911,42.11319329825853 9.003357583029564,42.112903278140898 9.005935583998921,42.104309111464381 9.010760712596724,42.100379287775574 9.006901103191728,42.094463627333234 9.006995434667305,42.087756716664003 8.997221612692821,42.083115769790645 8.997353288020749,42.075350689027438 8.991603159320004,42.072425431557086 8.98011969697102,42.075739096508421 8.974569894534422,42.074824182432231 8.966732024406959,42.07358999062626 8.963741194465696,42.067929876258084 8.954933726892783,42.067852674740855 8.945271907829749,42.071201926360118 8.939238088889978,42.070990830941774 8.933564686413064,42.066316002924758 8.924608119095494,42.065143581347563 8.919803772601089,42.064859750950951 8.912737770115497,42.058295958588815 8.901610165509142,42.059197043524456 8.897764375218925,42.060555901532638</coordinates></LinearRing></outerBoundaryIs></Polygon>
  </Placemark>
</Folder></Document></kml>

**Comment by bluezeus** [comment]
I too have the same problem . Any news ?

**Comment by Hirbod** [comment]
Do you load from remote? Or cdv / www / files ?

**Comment by bluezeus** [comment]
I have KML file in local project folder.

**Comment by Renrell** [comment]
I still have this problem, and i load from the local project folder as for android version. I also tried to load from distant url, didn't work too. Any help could be appreciated.

**Comment by egmobile** [comment]
Hi, I have the same problem (I load from local folder), did you find a solution? Thanks in advance.
