### ISSUE TITLE
map does not replace div content with OnsenUI

### ISSUE THREAD

**Issue by pawlee** [wf9a5m75/phonegap-googlemaps-plugin#544]
This is the html

        <ons-template id="view.html">
            <ons-page id="view">
                <ons-toolbar>
                    <div class="left">
                        <ons-toolbar-button onclick="menu.toggleMenu()"><ons-icon icon="ion-navicon" style="font-size: 32px; width: 1em;"></ons-icon></ons-toolbar-button>
                    </div>
                    <div class="center">Event View</div>
                </ons-toolbar>

                <div id="info"></div>
                <div id="mapCanvas">MAP PLACEHOLDER</div>

            </ons-page>
        </ons-template>

and javascript

    /**
     * Init the view
     */
    initView: function() {

        var mapDiv = document.getElementById("mapCanvas");
        app.map = plugin.google.maps.Map.getMap(mapDiv);
        //alert(app.stringifyObject(app.map));

        var info = document.getElementById("info");
        info.innerHTML = "works";

    },

The info div is altered as expected to "works", but nothing happens with the mapCanvas div, it remains "MAP PLACEHOLDER".

Oh and the alert() below getMap() does indeed print a seemingly correct object.

Any ideas?

Regards,
Paul

**Comment by aspacardin** [comment]
Why should anything happen to the map div, you're not doing any action on it?

**Comment by pawlee** [comment]
Am I not?

app.map = plugin.google.maps.Map.getMap(mapDiv);

Pretty sure that function does.

**Comment by Luukschoen** [comment]
Have you tried the setDiv function?

**Comment by pawlee** [comment]
Haven't been coding the past few weeks. Just tried the setDiv and same thing there. Has anyone else managed to get their map working in onsen.oi?

Maybe I wasn't clear before, the problem is to get it working with onsen.oi. Has anyone managed to get it working inside a onsen-page? It works fine if I don't use onsen.
