### ISSUE TITLE
blank Map

### ISSUE THREAD

**Issue by omaisali** [wf9a5m75/phonegap-googlemaps-plugin#545]
Hi,

I am just trying to use your plugin for android google map.

I create one test app in phonegap with one page, and its working fine.
But my other app have blank Map.

i checked almost everything ,

debug keystore, ( I create the SHA1 from same computer which i used to create for working map in first app)

Google map v2 Enabled.

same index.html code.

what could be reason? any help
I checked your all TroubleShooting
steps. but no luck﻿

**Comment by aspacardin** [comment]
If you're able to see the Google logo on the blank map, the problem is with the keystore. If not, you're probably not setting correctly the height/width of the map container, or there's something above the map. Can't you debug with Chrome?

**Comment by omaisali** [comment]
Yes i am able to see Google logo with blank map. 

I have used same debug.keystore for other app which have working map.

**Comment by aspacardin** [comment]
Then maybe you've got the wrong package id. Can you check in config.xml that the <widget id="XXX"> has the same XXX as the one you input in google apis?

**Comment by omaisali** [comment]
Yes it is same package id, i have confirmed again. But map is blank

**Comment by omaisali** [comment]
the app with working map have map on first index page. 
the app with blank map have map on 4th page. user need to navigate from 3 pages to reach 4th map page.

Does this makes any difference?

**Comment by aspacardin** [comment]
I'm no expert, but in my case, if I was able to see the google logo, the problem was with the keystore, and if the map was not on right page I wasn't able to see the google logo.

**Comment by omaisali** [comment]
yes possibly keystore problem because i can see the google logo. But dont know what to try for keystore.

**Comment by omaisali** [comment]
In mainifest of android when i build the project. this line was getting add automatically in the mainfest file. 

<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="YOUR_ANDROID_API_KEY_IS_HERE" />

i try to enter my Key but again when i build the project this line get replace with "YOUR_ANDROID_API_KEY_IS_HERE"

So i add meta-data tag two times with my key. 
one before and one after this. so now its not adding the line again. 
like this. 

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="AIza------------------------------------------k0" />
        <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="YOUR_ANDROID_API_KEY_IS_HERE" />
        <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="AIza------------------------------------------k0" />


And now map is working fine.

**Comment by Luukschoen** [comment]
This issue is resolved. Can it be closed?
