### ISSUE TITLE
searchBox autocompete places 

### ISSUE THREAD

**Issue by omaisali** [wf9a5m75/phonegap-googlemaps-plugin#546]
Hi, 

I am using this plugin for map . Map is working fine but how i can use SearchBox autocomplete places in this map ?

**Comment by masashiGMS** [comment]
Not available yet.

**Comment by sam-lex** [comment]
Hi, I was wondering if someone succeeded in using the Places SearchBox autocomplete with this plugin, I'd really like to see your code sample...

I have a strong feeling that this line should be changed...
`autocomplete.bindTo( 'bounds', $scope.map );`

I've checked the html input, css, etc.. but I still can't get the autocomplete (dropdown) to work, any ideas?

**Comment by Hirbod** [comment]
The native places widget isn't implemented yet, maybe soon

**Comment by walfridosp** [comment]
+1
