### ISSUE TITLE
Error form tutorial

### ISSUE THREAD

**Issue by piernik** [wf9a5m75/phonegap-googlemaps-plugin#555]
I've tried to complete this tutorial https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-(Android) and got error:

`Execution failed for task ':compileArmv7DebugJava'.`

I tried cordova 5.1.1 and 5.0.0
I'm on windows 8.1

**Comment by Honry** [comment]
@piernik, could you please provide more error info?

**Comment by piernik** [comment]
Sadly no - I'm not there anymore.
Now I'm using this https://github.com/cosmith/phonegap-googlemaps-plugin version of plugin and it works great.
BTW someone could update official version because fragmentation is very confusing:/

**Comment by Honry** [comment]
I guess you meet the problem of https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/512

**Comment by piernik** [comment]
No I was using and still am cordova 5.1.1 Simply have to use different  google maps version. Sadly it's not official

**Comment by Honry** [comment]
I am also looking forward to an official one for cordova 5.1.1.  :disappointed:
