### ISSUE TITLE
click on marker crash app ios 6

### ISSUE THREAD

**Issue by Menusito** [wf9a5m75/phonegap-googlemaps-plugin#556]
when I use the following code and click over the marker the app crash:

iOS 6
Phonegap Build
cli-5.1.1 (3.8.0 iOS)

			map.on(plugin.google.maps.event.MAP_READY,function(){
				map.addEventListener(plugin.google.maps.event.MAP_CLICK, function(latLng){
					map.addMarker({
						"position": latLng,
						"title": "The map was clicked at "
					});
				});
			});

**Comment by Hirbod** [comment]
iOS 6 will not be updated anymore
