### ISSUE TITLE
I can't get any events working for phone gap on iOS

### ISSUE THREAD

**Issue by brandonday** [wf9a5m75/phonegap-googlemaps-plugin#558]
I've tried MAP_READY and other events. None seem to work. What am I doing wrong? Is there a bug?

var mapDiv = document.getElementById("map_canvas");
  const GOOGLE = new window.plugin.google.maps.LatLng(late,long); /* latt and longg variables contain the latitude and longitude */
  var map = window.plugin.google.maps.Map.getMap(mapDiv, {
    'camera': {
      'latLng': GOOGLE,
      'zoom': 17
    }
  });
map.addEventListener(window.plugin.google.maps.event.MAP_READY, function() {

    map.addMarker({
      'position': GOOGLE,
      'title': "Hello GoogleMap for Cordova!"
    }, function(marker) {

      marker.showInfoWindow();

    });

  });

**Comment by Luukschoen** [comment]
const GOOGLE = new window.plugin.google.maps.LatLng(late,long); /* latt and longg variables contain the latitude and longitude */

i should change it to lat,long for starters. Maybe the typo causes your problems.

**Comment by brandonday** [comment]
Sorry, the typos actually aren't exactly what my issues are. I see the map. There is no problem loading the map but I'm having difficulty with events. For example:


var map;
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

    function onMapReady() {
      alert("Event fired");
    }


When this code is executed, the map loads but I get no alert message. The same goes for the CHANGE_CAMERA event. Ultimately, I would like to be able to determine when the map is being moved like a dragend event. I haven't been successful so far. I would appreciate your help very much. Thank you.

**Comment by brandonday** [comment]
Also, I'm using appgyver supersonic

**Comment by Hirbod** [comment]
Aggpyver isn't supported directly. You could try 
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/443

@bFlood has knowledge, maybe he can help you!
