### ISSUE TITLE
Adding HTML inside an InfoWindow

### ISSUE THREAD

**Issue by jvence** [wf9a5m75/phonegap-googlemaps-plugin#560]
Is it possible to add HTML (image and an anchor) inside a Marker's InfoWindow?

**Comment by leandroz** [comment]
Is not posible!

**Comment by jvence** [comment]
Look at your screenshot: https://camo.githubusercontent.com/ee2658fe6364bd3d45642bfaab441124cf935d5e/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f304231454366715443634c45384c557855576d6873516d67785656552f6d61726b6572352e676966 it has an image and formatted text inside an InfoWindow

**Comment by Slavrix** [comment]
The example Image you have linked there is done using html5's Canvas.

The demo code below comes straight from the docs regarding markers.

var icon = "data:image/png;base64,iVBORw0KGgo...CC";
var canvas = document.createElement('canvas');
canvas.width = 120;
canvas.height = 40;
var context = canvas.getContext('2d');

var img = new Image();
img.src = "./images/google_logo.gif";
img.onload = function() {
  context.drawImage(img, 0, 0);

  context.font = '15pt Calibri';
  context.fillStyle = 'blue';
  context.fillText('Google', 40, 15);
  context.fillText('Tokyo!', 60, 35);

  map.addMarker({
    'position': latLng,
    'title': canvas.toDataURL(),
    'icon': icon
  }, function(marker) {
    marker.showInfoWindow();
  });
};
map.addMarker({
  'position': latLng,
  'title': canvas.toDataURL(),
  'icon': icon
}, function(marker) {
  marker.showInfoWindow();
});
