### ISSUE TITLE
WebView is pushed up on input focus

### ISSUE THREAD

**Issue by leandroz** [wf9a5m75/phonegap-googlemaps-plugin#561]
I have the scroll disabled and I am handling the scroll manually when the keyboard is opened. For some reason is not working with the plugin, it was working before so I have no idea what changed.
When you focus an input, the web view is pushed up, but not the size of the keyboard, an image is better to explain.

![scrollproblem](https://cloud.githubusercontent.com/assets/4624850/8560785/10dce7a6-255f-11e5-8deb-496d0dd574eb.gif)

So for testing I removed the plugin, and it started working again. I add the plugin and the problem appears again.
I was using Niper version with the changes for Cordova Android 4.x but now I just installed from master and is the same.
Right now I am looking into the code to check where this is happening.

**Comment by leandro-shifteight** [comment]
With some help I got into a solution, commenting https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/src/ios/GoogleMaps/GoogleMaps.m#L30

But probably that will make something else to not work. Testing.

**Comment by leandroz** [comment]
Don't close the issue, is not resolved yet, because commenting a line is not a solution, there is something that is moving the webview.

**Comment by Hirbod** [comment]
this i

**Comment by Hirbod** [comment]
This should not be related to this plugin. Normally, every input will push up the webview. You should use a third-party keyboard plugin (like ionic-keyboard) and use its "disableScroll(true)" function.
https://github.com/driftyco/ionic-plugin-keyboard

**Comment by leandroz** [comment]
@Hirbod actually don't. This plugin takes control of the scroll behaviour, Line 30 of GoogleMaps.m ````self.webView.scrollView.delegate = self;````. 
I am using ionic keyboard plugin and I have the scroll disabled, but somehow that config is bypassed by the delegate. When you don't have the scroll disabled, the web view is pushed up the height of the keyboard, but here something else is happening, see that how much is pushed depends on where is the input.
But if it's happening only to me... I solved this commenting that line and the rest is still working properly.

**Comment by Hirbod** [comment]
I'll investigate further into this, as it could be related to some kind of bug I've faced before.
