### ISSUE TITLE
Why does plugin add style class "_gmaps_cdv_" to all DOM elements

### ISSUE THREAD

**Issue by jvence** [wf9a5m75/phonegap-googlemaps-plugin#562]
After a map is loaded, I noticed that all DOM elements are assigned style class "_gmaps_cdv_". Why is this?

**Comment by Hirbod** [comment]
This plugin watch and change all the DOM-Nodes for movement / content-placing over the map. It's required to remove transparency, once the map is removed. You can ignore this.

**Comment by ArturoGallegos** [comment]
This class can not be ignored, its a problem when you have background in your elements. for example I have a DIV element with id #app and background # 036 when the map loaded, this add _gmaps_cdv_ for several elements and apply background transparent, if I tried to force the background of my element the map is not showed.

**Comment by wf9a5m75** [comment]
Then you should not use this plugin.

**Comment by ArturoGallegos** [comment]
Yes, I have disabled the map for this section but I think there must be another solution

**Comment by wf9a5m75** [comment]
If you find a solution, please send a PR
