### ISSUE TITLE
Cordova 5 support for Android [$15]

### ISSUE THREAD

**Issue by alexislg2** [wf9a5m75/phonegap-googlemaps-plugin#563]
Hey,
I have spent hours trying to make the cordova 5 pull request work.
I tried with this one
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/516
and this one
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/528

Both give me same compilation errors (see my comments in this PR)

Cordova 5 is much better for handling depencies with npm

So I'm waiting for a working version compatible with Cordova 5 and I'm giving a bounty for this

**Comment by lalop** [comment]
Is that means this plugin doesn't work with cordova 5 for android ?

**Comment by alexislg2** [comment]
Indeed. There is a PR that is supposed to support Cordova 5 but is not
working for me (build fails)

**Comment by cvaliere** [comment]
Check this fork, it works for me with Cordova 5 : https://github.com/Nipher/phonegap-googlemaps-plugin

**Comment by Hirbod** [comment]
Tried that. It does not work

**Comment by cvaliere** [comment]
Well, it works at least for me.
Note that it requires Google Play Services v23 (cloned from here : https://github.com/wf9a5m75/google-play-services.git#v23)

**Comment by alexislg2** [comment]
This is PR https://github.com/wf9a5m75/phonegap-googlemaps-plugin/pull/528 I already tried

I know it is working with some people. Question is: why it doesn't work with some other people?

I tried with Google Play Services v23

**Comment by cvaliere** [comment]
Do you try with Crosswalk ?
If so, you have also to modify the cordova-plugin-crosswalk-webview like this :
1) Add webView.setZOrderOnTop(true); in XWalkWebViewEngine.initWebViewSettings()
2) Add XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, false); in XWalkCordovaView.setGlobalPrefs() and remove XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, true);

(inspired from this tutorial : https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-(Android)#5-change-the-androidmanifestxml-mainactivityjava-and-xwalkwebviewenginejava)

**Comment by cvaliere** [comment]
I've checked your stacktrace: src/plugin/google/maps/GoogleMaps.java:138: error: cannot find symbol
    root = (ViewGroup) webView.getParent();

If you look at Nipher's version, it precisely fixes this error
The line 138 is replaced by root = (ViewGroup) webView**.getView()**.getParent();

So, logically, you **can't** have the stacktrace you have with Nipher's version.

Anyway, now I use this fork : https://github.com/dubcanada/phonegap-googlemaps-plugin

(which is the Nipher's version + 1 commit to fix base 64 icons on Android)

Note : I don't know how this bounty thing works, but if it finally works for you, I don't want the bounty at all, I didn't code anything. It's just that I've spent more than 100 hours to install this plugin and make it work with Crosswalk, so I feel that I can help others :)

**Comment by Hirbod** [comment]
I've spent 20 hours to get cordova 5 working. I will investigate again later.

**Comment by alexislg2** [comment]
OK thanks for your help.

Concerning the stack trace that shows `root = (ViewGroup) webView.getParent();` at L138 it is because I used the Phenome fork: https://github.com/Phenome/phonegap-googlemaps-plugin/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L138

But then I tried with Nipher's fork and it worked **but be careful to download the master branch and not the release called `cordova5.0.0` because there was 1 commit after this release**

So solution was:

1. Don't forget to use Google Play Services v23
1. Use Nipher fork **and use master branch**: `cordova plugin add https://github.com/Nipher/phonegap-googlemaps-plugin.git`

Concerning the bounty would you mind if I give it to @wf9a5m75 ? I think he deserves it

**Comment by cvaliere** [comment]
Happy that it works for you :)
Of course for the bounty, as I said, I didn't do anything :)

**Comment by alexislg2** [comment]
OK @wf9a5m75 you have to claim the bounty so that I can give it to you

Thank you @cvaliere you didn't do anything but that solved my issue ;)

**Comment by Hirbod** [comment]
v.1.2.8 is out and works for Cordova 5+ and Android-Cordova 4.x+
It fixes many other problems and has some new features. The forks outside are tested and unstable and should not be used.
