### ISSUE TITLE
blank map 

### ISSUE THREAD

**Issue by kaesebaellchen** [wf9a5m75/phonegap-googlemaps-plugin#564]
I know this issue came up several times,.. but none of the solutions worked for me.

I followed the tutorial, got my sha1 key, got my api key and replaced the index.html with the code from the linux / osx tutorial.

i downgraded cordova to 4.3.1, still no luck

i removed my fingerprint from the console, so that google allows any application,.. but still i get a blank map.

since it still doesnt work while allowing any application, i think my keychain does not invole in this problem
the problem also occurs in the ios simulator (ios 6)

my setup:
OSX 10.10.3
java version "1.6.0_65"
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
npm 2.11.2
node v0.12.6
cordova 4.3.1
android:
sdk 22-19
sdk-tools 24.3.3.
sdk platform-tools 22
sdk build tools 22 - 19
android support repo 15
android support lib 22.2
google play services 25

my devices: 
S3 mini with android 4.4.4
galaxy note 2014 LTE with android 4.4.2

Thank you alot in advance!

**Comment by Hirbod** [comment]
Pleas read the wiki!
