### ISSUE TITLE
possibility of native map coordinates manual change 

### ISSUE THREAD

**Issue by acidmk** [wf9a5m75/phonegap-googlemaps-plugin#565]
Recently I've added scaling for cordova webView. But native map seems to be recognizing only unscaled div containers screen coordinates. Is there a possibility or hint where to put some code to enforce map border coordinates to fixed position like "plugin.google.map.setTop(nTop) etc."? Hope for tips :)

**Comment by Hirbod** [comment]
Sorry, there is not such a function.
