### ISSUE TITLE
Anyone known how to replace play-services plugin with the framework syntax ?

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#566]
Hello,

I want to use another plugin that also require google play service framework and this make a conflicts ( because the other plugin require the version 25 )

The new syntax of dependencies have switched from : 
````
        <dependency id="com.google.playservices" url="https://github.com/wf9a5m75/google-play-services#v23" />
````
to : 
````
       <framework src="com.google.android.gms:play-services-maps:+" />
````

If I remove theses lines, and remove dependencies in the plugins/*.json files, I can now remove the  plugin com.google.playservices, it's build sucessfully but the object Javascript of the plugin is not created.

Any ideas will be appreciated :)

EDIT:

I also tried to upgrade manually the play-services plugin, but this doesn't seems to help

**Comment by jscuba** [comment]
I hit the same issue with cordova-background-geolocation. Thanks for sorting it out with christocracy. I created a pull request to get the change into phonegap-googlemaps-plugin.

**Comment by lakano** [comment]
Yep, for interested people, I have add a fork from Nipher and made the change :
https://github.com/lakano/phonegap-googlemaps-plugin
