### ISSUE TITLE
OVERLAY_CLICK problem with iOS

### ISSUE THREAD

**Issue by Renrell** [wf9a5m75/phonegap-googlemaps-plugin#569]
Hi,

I'm having troubles with the OVERLAY_CLICK event, seems he's not working on iOS.
There is my code : http://pastebin.com/Cs3TvyJw

Can someone help me please ?

EDIT: Just want to add, OVERLAY_CLICK is working with addCircle, addPolygon... but not with addKml.

**Comment by Hirbod** [comment]
try to pass your click function directly as a function

```js
{
...
...
click: function(){
  this.doSomething..
} 
}, function(kmlayer)...
```

**Comment by Hirbod** [comment]
Also, try this please: #541

there seem to be a workaround for your problem.
