### ISSUE TITLE
How to give priority for a marker to be visible when two markers appear at same location? 

### ISSUE THREAD

**Issue by ramsabarish** [wf9a5m75/phonegap-googlemaps-plugin#570]
There are two markers located close to each other and they overlap. But one of the marker is important and it needs to be shown all the times.

**Comment by Hirbod** [comment]
There is no solution for this right now. There are some solutions on JS-Side (like spider-clustering) but currently this can't be done with this plugin.

**Comment by giladrom** [comment]
Reopening this - it's been 5 years. Is this possible now?

**Comment by wf9a5m75** [comment]
`markerOptions.zIndex`
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/addMarker/README.md
