### ISSUE TITLE
Cordova compatibility

### ISSUE THREAD

**Issue by fcavola** [wf9a5m75/phonegap-googlemaps-plugin#573]
Hi,
is the plugin compatible with version of cordova > 4?
If not is the support in roadmap?
Thank you in advance.
Francesco

**Comment by craig-at-rsg** [comment]
Here's another issue with a lot of detail - it looks like some people have gotten it to work, but general support isn't there yet:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/512

**Comment by Juelcf** [comment]
Hi all,

I found a solution that worked for me to build with cordova 5.1.1

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/576
