### ISSUE TITLE
Can anyone help with the events not firing when using this plugin with appgyver?

### ISSUE THREAD

**Issue by brandonday** [wf9a5m75/phonegap-googlemaps-plugin#574]
So far, I've been using bflood's way of adding the plugin to my appgyver project however I've been stuck for weeks on trying to get events to fire. MAP_READY does not work. Neither do any of the other events.

This is code I'm using:

document.addEventListener("deviceready", function() {
  // Define a div tag with id="map_canvas"
  var mapDiv = document.getElementById("map_canvas");

  // Initialize the map plugin
  var map = plugin.google.maps.Map.getMap(mapDiv);

  // You have to wait the MAP_READY event.
  map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

function onMapReady () {
alert("yay I finally work");
}

});

This is the way I get the plugin to work. The map loads but no events get fired.

[
  {"source":"https://github.com/wf9a5m75/googlemaps-ios-sdk-for-phonegap"},
  {"source":"https://github.com/bFlood/phonegap-googlemaps-plugin#appgyver_bf","variables":{"API_KEY_FOR_IOS":"..."}},
  {"source":"https://github.com/wf9a5m75/phonegap-http-request#app_gyver"}
]

**Comment by Hirbod** [comment]
Please have a look here:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/443

and maybe you could ask for help @bFlood

He's the only one with appgyver knowledge
