### ISSUE TITLE
Google Maps Android API v2 is not available

### ISSUE THREAD

**Issue by mjaverto** [wf9a5m75/phonegap-googlemaps-plugin#581]
The latest releases > 1.2.4 seems to not work for me any longer on older Android devices like 4.4.4 or 4.4.2 and I get the following message:

Google Maps Android API v2 is not available, because this device does not have Google Play Service

I think this is related to https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/564

and I have the same issues with Cordova 4.3.1 or 5.1.1.

The APK runs fine on Android 5+.

Any ideas?

I tried older releases but there seems to have been bugs in those that we need the newer releases for.

**Comment by Hirbod** [comment]
This plugin works well on older devices. I've installed it on 4.4.2 and it works as expected!

**Comment by mjaverto** [comment]
@Hirbod do you have any information on what release # you are using along with what Cordova version to do that?

**Comment by mjaverto** [comment]
@Hirbod It worked well for us also on older devices until the last 2 months also until releases > 1.2.4.

**Comment by Hirbod** [comment]
There are some reports for 4.1.
Currently, the most of us integrated Crosswalk in Combination with this plugin. Maybe this is the reason it works for us and not for you.

I'm afraid to tell you, that the main developer of this plugin is unreachable currently. He don't even response to my mails. I'm more familiar with iOS, but without any crash reports, logs etc, there is really no chance that anybody can help you. If you provide more informations, I'll reopen this one.

**Comment by Distopico** [comment]
Same error in android 4.3.x and cordova 5.0.0
