### ISSUE TITLE
Can't compile project after adding plug-in

### ISSUE THREAD

**Issue by drabb1956** [wf9a5m75/phonegap-googlemaps-plugin#585]
I'm trying to add this plugin to a Cordova project in VS2015.  The project compiles and runs fine before adding this plug-in.  However, after adding the plug-in, the build fails:

1>
1>  BUILD FAILED
1>
1>  Total time: 23.178 secs
1>  Command finished with error code 1: cmd /s /c ""C:\Projects\AZT Mobile\AZT Mobile\platforms\android\cordova\build.bat" --debug "--buildConfig=C:\Projects\AZT Mobile\AZT Mobile\build.json""
1>ERROR building one of the platforms : error : cmd: Command failed with exit code 1
1>  You may not have the required environment or OS to build this project
1>MDAVSCLI : error : cmd: Command failed with exit code 1

**Comment by ayman-alkom** [comment]
Hi @drabb1956 
try to change the app folder location to be short, like d:\app_folder, this solved my problem
because windows dosn't support link longer than 255 char I think
