### ISSUE TITLE
Map not showing after setDiv Cordova 5

### ISSUE THREAD

**Issue by Jerome2606** [wf9a5m75/phonegap-googlemaps-plugin#587]
Hi,

I use AngularJs and Ionic and this plugin.
Versions:
```
cordova 5.1.1
ionic 1.6.3
cordova-android 4.0.2
use the plugin from https://github.com/dubcanada/phonegap-googlemaps-plugin (compatible cordova 5)
```

In the debug console:
If I access on window.plugin.google.maps.Map.get('div') it gives me the right div but I see nothing on my Android device (not a problem of API Key because it was working before I update to cordova 5.1.1). Not event the zoom buttons. A blank content

If I use the console to set the div
```
window.plugin.google.maps.Map.setDiv(document.querySelector('.....Chemin CSS Path))
```
the map is well displayed.
So It seems that it is link to an async method and I call setDiv before all is ready.

Remarks: the map is not display on the home page but on another view. And I use new window.plugin.google.maps.LatLng on the home page with success

here's my directive angular to display map:
```
.directive('map', ['$window', function ($window) {
    return {
        restrict: 'E',
        scope: {
            onCreate: '&'
        },
        link: function ($scope, $element) {
            function initialize() {
                //console.log('initialize');
                var mapOptions = {
                    camera: {
                        latLng: new $window.plugin.google.maps.LatLng(52.796875, 4.757007),
                        zoom: 16
                    },
                    mapType: $window.plugin.google.maps.MapTypeId.ROADMAP
                };

                var map = $window.plugin.google.maps.Map.getMap(mapOptions);
                map.setDiv($element[0]);
                //window.plugin.google.maps.Map.setOptions(mapOptions);
                //window.plugin.google.maps.Map.setDiv($element[0]);

                map.addEventListener($window.plugin.google.maps.event.MAP_READY, function () {
                    $scope.onCreate({ map: map });
                });

                //        // Stop the side bar from dragging when mousedown/tapdown on the map
                //        google.maps.event.addDomListener($element[0], 'mousedown', function (e) {
                //          e.preventDefault();
                //          return false;
                //        });
            }

            if (document.readyState === 'complete') {
                initialize();
                //cordovaReady(initialize);
            } else {
                //console.log('ready state is not complete');
            }
        }
    };
}])
```

I added the event MAP_READY in a second time but with old versions of cordova and plugin 1.2.4 everything worked fine.

My device is on Lollipop and I don't see any error on adb logcat, maybe this line but I don't know if it is linked:
```
E/GoogleTagManager(13270): Invalid macro: _gtm.loadEventEnabled
```

Thanks for your help

**Comment by obetomuniz** [comment]
@Jerome2606 Try this https://github.com/obetomuniz/ionic-gmaps

**Comment by johnrobertcobbold** [comment]
Hi @Jerome2606 

Interesting timing, I have been stuck on a similar issue for the past one hour and your post indirectly helped me when manually `window.plugin.google.maps.Map.setDiv`in the console also did display the map when I was facing a white canvas.

In my case, the `div` element I was passing to plugin.google.maps.Map.getMap wasn't valid.
Quickly looking at your code, double-check that `$element[0]` in `map.setDiv($element[0]);` is a valid element ? Maybe try replacing it with a hard-coded `document.getElementById( ... )` ?

**Comment by Jerome2606** [comment]
@obetomuniz  thanks for the proposal but Nipher hasn't the most stable version for Cordova 5.x.x, use https://github.com/dubcanada/phonegap-googlemaps-plugin forks in place

@johnrobertcobbold my div is ok, I try with a document.getElementById(...) with same issue :(

in the console.log I have the right html element

**Comment by obetomuniz** [comment]
Wow!!! Thanks @Jerome2606! I'll update my demo then!

**Comment by Jerome2606** [comment]
I'm alone to have this issue ?

**Comment by johnrobertcobbold** [comment]
@Jerome2606 

+ check if all the elements in your HTML are set to transparent ?
I had another yet similar problem and realised that something was not quite right with my main ion-nav-view of my index.html file when on iOS (did not test with Android). Map would sometimes appear, sometimes not . Turns out that toggling its style.opacity to 0 then back to 1 once the map is loaded makes the map appear every time.

**Comment by Jerome2606** [comment]
I found !! ^^

I just need to set the div after the map is ready:

Old code:
```
var map = $window.plugin.google.maps.Map.getMap(mapOptions);
map.setDiv($element[0]);
map.addEventListener($window.plugin.google.maps.event.MAP_READY, function () {
      $scope.onCreate({ map: map });
});
```

New code:
```
var map = $window.plugin.google.maps.Map.getMap(mapOptions);
map.addEventListener($window.plugin.google.maps.event.MAP_READY, function () {
      map.setDiv($element[0]);
      $scope.onCreate({ map: map });
});
```

**Comment by kamakshi417** [comment]
dragstart and dragend available in this plugin

**Comment by kamakshi417** [comment]
can we set position to map..
