### ISSUE TITLE
Showing map in first plan with jquerry mobile 

### ISSUE THREAD

**Issue by zaouifahd** [wf9a5m75/phonegap-googlemaps-plugin#589]
Hi, 
after reading a lot of documentation, I would like to know if there is a person who has succeeded to display the map in 1st plan

I need of displaying the map in a div with the same result as if I use Z-index,

Does there's a one trick?

**Comment by celron** [comment]
I use this plugin pretty extensively with jquery and jquery mobile and it works pretty well on Android, iOS and Web.  I have no idea what you mean by first plan.
