### ISSUE TITLE
Cannot interact with overlay elements

### ISSUE THREAD

**Issue by jvence** [wf9a5m75/phonegap-googlemaps-plugin#590]
It seems that all interactions are ignored by map overlay div element and passed directly to the map. We dynamically generate an info window in an overlay. This window has a button. When it is clicked, the button never receives the click request and instead it is send directly to the map behind the overlay. 
We tested by placing various other HTML code in the overlay, but all interactions go directly to map behind it.

**Comment by jvence** [comment]
Seems like if a button is floated (float: right;) then they are not clickable when placed above the map. When removing the float, the button is clickable.

**Comment by johnrobertcobbold** [comment]
@jvence try `map.setDebuggable( true )` and you will see the clickable zones generated. I also had some issues when marking some divs absolute and with a 0 right margin.

**Comment by jvence** [comment]
@johnrobertcobbold definitely noticed the bug when having a div with an absolute margin so I should perhaps report it as a bug. Thanks for your feedback

**Comment by Hirbod** [comment]
you should use setClickable(false)
