### ISSUE TITLE
 more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by n00dl3** [wf9a5m75/phonegap-googlemaps-plugin#591]
Hi guys,
I'm building an application that uses this plugin and the [aerogear push plugin](https://github.com/aerogear/aerogear-cordova-push). The fact is aerogear requires `com.google.android.gms:play-services:6.1.11` whereas google maps plugin requires the version from [google-play-service](https://github.com/wf9a5m75/google-play-services) plugin. 

As the google-play-service plugin is deprecated, I tried using the recommended `<framework>` tag in `plugin.xml`, for the moment I'm trying with the 7.8.0 version, don't know if it will work with this version, but it's not important, for now I just want it to compile :-)...

So I have replaced  this:
````xml
<dependency id="com.google.playservices" url="https://github.com/wf9a5m75/google-play-services#v23" /> 
````
by this:
````xml
<framework src="com.google.android.gms:play-services-maps:7.8.0"/>
<framework src="com.google.android.gms:play-services-location:7.8.0"/>
````

However, when I run `cordova build` gradle complains :

>Error: more than one library with package name 'com.google.android.gms'

I have no idea how to handle this version conflict, any help would be appreciated....

**Comment by Hirbod** [comment]
Please ask on stack-overflow

**Comment by Hirbod** [comment]
Fixed in the master
