### ISSUE TITLE
Map moves on Marker dragstart instead of marker !

### ISSUE THREAD

**Issue by johnrobertcobbold** [wf9a5m75/phonegap-googlemaps-plugin#592]
I have no idea why this is happening... When I longpress on a marker which is draggable, the map shifts downwards instead of the marker "getting lifted in the air" ! Does anyone know why ?
I would actually ideally set 'raiseOnDrag' to false to have no animation at all but it seems that this property has no effect (it does not seem to be documented in the Google API but I found it when googling)

**Comment by Hirbod** [comment]
Could you provide a video?

**Comment by Hirbod** [comment]
wll reopen when you provided some more informations

**Comment by iBasit** [comment]
this is uber like feature, where map is moving, but marker is static  on middle of screen. I need to know this too please..
