### ISSUE TITLE
proguard configuration

### ISSUE THREAD

**Issue by craig-at-rsg** [wf9a5m75/phonegap-googlemaps-plugin#593]
Can someone share a proguard configuration that works for this project? My maps work fine until I try them in a release build, and from error messages it looks like obfuscation is the problem.

**Comment by craig-at-rsg** [comment]
Adding this seemed to do the trick for me (I also needed to handle the fact that the API keys are based on which keystore you use, and I had debug and release keystores):

-keep public class * extends plugin.google.maps.MyPlugin
-keepclassmembers public class plugin.google.maps.GoogleMaps {
  *;
}
-keepclassmembers public class * extends plugin.google.maps.MyPlugin {
  *;
}

**Comment by Alex-Sessler** [comment]
you are awesome! thanks for sharing!!
