### ISSUE TITLE
Can we add Geojson object with this plugin ?

### ISSUE THREAD

**Issue by eljazouli** [wf9a5m75/phonegap-googlemaps-plugin#594]
Hello everyone, thank you for making this plugin possible ! It really is the best way to add google maps to a cordova project. Now i'm using the angular-google-maps and i am thinking of migrating to this plugin but i need to know how easy is it to add a geojson object to a map ? If it's not possible out of the box, how difficult it is to add it manually (not by forking the plugin and adding native code but doing it throught the Javascript using arrays of markers for example..) 

Thank you all !

**Comment by Hirbod** [comment]
You need to iterate with JS and use the methods from the API (map.addMarker()....)
There is no other way currently.

**Comment by eljazouli** [comment]
I see.. thank you !
