### ISSUE TITLE
iOS 9 not working

### ISSUE THREAD

**Issue by huemans** [wf9a5m75/phonegap-googlemaps-plugin#596]
Hi love your plugin, thanks. We've been using it for a while but unfortunately after beginning to use ios9 its stopped working. Is there a plan to support ios9, is there something we might be doing wrong?

best

**Comment by celron** [comment]
I'm using it on ios9 with my ipad and it's working fine, I haven't seen anything that doesn't work, yet.  The map appears, markers, drawing shapes, etc.  I don't think there is anything particular that they have to get it to work on ios9.  I'm using 9.0 (13A4325c)

**Comment by Hirbod** [comment]
Also can't confirm. Works with iOS9
