### ISSUE TITLE
Ionic View support

### ISSUE THREAD

**Issue by drewwells** [wf9a5m75/phonegap-googlemaps-plugin#598]
I have this plugin working finally locally and via the emulator. However, I can't view google maps via the Ionic View app. This is probably because Ionic View is its own package and Google is blocking calls from it. How do you authorize Ionic View for your google maps API key?

**Comment by Hirbod** [comment]
I'm sorry but there is no support for Ionic View currently and in the near future.

**Comment by drewwells** [comment]
Ionic View does not support this plugin

`At the moment, plugin access is restricted to a specific subset of plugins, including GeoLocation, Keyboard, StatusBar, and BarcodeScanner`

More info here: http://blog.ionic.io/view-app-is-alive/
