### ISSUE TITLE
iOS: CDVPlugin class GoogleMaps (pluginName: GoogleMaps) does not exist. 

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#600]
Hello,

Thanks @Hirbod for your time to merge all forks fix inside the main project!

I've tested the 1.2.8 version yesterday, and this working fine under Android, but I have a problem under iOS:
```
CDVPlugin class GoogleMaps (pluginName: GoogleMaps) does not exist.
2015-09-03 10:12:02.722 My APP [587:427117] ERROR: Plugin 'GoogleMaps' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
-[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["GoogleMaps857375197","GoogleMaps","getMap",[{"gestures":{"zoom":true,"tilt":true,"rotate":true,"scroll":true},"backgroundColor":[0,0,0,0],"controls":{"zoom":false,"compass":true,"myLocationButton":true}}]]
```

Do you known why the plugin doesn't seems to works under iOS please?

Regards

EDIT: I also tried to remove the plugin ( and com.googlemaps.ios ) and to re-install, it's the same problem.

**Comment by Hirbod** [comment]
Hi @lakano 
This is an easy problem and a cordova bug. The Target Membership is not set.
Fast fix: remove iOS platform an re-add.

Manual fix:
Open Xcode-> Expand "Plugins" (right click on it) -> Choose "Sort by Type", mark ALL .m and .mm files (not .h) and on the right side, toggle "Target Membership" active.

Then, expand "Frameworks", check if all of them have active "Target Membership".

I made a video for this a while ago.
https://www.youtube.com/watch?v=gr0QrEShPbQ

**Comment by lakano** [comment]
This works!
Thanks a lot :-)

**Comment by Hirbod** [comment]
By the way, this fix is not just for this plugin, you can use it whenever you stuck with "CDVPlugin" not found. This bug should be fixed for ages by cordova but it seems not to be possible. Xcode just won't update removed and readded plugins like it should.

Glad I could help

**Comment by zaarheed** [comment]
@Hirbod what if the error is "Plugin 'map_0_985702201981' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml"?

I don't recognise what `map_0_985702201981` is, but it only occurs when I open the screen that contains the map created by `cordova-plugin-googlemaps`
