### ISSUE TITLE
Error on iOS version (1.2.8) No visible @interface for NSString declares the selector isNumeric'

### ISSUE THREAD

**Issue by arilsonkarmo** [wf9a5m75/phonegap-googlemaps-plugin#601]
Exception on line  386 - else if ([widthString isNumeric:widthString]) {
and line  409 - else if ([widthString isNumeric:widthString]) {

Someone forget to push something in last version ?

**Comment by Hirbod** [comment]
@arilsonkarmo sure that you have downloaded with tag #1.2.8 or did you download from master?

**Comment by Hirbod** [comment]
Just tested, version 1.2.8 (you need to explicitly add it with #1.2.8) works, where master is in development currently and does not work.

**Comment by arilsonkarmo** [comment]
Hi! im download from master.
my cordova plugin ls shows: 
plugin.google.maps 1.2.8 "phonegap-googlemaps-plugin"

**Comment by Hirbod** [comment]
Yes but this is wrong.

```bash
cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#1.2.8 --variable API_KEY_FOR_ANDROID="...." --variable API_KEY_FOR_IOS="..."
```

**Comment by arilsonkarmo** [comment]
Nice one! 
I think you have to put it in readme for new users.

Thank you!

**Comment by Hirbod** [comment]
Normally master is fine, but I merged some code two hours ago for the next 1.2.9 release but it was buggy

**Comment by arilsonkarmo** [comment]
Ok now we can put zIndex on markers?

**Comment by Hirbod** [comment]
no

**Comment by arilsonkarmo** [comment]
OK thanks! :)

**Comment by Hirbod** [comment]
The master is fixed, thanks for the info

**Comment by Hirbod** [comment]
@arilsonkarmo I will add zIndex for iOS only on version 1.3.3. Android has no zIndex Support
