### ISSUE TITLE
Can't install plugin. TypeError: Uh oh!

### ISSUE THREAD

**Issue by LucasNova** [wf9a5m75/phonegap-googlemaps-plugin#602]
Hi, i can't install plugin, look screenshot:
![googlemapserror](https://cloud.githubusercontent.com/assets/8263974/9681497/2f788424-5320-11e5-9a76-b675fbed64bb.jpg)

If i try install via alias plugin.google.maps, then installation done successful, screenshot:
![googlemapserror2](https://cloud.githubusercontent.com/assets/8263974/9681562/c77684d8-5320-11e5-8bc6-6c45bb9ec9bc.jpg)

But cordova throw error when i want build, screenshot:
![googlemapserror3](https://cloud.githubusercontent.com/assets/8263974/9681821/116c9c92-5323-11e5-948d-9c6087325455.jpg)

I have used the previous version a while back, but now this not work? How i can install this? Thx.

**Comment by arilsonkarmo** [comment]
Hi Lucas! you try to remove platform and add again ?

cordova platform rm android

cordova add platform add android

cordova build android

**Comment by xoxbet** [comment]
I have the same problem. When installed from cordova registry, cordova plugin list shows that I have 1.2.5. When installing from github repo, I get 
```Failed to install 'plugin.google.maps':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)```

**Comment by Hirbod** [comment]
I'll answer the last time to this kind of bugs.

1) Upgrade your Cordova: sudo npm -g install cordova
2) start with a clean project or do "cordova platform update android" (or update android@4.1.1)
3) remove old version and install master or 1.2.9 tag
4) build it

It will work fine.

**Comment by Hirbod** [comment]
By the way: seems like you're on windows. The uplift changes came from @wolf-s , maybe he can support you, as I don't have any windows environment

**Comment by xoxbet** [comment]
@Hirbod I have Cordova 4.3 which is supported by this plugin. I can't upgrade Cordova globally, because I have projects that does not work with Cordova 5. And I'm on linux. So this is not platform related, it's probably Cordova 4.3 and this plugin 1.2.9 problem.

**Comment by Hirbod** [comment]
1.2.9 does not work with old Cordova. Last supported version is 1.2.5. Grab it with #1.2.5
