### ISSUE TITLE
How to update version of google maps api ?

### ISSUE THREAD

**Issue by arilsonkarmo** [wf9a5m75/phonegap-googlemaps-plugin#603]
I have to add zIndex  on markers and i see in somewhere (http://stackoverflow.com/questions/9021159/how-do-i-set-the-z-index-of-a-marker-in-google-maps-api-v3)  in the version 3 of the google maps api have this property. How can I update the maps api version?

**Comment by Hirbod** [comment]
zIndex is for Google Maps JS Api, not the native SDKs

**Comment by arilsonkarmo** [comment]
And about marker cluster project? Any news?

**Comment by Hirbod** [comment]
Development was dropped and a refund will be paid to the users. I'm looking for some experts to start a new funding

**Comment by arilsonkarmo** [comment]
I'm obj-c and javascript programmer. And I have some free times. I can help :)

**Comment by Hirbod** [comment]
@arilsonkarmo I will add zIndex for iOS only in version 1.3.3. Android has no zIndex support
