### ISSUE TITLE
Is it possible to choose to overlay map above webview?

### ISSUE THREAD

**Issue by raulfelix** [wf9a5m75/phonegap-googlemaps-plugin#604]
My use case is: 

I have a modal and the plugin does not set the opacity of all div elements sitting behind the modal correctly meaning that the map is still hidden.

I would like to overlay the map as this is a simpler solution for me. Is this possible?
I apologise if this is answered somewhere but I could not find this in the documentation of existing issues.

**Comment by Hirbod** [comment]
I'm sorry it's not possible. Just set the transparency manually (the plugin can't detect absolut positioned elements automatically, only parent nodes)

I had similar problems before, I just made them transparent with jQuery

**Comment by raulfelix** [comment]
Thank you @Hirbod
