### ISSUE TITLE
crosswalk on v1.2.8 doesn't work

### ISSUE THREAD

**Issue by grigored** [wf9a5m75/phonegap-googlemaps-plugin#605]
I followed the new xwalk tutorial, and it doesn't work. 
I have cordova 5.2.0, and Android API 22 sdk. If I try using https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test, I get the scrollevent error:

```~/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:15: error: cannot find symbol
import org.apache.cordova.ScrollEvent;
                         ^
  symbol:   class ScrollEvent
  location: package org.apache.cordova
~/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:138: error: cannot find symbol
    root = (ViewGroup) webView.getParent();```

If I try using the non-test, I get:

``` FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-maps:+. ```

Any suggestions on making this work with crosswalk? Also, I think the run command should now be ```cordova run android``` instead of ```./cordova/run android```.

**Comment by grigored** [comment]
I didn't have the right android extras installed, it works great if i don't use #test branch. Great job!

**Comment by Hirbod** [comment]
#test branch is dead. I just don't have enough rights to delete the old branches. Just use master!

**Comment by cwoolum** [comment]
What android extras did you need to install? I'm running into the same problem

**Comment by Hirbod** [comment]
Crosswalk works perfectly fine

Just follow the wiki
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29
