### ISSUE TITLE
Question: Is it possible to hide the "Goto my position" button but still have the functionality

### ISSUE THREAD

**Issue by thim81** [wf9a5m75/phonegap-googlemaps-plugin#609]
Hi, 

We tried to hide the "Goto my position" (right bottom on iOS / top right on iOS) but it does not seem possible? Or is there a setting / option somewhere to have control over the visibility of the UI elements/buttons?

When using setMyLocationEnabled(Boolean), the marker of my position on the map also dissapears?

**Comment by Hirbod** [comment]
Android or iOS? Did you install the newest version?

map.setMyLocationEnabled(false) should hide the button actually.

**Comment by thim81** [comment]
Hi Hirbod,

On iOS and Android, using the map.setMyLocationEnabled(false) also hide the blue dot marker of my position on the map.
I only want to disable the UI button not the behaviour and blue dot.

**Comment by Hirbod** [comment]
I think that there are linked.

**Comment by mickadoua** [comment]
hello, 
any update about this on V1.4 or v2-beta2  ?
or if its possible to move the button

**Comment by wf9a5m75** [comment]
```js
var map = plugin.google.maps.Map.getMap(div, {
   controls: {
     myLocationButton : false
   }
});

map.on(plugin.google.maps.event.MAP_READY, function() {
  var button = document.getElementById("my_button");
  button.addEventListener("click", function() {
    map.getMyLoacation(function(result) {
      map.animateCamera({
        position: result.location,
        zoom: 18
    }, function() {
       // complete
    });
  });
});
```

**Comment by battika** [comment]
I think it will also hide the "blue dot", won't it?

**Comment by wf9a5m75** [comment]
Why don't you create a maker by yourself.

**Comment by battika** [comment]
Probably, because you will need to update the position and animate it manually vs. being a native functionality. Anyway, it should not be too hard to fork this plugin and override the setMyLocationEnabled() function to remove the button.
