### ISSUE TITLE
Build failed with XCode 7 (GTMStringEncoding.o does not contain bitcode)

### ISSUE THREAD

**Issue by pyroon** [wf9a5m75/phonegap-googlemaps-plugin#610]
When trying to build my app with XCode 7, I'm getting the following error:
```
ld: '<AppName>/Plugins/com.googlemaps.ios/GoogleMaps.framework/GoogleMaps(GTMStringEncoding.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
```

When disabling the bitcode option, I'm getting an error when trying to submit the app to the store.

Any idea?

**Comment by Hirbod** [comment]
Yes, we need to update Google SDK to 1.10.2+

**Comment by pyroon** [comment]
Hi
Ok, is there already a plan when this will happen?
Cheers

**Comment by Hirbod** [comment]
This week

**Comment by Hirbod** [comment]
maybe today :)

**Comment by Hirbod** [comment]
Just pushed version 1.3.0 (still untested, but should work). I will do my tests now, but feel free to grab the master!

**Comment by Hirbod** [comment]
Just to mention:

- Delete plugin (```cordova plugin rm plugin.google.maps```)
- Delete iOS SDK (```cordova plugin rm plugin.google.maps```)
- Install plugin from master

**Comment by Hirbod** [comment]
Confirmed: works :)

**Comment by Hirbod** [comment]
Btw: you will still need to disable bitcode, as Google Maps SDK isn't build with bitcode.
https://code.google.com/p/gmaps-api-issues/issues/detail?id=8219

**Comment by pyroon** [comment]
Hi
thx.
Just got the following error, any idea?

```Installing "plugin.google.maps" for android
Error during processing of action! Attempting to revert...
Failed to install 'plugin.google.maps':TypeError: Uh oh!
Arguments to path.resolve must be strings
```

**Comment by Hirbod** [comment]
In order to install the new version, you have to:
```bash
1) Delete plugin 
> cordova plugin rm plugin.google.maps

2) Delete Google Maps iOS SDK 
> cordova plugin rm com.googlemaps.ios

3) Re-Install plugin from master (follow wiki for Mac/Linux/Windows) 
> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_KEY" --variable API_KEY_FOR_IOS="YOUR_KEY"
```

**Comment by pyroon** [comment]
Ok, after an update of cordova this worked.
But now I'm getting tons of errors like while compiling

```
Undefined symbols for architecture i386:
  "_CACurrentMediaTime", referenced from:
      -[GMSx_QTMActivityIndicator addStrokeRotationCycle] in GoogleMapsM4B(GoogleKitActivityIndicator.o)
      -[GMSSystemClock relativeTimeMillis] in GoogleMapsM4B(GMSSystemClock.o)
      gmscore::renderer::ios::Time::CurrentUpTime() const in GoogleMapsM4B(Time-E6274B8F66CFB542.o)
```

**Comment by Hirbod** [comment]
https://developers.google.com/maps/documentation/business/mobile/ios/config

Replace the default value of Architectures with armv7.

**Comment by Hirbod** [comment]
I'm still downloading Xcode 7 (my connection is very bad today)
On Xcode 6, there is no problem.

**Comment by Hirbod** [comment]
Ah.. you're missing QuartzCore Framework.

You need to target the Memberships. You can do this manually (have a look at my video)
https://www.youtube.com/watch?v=gr0QrEShPbQ

Just link all the .m files and bundles inside Framework like in my video.
If you're lazy, just: 
> cordova platform rm ios
> cordova platform add ios

**Comment by pyroon** [comment]
Hi,
yes, this was the problem :-) Thx

But now when I'm trying to submit the app to the app store I'm getting t his:
![image](https://cloud.githubusercontent.com/assets/1299253/9848639/45466b2a-5ae3-11e5-9dac-65a14984ef4d.png)

**Comment by Hirbod** [comment]
Use google or stackoverflow please. Just remove the CFBudles. #612 
http://stackoverflow.com/questions/32096130/unexpected-cfbundleexecutable-key

I'm locking this issue now!

**Comment by Hirbod** [comment]
SDK 1.11.0 is out, with Bitcode support. I will update the SDK today.
