### ISSUE TITLE
Possible User Error: Using getMyLocation offline on Android

### ISSUE THREAD

**Issue by jaradi** [wf9a5m75/phonegap-googlemaps-plugin#611]
Hello, I've done some research on this issue to no avail. When using the "getMyLocation" function offline (wifi/cellular data off) on Android it throws the following error:

{
 "status": "false",
"error_code":"service_not_available",
"error_message": "This app has been rejected to use Location Services."
}

I'm not sure what's "rejected" my app, whether it's because it can't reach Google's servers or if the issue is local. Turning data back on and it works like a charm.

Is this normal? Is there a workaround?

**Comment by Hirbod** [comment]
Please use Cordovas Geolocation plugin, it's much more stable and updated.
