### ISSUE TITLE
Build fails, can't find google services library

### ISSUE THREAD

**Issue by kenoph0be** [wf9a5m75/phonegap-googlemaps-plugin#613]
Hi,

I followed all the steps mentioned in the guide for Linux but when I write `cordova build android` I get the following error:
```
Running command: /home/empty/projects/app/Map/platforms/android/cordova/build --debug
ANDROID_HOME=/home/empty/android_sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle/
Running: /home/empty/projects/app/Map/platforms/android/gradlew cdvBuildDebug -b /home/empty/projects/app/Map/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-maps:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-location:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
     Required by:
         :android:unspecified
```

Some infos:
* Cordova 5.3.1
* Android SDK Tools 24.3.4
* Android SDK Platform Tools 23.0.1
* Android SDK Build Tools 23.0.1
* Android 5.1.1 (API 22) SDK Platform Rev. 2

So can you please help me figure out what I did wrong?

Thank you very much and thank you for creating this library ;)

Paolo

**Comment by anaibol** [comment]
Try
```
cordova plugin rm plugin.google.maps
cordova plugin rm com.google.playservices
cordova plugin add https://github.com/wf9a5m75/google-play-services#v23
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by Hirbod** [comment]
@anaibol  
this would install version 1.2.5 - which is not compatible with new cordova/ cordova-android

**Comment by Hirbod** [comment]
@kenoph0be please open your config.xml and try to add

```
    <platform name="android">
        ...
        ...
        <preference name="android-minSdkVersion" value="16" />
```

It should also work with 14. I think that should fix you problems.

**Comment by Hirbod** [comment]
If not, open SDK-Manager and download "Google Repository"

**Comment by Hirbod** [comment]
Also, check #606 
Some have problems due to wrong SDK enviroment-path. Closing this here, as the plugin works as expected!

**Comment by kenoph0be** [comment]
I followed all the steps and installing Android Support Repository seems to have fixed the problem.

Thank you very much!

P.S.: Maybe the Wiki should be updated?

**Comment by Hirbod** [comment]
@kenoph0be I updated today :)

**It's also important to install the Android Support Repository, Library, Play Services and Google Repository.**
![](https://cloud.githubusercontent.com/assets/504909/9845520/cb08e278-5acb-11e5-9cd6-cc4d98abb2cc.png)
