### ISSUE TITLE
Confusion about which SDK/API to enable

### ISSUE THREAD

**Issue by ma-pe** [wf9a5m75/phonegap-googlemaps-plugin#615]
Hey,

I am currently trying to get a simple Google Map to work in my Cordova-App for iOS and Android.

Until now I did the following steps:

1. I generated API-Keys for both iOS and Android.
2. I used the API-Keys from (1) to install the phonegap-plugin.
3. I built both iOS and Android and tried them on testing-devices.

Both just show a grey Map with the Google-Logo in the bottom-right-corner. 
Xcode tells me that I am getting 400-Responses and that the API-Key may be wrong. For both platforms I don't get any Browser-console-logs. I checked the iOS-Plist and it contains the correct API-Key - seems to work fine though.

In my Google Developer Console (Google Maps for Work) there is enabled just one API (the "Google Maps Mobile SDK"). This one says to be "An SDK for embedding a native Google Map in a mobile app (Android and iOS).". This sounds fine for me - although following tutorial (https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-Mac) says, I need to prepare my API keys for both Google Maps Android API v2 and Google Maps iOS SDK.

Maybe you can bring some light into the darkness - thanks :-)

**Comment by Hirbod** [comment]
API v2 = Android
iOS SDK = iOS

Currently I also do encounter 400er problems. I'm still not really sure what happened, I guess it has something to do with the BundleID/API or (Whitelist?). Still investigating. My map is loading, but my markers not.. Weird.

**Comment by ma-pe** [comment]
Thanks for your reply.
Does that mean, that in general "Google Maps Mobile SDK" is alright (because it covers both Android and iOS)? Or do I need to enable both API v2 and iOS SDK?

**Comment by Hirbod** [comment]
If you want to run the map on iOS only, you don't need to activate API v2. If you want to run on both iOS and android, both APIs have to be activated. If you just want to run on android, API v2 is enough!

**Comment by ma-pe** [comment]
I think you missed my point. At the moment I have none of them (API v2, iOS SDK) enabled.

I have enabled a different API, that is called "Google Maps Mobile SDK". This API has the following description: "An SDK for embedding a native Google Map in a mobile app (Android and iOS)."

This sounds as if it would cover both API's you mentioned. Do you know this third API and do you know wether this i correct, too?

**Comment by Hirbod** [comment]
I've never heard of that API. In order to get this map work, you need to select Maps SDK for iOS.
As you can see in my list, I don't have "Google Maps Mobile SDK"

<img width="292" alt="bildschirmfoto 2015-09-14 um 12 05 28" src="https://cloud.githubusercontent.com/assets/504909/9847426/04889810-5ad9-11e5-8129-9e0d541c8b00.png">

**Comment by ma-pe** [comment]
It seems that the "Google Maps Mobile SDK" is the "Google Maps For Work"-Version, while Maps iOS SDK and Android API are for private use. Am I right, that the plugin will not work with "Google Maps for Work"? Thanks for your replies.

**Comment by Hirbod** [comment]
I guess so
