### ISSUE TITLE
is there a npm version ?

### ISSUE THREAD

**Issue by bau720123** [wf9a5m75/phonegap-googlemaps-plugin#617]
hi @wf9a5m75 
is there a npm version ?
https://www.npmjs.com

**Comment by Hirbod** [comment]
Currently not. Masashi is not involved in this project currently.

**Comment by bau720123** [comment]
Thanks @Hirbod
Hope one day can have a mom version

**Comment by Hirbod** [comment]
I would push it to npm but I have no experience as I never used it to pusblish something, just to download. Will check this these days and try to submit it.

**Comment by bau720123** [comment]
Thanks @Hirbod

**Comment by jperl** [comment]
Seems like @roberthovhannisyan published v1.2.5 https://www.npmjs.com/package/am.armsoft.plugins.googlemaps

**Comment by bau720123** [comment]
hi @jperl 
thanks for your feedback
but sad is a old version 1.2.5
maybe waiting @Hirbod to publish a new one

**Comment by Hirbod** [comment]
I dont know, why this is so important to you guys. Entering the Github address isn’t that hard: D

**Comment by bau720123** [comment]
hi @Hirbod 
HAHA
sorry for the bother
because in PGB (build.phonegap.com)
for now there is no way install plugin directly in Github
so...npm is the only way for PGB...

**Comment by roberthovhannisyan** [comment]
Hi @bau720123,
Even if this version is published on npm you would not be able to use it with PGB.
As far as I know, currently PGB doesn’t support gradle builds, which is required if the plugin uses frameworks (see https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/plugin.xml#L47). That is why I also reverted to dependencies instead of frameworks in my fork. 

So the option is either to use cordova CLI, or wait for PGB to support gradle.

Hope it helps

**Comment by bau720123** [comment]
thanks @roberthovhannisyan 
fully understand
got it !!!

**Comment by Hirbod** [comment]
@roberthovhannisyan one of the main reasons I did not publish to npm currently. Gradle isn't supported actually. But they are discussing at JIRA about that. Let's wait. Closing this for now!

**Comment by jperl** [comment]
One major benefit of npm is that you do not have to clone the whole repo w/ examples, only the relevant code.

**Comment by roberthovhannisyan** [comment]
Hi all,
According to http://phonegap.com/blog/2015/09/28/android-using-gradle/ beginning from September 28 Phonegap Build is using Gradle by default for all android builds.

@Hirbod, I assume the issue can be re-opened to be considered for implementation.

Thank you in advance !

**Comment by gwendall** [comment]
+1

**Comment by Hirbod** [comment]
cordova-plugin-googlemaps@1.3.4 is on npm now
