### ISSUE TITLE
Error on IOs 9.1

### ISSUE THREAD

**Issue by rqsakai** [wf9a5m75/phonegap-googlemaps-plugin#620]
Hi guys,

It was working perfectly until i tested on ios 9.1

Gives me the following error on build on Xcode (Command line is fine)

```
Ld /Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Products/Debug-iphoneos/CupoMap.app/CupoMap normal armv7
    cd /Users/sakai/mobile/cupomap/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Products/Debug-iphoneos -F/Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Products/Debug-iphoneos -FCupoMap/Plugins/com.googlemaps.ios -filelist /Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Intermediates/CupoMap.build/Debug-iphoneos/CupoMap.build/Objects-normal/armv7/CupoMap.LinkFileList -miphoneos-version-min=6.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Products/Debug-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreMotion -framework CoreLocation -weak_framework AudioToolbox -framework GoogleMapsM4B -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreText -framework GLKit -framework ImageIO -lc++ -licucore -lz -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -Xlinker -dependency_info -Xlinker /Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Intermediates/CupoMap.build/Debug-iphoneos/CupoMap.build/Objects-normal/armv7/CupoMap_dependency_info.dat -o /Users/sakai/Library/Developer/Xcode/DerivedData/CupoMap-glabnpveqvsedlbadiwboazszesm/Build/Products/Debug-iphoneos/CupoMap.app/CupoMap
```
```
ld: 'CupoMap/Plugins/com.googlemaps.ios/GoogleMapsM4B.framework/GoogleMapsM4B(GMSCachedTile.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I Appreciate any help.

**Comment by rqsakai** [comment]
FYI Just update all project plugins

**Comment by Hirbod** [comment]
I see that you have the new version installed. As you can see in your log, you have GoogleMapsM4B - THIS IS WRONG. It was my fault. Please

1) Delete plugin 
> cordova plugin rm plugin.google.maps

2) Delete Google Maps iOS SDK 
> cordova plugin rm com.googlemaps.ios

3) Re-Install plugin from master (follow wiki for Mac/Linux/Windows)
> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_KEY" --variable API_KEY_FOR_IOS="YOUR_KEY"

Disable bitcoin, target all memberships (or just call "cordova platform rm ios" before)

**Comment by Hirbod** [comment]
https://www.youtube.com/watch?v=gr0QrEShPbQ

**Comment by rqsakai** [comment]
Perfect. 


Thank you very much Hirbod.

**Comment by rqsakai** [comment]
Sorry still gets the same error :( 

Did everything as asked (including video). Also create a new project from scratch, and same issue.

Thank you

**Comment by Hirbod** [comment]
Not possible. You're doing something wrong. It is important to reinstall the plugin AND the ios-sdk, as I made an error today. I just tried it, build perfectly on Xcode 6.4 and Xcode 7 GM (iOS 9)

**Comment by rqsakai** [comment]
Here follows the code to the project

New Project
```
Rauls-MacBook-Pro:mobile sakai$ cordova create cupomap com.grouptools.cupomap CupoMap
Creating a new cordova project.
```
Add Platforms
```
cordova platform add android && cordova platform add ios
```
Add default plugins
```
cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-device-motion
cordova plugin add cordova-plugin-device-orientation
cordova plugin add cordova-plugin-dialogs
cordova plugin add cordova-plugin-geolocation
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-whitelist
cordova plugin add phonegap-plugin-push
```

Add Google Maps Plugin

```
cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="xxxxxx" --variable API_KEY_FOR_IOS="xxxxx"
```

Building now it gives and Android issue duplicating a lib
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/sakai/Library/Android/sdk/build-tools/23.0.1/dx --dex --no-optimize --output /Users/sakai/mobile/cupomap/platforms/android/build/intermediates/dex/debug --input-list=/Users/sakai/mobile/cupomap/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```
Fix with this on you platforms/android/build.gradle right after the: apply plugin "Android"
```
configurations {
   all*.exclude group: 'com.android.support', module: 'support-v4'
}
```

* Build on cordova CLI is perfect (cordova build)

Tried build with:
*cordova run --device
* build on Xcode 7.1

Both give me the same error

```
Ld build/device/CupoMap.app/CupoMap normal armv7
    cd /Users/sakai/mobile/cupomap/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin/mysql:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/bin:/usr/X11/bin/xhost:/Users/sakai/sdks/android/platform-tools:/Users/sakai/sdks/android/tools:/Users/sakai/groovy-2.3.7/bin:/usr/local/mysql/bin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/sakai/mobile/cupomap/platforms/ios/build/device -F/Users/sakai/mobile/cupomap/platforms/ios/build/device -FCupoMap/Plugins/com.googlemaps.ios -filelist /Users/sakai/mobile/cupomap/platforms/ios/build/CupoMap.build/Debug-iphoneos/CupoMap.build/Objects-normal/armv7/CupoMap.LinkFileList -miphoneos-version-min=6.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/sakai/mobile/cupomap/platforms/ios/build/device/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreMotion -framework CoreLocation -weak_framework AudioToolbox -framework GoogleMaps -framework AVFoundation -framework CoreData -framework CoreText -framework GLKit -framework ImageIO -lc++ -licucore -lz -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -Xlinker -dependency_info -Xlinker /Users/sakai/mobile/cupomap/platforms/ios/build/CupoMap.build/Debug-iphoneos/CupoMap.build/Objects-normal/armv7/CupoMap_dependency_info.dat -o /Users/sakai/mobile/cupomap/platforms/ios/build/device/CupoMap.app/CupoMap
ld: 'CupoMap/Plugins/com.googlemaps.ios/GoogleMaps.framework/GoogleMaps(GTMStringEncoding.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anything that i'm doing wrong?

**Comment by Hirbod** [comment]
Do you have Teamviewer? Send me your ID and Password, I would connect to your screen and check on your computer. Mail me your details to info [THAT@SIGN] nightstomp.com

**Comment by Hirbod** [comment]
Just disable Bitcode as the error message cleary tells you!

<img width="721" alt="bildschirmfoto 2015-09-14 um 21 28 14" src="https://cloud.githubusercontent.com/assets/504909/9859572/926db022-5b27-11e5-93ff-d9a98d379197.png">

**Comment by rqsakai** [comment]
IT Worked, perfectly..

Sorry i assumed  i've changed it, but it was on the old project.

# Thank you very much Hirbod. you are the best!

**Comment by Hirbod** [comment]
:+1:

**Comment by pnakhat** [comment]
I have BIT code disabled but facing similar issues


d /Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Products/Debug-iphonesimulator/iSuraksha.app/iSuraksha normal x86_64
    cd /Users/pankajnakhat/isurakshaIos/isuraksha-mobile/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Products/Debug-iphonesimulator -F/Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Products/Debug-iphonesimulator -FiSuraksha/Plugins/com.googlemaps.ios -filelist /Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Intermediates/iSuraksha.build/Debug-iphonesimulator/iSuraksha.build/Objects-normal/x86_64/iSuraksha.LinkFileList -mios-simulator-version-min=6.0 -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Products/Debug-iphonesimulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework QuartzCore -weak_framework ImageIO -framework CoreLocation -framework GoogleMaps -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreText -framework GLKit -lc++ -licucore -lz -framework OpenGLES -framework SystemConfiguration -framework Security -Xlinker -dependency_info -Xlinker /Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Intermediates/iSuraksha.build/Debug-iphonesimulator/iSuraksha.build/Objects-normal/x86_64/iSuraksha_dependency_info.dat -o /Users/pankajnakhat/Library/Developer/Xcode/DerivedData/iSuraksha-dyspingzzcxewigbzwvcdnqxwbex/Build/Products/Debug-iphonesimulator/iSuraksha.app/iSuraksha

**Comment by Hirbod** [comment]
There is no error message.

But I can see:
IPHONEOS_DEPLOYMENT_TARGET=6.0

This need to be set to 7.0

**Comment by pnakhat** [comment]
How do I set this?

**Comment by Hirbod** [comment]
This is not a support-forum.

**Comment by Hirbod** [comment]
SDK 1.11.0 is out, with Bitcode support. I will update the SDK today.
