### ISSUE TITLE
Error on map.setPadding

### ISSUE THREAD

**Issue by alessandrobelli** [wf9a5m75/phonegap-googlemaps-plugin#621]
map.setPadding( 10, 50 , 90 , 10 );
this line of code doesn't work anymore after upgrading at the last version... I can't see the buttons of the map in this way (because they're outside the map).

**Comment by Hirbod** [comment]
I made an error today. You probably have GoogleMapsM4B - THIS IS WRONG. It was my fault. Please

1) Delete plugin 
> cordova plugin rm plugin.google.maps

2) Delete Google Maps iOS SDK 
> cordova plugin rm com.googlemaps.ios

3) Re-Install plugin from master (follow wiki for Mac/Linux/Windows)
> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_KEY" --variable API_KEY_FOR_IOS="YOUR_KEY"

Disable bitcoin, target all memberships (or just call "cordova platform rm ios" before)
https://www.youtube.com/watch?v=gr0QrEShPbQ
