### ISSUE TITLE
iOS compiling issue

### ISSUE THREAD

**Issue by jsappme** [wf9a5m75/phonegap-googlemaps-plugin#622]
Hello,

I am experiencing the following error when iOS compiling with the new version 1.3:

```
Undefined symbols for architecture armv7:
  "_kSecRandomDefault", referenced from:
      +[NSData(GMSCrypto) gms_randomDataWithLength:] in GoogleMaps(NSData+GMSCrypto.o)
  "_SecRandomCopyBytes", referenced from:
      +[NSData(GMSCrypto) gms_randomDataWithLength:] in GoogleMaps(NSData+GMSCrypto.o)
  "_kSecAttrApplicationLabel", referenced from:
      -[GMSPersistentStorage encryptionKeyQuery] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecReturnData", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecClassKey", referenced from:
      -[GMSPersistentStorage encryptionKeyQuery] in GoogleMaps(GMSPersistentStorage.o)
  "_SecItemCopyMatching", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecClass", referenced from:
      -[GMSPersistentStorage encryptionKeyQuery] in GoogleMaps(GMSPersistentStorage.o)
  "_SecTrustEvaluate", referenced from:
      -[GMSx_GTMSessionFetcher URLSession:task:didReceiveChallenge:completionHandler:] in GoogleMaps(GTMSessionFetcher.o)
  "_kSecAttrAccessible", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecValueData", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecAttrKeyClass", referenced from:
      -[GMSPersistentStorage encryptionKeyQuery] in GoogleMaps(GMSPersistentStorage.o)
  "_SecItemAdd", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_SecItemDelete", referenced from:
      -[GMSPersistentStorage deleteEncryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecAttrAccessibleAlwaysThisDeviceOnly", referenced from:
      -[GMSPersistentStorage encryptionKey] in GoogleMaps(GMSPersistentStorage.o)
  "_kSecAttrKeyClassSymmetric", referenced from:
      -[GMSPersistentStorage encryptionKeyQuery] in GoogleMaps(GMSPersistentStorage.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/device/Tree\ The\ World.app/Tree\ The\ World normal armv7
(1 failure)
```

I could not find how to disable the Bitcode on Xcode. I dont know if it's the problem or not.

Cordially,

Hervé

**Comment by Hirbod** [comment]
I'm not going to give support to the same type of questions again and again. Your error is not bitcode related, if you read your logs, you will understand.
Check your build settings, check that your frameworks are linked correctly (https://www.youtube.com/watch?v=gr0QrEShPbQ), do a reinstall.

In order to install the new version, you have to:

1) Delete plugin
    cordova plugin rm plugin.google.maps
2) Delete Google Maps iOS SDK
    cordova plugin rm com.googlemaps.ios
3) Re-Install plugin from master (follow wiki for Mac/Linux/Windows)
    cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_KEY" --variable API_KEY_FOR_IOS="YOUR_KEY"

If nothing helps, delete your iOS Platform and start over

**Comment by jsappme** [comment]
I tried this already. But I will try again.

**Comment by jsappme** [comment]
I deleted the iOS platform. I followed all your instructions again. Re-added the iOS platform and I am still getting the same error.

**Comment by Hirbod** [comment]
Im sure you did not delete the SDK before:

cordova plugin rm com.googlemaps.ios

**Comment by Hirbod** [comment]
Show me a screenshot inside of Xcode with your "Frameworks"

**Comment by jsappme** [comment]
Yes I did remove this plugin twice.

Maybe the problem comes from this:
```
Ld build/device/Tree\ The\ World.app/Tree\ The\ World normal armv7
    cd /Users/herve76/Desktop/TreeTheWorld/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
```
?

**Comment by Hirbod** [comment]
Set target inside of Xcode to 7.0

**Comment by jsappme** [comment]
Do I have to open Xcode every time I want to compile the app?

Can I use the command "ionic run ios -l --device" ?

**Comment by Hirbod** [comment]
Normally not. I also compile with CLI. Just open Xcode one time, set everything correct, check targets, build 1 time to device and afterwards, it should work with CLI again

**Comment by jsappme** [comment]
![screen shot 2015-09-15 at 10 14 32 am](https://cloud.githubusercontent.com/assets/13439477/9882589/a746c932-5b92-11e5-84a7-698790580b02.png)

**Comment by jsappme** [comment]
![screen shot 2015-09-15 at 10 15 49 am](https://cloud.githubusercontent.com/assets/13439477/9882605/c31d748a-5b92-11e5-92ad-6161169c6acd.png)

**Comment by Hirbod** [comment]
Frameworks seem to be fine. Would you mind to share a Teamviewer session with me? I'd like to connect to your Mac to test inside of your Xcode

**Comment by jsappme** [comment]
Yes you can. Please send me an email at herve76@gmail.com

**Comment by Hirbod** [comment]
you need to send me an email with your teamviewer id and password.

info@nightstomp.com

**Comment by jsappme** [comment]
I still have the following error when trying to compile for my phone.

![screen shot 2015-09-15 at 10 40 34 am](https://cloud.githubusercontent.com/assets/13439477/9883236/39feeebe-5b96-11e5-938b-0875d16c5f52.png)

**Comment by Hirbod** [comment]
Just for everybody: The Security.Framework was missing. Just added to your frameworks, the current master is fixed now!
