### ISSUE TITLE
iPhone Simulator Key in Info.plist

### ISSUE THREAD

**Issue by Mojo90** [wf9a5m75/phonegap-googlemaps-plugin#626]
I got Errors while uploading an App with Xcode 7 to itunesconnect because iPhoneSimulator was in Info.Plist as supported platform.
Why is it stated in Info.plist?

Just deleted this 2 times and seems to work now: 
I got Errors while uploading an App with Xcode 7 to itunesconnect because iPhoneSimulator was in Info.Plist as supported platform.
Why is it stated in Info.plist?

Just deleted this 2 times and seems to work now: 

```
<key>CFBundleSupportedPlatforms</key>
 <array>
    <string>iPhoneSimulator</string>
 </array>
```

**Comment by Hirbod** [comment]
You should upgrade to v 1.3.0 (please readme on startpage how to do this corretly)
This includes the new SDK which should be fine (i hope so)

**Comment by Mojo90** [comment]
I did this yesterday evening.
My plugin list says:
plugin.google.maps 1.3.0 "phonegap-googlemaps-plugin"
and installed automatically this SDK:
com.googlemaps.ios 1.10.2 "Google Map iOS SDK for Cordova"

**Comment by Hirbod** [comment]
Will check the plist problems these days

**Comment by vash15** [comment]
Hi @Hirbod I have same problem. How do I fix the error without waiting for the update?

**Comment by Mojo90** [comment]
@vash15  read my first comment?

**Comment by vash15** [comment]
@Mojo90  I've read. I solved changing:

DTPlatformName: iphoneos
DTSDKName: iphoneos8.4
CFBundleSupportedPlatforms->
  Item0: iPhoneOS

but I do not know if it is correct.

**Comment by Mojo90** [comment]
okay as I mentioned I just deleted those 2 lines with iPhoneSimulator and does work for me. Don't know what this has to mean there

**Comment by johnrobertcobbold** [comment]
Same problem here

**Comment by fgarzonhz** [comment]
Pueden ejecutar la instrucción: command+shift+F y busquen el key que sale en la lista de errores. Lo eliminamos y funcionó correctamente. (ojo solo borren el item no todo el nodo)


Cordialmente, 
M.Sc. Franklin Garzón
  *Lucha hasta alcanzar tus sueños*


 
 Date: Wed, 23 Sep 2015 04:34:10 -0700

**Comment by Hirbod** [comment]
Will update SDK later

**Comment by MrPro100** [comment]
+1 Please update Google SDK

**Comment by Hirbod** [comment]
Grab 1.3.2 from master - included new SDK 1.10.3

**Comment by johnrobertcobbold** [comment]
Thanks Hirbod

**Comment by vash15** [comment]
Thanks!
