### ISSUE TITLE
Feature request: Add label support

### ISSUE THREAD

**Issue by Peter-77** [wf9a5m75/phonegap-googlemaps-plugin#627]
Hi,

What I would really like to see added is the use of labels on markers. Now you can only set a color, but not set any text on the marker. 

I would like to be able set text on a marker, instead of having to use images.

**Comment by Hirbod** [comment]
Of course, you can use the "title" attribute for the infoWindow. There is nothing like a label, I've checked the docs. If you want something like a always visibale label, you need to use a image.
