### ISSUE TITLE
Question: Marker-InfoWindow

### ISSUE THREAD

**Issue by ma-pe** [wf9a5m75/phonegap-googlemaps-plugin#628]
Hey,

what I want to achieve is an InfoWindow, when a Marker is clicked, that contains different links and buttons as well as styled text. I saw the possibility for base64-encoded Canvas-Images, therefore buttons and styling is no problem. 

But... I didn't see any possibility for Click-Events other than the window-click-Event. Currently there is no possibility to use two different links, that trigger a js-functions on click, is it?

And there is as well no possibility to find out the coordinates, where the click happend, right?

**Comment by Hirbod** [comment]
You're right. What you're trying to achieve is something more complex and special, therefor, I would recommend that you don't rely on the default InfoWindow. Just style your own with HTML and open it on markerClick.

**Comment by ma-pe** [comment]
Ok, that's what I am about to do. :)
