### ISSUE TITLE
Switch to com.synconset.cordovahttp [$150]

### ISSUE THREAD

**Issue by jperl** [wf9a5m75/phonegap-googlemaps-plugin#630]
[phonegap-googlemaps-plugin](https://github.com/wf9a5m75/phonegap-googlemaps-plugin) depends on [plugin.http.request](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/64fa35f3ba04d43557e47d614a8d0061993457ad/plugin.xml#L21) which depends on google-volley through a [jar file](https://github.com/wf9a5m75/phonegap-http-request/blob/master/plugin.xml#L21
). This makes it incompatible with other plugins that rely on `google-volley`.

[com.synconset.cordovahttp](https://github.com/wymsee/cordova-HTTP) does not rely on google volley, has no [`jar`](https://github.com/wymsee/cordova-HTTP/blob/master/plugin.xml) dependencies, and is up-to-date / better supported plugin than `phonegap-http-request`. So switching to that should fix this issue as well as allow `phonegap-http-request` to be deprecated.

-----------------------

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/android/volley/VolleyError;
at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
at com.android.dx.command.dexer.Main.run(Main.java:277)
at com.android.dx.command.dexer.Main.main(Main.java:245)
at com.android.dx.command.Main.main(Main.java:106)

**Comment by matsprea** [comment]
It's possible to use gradle to include and compile google-volley, but it will be via an ["unofficial" maven mirror](http://stackoverflow.com/a/26587166/3463707) (ex. [mcxiaoke/android-volley] (https://github.com/mcxiaoke/android-volley)) and it will reamain a *third party* libray so another plugin could include a different version and you will get the same problem.

A more radical solution could be replace [plugin.http.request](https://github.com/wf9a5m75/phonegap-http-request) with [wymsee/cordova-HTTP](https://github.com/wymsee/cordova-HTTP) a.k.a [com.synconset.cordovahttp](http://plugins.cordova.io/#/package/com.synconset.cordovahttp) that does not use google-volley.

**Comment by jperl** [comment]
That sounds like a good plan. [cordova-HTTP](https://github.com/wymsee/cordova-HTTP) looks better.

**Comment by matsprea** [comment]
@jperl this should do it, the two DemoApp are working on my devices.
Give it a try.

**Comment by jperl** [comment]
Before I manually included `com.synconset.cordovaHTTP` I got this error

````
   While adding plugin
   https://github.com/matsprea/phonegap-googlemaps-plugin.git#74e88ac07ca066455f5ac50b4095a16987c35bc9
   to Cordova project:
   Cordova error: CordovaError: Failed to fetch plugin
   com.synconset.cordovaHTTP via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
````

afterwards I get this error

````
.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:914: error: cannot find symbol
                            JSONObject fileEntry = filePlugin.getEntryForFile(file);
                                                             ^
  symbol:   method getEntryForFile(File)
  location: variable filePlugin of type FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileArmv7DebugJava FAILED
````

**Comment by Hirbod** [comment]
Maybe we could drop the plugin, already removed all dependencies for iOS. Marker download native, version check is also not important. Will dig into this these days

**Comment by jperl** [comment]
That sounds really good ^ :+1:

**Comment by Hirbod** [comment]
Pushed 1.3.1 to master. See updated README / Relasenotes. 

1) Delete plugin 
> cordova plugin rm plugin.google.maps

2) Delete Google Maps iOS SDK 
> cordova plugin rm com.googlemaps.ios

3) Delete plugin.http.request
> cordova plugin rm plugin.http.request

3) Re-Install plugin from master (follow wiki for Mac/Linux/Windows)
> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_KEY" --variable API_KEY_FOR_IOS="YOUR_KEY"
