### ISSUE TITLE
Google Maps framework

### ISSUE THREAD

**Issue by cburghardt** [wf9a5m75/phonegap-googlemaps-plugin#632]
I have updated to 1.3.0 as thus also updated the sdk.
Now the google maps framework does not appear anymore in Xcode in the list of frameworks. I had to manually add the framework from the Project navigator via drag and drop to the list of dependencies. Unfortunately this is removed every time I do a cordova prepare
Any clue what I can do?
Using Xcode 7

**Comment by Hirbod** [comment]
Can't reproduce. It's working fine!

**Comment by cburghardt** [comment]
I have updated Cordova - now it is working
