### ISSUE TITLE
Onsen ui sliding menu  is flickering

### ISSUE THREAD

**Issue by githubkyo** [wf9a5m75/phonegap-googlemaps-plugin#634]
When i toggle Onsen ui's  sliding menu 、it is flickering.

**Comment by Hirbod** [comment]
you can only use slide animation for menu (not reveal) on onsenui

**Comment by githubkyo** [comment]
Thank you for you answer.

But, it have tried that way that use onsen ui's sliding menu, and set type with push(not reveal).

Flickering issue was stil happened.

Like this,

When I toggle slide menu, the menu have  arrived  target position, but map's div tag move slowly.

**Comment by Hirbod** [comment]
Yes, as the map position can't be updated in realtime. Have a look at the watchdogTimer (see docs). Set value to 0 on preopen of the menu, back to 100 (default value) when menu opened. Same on pre/post push and pop

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/313

**Comment by Hirbod** [comment]
Check the last comments on #313 made by me. The functions are available, as my pr got merged.

https://www.youtube.com/watch?v=cddcqIibOl8&feature=youtu.be

**Comment by githubkyo** [comment]
thank you very much.
can you give me your code . javascript and onsen uil.
