### ISSUE TITLE
Question:when i set one marker's icon url , it's infowindows  can't view.

### ISSUE THREAD

**Issue by githubkyo** [wf9a5m75/phonegap-googlemaps-plugin#635]
when i set one marker's icon url , it's infowindows  can't view.

**Comment by Hirbod** [comment]
No support when you

1) Don't provide version (both CLI cordova -v and cordova plugins ls)
2) System / Env
3) Code-Examples what you did

**Comment by githubkyo** [comment]
Thank you very much.

I return my company, and I will tell you that infomation.

**Comment by githubkyo** [comment]
1) Don't provide version (both CLI cordova -v and cordova plugins ls)
->
cordova: 5.1.1
plugin.google.maps 1.3.0 "phonegap-googlemaps-plugin"

2) System / Env
windows7, 64bit

3) Code-Examples what you did
->
code like this
var couponsResult = coupons.data;
console.log(couponsResult);

var latLng = new plugin.google.maps.LatLng(result[key].lat, result[key].lon);
var iconSize = {
    width: 220,
    height: 133
};
$scope.map.addMarker({
    'position': latLng,
    'title': couponsResult.shop_name,
    'icon': {
        'url': couponsResult.shop_img_mobile,
        'size': {
            width: Math.round(iconSize.width * 0.2),
            height: Math.round(iconSize.height * 0.2)
        }
    }
}, function (marker) {
    console.log('iconId:' + marker.getHashCode())
    marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, function () {
        marker.showInfoWindow();
        
        marker.setIcon({
            'url': 'www/img/faverit.jpg',
            'size': {
                width: Math.round(iconSize.width * 0.2),
                height: Math.round(iconSize.height * 0.2)
            }
        });
        
    });

});

thanks for your help.

**Comment by Hirbod** [comment]
Why do you use the callback function for doing stuff like that? And I don't know why you added a event-listener inside of this callback. This will also cause a memory leak.

I just tested everything, it works fine.

```js

                $scope.onMarkerClick = function(marker) {
                    marker.showInfoWindow();
                    marker.setIcon.......
                };

                $scope.map.addMarker({

                    position: latLng,
                    title: "Test",
                    icon: {
                        url: obj['icon'],
                        size: {
                            width: 30,
                            height: 36
                        }
                    },
                    markerClick: $scope.onMarkerClick     

                });
```

**Comment by githubkyo** [comment]
Thank you.

**Comment by githubkyo** [comment]
It was corrected as has been pointed out.

But,  The marker's InfoWindow left for a moment, soon disappear.

code like this

---------------
$scope.onMarkerClick = function (marker) {
        marker.showInfoWindow();
        marker.setIcon({
            url: 'www/img/map/map_marker_160x140_select.png',
            size: {
                width: 160 * 0.4,
                height: 140 * 0.4
            }
        });
    };

    $scope.makeMarker = function (latlon, tenpoStr) {
        
        map.addMarker({
            position: latlon,
            title: tenpoStr,
            icon: {
                url: 'www/img/map/map_marker_160x140_normal.png',
                size: {
                    width: 160 * 0.4,
                    height: 140 * 0.4
                }
            },
            markerClick: $scope.onMarkerClick
        });
    };
------------------
