### ISSUE TITLE
Question: styles and LatLngBounds

### ISSUE THREAD

**Issue by frank-borkin** [wf9a5m75/phonegap-googlemaps-plugin#639]
Hi,

Does the plugin support the following:
"styles" as a map init option (preferably using the same json used by JS maps). I don't see anything like this in the Android API docs, so I guess not?
google.maps.LatLngBounds() and map.fitBounds()

Thanks

Frank

**Comment by Hirbod** [comment]
No, but when you pass a latlng object it will automatically fitBounds internally
