### ISSUE TITLE
Question : Plugin Was Add But Have Some Error

### ISSUE THREAD

**Issue by rudihardtono** [wf9a5m75/phonegap-googlemaps-plugin#641]
I have add https://github.com/wf9a5m75/phonegap-googlemaps-plugin to my project, but when i test it in "run on android device in eclipse" it have error like 
![image](https://cloud.githubusercontent.com/assets/3478210/10015414/35496e1c-614a-11e5-9d35-5afb424c41c3.png)
i think it was succesfully add

**Comment by Hirbod** [comment]
Please read the wiki howto install. If you're on Cordova 5 and Android Cordova 4, Eclipse won't work, use Android Studio.

**Comment by rudihardtono** [comment]
@Hirbod thanks for your response
when i build my apps using phonegap CLI it works fine, but when i used eclipse thym "https://www.eclipse.org/thym/" for compile my apps it doesnt work

anybody has try to implement it using cordova thym ???
