### ISSUE TITLE
Question : How to use event touchstart on map

### ISSUE THREAD

**Issue by veep2240** [wf9a5m75/phonegap-googlemaps-plugin#642]
Now I have a problem using the click event.
I want Event touchstart.
Features of the app when the open app the camera is moving along my location.
If event touchstart the camera isn't moving along my location.
i did not used touchend.

**Comment by Hirbod** [comment]
You can't trigger touchstart on the map. If you need touchstart, you have to set map.setClickable(false)

**Comment by veep2240** [comment]
There are other ways I can touch keep moving along map and use touchstart.
Now I can not move on the map by touch.
