### ISSUE TITLE
Question: Is whitelist or something else required ? Tiles not displaying anymore (iOS/plugin.google.maps 1.3.1)

### ISSUE THREAD

**Issue by johnrobertcobbold** [wf9a5m75/phonegap-googlemaps-plugin#643]
My map used to work fine but since I have upgraded to iOS9/1.3.1 all I am getting is a map with no tiles, although markers and circling are displaying fine :

<img width="350" alt="screen shot 2015-09-22 at 7 12 42 pm" src="https://cloud.githubusercontent.com/assets/307565/10017317/ed11a63a-615f-11e5-9d1d-87830cf6a900.png">

**Comment by Hirbod** [comment]
Whitelistplugin is required, but it looks like your API Key is wrong

**Comment by johnrobertcobbold** [comment]
Hi @Hirbod, my bad for not testing this out with Xcode and just relying on the simulator. Xcode gave it away and you were right. No idea why my iOS API key seems to have changed. All this iOS9 changes are pretty nerve-racking

**Comment by Hirbod** [comment]
Yeah, iOS 9 and ATS (Apple Transport Security), urlscheme, Bitcode and all that stuff is extremely annoying. Wasted a couple of days to fix my apps, too.
