### ISSUE TITLE
install phonegap googlemaps plugin in eclipse thym 

### ISSUE THREAD

**Issue by rudihardtono** [wf9a5m75/phonegap-googlemaps-plugin#644]
anybody have ever install this plugin with eclipse thym? https://www.eclipse.org/thym/
i install it with cordova/phonegap CLI step by step like wiki howto install its work. 
but when i use Hybid Mobile (cordova) app its doesnt work

**Comment by Hirbod** [comment]
Eclipse = ant = no cordova 5 support
Get Android Studio, as it supports Gradle.

**Comment by rudihardtono** [comment]
tq @Hirbod
