### ISSUE TITLE
Ionic Support - Help?

### ISSUE THREAD

**Issue by gregavola** [wf9a5m75/phonegap-googlemaps-plugin#645]
Hi there,

I know there has been great discussion on how to get this plugin to work for Ionic,  but I have searched and read everything - but I can't find a solution. Everytime I try to init the Maps - I get nothing (I assume that it's hidden behind the JS framework). 

I have tried this (https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/199#issuecomment-56475636), but it doesn't work and it's written for OsenUI.

Is there a solution for Ionic users that we all reference? I know your probally tired or hearing this, but just wanted to get an answer:

       var currentLocation = new plugin.google.maps.LatLng(position.coords.latitude, position.coords.longitude);   

                            var mapDiv=document.getElementById("map_canvas");
                            $rootScope.map = plugin.google.maps.Map.getMap(mapDiv);

                            map.on(plugin.google.maps.event.MAP_READY, function onMapInit(map) {

                                $rootScope.map.animateCamera({
                                  'target': currentLocation,
                                  'zoom': 18,
                                });
             })

At this stage, there is no page on the page, and it's completely empty. This only way to solve this is to completely go ```map.openDialog``` which makes it go full screen. Any way to limit the margin on this?

**Comment by grigored** [comment]
Have you looked at https://market.ionic.io/starters/google-maps ? You'll still have problems with the menu, as ionic menu tries to slide the content (the map in our case) instead of sliding the menu over the content. Better use onsen.

**Comment by gregavola** [comment]
I've actually found out the issue - I was setting a background-color (via an important class) on the body of the element, so the map couldn't see through, I'll go ahead and close this one. Sorry about this!
