### ISSUE TITLE
mapElement.remove() breaks visibility

### ISSUE THREAD

**Issue by roblav96** [wf9a5m75/phonegap-googlemaps-plugin#648]
```javascript
$rootScope.removeMap = function ( reload ) {
		// $rootScope.mapElm.remove()
		console.log("removing map")
		if ( $rootScope.map ) {
			$rootScope.map.remove()
			$rootScope.map = null
			if ( reload == true ) {
				$rootScope.loadMap()
			}
		}
	}
```

With
```javascript
$rootScope.mapElm.remove()
```
uncommented, the view gets removed, but then there's no way to get it back. Tried starting fresh, restarting app, etc.

Only way I got it back was to do:
```javascript
$rootScope.map.showDialog()
```

Not a biggie, just thought I'd let you know. Thank you!!!

**Comment by Hirbod** [comment]
Can't reproduce. I'm also removing my map and readding it on another view, it works fine!

**Comment by roblav96** [comment]
Must've been something on my end. I do apologize. Thank you!
