### ISSUE TITLE
CoreData: Failed to load optimized model at path

### ISSUE THREAD

**Issue by arilsonkarmo** [wf9a5m75/phonegap-googlemaps-plugin#649]
Hi An error appears all the time here
CoreData: Failed to load optimized model at path '/var/mobile/Containers/Bundle/Application/57A7E3CE-46B6-43C1-9F6F-139258AF5E00/MapsTests.app/GoogleMaps.bundle/GMSCacheStorage.momd/Storage.omo'

Someone had this problexm too?

IOS9 + Xcode 7.

**Comment by Hirbod** [comment]
You can ignore this. It's a Google Bug and will be fixed in future SDK releases

**Comment by DeepakP2** [comment]
Can u tell me why this error is coming?
And How to fix it?
