### ISSUE TITLE
Android error with com master branch (iOS9 fix)

### ISSUE THREAD

**Issue by heks** [wf9a5m75/phonegap-googlemaps-plugin#650]
Anyone getting this error when using the latest master branch?

Could not find com.android.support:support-v4:21.0.0

Required by:
         :android:unspecified > com.google.android.gms:play-services-maps:6.5.87 > com.google.android.gms:play-services-base:6.5.87

**Comment by Hirbod** [comment]
Use search, read wiki. Install android and Google repository in Android SDK Manager. Getting tired of lazy people
