### ISSUE TITLE
Adding google maps plugin in AppGyver cloud build service throws error

### ISSUE THREAD

**Issue by sunny061** [wf9a5m75/phonegap-googlemaps-plugin#652]
The error I am getting in the build logs is below.

Adding plugin from: https://github.com/wf9a5m75/phonegap-googlemaps-plugin.git
Does not appear to be an xcode project, no xcode project file in STAGING/client/modules/AGCordova

AppGyver supersonic/steroids apps uses cordova version 3.5.0. I am trying to build for the Android platform
http://docs.appgyver.com/tooling/build-service/plugins/configuring-custom-plugins/

**Comment by Hirbod** [comment]
Sorry, I do not support 3rd party build services
