### ISSUE TITLE
Error from iTunes Connect while submitting a new build from Xcode 7 for iOS 9.

### ISSUE THREAD

**Issue by ramsabarish** [wf9a5m75/phonegap-googlemaps-plugin#654]
![screen shot 2015-09-30 at 6 17 50 pm](https://cloud.githubusercontent.com/assets/10074524/10193558/89a2c9e2-67a1-11e5-9a2f-9a22c5166979.png)

While submitting a new build from Xcode 7 for iOS 9 I received the above error. I tried to edit the 'App.plist' file but I couldn't find the keys CFBundleExecutable  and CFBundleSupportedPlatforms.

Kindly assist me over this issue.

**Comment by Hirbod** [comment]
This should be fixed. Try 1.3.2 of this plugin
