### ISSUE TITLE
Map click handler

### ISSUE THREAD

**Issue by joewoodhouse** [wf9a5m75/phonegap-googlemaps-plugin#660]
So I have an application that renders a lot of content onto the map in the form of polygons and groundoverlays. I then need the user to be able to click (anywhere) on the map, for them to indicate a location.

Is there any way to catch this click, without registering a click handler on every single polygon and ground overlay displayed? As I understand events don't "bubble" through the layers. So if I register a click handler on the overall map, but the user clicks on a ground overlay, the event isn't going to fire.

Any suggestions would be greatly welcomed.

**Comment by Hirbod** [comment]
Did you actually try just to add a click-event on the map?

**Comment by Hirbod** [comment]
There is another method, but only, If you don't need the click events on ground overlay.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/search?q=tappable&type=Code&utf8=%E2%9C%93

Just comment out all these lines where "tappable = YES".
But when you do, you won't be able to add any click events on them anymore.
