### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by yedeba** [wf9a5m75/phonegap-googlemaps-plugin#662]
Hi Masashi, have you thought about the possibility of exporting "phonegap-googlemaps-plugin" to react native? That would be great!!!
Thanks ;)

**Comment by cosmith** [comment]
I have a version working on iOS of Google Maps (not all features yet) that I should open source when I find the time. It's not a port of this plugin though, writing React Native plugins is way easier than cordova plugins...

**Comment by Hirbod** [comment]
Not planned

**Comment by yedeba** [comment]
Thanks
I understand you 're collaborator but was not asking you.
If anyone is interested I found this:
https://github.com/axemclion/react-native-cordova-plugin

**Comment by Hirbod** [comment]
Masashi dropped the Development and will not answer to your requests. So I'm the main contributor here

**Comment by yedeba** [comment]
no wonder , phonegap or cordova apps will die as technologies with react native.
