### ISSUE TITLE
Phonegap build support

### ISSUE THREAD

**Issue by lengoyvaerts** [wf9a5m75/phonegap-googlemaps-plugin#664]
Is it possible to have this on npm for Phonegap Build? There are some forks of it but I don't think they are up to date with this one...

**Comment by Hirbod** [comment]
soon

**Comment by Hirbod** [comment]
cordova-plugin-googlemaps@1.3.4 is on npm now

**Comment by fgarzonhz** [comment]
Thanks


Cordialmente, 
M.Sc. Franklin Garzón
  *Lucha hasta alcanzar tus sueños*


 
 Date: Thu, 15 Oct 2015 14:13:11 -0700

**Comment by CrankyMero** [comment]
Im gettings this issue:

+ resolve to a path with no project.properties file for project /tmp/gimlet/1605/1724801/www_android/project

Cordova Version 3.7.0
Using DevExtreme Application Template
