### ISSUE TITLE
Get Center of Map Bug?

### ISSUE THREAD

**Issue by ffabreti** [wf9a5m75/phonegap-googlemaps-plugin#665]
Hi there,
I'm running on:
- Android 4.4 Device
- Crosswalk 14
- Ionic 1.1.0
- $ ionic info:
  * Cordova CLI: 5.3.3
  * Gulp version:  CLI version 3.9.0
  * Gulp local:   Local version 3.9.0
  * Ionic Version: 1.0.1
  * Ionic CLI Version: 1.6.5
  * Ionic App Lib Version: 0.3.9
  * OS: Distributor ID:     Fedora Description:     Fedora release 21 (Twenty One) 
  * Node Version: v0.12.7

I'm running a map with a crosshair HTML <img> overlay at the center of the map `<div>`
The intention is to let user select the center of the map as his location by pressing a button:

[screenshot](https://drive.google.com/file/d/0Bz9EAjPa_w23WHZTa1JvTzNOOEE/view?usp=sharing) 

Although API has a `map.setCenter()`, it lack a `map.getCenter()`

Searching thru docs, I've found a possible workaround: 
`map.getVisibleRegion(function (latLngBounds) { console.log(latLngBounds.getCenter() ) } ) `

I thought `getVisibleRegion` would "Get the latitude and longitude coordinates of the corner of the map as LatLngBounds", and that `getCenter` would "Compute the center of this LatLngBounds"

Problem is I always get 0,0 as the center, but my map center is not at 0,0

Is it the right way to get center of the map?
Is it a bug or am I doing something wrong?

## UPDATE
I guess my code had multiple function calls running simultaneously and things were getting cancelled or overwritten. Once I set a linear flow of calls, `getVisibleRegion`  worked fine.

**Comment by Hirbod** [comment]
:+1:
