### ISSUE TITLE
Issues with Android

### ISSUE THREAD

**Issue by jsappme** [wf9a5m75/phonegap-googlemaps-plugin#669]
The plugin is working good with iOS but I am experiencing the following issues with Android. Am I the only one?

- Hybrid mode does not work. Here is my code:

var mapType = plugin.google.maps.MapTypeId.HYBRID;
map.setMapTypeId(mapType);

- The location button does not show:

      'controls': {
         'compassButton': true,
         'myLocationButton': true,
         'indoorPicker': true,
         'zoom': true,
         'pan':true,
      },

- I am also getting the 'getMap' is not defined in GoogleMaps plugin error message.

**Comment by Hirbod** [comment]
No issues here. Hybrid works and I never get the getMap undefined error.

**Comment by jsappme** [comment]
I created this repo to replicate the android problem:
https://github.com/jsappme/phonegap-google-maps-ionic-demo

Same thing, the iOS version is working fine but android still gives me the 'getMap' is not defined in GoogleMaps plugin error message.

**Comment by jsappme** [comment]
I figured up the problem.

map = plugin.google.maps.Map.getMap(div, options); does not work anymore.

it should be replace by:

    var map = plugin.google.maps.Map.getMap({
      'backgroundColor': 'transparent',
      'mapType': plugin.google.maps.MapTypeId.HYBRID,
      'controls': {
        'compass': true,
        'myLocationButton': true,
        'indoorPicker': true,
        'zoom': true
      },
      'gestures': {
        'scroll': true,
        'tilt': true,
        'rotate': true,
        'zoom': true
      },
      'camera': {
        'zoom': 0,
      }
    });
    var div = document.getElementById("map_canvas");
    map = plugin.google.maps.Map.getMap(div);

**Comment by Hirbod** [comment]
very weird.

**Comment by jsappme** [comment]
no more getmap error but all the options are not taken into account. it's still very buggy. I keep investigate.

**Comment by Hirbod** [comment]
cause what you are doing is wrong.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L255

**Comment by Hirbod** [comment]
https://github.com/jsappme/phonegap-google-maps-ionic-demo/blob/master/www/js/controllers.js#L17
https://github.com/jsappme/phonegap-google-maps-ionic-demo/blob/master/www/js/controllers.js#L26

remove , here

**Comment by Hirbod** [comment]
And there is also no "compassButton" there. Only "compass"

**Comment by Hirbod** [comment]
and please, also try without "camera"

**Comment by jsappme** [comment]
it looks like it's working. testing it right now. you're the man.

**Comment by Hirbod** [comment]
What did the trick? Camera or compass, or comma?

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/dd87c6ac58b76f1e49e8337f6ff4e43bb1aee927/src/android/plugin/google/maps/GoogleMaps.java#L540

When camera was the problem, try "zoom": "1" or "zoom": "1.0" (cause it has a float-cast) - and I'm not sure how Java handle this.

**Comment by jsappme** [comment]
Here is my code:

    var div = document.getElementById("map_canvas");
    var options = {
      'backgroundColor': 'transparent',
      'mapType': plugin.google.maps.MapTypeId.HYBRID,
      'controls': {
         'compass': true,
         'myLocationButton': true,
         'indoorPicker': true,
         'zoom': true,
         'pan':true
      },
      'gestures': {
         'scroll': true,
         'tilt': true,
         'rotate': true,
         'zoom': true
      }
    };
    map = plugin.google.maps.Map.getMap(div, options);

**Comment by Hirbod** [comment]
So camera was the problem. Please try my suggestions above

**Comment by jsappme** [comment]
map.getMyLocation(function(location) {
      map.setCenter(location.latLng);
    }, function(){
      error.log("Error getMyLocation");
    });

is not taken into account. Do you see something wrong with?

**Comment by jsappme** [comment]
I upadated https://github.com/jsappme/phonegap-google-maps-ionic-demo

the getmylocation does not return anything at the first time. no idea why.

**Comment by Hirbod** [comment]
Please don't use getMyLocation. I'm sure that you're settings are wrong, but anyway, you should grab the cordova geolocation plugin for that. It's less bug free and uses W3C standards. Just grab it and pass the results to your map.

**Comment by Hirbod** [comment]
I will deprecate getMyLocation from now!

**Comment by jsappme** [comment]
ok
